// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DynamicForm module
	public static void aCT_AddNewRole(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_AddNewRole").withParams(params).execute(context);
	}
	public static void aCT_AddNewRole_Grant(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_AddNewRole_Grant").withParams(params).execute(context);
	}
	public static void act_Create_LongAns(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_Create_LongAns").withParams(params).execute(context);
	}
	public static void aCT_Create_NewAddress(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Create_NewAddress").withParams(params).execute(context);
	}
	public static void aCT_Create_NewCountry(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Create_NewCountry").withParams(params).execute(context);
	}
	public static void aCT_Create_NewWebsite(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Create_NewWebsite").withParams(params).execute(context);
	}
	public static void act_Create_ShortAns(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_Create_ShortAns").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template act_CreateNewBoolean(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewBoolean").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDate(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDate").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDecimal(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDecimal").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void act_CreateNewDoc(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewDoc").withParams(params).execute(context);
	}
	public static void act_CreateNewEmail(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEmail").withParams(params).execute(context);
	}
	public static void act_CreateNewEnum(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template act_CreateNewNumber(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewNumber").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void aCT_CreateNewPhoneNo(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_CreateNewPhoneNo").withParams(params).execute(context);
	}
	public static void act_CreateNewString(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString").withParams(params).execute(context);
	}
	public static void aCT_CreateTemplate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicForm.ACT_CreateTemplate").withParams(params).execute(context);
	}
	public static void aCT_Delete_Address(IContext context, dynamicform.proxies.Address _address, dynamicform.proxies.Template _template, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Address", _address == null ? null : _address.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Delete_Address").withParams(params).execute(context);
	}
	public static void aCT_Delete_Country(IContext context, dynamicform.proxies.Country _country, dynamicform.proxies.Template _template, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Country", _country == null ? null : _country.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Delete_Country").withParams(params).execute(context);
	}
	public static void aCT_Delete_LongAnswer(IContext context, dynamicform.proxies.LongAnswer _longAnswer, dynamicform.proxies.Template _template, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LongAnswer", _longAnswer == null ? null : _longAnswer.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Delete_LongAnswer").withParams(params).execute(context);
	}
	public static void aCT_Delete_PhNumber(IContext context, dynamicform.proxies.PhoneNumber _phNumber, dynamicform.proxies.Template _template, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PhNumber", _phNumber == null ? null : _phNumber.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Delete_PhNumber").withParams(params).execute(context);
	}
	public static void aCT_Delete_ShortAnswer(IContext context, dynamicform.proxies.ShortAnswer _shortAnswer, dynamicform.proxies.Template _template, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ShortAnswer", _shortAnswer == null ? null : _shortAnswer.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Delete_ShortAnswer").withParams(params).execute(context);
	}
	public static void act_DeleteBoolean(IContext context, dynamicform.proxies.Boolean_ _string, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteBoolean").withParams(params).execute(context);
	}
	public static void act_DeleteDateAndTime(IContext context, dynamicform.proxies.DateAndTime _dateAndTime, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateAndTime", _dateAndTime == null ? null : _dateAndTime.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDateAndTime").withParams(params).execute(context);
	}
	public static void act_DeleteDecimal(IContext context, dynamicform.proxies.Decimal _string, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDecimal").withParams(params).execute(context);
	}
	public static void act_DeleteDoc(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDoc").withParams(params).execute(context);
	}
	public static void act_DeleteEnum(IContext context, dynamicform.proxies.Enumeration _enum, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enum", _enum == null ? null : _enum.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteEnum").withParams(params).execute(context);
	}
	public static void act_deletenewworkflow(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_deletenewworkflow").withParams(params).execute(context);
	}
	public static void act_DeleteNumber(IContext context, dynamicform.proxies.Number _number, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteNumber").withParams(params).execute(context);
	}
	public static void aCT_DeleteRole(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_DeleteRole").withParams(params).execute(context);
	}
	public static void aCT_DeleteRole_Grant(IContext context, ugs.proxies.GrantSystem _grantSystem, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_DeleteRole_Grant").withParams(params).execute(context);
	}
	public static void act_DeleteString(IContext context, dynamicform.proxies.String _string, dynamicform.proxies.Template _customer, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteString").withParams(params).execute(context);
	}
	public static void aCT_DynamicWorkflowPass(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_DynamicWorkflowPass").withParams(params).execute(context);
	}
	public static void aCT_InsertNewRole(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_InsertNewRole").withParams(params).execute(context);
	}
	public static void aCT_InsertNewRole2(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_InsertNewRole2").withParams(params).execute(context);
	}
	public static void act_MakeActive(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_MakeActive").withParams(params).execute(context);
	}
	public static void act_MakeInactive(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_MakeInactive").withParams(params).execute(context);
	}
	public static void aCT_MoveRoleDown(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_MoveRoleDown").withParams(params).execute(context);
	}
	public static void aCT_MoveRoleDown_Grant(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_MoveRoleDown_Grant").withParams(params).execute(context);
	}
	public static void aCT_MoveRoleUp(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_MoveRoleUp").withParams(params).execute(context);
	}
	public static void aCT_MoveRoleUp_Grant(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_MoveRoleUp_Grant").withParams(params).execute(context);
	}
	public static void act_NewGrant(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("DynamicForm.Act_NewGrant").withParams(params).execute(context);
	}
	public static void act_NewSection(IContext context, dynamicform.proxies.ApplicationForm _aF)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AF", _aF == null ? null : _aF.getMendixObject());
		Core.microflowCall("DynamicForm.Act_NewSection").withParams(params).execute(context);
	}
	public static void aCT_NewTokenReplacer_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicForm.ACT_NewTokenReplacer_2").withParams(params).execute(context);
	}
	public static void act_OpenStringorEmailPage(IContext context, dynamicform.proxies.String _string, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_OpenStringorEmailPage").withParams(params).execute(context);
	}
	public static java.util.List<system.proxies.UserRole> aCT_RetAllUserRoles(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.ACT_RetAllUserRoles").withParams(params).execute(context);
		java.util.List<system.proxies.UserRole> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(system.proxies.UserRole.initialize(context, obj));
		}
		return result;
	}
	public static void aCT_Save_Status(IContext context, dynamicform.proxies.Status _status)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Status", _status == null ? null : _status.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Save_Status").withParams(params).execute(context);
	}
	public static void aCT_SaveNewRole(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_SaveNewRole").withParams(params).execute(context);
	}
	public static void act_SaveTEmplate(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_SaveTEmplate").withParams(params).execute(context);
	}
	public static void act_ShowTemplatePage(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_ShowTemplatePage").withParams(params).execute(context);
	}
	public static void act_Template_save(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_Template_save").withParams(params).execute(context);
	}
	public static void act_Template_save_Grant(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_Template_save_Grant").withParams(params).execute(context);
	}
	public static void afterStartUp_Create_Status(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicForm.AfterStartUp_Create_Status").withParams(params).execute(context);
	}
	public static java.math.BigDecimal cal_DaysLeft(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		return (java.math.BigDecimal) Core.microflowCall("DynamicForm.Cal_DaysLeft").withParams(params).execute(context);
	}
	public static java.lang.String cal_IconClass(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.String) Core.microflowCall("DynamicForm.Cal_IconClass").withParams(params).execute(context);
	}
	public static boolean calculate_all_formulae(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DynamicForm.Calculate_all_formulae").withParams(params).execute(context);
	}
	public static void clone_Template_Cloneobject(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Clone_Template_Cloneobject").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Document> dS_GetALLDocuments(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.DS_GetALLDocuments").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Document> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Document.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> dS_GetCurrWF(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.DS_GetCurrWF").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static void ds_GetDefTemplate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicForm.Ds_GetDefTemplate").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Document> dS_GetTemplateDocs(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.DS_GetTemplateDocs").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Document> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Document.initialize(context, obj));
		}
		return result;
	}
	public static dynamicform.proxies.Template duplicate_Template_Cloneobject(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Duplicate_Template_Cloneobject").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void formula_Calculation_MF(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Formula_Calculation_MF").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Number> get_assoc_Numb_Obj_for_Grid(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Get_assoc_Numb_Obj_for_Grid").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Number> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Number.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Number> get_assoc_Numb_Obj_for_Java(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Get_assoc_Numb_Obj_for_Java").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Number> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Number.initialize(context, obj));
		}
		return result;
	}
	public static void map_EnumValue_to_Enum(IContext context, dynamicform.proxies.Enumeration _enumeration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enumeration", _enumeration == null ? null : _enumeration.getMendixObject());
		Core.microflowCall("DynamicForm.Map_EnumValue_to_Enum").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Template> microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Microflow").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Template> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Template.initialize(context, obj));
		}
		return result;
	}
	public static void oCE_AllocateLAyout(IContext context, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.OCE_AllocateLAyout").withParams(params).execute(context);
	}
	public static void oCH_changeLayout(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_changeLayout").withParams(params).execute(context);
	}
	public static void oCH_NumberValue(IContext context, dynamicform.proxies.Number _number, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_NumberValue").withParams(params).execute(context);
	}
	public static void oCH_Open_Dynamic_Page(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_Open_Dynamic_Page").withParams(params).execute(context);
	}
	public static void oCH_PastAndFutureValidation(IContext context, dynamicform.proxies.DateAndTime _dateAndTime)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateAndTime", _dateAndTime == null ? null : _dateAndTime.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_PastAndFutureValidation").withParams(params).execute(context);
	}
	public static void oCH_PastAndFutureValidation_2(IContext context, dynamicform.proxies.DateAndTime _dateAndTime)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateAndTime", _dateAndTime == null ? null : _dateAndTime.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_PastAndFutureValidation_2").withParams(params).execute(context);
	}
	public static void oCH_SelectAllFileFormats(IContext context, dynamicform.proxies.Doc _doc)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Doc", _doc == null ? null : _doc.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_SelectAllFileFormats").withParams(params).execute(context);
	}
	public static void oCH_SelectNone(IContext context, dynamicform.proxies.Doc _doc)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Doc", _doc == null ? null : _doc.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_SelectNone").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> rET_AllUserRoles(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.RET_AllUserRoles").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> rET_AllUserRolesGrant(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.RET_AllUserRolesGrant").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Enum_Values> retrieve_assoc_Obj(IContext context, dynamicform.proxies.Enumeration _enumeration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enumeration", _enumeration == null ? null : _enumeration.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Retrieve_assoc_Obj").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Enum_Values> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Enum_Values.initialize(context, obj));
		}
		return result;
	}
	public static void save_Number_Value(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Save_Number_Value").withParams(params).execute(context);
	}
	public static void save_Number_Value_2(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Save_Number_Value_2").withParams(params).execute(context);
	}
	public static void sub_CheckElements(IContext context, java.util.List<dynamicform.proxies.Element> _elementList, dynamicform.proxies.Element _mainElement, java.util.List<dynamicform.proxies.Element> _elementListMain)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_elementList = null;
		if (_elementList != null)
		{
			listparam_elementList = new java.util.ArrayList<>();
			for (dynamicform.proxies.Element obj : _elementList)
				listparam_elementList.add(obj.getMendixObject());
		}
		params.put("ElementList", listparam_elementList);

		params.put("MainElement", _mainElement == null ? null : _mainElement.getMendixObject());
		java.util.ArrayList<IMendixObject> listparam_elementListMain = null;
		if (_elementListMain != null)
		{
			listparam_elementListMain = new java.util.ArrayList<>();
			for (dynamicform.proxies.Element obj : _elementListMain)
				listparam_elementListMain.add(obj.getMendixObject());
		}
		params.put("ElementListMain", listparam_elementListMain);

		Core.microflowCall("DynamicForm.Sub_CheckElements").withParams(params).execute(context);
	}
	public static void sub_CloneElementObjects(IContext context, dynamicform.proxies.Element _element, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Sub_CloneElementObjects").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Intermediate> sUB_ConvertToIntermediate(IContext context, ugs.proxies.GrantSystem _grantSystem, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.SUB_ConvertToIntermediate").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Intermediate> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Intermediate.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Intermediate> sUB_ConvertToIntermediateFromGrant(IContext context, ugs.proxies.GrantSystem _grantSystem, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.SUB_ConvertToIntermediateFromGrant").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Intermediate> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Intermediate.initialize(context, obj));
		}
		return result;
	}
	public static void sUB_Create_FlowChart_Grant(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("DynamicForm.SUB_Create_FlowChart_Grant").withParams(params).execute(context);
	}
	public static void sUB_Create_FlowChart_template(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.SUB_Create_FlowChart_template").withParams(params).execute(context);
	}
	public static void sUB_Delete_Align(IContext context, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.SUB_Delete_Align").withParams(params).execute(context);
	}
	public static void sUB_IntermediateNamer(IContext context, dynamicform.proxies.Intermediate _intermediate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Intermediate", _intermediate == null ? null : _intermediate.getMendixObject());
		Core.microflowCall("DynamicForm.SUB_IntermediateNamer").withParams(params).execute(context);
	}
	public static boolean sub_ObjectCasting(IContext context, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DynamicForm.Sub_ObjectCasting").withParams(params).execute(context);
	}
	public static boolean sUB_ValidateDocs(IContext context, java.util.List<dynamicform.proxies.Element> _elementList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_elementList = null;
		if (_elementList != null)
		{
			listparam_elementList = new java.util.ArrayList<>();
			for (dynamicform.proxies.Element obj : _elementList)
				listparam_elementList.add(obj.getMendixObject());
		}
		params.put("ElementList", listparam_elementList);

		return (java.lang.Boolean) Core.microflowCall("DynamicForm.SUB_ValidateDocs").withParams(params).execute(context);
	}
	public static java.lang.String vAl_CreateFileTypeString(IContext context, dynamicform.proxies.Doc _doc)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Doc", _doc == null ? null : _doc.getMendixObject());
		return (java.lang.String) Core.microflowCall("DynamicForm.VAl_CreateFileTypeString").withParams(params).execute(context);
	}
	public static java.lang.String vAl_CreateFileTypeString_2(IContext context, dynamicform.proxies.Doc _doc)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Doc", _doc == null ? null : _doc.getMendixObject());
		return (java.lang.String) Core.microflowCall("DynamicForm.VAl_CreateFileTypeString_2").withParams(params).execute(context);
	}
	public static boolean val_Template(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DynamicForm.Val_Template").withParams(params).execute(context);
	}
}