// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ugs.actions;

import java.util.Date;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Java_action_TimeCalculation extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __History;
	private ugs.proxies.History History;

	public Java_action_TimeCalculation(IContext context, IMendixObject History)
	{
		super(context);
		this.__History = History;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.History = __History == null ? null : ugs.proxies.History.initialize(getContext(), __History);

		// BEGIN USER CODE
		Date recieved = this.History.getRecievedDate(this.getContext());
		Date processed = this.History.getProcessedDate(this.getContext());
		String sl = "";
			long diff_time=processed.getTime()-recieved.getTime();
			//long diff_sec=(diff_time/1000)%60;
			long diff_min=(diff_time/(1000*60))%60;
			long diff_hrs=(diff_time/(1000*60*60))%24;
			//long diff_yrs=(diff_time/(1000*60*60*24*365));
			long diff_days=(diff_time/(1000*60*60*60*24))%365;
			sl=sl+diff_days+" days : "+diff_hrs+" hours : "+diff_min+" minutes";
		
		return sl;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_TimeCalculation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
