// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bizzomatetokenreplacer.proxies;

public class ContentParser
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contentParserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BizzomateTokenReplacer.ContentParser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UUID("UUID"),
		LanguageCode("LanguageCode"),
		IsValueOfDataTypeEnumeration("IsValueOfDataTypeEnumeration"),
		Value("Value"),
		ParseToValue("ParseToValue"),
		ContentParser_Token("BizzomateTokenReplacer.ContentParser_Token"),
		ContentParser_Language("BizzomateTokenReplacer.ContentParser_Language"),
		ContentParser_MxObjectEnumValue("BizzomateTokenReplacer.ContentParser_MxObjectEnumValue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContentParser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BizzomateTokenReplacer.ContentParser"));
	}

	protected ContentParser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contentParserMendixObject)
	{
		if (contentParserMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BizzomateTokenReplacer.ContentParser", contentParserMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BizzomateTokenReplacer.ContentParser");

		this.contentParserMendixObject = contentParserMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ContentParser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bizzomatetokenreplacer.proxies.ContentParser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bizzomatetokenreplacer.proxies.ContentParser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bizzomatetokenreplacer.proxies.ContentParser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bizzomatetokenreplacer.proxies.ContentParser(context, mendixObject);
	}

	public static bizzomatetokenreplacer.proxies.ContentParser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bizzomatetokenreplacer.proxies.ContentParser.initialize(context, mendixObject);
	}

	public static java.util.List<bizzomatetokenreplacer.proxies.ContentParser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<bizzomatetokenreplacer.proxies.ContentParser> result = new java.util.ArrayList<bizzomatetokenreplacer.proxies.ContentParser>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BizzomateTokenReplacer.ContentParser" + xpathConstraint))
			result.add(bizzomatetokenreplacer.proxies.ContentParser.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of LanguageCode
	 */
	public final java.lang.String getLanguageCode()
	{
		return getLanguageCode(getContext());
	}

	/**
	 * @param context
	 * @return value of LanguageCode
	 */
	public final java.lang.String getLanguageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LanguageCode.toString());
	}

	/**
	 * Set value of LanguageCode
	 * @param languagecode
	 */
	public final void setLanguageCode(java.lang.String languagecode)
	{
		setLanguageCode(getContext(), languagecode);
	}

	/**
	 * Set value of LanguageCode
	 * @param context
	 * @param languagecode
	 */
	public final void setLanguageCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languagecode)
	{
		getMendixObject().setValue(context, MemberNames.LanguageCode.toString(), languagecode);
	}

	/**
	 * @return value of IsValueOfDataTypeEnumeration
	 */
	public final java.lang.Boolean getIsValueOfDataTypeEnumeration()
	{
		return getIsValueOfDataTypeEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValueOfDataTypeEnumeration
	 */
	public final java.lang.Boolean getIsValueOfDataTypeEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValueOfDataTypeEnumeration.toString());
	}

	/**
	 * Set value of IsValueOfDataTypeEnumeration
	 * @param isvalueofdatatypeenumeration
	 */
	public final void setIsValueOfDataTypeEnumeration(java.lang.Boolean isvalueofdatatypeenumeration)
	{
		setIsValueOfDataTypeEnumeration(getContext(), isvalueofdatatypeenumeration);
	}

	/**
	 * Set value of IsValueOfDataTypeEnumeration
	 * @param context
	 * @param isvalueofdatatypeenumeration
	 */
	public final void setIsValueOfDataTypeEnumeration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalueofdatatypeenumeration)
	{
		getMendixObject().setValue(context, MemberNames.IsValueOfDataTypeEnumeration.toString(), isvalueofdatatypeenumeration);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of ParseToValue
	 */
	public final java.lang.String getParseToValue()
	{
		return getParseToValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ParseToValue
	 */
	public final java.lang.String getParseToValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParseToValue.toString());
	}

	/**
	 * Set value of ParseToValue
	 * @param parsetovalue
	 */
	public final void setParseToValue(java.lang.String parsetovalue)
	{
		setParseToValue(getContext(), parsetovalue);
	}

	/**
	 * Set value of ParseToValue
	 * @param context
	 * @param parsetovalue
	 */
	public final void setParseToValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parsetovalue)
	{
		getMendixObject().setValue(context, MemberNames.ParseToValue.toString(), parsetovalue);
	}

	/**
	 * @return value of ContentParser_Token
	 */
	public final bizzomatetokenreplacer.proxies.Token getContentParser_Token() throws com.mendix.core.CoreException
	{
		return getContentParser_Token(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentParser_Token
	 */
	public final bizzomatetokenreplacer.proxies.Token getContentParser_Token(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bizzomatetokenreplacer.proxies.Token result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContentParser_Token.toString());
		if (identifier != null)
			result = bizzomatetokenreplacer.proxies.Token.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ContentParser_Token
	 * @param contentparser_token
	 */
	public final void setContentParser_Token(bizzomatetokenreplacer.proxies.Token contentparser_token)
	{
		setContentParser_Token(getContext(), contentparser_token);
	}

	/**
	 * Set value of ContentParser_Token
	 * @param context
	 * @param contentparser_token
	 */
	public final void setContentParser_Token(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.Token contentparser_token)
	{
		if (contentparser_token == null)
			getMendixObject().setValue(context, MemberNames.ContentParser_Token.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ContentParser_Token.toString(), contentparser_token.getMendixObject().getId());
	}

	/**
	 * @return value of ContentParser_Language
	 */
	public final system.proxies.Language getContentParser_Language() throws com.mendix.core.CoreException
	{
		return getContentParser_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentParser_Language
	 */
	public final system.proxies.Language getContentParser_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContentParser_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ContentParser_Language
	 * @param contentparser_language
	 */
	public final void setContentParser_Language(system.proxies.Language contentparser_language)
	{
		setContentParser_Language(getContext(), contentparser_language);
	}

	/**
	 * Set value of ContentParser_Language
	 * @param context
	 * @param contentparser_language
	 */
	public final void setContentParser_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language contentparser_language)
	{
		if (contentparser_language == null)
			getMendixObject().setValue(context, MemberNames.ContentParser_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ContentParser_Language.toString(), contentparser_language.getMendixObject().getId());
	}

	/**
	 * @return value of ContentParser_MxObjectEnumValue
	 */
	public final mxmodelreflection.proxies.MxObjectEnumValue getContentParser_MxObjectEnumValue() throws com.mendix.core.CoreException
	{
		return getContentParser_MxObjectEnumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentParser_MxObjectEnumValue
	 */
	public final mxmodelreflection.proxies.MxObjectEnumValue getContentParser_MxObjectEnumValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectEnumValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContentParser_MxObjectEnumValue.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectEnumValue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ContentParser_MxObjectEnumValue
	 * @param contentparser_mxobjectenumvalue
	 */
	public final void setContentParser_MxObjectEnumValue(mxmodelreflection.proxies.MxObjectEnumValue contentparser_mxobjectenumvalue)
	{
		setContentParser_MxObjectEnumValue(getContext(), contentparser_mxobjectenumvalue);
	}

	/**
	 * Set value of ContentParser_MxObjectEnumValue
	 * @param context
	 * @param contentparser_mxobjectenumvalue
	 */
	public final void setContentParser_MxObjectEnumValue(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectEnumValue contentparser_mxobjectenumvalue)
	{
		if (contentparser_mxobjectenumvalue == null)
			getMendixObject().setValue(context, MemberNames.ContentParser_MxObjectEnumValue.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ContentParser_MxObjectEnumValue.toString(), contentparser_mxobjectenumvalue.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contentParserMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bizzomatetokenreplacer.proxies.ContentParser that = (bizzomatetokenreplacer.proxies.ContentParser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BizzomateTokenReplacer.ContentParser";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
