// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bizzomatetokenreplacer.proxies;

public enum DataType
{
	TEXT(new java.lang.String[][] { new java.lang.String[] { "en_US", "Text" }, new java.lang.String[] { "nl_NL", "Tekst" }, new java.lang.String[] { "nl_BE", "Tekst" } }),
	WHOLE_NUMBER(new java.lang.String[][] { new java.lang.String[] { "en_US", "Whole number" }, new java.lang.String[] { "nl_NL", "Heel getal" }, new java.lang.String[] { "nl_BE", "Heel getal" } }),
	DECIMAL_NUMBER(new java.lang.String[][] { new java.lang.String[] { "en_US", "Decimal number" }, new java.lang.String[] { "nl_NL", "Decimaal nummer" }, new java.lang.String[] { "nl_BE", "Decimaal nummer" } }),
	DATE(new java.lang.String[][] { new java.lang.String[] { "en_US", "Date" }, new java.lang.String[] { "nl_NL", "Datum" }, new java.lang.String[] { "nl_BE", "Datum" } }),
	ENUMERATION(new java.lang.String[][] { new java.lang.String[] { "en_US", "Enumeration" }, new java.lang.String[] { "nl_NL", "Enumeratie" }, new java.lang.String[] { "nl_BE", "Enumeratie" } }),
	YES_NO(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes / No" }, new java.lang.String[] { "nl_NL", "Ja / Nee" }, new java.lang.String[] { "nl_BE", "Ja / Nee" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private DataType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
