// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bizzomatetokenreplacer.proxies;

public class Token
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BizzomateTokenReplacer.Token";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UUID("UUID"),
		Token("Token"),
		CompleteToken("CompleteToken"),
		AttributeName("AttributeName"),
		DataType("DataType"),
		EscapeParsedValue("EscapeParsedValue"),
		ParserMethod("ParserMethod"),
		NumberOfDecimalsMin("NumberOfDecimalsMin"),
		NumberOfDecimalsMax("NumberOfDecimalsMax"),
		ApplyGrouping("ApplyGrouping"),
		DateFormat("DateFormat"),
		FreeDateFormat("FreeDateFormat"),
		FreeDateFormatResult("FreeDateFormatResult"),
		Token_TokenObject("BizzomateTokenReplacer.Token_TokenObject"),
		Token_TokenReplacer("BizzomateTokenReplacer.Token_TokenReplacer"),
		Token_MxObjectMember("BizzomateTokenReplacer.Token_MxObjectMember"),
		Token_Intermediate("BizzomateTokenReplacer.Token_Intermediate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BizzomateTokenReplacer.Token"));
	}

	protected Token(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject)
	{
		if (tokenMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BizzomateTokenReplacer.Token", tokenMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BizzomateTokenReplacer.Token");

		this.tokenMendixObject = tokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Token.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bizzomatetokenreplacer.proxies.Token initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bizzomatetokenreplacer.proxies.Token.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bizzomatetokenreplacer.proxies.Token initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bizzomatetokenreplacer.proxies.Token(context, mendixObject);
	}

	public static bizzomatetokenreplacer.proxies.Token load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bizzomatetokenreplacer.proxies.Token.initialize(context, mendixObject);
	}

	public static java.util.List<bizzomatetokenreplacer.proxies.Token> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<bizzomatetokenreplacer.proxies.Token> result = new java.util.ArrayList<bizzomatetokenreplacer.proxies.Token>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BizzomateTokenReplacer.Token" + xpathConstraint))
			result.add(bizzomatetokenreplacer.proxies.Token.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of CompleteToken
	 */
	public final java.lang.String getCompleteToken()
	{
		return getCompleteToken(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteToken
	 */
	public final java.lang.String getCompleteToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompleteToken.toString());
	}

	/**
	 * Set value of CompleteToken
	 * @param completetoken
	 */
	public final void setCompleteToken(java.lang.String completetoken)
	{
		setCompleteToken(getContext(), completetoken);
	}

	/**
	 * Set value of CompleteToken
	 * @param context
	 * @param completetoken
	 */
	public final void setCompleteToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String completetoken)
	{
		getMendixObject().setValue(context, MemberNames.CompleteToken.toString(), completetoken);
	}

	/**
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(java.lang.String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * Set value of DataType
	 * @param datatype
	 */
	public final bizzomatetokenreplacer.proxies.DataType getDataType()
	{
		return getDataType(getContext());
	}

	/**
	 * @param context
	 * @return value of DataType
	 */
	public final bizzomatetokenreplacer.proxies.DataType getDataType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DataType.toString());
		if (obj == null)
			return null;

		return bizzomatetokenreplacer.proxies.DataType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DataType
	 * @param datatype
	 */
	public final void setDataType(bizzomatetokenreplacer.proxies.DataType datatype)
	{
		setDataType(getContext(), datatype);
	}

	/**
	 * Set value of DataType
	 * @param context
	 * @param datatype
	 */
	public final void setDataType(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.DataType datatype)
	{
		if (datatype != null)
			getMendixObject().setValue(context, MemberNames.DataType.toString(), datatype.toString());
		else
			getMendixObject().setValue(context, MemberNames.DataType.toString(), null);
	}

	/**
	 * @return value of EscapeParsedValue
	 */
	public final java.lang.Boolean getEscapeParsedValue()
	{
		return getEscapeParsedValue(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeParsedValue
	 */
	public final java.lang.Boolean getEscapeParsedValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EscapeParsedValue.toString());
	}

	/**
	 * Set value of EscapeParsedValue
	 * @param escapeparsedvalue
	 */
	public final void setEscapeParsedValue(java.lang.Boolean escapeparsedvalue)
	{
		setEscapeParsedValue(getContext(), escapeparsedvalue);
	}

	/**
	 * Set value of EscapeParsedValue
	 * @param context
	 * @param escapeparsedvalue
	 */
	public final void setEscapeParsedValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean escapeparsedvalue)
	{
		getMendixObject().setValue(context, MemberNames.EscapeParsedValue.toString(), escapeparsedvalue);
	}

	/**
	 * Set value of ParserMethod
	 * @param parsermethod
	 */
	public final bizzomatetokenreplacer.proxies.ParserMethod getParserMethod()
	{
		return getParserMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of ParserMethod
	 */
	public final bizzomatetokenreplacer.proxies.ParserMethod getParserMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ParserMethod.toString());
		if (obj == null)
			return null;

		return bizzomatetokenreplacer.proxies.ParserMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ParserMethod
	 * @param parsermethod
	 */
	public final void setParserMethod(bizzomatetokenreplacer.proxies.ParserMethod parsermethod)
	{
		setParserMethod(getContext(), parsermethod);
	}

	/**
	 * Set value of ParserMethod
	 * @param context
	 * @param parsermethod
	 */
	public final void setParserMethod(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.ParserMethod parsermethod)
	{
		if (parsermethod != null)
			getMendixObject().setValue(context, MemberNames.ParserMethod.toString(), parsermethod.toString());
		else
			getMendixObject().setValue(context, MemberNames.ParserMethod.toString(), null);
	}

	/**
	 * @return value of NumberOfDecimalsMin
	 */
	public final java.lang.Integer getNumberOfDecimalsMin()
	{
		return getNumberOfDecimalsMin(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfDecimalsMin
	 */
	public final java.lang.Integer getNumberOfDecimalsMin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfDecimalsMin.toString());
	}

	/**
	 * Set value of NumberOfDecimalsMin
	 * @param numberofdecimalsmin
	 */
	public final void setNumberOfDecimalsMin(java.lang.Integer numberofdecimalsmin)
	{
		setNumberOfDecimalsMin(getContext(), numberofdecimalsmin);
	}

	/**
	 * Set value of NumberOfDecimalsMin
	 * @param context
	 * @param numberofdecimalsmin
	 */
	public final void setNumberOfDecimalsMin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofdecimalsmin)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfDecimalsMin.toString(), numberofdecimalsmin);
	}

	/**
	 * @return value of NumberOfDecimalsMax
	 */
	public final java.lang.Integer getNumberOfDecimalsMax()
	{
		return getNumberOfDecimalsMax(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfDecimalsMax
	 */
	public final java.lang.Integer getNumberOfDecimalsMax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfDecimalsMax.toString());
	}

	/**
	 * Set value of NumberOfDecimalsMax
	 * @param numberofdecimalsmax
	 */
	public final void setNumberOfDecimalsMax(java.lang.Integer numberofdecimalsmax)
	{
		setNumberOfDecimalsMax(getContext(), numberofdecimalsmax);
	}

	/**
	 * Set value of NumberOfDecimalsMax
	 * @param context
	 * @param numberofdecimalsmax
	 */
	public final void setNumberOfDecimalsMax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofdecimalsmax)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfDecimalsMax.toString(), numberofdecimalsmax);
	}

	/**
	 * @return value of ApplyGrouping
	 */
	public final java.lang.Boolean getApplyGrouping()
	{
		return getApplyGrouping(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplyGrouping
	 */
	public final java.lang.Boolean getApplyGrouping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ApplyGrouping.toString());
	}

	/**
	 * Set value of ApplyGrouping
	 * @param applygrouping
	 */
	public final void setApplyGrouping(java.lang.Boolean applygrouping)
	{
		setApplyGrouping(getContext(), applygrouping);
	}

	/**
	 * Set value of ApplyGrouping
	 * @param context
	 * @param applygrouping
	 */
	public final void setApplyGrouping(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean applygrouping)
	{
		getMendixObject().setValue(context, MemberNames.ApplyGrouping.toString(), applygrouping);
	}

	/**
	 * Set value of DateFormat
	 * @param dateformat
	 */
	public final bizzomatetokenreplacer.proxies.DateFormat getDateFormat()
	{
		return getDateFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFormat
	 */
	public final bizzomatetokenreplacer.proxies.DateFormat getDateFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DateFormat.toString());
		if (obj == null)
			return null;

		return bizzomatetokenreplacer.proxies.DateFormat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DateFormat
	 * @param dateformat
	 */
	public final void setDateFormat(bizzomatetokenreplacer.proxies.DateFormat dateformat)
	{
		setDateFormat(getContext(), dateformat);
	}

	/**
	 * Set value of DateFormat
	 * @param context
	 * @param dateformat
	 */
	public final void setDateFormat(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.DateFormat dateformat)
	{
		if (dateformat != null)
			getMendixObject().setValue(context, MemberNames.DateFormat.toString(), dateformat.toString());
		else
			getMendixObject().setValue(context, MemberNames.DateFormat.toString(), null);
	}

	/**
	 * @return value of FreeDateFormat
	 */
	public final java.lang.String getFreeDateFormat()
	{
		return getFreeDateFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of FreeDateFormat
	 */
	public final java.lang.String getFreeDateFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FreeDateFormat.toString());
	}

	/**
	 * Set value of FreeDateFormat
	 * @param freedateformat
	 */
	public final void setFreeDateFormat(java.lang.String freedateformat)
	{
		setFreeDateFormat(getContext(), freedateformat);
	}

	/**
	 * Set value of FreeDateFormat
	 * @param context
	 * @param freedateformat
	 */
	public final void setFreeDateFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String freedateformat)
	{
		getMendixObject().setValue(context, MemberNames.FreeDateFormat.toString(), freedateformat);
	}

	/**
	 * @return value of FreeDateFormatResult
	 */
	public final java.lang.String getFreeDateFormatResult()
	{
		return getFreeDateFormatResult(getContext());
	}

	/**
	 * @param context
	 * @return value of FreeDateFormatResult
	 */
	public final java.lang.String getFreeDateFormatResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FreeDateFormatResult.toString());
	}

	/**
	 * Set value of FreeDateFormatResult
	 * @param freedateformatresult
	 */
	public final void setFreeDateFormatResult(java.lang.String freedateformatresult)
	{
		setFreeDateFormatResult(getContext(), freedateformatresult);
	}

	/**
	 * Set value of FreeDateFormatResult
	 * @param context
	 * @param freedateformatresult
	 */
	public final void setFreeDateFormatResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String freedateformatresult)
	{
		getMendixObject().setValue(context, MemberNames.FreeDateFormatResult.toString(), freedateformatresult);
	}

	/**
	 * @return value of Token_TokenObject
	 */
	public final bizzomatetokenreplacer.proxies.TokenObject getToken_TokenObject() throws com.mendix.core.CoreException
	{
		return getToken_TokenObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_TokenObject
	 */
	public final bizzomatetokenreplacer.proxies.TokenObject getToken_TokenObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bizzomatetokenreplacer.proxies.TokenObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_TokenObject.toString());
		if (identifier != null)
			result = bizzomatetokenreplacer.proxies.TokenObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Token_TokenObject
	 * @param token_tokenobject
	 */
	public final void setToken_TokenObject(bizzomatetokenreplacer.proxies.TokenObject token_tokenobject)
	{
		setToken_TokenObject(getContext(), token_tokenobject);
	}

	/**
	 * Set value of Token_TokenObject
	 * @param context
	 * @param token_tokenobject
	 */
	public final void setToken_TokenObject(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.TokenObject token_tokenobject)
	{
		if (token_tokenobject == null)
			getMendixObject().setValue(context, MemberNames.Token_TokenObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Token_TokenObject.toString(), token_tokenobject.getMendixObject().getId());
	}

	/**
	 * @return value of Token_TokenReplacer
	 */
	public final bizzomatetokenreplacer.proxies.TokenReplacer getToken_TokenReplacer() throws com.mendix.core.CoreException
	{
		return getToken_TokenReplacer(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_TokenReplacer
	 */
	public final bizzomatetokenreplacer.proxies.TokenReplacer getToken_TokenReplacer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bizzomatetokenreplacer.proxies.TokenReplacer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_TokenReplacer.toString());
		if (identifier != null)
			result = bizzomatetokenreplacer.proxies.TokenReplacer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Token_TokenReplacer
	 * @param token_tokenreplacer
	 */
	public final void setToken_TokenReplacer(bizzomatetokenreplacer.proxies.TokenReplacer token_tokenreplacer)
	{
		setToken_TokenReplacer(getContext(), token_tokenreplacer);
	}

	/**
	 * Set value of Token_TokenReplacer
	 * @param context
	 * @param token_tokenreplacer
	 */
	public final void setToken_TokenReplacer(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.TokenReplacer token_tokenreplacer)
	{
		if (token_tokenreplacer == null)
			getMendixObject().setValue(context, MemberNames.Token_TokenReplacer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Token_TokenReplacer.toString(), token_tokenreplacer.getMendixObject().getId());
	}

	/**
	 * @return value of Token_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getToken_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getToken_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getToken_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Token_MxObjectMember
	 * @param token_mxobjectmember
	 */
	public final void setToken_MxObjectMember(mxmodelreflection.proxies.MxObjectMember token_mxobjectmember)
	{
		setToken_MxObjectMember(getContext(), token_mxobjectmember);
	}

	/**
	 * Set value of Token_MxObjectMember
	 * @param context
	 * @param token_mxobjectmember
	 */
	public final void setToken_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember token_mxobjectmember)
	{
		if (token_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.Token_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Token_MxObjectMember.toString(), token_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return value of Token_Intermediate
	 */
	public final dynamicform.proxies.Intermediate getToken_Intermediate() throws com.mendix.core.CoreException
	{
		return getToken_Intermediate(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_Intermediate
	 */
	public final dynamicform.proxies.Intermediate getToken_Intermediate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Intermediate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_Intermediate.toString());
		if (identifier != null)
			result = dynamicform.proxies.Intermediate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Token_Intermediate
	 * @param token_intermediate
	 */
	public final void setToken_Intermediate(dynamicform.proxies.Intermediate token_intermediate)
	{
		setToken_Intermediate(getContext(), token_intermediate);
	}

	/**
	 * Set value of Token_Intermediate
	 * @param context
	 * @param token_intermediate
	 */
	public final void setToken_Intermediate(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Intermediate token_intermediate)
	{
		if (token_intermediate == null)
			getMendixObject().setValue(context, MemberNames.Token_Intermediate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Token_Intermediate.toString(), token_intermediate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bizzomatetokenreplacer.proxies.Token that = (bizzomatetokenreplacer.proxies.Token) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BizzomateTokenReplacer.Token";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
