// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bizzomatetokenreplacer.proxies;

public class TokenReplacer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tokenReplacerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BizzomateTokenReplacer.TokenReplacer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UUID("UUID"),
		Title("Title"),
		Description("Description"),
		IsGenerated("IsGenerated"),
		TokenObject_TokenReplacer_Main("BizzomateTokenReplacer.TokenObject_TokenReplacer_Main");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TokenReplacer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BizzomateTokenReplacer.TokenReplacer"));
	}

	protected TokenReplacer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tokenReplacerMendixObject)
	{
		if (tokenReplacerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BizzomateTokenReplacer.TokenReplacer", tokenReplacerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BizzomateTokenReplacer.TokenReplacer");

		this.tokenReplacerMendixObject = tokenReplacerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TokenReplacer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bizzomatetokenreplacer.proxies.TokenReplacer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bizzomatetokenreplacer.proxies.TokenReplacer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bizzomatetokenreplacer.proxies.TokenReplacer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bizzomatetokenreplacer.proxies.TokenReplacer(context, mendixObject);
	}

	public static bizzomatetokenreplacer.proxies.TokenReplacer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bizzomatetokenreplacer.proxies.TokenReplacer.initialize(context, mendixObject);
	}

	public static java.util.List<bizzomatetokenreplacer.proxies.TokenReplacer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<bizzomatetokenreplacer.proxies.TokenReplacer> result = new java.util.ArrayList<bizzomatetokenreplacer.proxies.TokenReplacer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BizzomateTokenReplacer.TokenReplacer" + xpathConstraint))
			result.add(bizzomatetokenreplacer.proxies.TokenReplacer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of IsGenerated
	 */
	public final java.lang.Boolean getIsGenerated()
	{
		return getIsGenerated(getContext());
	}

	/**
	 * @param context
	 * @return value of IsGenerated
	 */
	public final java.lang.Boolean getIsGenerated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsGenerated.toString());
	}

	/**
	 * Set value of IsGenerated
	 * @param isgenerated
	 */
	public final void setIsGenerated(java.lang.Boolean isgenerated)
	{
		setIsGenerated(getContext(), isgenerated);
	}

	/**
	 * Set value of IsGenerated
	 * @param context
	 * @param isgenerated
	 */
	public final void setIsGenerated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isgenerated)
	{
		getMendixObject().setValue(context, MemberNames.IsGenerated.toString(), isgenerated);
	}

	/**
	 * @return value of TokenObject_TokenReplacer_Main
	 */
	public final bizzomatetokenreplacer.proxies.TokenObject getTokenObject_TokenReplacer_Main() throws com.mendix.core.CoreException
	{
		return getTokenObject_TokenReplacer_Main(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenObject_TokenReplacer_Main
	 */
	public final bizzomatetokenreplacer.proxies.TokenObject getTokenObject_TokenReplacer_Main(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bizzomatetokenreplacer.proxies.TokenObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TokenObject_TokenReplacer_Main.toString());
		if (identifier != null)
			result = bizzomatetokenreplacer.proxies.TokenObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TokenObject_TokenReplacer_Main
	 * @param tokenobject_tokenreplacer_main
	 */
	public final void setTokenObject_TokenReplacer_Main(bizzomatetokenreplacer.proxies.TokenObject tokenobject_tokenreplacer_main)
	{
		setTokenObject_TokenReplacer_Main(getContext(), tokenobject_tokenreplacer_main);
	}

	/**
	 * Set value of TokenObject_TokenReplacer_Main
	 * @param context
	 * @param tokenobject_tokenreplacer_main
	 */
	public final void setTokenObject_TokenReplacer_Main(com.mendix.systemwideinterfaces.core.IContext context, bizzomatetokenreplacer.proxies.TokenObject tokenobject_tokenreplacer_main)
	{
		if (tokenobject_tokenreplacer_main == null)
			getMendixObject().setValue(context, MemberNames.TokenObject_TokenReplacer_Main.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TokenObject_TokenReplacer_Main.toString(), tokenobject_tokenreplacer_main.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tokenReplacerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bizzomatetokenreplacer.proxies.TokenReplacer that = (bizzomatetokenreplacer.proxies.TokenReplacer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BizzomateTokenReplacer.TokenReplacer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
