// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the UGS module

	public static java.lang.String getDatasetId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.DatasetId");
	}

	public static java.lang.String getEmbedUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.EmbedUrl");
	}

	public static java.lang.String getGroupId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.GroupId");
	}

	public static java.lang.String getReportId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.ReportId");
	}
}