// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the UGS module

	/**
	* Custom header to include in exported CSV data. Do not include a newline character.
	*/
	public static java.lang.String getCSV_EXPORT_HEADER()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.CSV_EXPORT_HEADER");
	}

	public static java.lang.String getDatasetId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.DatasetId");
	}

	public static java.lang.String getEmbedUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.EmbedUrl");
	}

	public static java.lang.String getGroupId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.GroupId");
	}

	public static java.lang.String getLOGNODE_DATATABLES_EXPORT()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.LOGNODE_DATATABLES_EXPORT");
	}

	public static java.lang.String getReportId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("UGS.ReportId");
	}
}