// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class ApplicationForm
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject applicationFormMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.ApplicationForm";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApplicationFormName("ApplicationFormName"),
		Template_ApplicationForm_Dummy("DynamicForm.Template_ApplicationForm_Dummy"),
		ApplicationForm_GrantSystem("DynamicForm.ApplicationForm_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApplicationForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.ApplicationForm"));
	}

	protected ApplicationForm(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject applicationFormMendixObject)
	{
		if (applicationFormMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.ApplicationForm", applicationFormMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.ApplicationForm");

		this.applicationFormMendixObject = applicationFormMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ApplicationForm.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.ApplicationForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.ApplicationForm.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.ApplicationForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.ApplicationForm(context, mendixObject);
	}

	public static dynamicform.proxies.ApplicationForm load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.ApplicationForm.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.ApplicationForm> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.ApplicationForm> result = new java.util.ArrayList<dynamicform.proxies.ApplicationForm>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.ApplicationForm" + xpathConstraint))
			result.add(dynamicform.proxies.ApplicationForm.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApplicationFormName
	 */
	public final java.lang.String getApplicationFormName()
	{
		return getApplicationFormName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationFormName
	 */
	public final java.lang.String getApplicationFormName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationFormName.toString());
	}

	/**
	 * Set value of ApplicationFormName
	 * @param applicationformname
	 */
	public final void setApplicationFormName(java.lang.String applicationformname)
	{
		setApplicationFormName(getContext(), applicationformname);
	}

	/**
	 * Set value of ApplicationFormName
	 * @param context
	 * @param applicationformname
	 */
	public final void setApplicationFormName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationformname)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationFormName.toString(), applicationformname);
	}

	/**
	 * @return value of Template_ApplicationForm_Dummy
	 */
	public final dynamicform.proxies.Template getTemplate_ApplicationForm_Dummy() throws com.mendix.core.CoreException
	{
		return getTemplate_ApplicationForm_Dummy(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_ApplicationForm_Dummy
	 */
	public final dynamicform.proxies.Template getTemplate_ApplicationForm_Dummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_ApplicationForm_Dummy.toString());
		if (identifier != null)
			result = dynamicform.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_ApplicationForm_Dummy
	 * @param template_applicationform_dummy
	 */
	public final void setTemplate_ApplicationForm_Dummy(dynamicform.proxies.Template template_applicationform_dummy)
	{
		setTemplate_ApplicationForm_Dummy(getContext(), template_applicationform_dummy);
	}

	/**
	 * Set value of Template_ApplicationForm_Dummy
	 * @param context
	 * @param template_applicationform_dummy
	 */
	public final void setTemplate_ApplicationForm_Dummy(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Template template_applicationform_dummy)
	{
		if (template_applicationform_dummy == null)
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm_Dummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm_Dummy.toString(), template_applicationform_dummy.getMendixObject().getId());
	}

	/**
	 * @return value of ApplicationForm_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getApplicationForm_GrantSystem() throws com.mendix.core.CoreException
	{
		return getApplicationForm_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationForm_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getApplicationForm_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApplicationForm_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ApplicationForm_GrantSystem
	 * @param applicationform_grantsystem
	 */
	public final void setApplicationForm_GrantSystem(ugs.proxies.GrantSystem applicationform_grantsystem)
	{
		setApplicationForm_GrantSystem(getContext(), applicationform_grantsystem);
	}

	/**
	 * Set value of ApplicationForm_GrantSystem
	 * @param context
	 * @param applicationform_grantsystem
	 */
	public final void setApplicationForm_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem applicationform_grantsystem)
	{
		if (applicationform_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.ApplicationForm_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ApplicationForm_GrantSystem.toString(), applicationform_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return applicationFormMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.ApplicationForm that = (dynamicform.proxies.ApplicationForm) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.ApplicationForm";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
