// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Country extends dynamicform.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Country";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CountryValue("CountryValue"),
		NameoftheAttribute("NameoftheAttribute"),
		Required("Required"),
		LayoutNo("LayoutNo"),
		LayoutType("LayoutType"),
		Validation("Validation"),
		Element_Template("DynamicForm.Element_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Country"));
	}

	protected Country(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject)
	{
		super(context, countryMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Country", countryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Country");
	}

	/**
	 * @deprecated Use 'Country.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Country.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Country(context, mendixObject);
	}

	public static dynamicform.proxies.Country load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Country.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Country> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Country> result = new java.util.ArrayList<dynamicform.proxies.Country>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Country" + xpathConstraint))
			result.add(dynamicform.proxies.Country.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of CountryValue
	 * @param countryvalue
	 */
	public final countriesv5.proxies.Countries getCountryValue()
	{
		return getCountryValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryValue
	 */
	public final countriesv5.proxies.Countries getCountryValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CountryValue.toString());
		if (obj == null)
			return null;

		return countriesv5.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CountryValue
	 * @param countryvalue
	 */
	public final void setCountryValue(countriesv5.proxies.Countries countryvalue)
	{
		setCountryValue(getContext(), countryvalue);
	}

	/**
	 * Set value of CountryValue
	 * @param context
	 * @param countryvalue
	 */
	public final void setCountryValue(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Countries countryvalue)
	{
		if (countryvalue != null)
			getMendixObject().setValue(context, MemberNames.CountryValue.toString(), countryvalue.toString());
		else
			getMendixObject().setValue(context, MemberNames.CountryValue.toString(), null);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Country that = (dynamicform.proxies.Country) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Country";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
