// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class DateAndTime extends dynamicform.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.DateAndTime";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateValue("DateValue"),
		PastDateValidation("PastDateValidation"),
		FutureDateValidation("FutureDateValidation"),
		NameoftheAttribute("NameoftheAttribute"),
		Required("Required"),
		LayoutNo("LayoutNo"),
		LayoutType("LayoutType"),
		Validation("Validation"),
		Element_Template("DynamicForm.Element_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DateAndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.DateAndTime"));
	}

	protected DateAndTime(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dateAndTimeMendixObject)
	{
		super(context, dateAndTimeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.DateAndTime", dateAndTimeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.DateAndTime");
	}

	/**
	 * @deprecated Use 'DateAndTime.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.DateAndTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.DateAndTime.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.DateAndTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.DateAndTime(context, mendixObject);
	}

	public static dynamicform.proxies.DateAndTime load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.DateAndTime.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.DateAndTime> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.DateAndTime> result = new java.util.ArrayList<dynamicform.proxies.DateAndTime>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.DateAndTime" + xpathConstraint))
			result.add(dynamicform.proxies.DateAndTime.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DateValue
	 */
	public final java.util.Date getDateValue()
	{
		return getDateValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateValue
	 */
	public final java.util.Date getDateValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateValue.toString());
	}

	/**
	 * Set value of DateValue
	 * @param datevalue
	 */
	public final void setDateValue(java.util.Date datevalue)
	{
		setDateValue(getContext(), datevalue);
	}

	/**
	 * Set value of DateValue
	 * @param context
	 * @param datevalue
	 */
	public final void setDateValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateValue.toString(), datevalue);
	}

	/**
	 * @return value of PastDateValidation
	 */
	public final java.lang.Boolean getPastDateValidation()
	{
		return getPastDateValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of PastDateValidation
	 */
	public final java.lang.Boolean getPastDateValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PastDateValidation.toString());
	}

	/**
	 * Set value of PastDateValidation
	 * @param pastdatevalidation
	 */
	public final void setPastDateValidation(java.lang.Boolean pastdatevalidation)
	{
		setPastDateValidation(getContext(), pastdatevalidation);
	}

	/**
	 * Set value of PastDateValidation
	 * @param context
	 * @param pastdatevalidation
	 */
	public final void setPastDateValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean pastdatevalidation)
	{
		getMendixObject().setValue(context, MemberNames.PastDateValidation.toString(), pastdatevalidation);
	}

	/**
	 * @return value of FutureDateValidation
	 */
	public final java.lang.Boolean getFutureDateValidation()
	{
		return getFutureDateValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of FutureDateValidation
	 */
	public final java.lang.Boolean getFutureDateValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FutureDateValidation.toString());
	}

	/**
	 * Set value of FutureDateValidation
	 * @param futuredatevalidation
	 */
	public final void setFutureDateValidation(java.lang.Boolean futuredatevalidation)
	{
		setFutureDateValidation(getContext(), futuredatevalidation);
	}

	/**
	 * Set value of FutureDateValidation
	 * @param context
	 * @param futuredatevalidation
	 */
	public final void setFutureDateValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean futuredatevalidation)
	{
		getMendixObject().setValue(context, MemberNames.FutureDateValidation.toString(), futuredatevalidation);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.DateAndTime that = (dynamicform.proxies.DateAndTime) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.DateAndTime";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
