// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Element
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject elementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Element";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NameoftheAttribute("NameoftheAttribute"),
		Required("Required"),
		LayoutNo("LayoutNo"),
		LayoutType("LayoutType"),
		Validation("Validation"),
		Element_Template("DynamicForm.Element_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Element(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Element"));
	}

	protected Element(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject elementMendixObject)
	{
		if (elementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Element", elementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Element");

		this.elementMendixObject = elementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Element.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Element initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Element.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Element initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Address", mendixObject.getType()))
			return dynamicform.proxies.Address.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Boolean_", mendixObject.getType()))
			return dynamicform.proxies.Boolean_.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Country", mendixObject.getType()))
			return dynamicform.proxies.Country.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.DateAndTime", mendixObject.getType()))
			return dynamicform.proxies.DateAndTime.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Decimal", mendixObject.getType()))
			return dynamicform.proxies.Decimal.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Doc", mendixObject.getType()))
			return dynamicform.proxies.Doc.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Enumeration", mendixObject.getType()))
			return dynamicform.proxies.Enumeration.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.LongAnswer", mendixObject.getType()))
			return dynamicform.proxies.LongAnswer.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.Number", mendixObject.getType()))
			return dynamicform.proxies.Number.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.PhoneNumber", mendixObject.getType()))
			return dynamicform.proxies.PhoneNumber.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.ShortAnswer", mendixObject.getType()))
			return dynamicform.proxies.ShortAnswer.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DynamicForm.String", mendixObject.getType()))
			return dynamicform.proxies.String.initialize(context, mendixObject);

		return new dynamicform.proxies.Element(context, mendixObject);
	}

	public static dynamicform.proxies.Element load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Element.initialize(context, mendixObject);
	}

	public static java.util.List<? extends dynamicform.proxies.Element> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Element> result = new java.util.ArrayList<dynamicform.proxies.Element>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Element" + xpathConstraint))
			result.add(dynamicform.proxies.Element.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NameoftheAttribute
	 */
	public final java.lang.String getNameoftheAttribute()
	{
		return getNameoftheAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of NameoftheAttribute
	 */
	public final java.lang.String getNameoftheAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameoftheAttribute.toString());
	}

	/**
	 * Set value of NameoftheAttribute
	 * @param nameoftheattribute
	 */
	public final void setNameoftheAttribute(java.lang.String nameoftheattribute)
	{
		setNameoftheAttribute(getContext(), nameoftheattribute);
	}

	/**
	 * Set value of NameoftheAttribute
	 * @param context
	 * @param nameoftheattribute
	 */
	public final void setNameoftheAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameoftheattribute)
	{
		getMendixObject().setValue(context, MemberNames.NameoftheAttribute.toString(), nameoftheattribute);
	}

	/**
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired()
	{
		return getRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Required.toString());
	}

	/**
	 * Set value of Required
	 * @param required
	 */
	public final void setRequired(java.lang.Boolean required)
	{
		setRequired(getContext(), required);
	}

	/**
	 * Set value of Required
	 * @param context
	 * @param required
	 */
	public final void setRequired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean required)
	{
		getMendixObject().setValue(context, MemberNames.Required.toString(), required);
	}

	/**
	 * @return value of LayoutNo
	 */
	public final java.lang.Integer getLayoutNo()
	{
		return getLayoutNo(getContext());
	}

	/**
	 * @param context
	 * @return value of LayoutNo
	 */
	public final java.lang.Integer getLayoutNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LayoutNo.toString());
	}

	/**
	 * Set value of LayoutNo
	 * @param layoutno
	 */
	public final void setLayoutNo(java.lang.Integer layoutno)
	{
		setLayoutNo(getContext(), layoutno);
	}

	/**
	 * Set value of LayoutNo
	 * @param context
	 * @param layoutno
	 */
	public final void setLayoutNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer layoutno)
	{
		getMendixObject().setValue(context, MemberNames.LayoutNo.toString(), layoutno);
	}

	/**
	 * Set value of LayoutType
	 * @param layouttype
	 */
	public final dynamicform.proxies.Enum_LayoutType getLayoutType()
	{
		return getLayoutType(getContext());
	}

	/**
	 * @param context
	 * @return value of LayoutType
	 */
	public final dynamicform.proxies.Enum_LayoutType getLayoutType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LayoutType.toString());
		if (obj == null)
			return null;

		return dynamicform.proxies.Enum_LayoutType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LayoutType
	 * @param layouttype
	 */
	public final void setLayoutType(dynamicform.proxies.Enum_LayoutType layouttype)
	{
		setLayoutType(getContext(), layouttype);
	}

	/**
	 * Set value of LayoutType
	 * @param context
	 * @param layouttype
	 */
	public final void setLayoutType(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Enum_LayoutType layouttype)
	{
		if (layouttype != null)
			getMendixObject().setValue(context, MemberNames.LayoutType.toString(), layouttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.LayoutType.toString(), null);
	}

	/**
	 * @return value of Validation
	 */
	public final java.lang.Boolean getValidation()
	{
		return getValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of Validation
	 */
	public final java.lang.Boolean getValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Validation.toString());
	}

	/**
	 * Set value of Validation
	 * @param validation
	 */
	public final void setValidation(java.lang.Boolean validation)
	{
		setValidation(getContext(), validation);
	}

	/**
	 * Set value of Validation
	 * @param context
	 * @param validation
	 */
	public final void setValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean validation)
	{
		getMendixObject().setValue(context, MemberNames.Validation.toString(), validation);
	}

	/**
	 * @return value of Element_Template
	 */
	public final dynamicform.proxies.Template getElement_Template() throws com.mendix.core.CoreException
	{
		return getElement_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Element_Template
	 */
	public final dynamicform.proxies.Template getElement_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Element_Template.toString());
		if (identifier != null)
			result = dynamicform.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Element_Template
	 * @param element_template
	 */
	public final void setElement_Template(dynamicform.proxies.Template element_template)
	{
		setElement_Template(getContext(), element_template);
	}

	/**
	 * Set value of Element_Template
	 * @param context
	 * @param element_template
	 */
	public final void setElement_Template(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Template element_template)
	{
		if (element_template == null)
			getMendixObject().setValue(context, MemberNames.Element_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Element_Template.toString(), element_template.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return elementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Element that = (dynamicform.proxies.Element) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Element";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
