// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Grant extends system.proxies.WorkflowContext
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Grant";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MainHeading("MainHeading"),
		SubHeading("SubHeading"),
		ExpiryDate("ExpiryDate"),
		CurrentOrderNumber("CurrentOrderNumber"),
		FlowchartString("FlowchartString"),
		Grant_WorkflowUserTask("DynamicForm.Grant_WorkflowUserTask"),
		Grant_AllWorkflowUserTask("DynamicForm.Grant_AllWorkflowUserTask"),
		WorkflowInstance_WorkflowContext("System.WorkflowInstance_WorkflowContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Grant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Grant"));
	}

	protected Grant(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject grantMendixObject)
	{
		super(context, grantMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Grant", grantMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Grant");
	}

	/**
	 * @deprecated Use 'Grant.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Grant initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Grant.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Grant initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Grant(context, mendixObject);
	}

	public static dynamicform.proxies.Grant load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Grant.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Grant> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Grant> result = new java.util.ArrayList<dynamicform.proxies.Grant>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Grant" + xpathConstraint))
			result.add(dynamicform.proxies.Grant.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of MainHeading
	 */
	public final java.lang.String getMainHeading()
	{
		return getMainHeading(getContext());
	}

	/**
	 * @param context
	 * @return value of MainHeading
	 */
	public final java.lang.String getMainHeading(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MainHeading.toString());
	}

	/**
	 * Set value of MainHeading
	 * @param mainheading
	 */
	public final void setMainHeading(java.lang.String mainheading)
	{
		setMainHeading(getContext(), mainheading);
	}

	/**
	 * Set value of MainHeading
	 * @param context
	 * @param mainheading
	 */
	public final void setMainHeading(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mainheading)
	{
		getMendixObject().setValue(context, MemberNames.MainHeading.toString(), mainheading);
	}

	/**
	 * @return value of SubHeading
	 */
	public final java.lang.String getSubHeading()
	{
		return getSubHeading(getContext());
	}

	/**
	 * @param context
	 * @return value of SubHeading
	 */
	public final java.lang.String getSubHeading(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubHeading.toString());
	}

	/**
	 * Set value of SubHeading
	 * @param subheading
	 */
	public final void setSubHeading(java.lang.String subheading)
	{
		setSubHeading(getContext(), subheading);
	}

	/**
	 * Set value of SubHeading
	 * @param context
	 * @param subheading
	 */
	public final void setSubHeading(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subheading)
	{
		getMendixObject().setValue(context, MemberNames.SubHeading.toString(), subheading);
	}

	/**
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate()
	{
		return getExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpiryDate.toString());
	}

	/**
	 * Set value of ExpiryDate
	 * @param expirydate
	 */
	public final void setExpiryDate(java.util.Date expirydate)
	{
		setExpiryDate(getContext(), expirydate);
	}

	/**
	 * Set value of ExpiryDate
	 * @param context
	 * @param expirydate
	 */
	public final void setExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirydate)
	{
		getMendixObject().setValue(context, MemberNames.ExpiryDate.toString(), expirydate);
	}

	/**
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber()
	{
		return getCurrentOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentOrderNumber.toString());
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(java.lang.Integer currentordernumber)
	{
		setCurrentOrderNumber(getContext(), currentordernumber);
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param context
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentordernumber)
	{
		getMendixObject().setValue(context, MemberNames.CurrentOrderNumber.toString(), currentordernumber);
	}

	/**
	 * @return value of FlowchartString
	 */
	public final java.lang.String getFlowchartString()
	{
		return getFlowchartString(getContext());
	}

	/**
	 * @param context
	 * @return value of FlowchartString
	 */
	public final java.lang.String getFlowchartString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FlowchartString.toString());
	}

	/**
	 * Set value of FlowchartString
	 * @param flowchartstring
	 */
	public final void setFlowchartString(java.lang.String flowchartstring)
	{
		setFlowchartString(getContext(), flowchartstring);
	}

	/**
	 * Set value of FlowchartString
	 * @param context
	 * @param flowchartstring
	 */
	public final void setFlowchartString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flowchartstring)
	{
		getMendixObject().setValue(context, MemberNames.FlowchartString.toString(), flowchartstring);
	}

	/**
	 * @return value of Grant_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrant_WorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getGrant_WorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Grant_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrant_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Grant_WorkflowUserTask.toString());
		if (identifier != null)
			result = system.proxies.WorkflowUserTask.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Grant_WorkflowUserTask
	 * @param grant_workflowusertask
	 */
	public final void setGrant_WorkflowUserTask(system.proxies.WorkflowUserTask grant_workflowusertask)
	{
		setGrant_WorkflowUserTask(getContext(), grant_workflowusertask);
	}

	/**
	 * Set value of Grant_WorkflowUserTask
	 * @param context
	 * @param grant_workflowusertask
	 */
	public final void setGrant_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTask grant_workflowusertask)
	{
		if (grant_workflowusertask == null)
			getMendixObject().setValue(context, MemberNames.Grant_WorkflowUserTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Grant_WorkflowUserTask.toString(), grant_workflowusertask.getMendixObject().getId());
	}

	/**
	 * @return value of Grant_AllWorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrant_AllWorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getGrant_AllWorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Grant_AllWorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrant_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Grant_AllWorkflowUserTask.toString());
		if (identifier != null)
			result = system.proxies.WorkflowUserTask.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Grant_AllWorkflowUserTask
	 * @param grant_allworkflowusertask
	 */
	public final void setGrant_AllWorkflowUserTask(system.proxies.WorkflowUserTask grant_allworkflowusertask)
	{
		setGrant_AllWorkflowUserTask(getContext(), grant_allworkflowusertask);
	}

	/**
	 * Set value of Grant_AllWorkflowUserTask
	 * @param context
	 * @param grant_allworkflowusertask
	 */
	public final void setGrant_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTask grant_allworkflowusertask)
	{
		if (grant_allworkflowusertask == null)
			getMendixObject().setValue(context, MemberNames.Grant_AllWorkflowUserTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Grant_AllWorkflowUserTask.toString(), grant_allworkflowusertask.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Grant that = (dynamicform.proxies.Grant) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Grant";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
