// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Icons
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject iconsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Icons";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IconName("IconName"),
		IconClass("IconClass");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Icons(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Icons"));
	}

	protected Icons(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject iconsMendixObject)
	{
		if (iconsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Icons", iconsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Icons");

		this.iconsMendixObject = iconsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Icons.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Icons initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Icons.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Icons initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Icons(context, mendixObject);
	}

	public static dynamicform.proxies.Icons load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Icons.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Icons> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Icons> result = new java.util.ArrayList<dynamicform.proxies.Icons>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Icons" + xpathConstraint))
			result.add(dynamicform.proxies.Icons.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of IconName
	 */
	public final java.lang.String getIconName()
	{
		return getIconName(getContext());
	}

	/**
	 * @param context
	 * @return value of IconName
	 */
	public final java.lang.String getIconName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IconName.toString());
	}

	/**
	 * Set value of IconName
	 * @param iconname
	 */
	public final void setIconName(java.lang.String iconname)
	{
		setIconName(getContext(), iconname);
	}

	/**
	 * Set value of IconName
	 * @param context
	 * @param iconname
	 */
	public final void setIconName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iconname)
	{
		getMendixObject().setValue(context, MemberNames.IconName.toString(), iconname);
	}

	/**
	 * @return value of IconClass
	 */
	public final java.lang.String getIconClass()
	{
		return getIconClass(getContext());
	}

	/**
	 * @param context
	 * @return value of IconClass
	 */
	public final java.lang.String getIconClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IconClass.toString());
	}

	/**
	 * Set value of IconClass
	 * @param iconclass
	 */
	public final void setIconClass(java.lang.String iconclass)
	{
		setIconClass(getContext(), iconclass);
	}

	/**
	 * Set value of IconClass
	 * @param context
	 * @param iconclass
	 */
	public final void setIconClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iconclass)
	{
		getMendixObject().setValue(context, MemberNames.IconClass.toString(), iconclass);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return iconsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Icons that = (dynamicform.proxies.Icons) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Icons";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
