// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class ShortAnswer extends dynamicform.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.ShortAnswer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShortAns_Value("ShortAns_Value"),
		Max_No_Of_Words("Max_No_Of_Words"),
		Remaining_Words("Remaining_Words"),
		NameoftheAttribute("NameoftheAttribute"),
		Required("Required"),
		LayoutNo("LayoutNo"),
		LayoutType("LayoutType"),
		Validation("Validation"),
		Element_Template("DynamicForm.Element_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ShortAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.ShortAnswer"));
	}

	protected ShortAnswer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject shortAnswerMendixObject)
	{
		super(context, shortAnswerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.ShortAnswer", shortAnswerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.ShortAnswer");
	}

	/**
	 * @deprecated Use 'ShortAnswer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.ShortAnswer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.ShortAnswer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.ShortAnswer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.ShortAnswer(context, mendixObject);
	}

	public static dynamicform.proxies.ShortAnswer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.ShortAnswer.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.ShortAnswer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.ShortAnswer> result = new java.util.ArrayList<dynamicform.proxies.ShortAnswer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.ShortAnswer" + xpathConstraint))
			result.add(dynamicform.proxies.ShortAnswer.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ShortAns_Value
	 */
	public final java.lang.String getShortAns_Value()
	{
		return getShortAns_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of ShortAns_Value
	 */
	public final java.lang.String getShortAns_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShortAns_Value.toString());
	}

	/**
	 * Set value of ShortAns_Value
	 * @param shortans_value
	 */
	public final void setShortAns_Value(java.lang.String shortans_value)
	{
		setShortAns_Value(getContext(), shortans_value);
	}

	/**
	 * Set value of ShortAns_Value
	 * @param context
	 * @param shortans_value
	 */
	public final void setShortAns_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shortans_value)
	{
		getMendixObject().setValue(context, MemberNames.ShortAns_Value.toString(), shortans_value);
	}

	/**
	 * @return value of Max_No_Of_Words
	 */
	public final java.lang.Integer getMax_No_Of_Words()
	{
		return getMax_No_Of_Words(getContext());
	}

	/**
	 * @param context
	 * @return value of Max_No_Of_Words
	 */
	public final java.lang.Integer getMax_No_Of_Words(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Max_No_Of_Words.toString());
	}

	/**
	 * Set value of Max_No_Of_Words
	 * @param max_no_of_words
	 */
	public final void setMax_No_Of_Words(java.lang.Integer max_no_of_words)
	{
		setMax_No_Of_Words(getContext(), max_no_of_words);
	}

	/**
	 * Set value of Max_No_Of_Words
	 * @param context
	 * @param max_no_of_words
	 */
	public final void setMax_No_Of_Words(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer max_no_of_words)
	{
		getMendixObject().setValue(context, MemberNames.Max_No_Of_Words.toString(), max_no_of_words);
	}

	/**
	 * @return value of Remaining_Words
	 */
	public final java.lang.Integer getRemaining_Words()
	{
		return getRemaining_Words(getContext());
	}

	/**
	 * @param context
	 * @return value of Remaining_Words
	 */
	public final java.lang.Integer getRemaining_Words(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Remaining_Words.toString());
	}

	/**
	 * Set value of Remaining_Words
	 * @param remaining_words
	 */
	public final void setRemaining_Words(java.lang.Integer remaining_words)
	{
		setRemaining_Words(getContext(), remaining_words);
	}

	/**
	 * Set value of Remaining_Words
	 * @param context
	 * @param remaining_words
	 */
	public final void setRemaining_Words(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer remaining_words)
	{
		getMendixObject().setValue(context, MemberNames.Remaining_Words.toString(), remaining_words);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.ShortAnswer that = (dynamicform.proxies.ShortAnswer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.ShortAnswer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
