// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Status
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject statusMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Status";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StatusName("StatusName"),
		Status_WorkflowRoles("DynamicForm.Status_WorkflowRoles");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Status"));
	}

	protected Status(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject statusMendixObject)
	{
		if (statusMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Status", statusMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Status");

		this.statusMendixObject = statusMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Status.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Status initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Status.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Status initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Status(context, mendixObject);
	}

	public static dynamicform.proxies.Status load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Status.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Status> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Status> result = new java.util.ArrayList<dynamicform.proxies.Status>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Status" + xpathConstraint))
			result.add(dynamicform.proxies.Status.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StatusName
	 */
	public final java.lang.String getStatusName()
	{
		return getStatusName(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusName
	 */
	public final java.lang.String getStatusName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusName.toString());
	}

	/**
	 * Set value of StatusName
	 * @param statusname
	 */
	public final void setStatusName(java.lang.String statusname)
	{
		setStatusName(getContext(), statusname);
	}

	/**
	 * Set value of StatusName
	 * @param context
	 * @param statusname
	 */
	public final void setStatusName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusname)
	{
		getMendixObject().setValue(context, MemberNames.StatusName.toString(), statusname);
	}

	/**
	 * @return value of Status_WorkflowRoles
	 */
	public final dynamicform.proxies.WorkflowRoles getStatus_WorkflowRoles() throws com.mendix.core.CoreException
	{
		return getStatus_WorkflowRoles(getContext());
	}

	/**
	 * @param context
	 * @return value of Status_WorkflowRoles
	 */
	public final dynamicform.proxies.WorkflowRoles getStatus_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.WorkflowRoles result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Status_WorkflowRoles.toString());
		if (identifier != null)
			result = dynamicform.proxies.WorkflowRoles.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Status_WorkflowRoles
	 * @param status_workflowroles
	 */
	public final void setStatus_WorkflowRoles(dynamicform.proxies.WorkflowRoles status_workflowroles)
	{
		setStatus_WorkflowRoles(getContext(), status_workflowroles);
	}

	/**
	 * Set value of Status_WorkflowRoles
	 * @param context
	 * @param status_workflowroles
	 */
	public final void setStatus_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.WorkflowRoles status_workflowroles)
	{
		if (status_workflowroles == null)
			getMendixObject().setValue(context, MemberNames.Status_WorkflowRoles.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Status_WorkflowRoles.toString(), status_workflowroles.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return statusMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Status that = (dynamicform.proxies.Status) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Status";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
