// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class String extends dynamicform.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.String";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StringValue("StringValue"),
		EmailValidation("EmailValidation"),
		StringLengthValidation("StringLengthValidation"),
		StringLength("StringLength"),
		WebsiteValidation("WebsiteValidation"),
		NameoftheAttribute("NameoftheAttribute"),
		Required("Required"),
		LayoutNo("LayoutNo"),
		LayoutType("LayoutType"),
		Validation("Validation"),
		Element_Template("DynamicForm.Element_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public String(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.String"));
	}

	protected String(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stringMendixObject)
	{
		super(context, stringMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.String", stringMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.String");
	}

	/**
	 * @deprecated Use 'String.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.String initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.String.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.String initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.String(context, mendixObject);
	}

	public static dynamicform.proxies.String load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.String.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.String> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.String> result = new java.util.ArrayList<dynamicform.proxies.String>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.String" + xpathConstraint))
			result.add(dynamicform.proxies.String.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return value of EmailValidation
	 */
	public final java.lang.Boolean getEmailValidation()
	{
		return getEmailValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailValidation
	 */
	public final java.lang.Boolean getEmailValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EmailValidation.toString());
	}

	/**
	 * Set value of EmailValidation
	 * @param emailvalidation
	 */
	public final void setEmailValidation(java.lang.Boolean emailvalidation)
	{
		setEmailValidation(getContext(), emailvalidation);
	}

	/**
	 * Set value of EmailValidation
	 * @param context
	 * @param emailvalidation
	 */
	public final void setEmailValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean emailvalidation)
	{
		getMendixObject().setValue(context, MemberNames.EmailValidation.toString(), emailvalidation);
	}

	/**
	 * @return value of StringLengthValidation
	 */
	public final java.lang.Boolean getStringLengthValidation()
	{
		return getStringLengthValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of StringLengthValidation
	 */
	public final java.lang.Boolean getStringLengthValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StringLengthValidation.toString());
	}

	/**
	 * Set value of StringLengthValidation
	 * @param stringlengthvalidation
	 */
	public final void setStringLengthValidation(java.lang.Boolean stringlengthvalidation)
	{
		setStringLengthValidation(getContext(), stringlengthvalidation);
	}

	/**
	 * Set value of StringLengthValidation
	 * @param context
	 * @param stringlengthvalidation
	 */
	public final void setStringLengthValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean stringlengthvalidation)
	{
		getMendixObject().setValue(context, MemberNames.StringLengthValidation.toString(), stringlengthvalidation);
	}

	/**
	 * @return value of StringLength
	 */
	public final java.lang.Integer getStringLength()
	{
		return getStringLength(getContext());
	}

	/**
	 * @param context
	 * @return value of StringLength
	 */
	public final java.lang.Integer getStringLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StringLength.toString());
	}

	/**
	 * Set value of StringLength
	 * @param stringlength
	 */
	public final void setStringLength(java.lang.Integer stringlength)
	{
		setStringLength(getContext(), stringlength);
	}

	/**
	 * Set value of StringLength
	 * @param context
	 * @param stringlength
	 */
	public final void setStringLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer stringlength)
	{
		getMendixObject().setValue(context, MemberNames.StringLength.toString(), stringlength);
	}

	/**
	 * @return value of WebsiteValidation
	 */
	public final java.lang.Boolean getWebsiteValidation()
	{
		return getWebsiteValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of WebsiteValidation
	 */
	public final java.lang.Boolean getWebsiteValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WebsiteValidation.toString());
	}

	/**
	 * Set value of WebsiteValidation
	 * @param websitevalidation
	 */
	public final void setWebsiteValidation(java.lang.Boolean websitevalidation)
	{
		setWebsiteValidation(getContext(), websitevalidation);
	}

	/**
	 * Set value of WebsiteValidation
	 * @param context
	 * @param websitevalidation
	 */
	public final void setWebsiteValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean websitevalidation)
	{
		getMendixObject().setValue(context, MemberNames.WebsiteValidation.toString(), websitevalidation);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.String that = (dynamicform.proxies.String) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.String";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
