// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Template extends system.proxies.WorkflowContext
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Template";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PermanentName("PermanentName"),
		Active("Active"),
		Form_Description("Form_Description"),
		Main("Main"),
		FormName("FormName"),
		FormNumber("FormNumber"),
		Submitted("Submitted"),
		CurrentOrderNumber("CurrentOrderNumber"),
		editable("editable"),
		noofcolumns("noofcolumns"),
		FlowchartString("FlowchartString"),
		SortOrder("SortOrder"),
		DynamicClass("DynamicClass"),
		IconClass("IconClass"),
		HasDocument("HasDocument"),
		Template_Grant("DynamicForm.Template_Grant"),
		Template_Icons("DynamicForm.Template_Icons"),
		Template_ApplicationForm("DynamicForm.Template_ApplicationForm"),
		Template_ApplicationForm_Dummy("DynamicForm.Template_ApplicationForm_Dummy"),
		GrantSystem_TemplateDummy("UGS.GrantSystem_TemplateDummy"),
		Formowner("DynamicForm.Formowner"),
		Template_WorkflowUserTask("DynamicForm.Template_WorkflowUserTask"),
		Template_AllWorkflowUserTask("DynamicForm.Template_AllWorkflowUserTask"),
		Template_GrantSystem("DynamicForm.Template_GrantSystem"),
		WorkflowInstance_WorkflowContext("System.WorkflowInstance_WorkflowContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Template(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.Template"));
	}

	protected Template(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject templateMendixObject)
	{
		super(context, templateMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.Template", templateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.Template");
	}

	/**
	 * @deprecated Use 'Template.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Template.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Template(context, mendixObject);
	}

	public static dynamicform.proxies.Template load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Template.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Template> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.Template> result = new java.util.ArrayList<dynamicform.proxies.Template>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.Template" + xpathConstraint))
			result.add(dynamicform.proxies.Template.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of PermanentName
	 */
	public final java.lang.String getPermanentName()
	{
		return getPermanentName(getContext());
	}

	/**
	 * @param context
	 * @return value of PermanentName
	 */
	public final java.lang.String getPermanentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PermanentName.toString());
	}

	/**
	 * Set value of PermanentName
	 * @param permanentname
	 */
	public final void setPermanentName(java.lang.String permanentname)
	{
		setPermanentName(getContext(), permanentname);
	}

	/**
	 * Set value of PermanentName
	 * @param context
	 * @param permanentname
	 */
	public final void setPermanentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String permanentname)
	{
		getMendixObject().setValue(context, MemberNames.PermanentName.toString(), permanentname);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of Form_Description
	 */
	public final java.lang.String getForm_Description()
	{
		return getForm_Description(getContext());
	}

	/**
	 * @param context
	 * @return value of Form_Description
	 */
	public final java.lang.String getForm_Description(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Form_Description.toString());
	}

	/**
	 * Set value of Form_Description
	 * @param form_description
	 */
	public final void setForm_Description(java.lang.String form_description)
	{
		setForm_Description(getContext(), form_description);
	}

	/**
	 * Set value of Form_Description
	 * @param context
	 * @param form_description
	 */
	public final void setForm_Description(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String form_description)
	{
		getMendixObject().setValue(context, MemberNames.Form_Description.toString(), form_description);
	}

	/**
	 * @return value of Main
	 */
	public final java.lang.Boolean getMain()
	{
		return getMain(getContext());
	}

	/**
	 * @param context
	 * @return value of Main
	 */
	public final java.lang.Boolean getMain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Main.toString());
	}

	/**
	 * Set value of Main
	 * @param main
	 */
	public final void setMain(java.lang.Boolean main)
	{
		setMain(getContext(), main);
	}

	/**
	 * Set value of Main
	 * @param context
	 * @param main
	 */
	public final void setMain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean main)
	{
		getMendixObject().setValue(context, MemberNames.Main.toString(), main);
	}

	/**
	 * @return value of FormName
	 */
	public final java.lang.String getFormName()
	{
		return getFormName(getContext());
	}

	/**
	 * @param context
	 * @return value of FormName
	 */
	public final java.lang.String getFormName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FormName.toString());
	}

	/**
	 * Set value of FormName
	 * @param formname
	 */
	public final void setFormName(java.lang.String formname)
	{
		setFormName(getContext(), formname);
	}

	/**
	 * Set value of FormName
	 * @param context
	 * @param formname
	 */
	public final void setFormName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String formname)
	{
		getMendixObject().setValue(context, MemberNames.FormName.toString(), formname);
	}

	/**
	 * @return value of FormNumber
	 */
	public final java.lang.Long getFormNumber()
	{
		return getFormNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of FormNumber
	 */
	public final java.lang.Long getFormNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.FormNumber.toString());
	}

	/**
	 * Set value of FormNumber
	 * @param formnumber
	 */
	public final void setFormNumber(java.lang.Long formnumber)
	{
		setFormNumber(getContext(), formnumber);
	}

	/**
	 * Set value of FormNumber
	 * @param context
	 * @param formnumber
	 */
	public final void setFormNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long formnumber)
	{
		getMendixObject().setValue(context, MemberNames.FormNumber.toString(), formnumber);
	}

	/**
	 * @return value of Submitted
	 */
	public final java.lang.Boolean getSubmitted()
	{
		return getSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of Submitted
	 */
	public final java.lang.Boolean getSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Submitted.toString());
	}

	/**
	 * Set value of Submitted
	 * @param submitted
	 */
	public final void setSubmitted(java.lang.Boolean submitted)
	{
		setSubmitted(getContext(), submitted);
	}

	/**
	 * Set value of Submitted
	 * @param context
	 * @param submitted
	 */
	public final void setSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean submitted)
	{
		getMendixObject().setValue(context, MemberNames.Submitted.toString(), submitted);
	}

	/**
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber()
	{
		return getCurrentOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentOrderNumber.toString());
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(java.lang.Integer currentordernumber)
	{
		setCurrentOrderNumber(getContext(), currentordernumber);
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param context
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentordernumber)
	{
		getMendixObject().setValue(context, MemberNames.CurrentOrderNumber.toString(), currentordernumber);
	}

	/**
	 * @return value of editable
	 */
	public final java.lang.Boolean geteditable()
	{
		return geteditable(getContext());
	}

	/**
	 * @param context
	 * @return value of editable
	 */
	public final java.lang.Boolean geteditable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.editable.toString());
	}

	/**
	 * Set value of editable
	 * @param editable
	 */
	public final void seteditable(java.lang.Boolean editable)
	{
		seteditable(getContext(), editable);
	}

	/**
	 * Set value of editable
	 * @param context
	 * @param editable
	 */
	public final void seteditable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean editable)
	{
		getMendixObject().setValue(context, MemberNames.editable.toString(), editable);
	}

	/**
	 * Set value of noofcolumns
	 * @param noofcolumns
	 */
	public final dynamicform.proxies.Enum_layout getnoofcolumns()
	{
		return getnoofcolumns(getContext());
	}

	/**
	 * @param context
	 * @return value of noofcolumns
	 */
	public final dynamicform.proxies.Enum_layout getnoofcolumns(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.noofcolumns.toString());
		if (obj == null)
			return null;

		return dynamicform.proxies.Enum_layout.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of noofcolumns
	 * @param noofcolumns
	 */
	public final void setnoofcolumns(dynamicform.proxies.Enum_layout noofcolumns)
	{
		setnoofcolumns(getContext(), noofcolumns);
	}

	/**
	 * Set value of noofcolumns
	 * @param context
	 * @param noofcolumns
	 */
	public final void setnoofcolumns(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Enum_layout noofcolumns)
	{
		if (noofcolumns != null)
			getMendixObject().setValue(context, MemberNames.noofcolumns.toString(), noofcolumns.toString());
		else
			getMendixObject().setValue(context, MemberNames.noofcolumns.toString(), null);
	}

	/**
	 * @return value of FlowchartString
	 */
	public final java.lang.String getFlowchartString()
	{
		return getFlowchartString(getContext());
	}

	/**
	 * @param context
	 * @return value of FlowchartString
	 */
	public final java.lang.String getFlowchartString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FlowchartString.toString());
	}

	/**
	 * Set value of FlowchartString
	 * @param flowchartstring
	 */
	public final void setFlowchartString(java.lang.String flowchartstring)
	{
		setFlowchartString(getContext(), flowchartstring);
	}

	/**
	 * Set value of FlowchartString
	 * @param context
	 * @param flowchartstring
	 */
	public final void setFlowchartString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flowchartstring)
	{
		getMendixObject().setValue(context, MemberNames.FlowchartString.toString(), flowchartstring);
	}

	/**
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder()
	{
		return getSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortOrder.toString());
	}

	/**
	 * Set value of SortOrder
	 * @param sortorder
	 */
	public final void setSortOrder(java.lang.Integer sortorder)
	{
		setSortOrder(getContext(), sortorder);
	}

	/**
	 * Set value of SortOrder
	 * @param context
	 * @param sortorder
	 */
	public final void setSortOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortorder)
	{
		getMendixObject().setValue(context, MemberNames.SortOrder.toString(), sortorder);
	}

	/**
	 * @return value of DynamicClass
	 */
	public final java.lang.String getDynamicClass()
	{
		return getDynamicClass(getContext());
	}

	/**
	 * @param context
	 * @return value of DynamicClass
	 */
	public final java.lang.String getDynamicClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DynamicClass.toString());
	}

	/**
	 * Set value of DynamicClass
	 * @param dynamicclass
	 */
	public final void setDynamicClass(java.lang.String dynamicclass)
	{
		setDynamicClass(getContext(), dynamicclass);
	}

	/**
	 * Set value of DynamicClass
	 * @param context
	 * @param dynamicclass
	 */
	public final void setDynamicClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dynamicclass)
	{
		getMendixObject().setValue(context, MemberNames.DynamicClass.toString(), dynamicclass);
	}

	/**
	 * @return value of IconClass
	 */
	public final java.lang.String getIconClass()
	{
		return getIconClass(getContext());
	}

	/**
	 * @param context
	 * @return value of IconClass
	 */
	public final java.lang.String getIconClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IconClass.toString());
	}

	/**
	 * Set value of IconClass
	 * @param iconclass
	 */
	public final void setIconClass(java.lang.String iconclass)
	{
		setIconClass(getContext(), iconclass);
	}

	/**
	 * Set value of IconClass
	 * @param context
	 * @param iconclass
	 */
	public final void setIconClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iconclass)
	{
		getMendixObject().setValue(context, MemberNames.IconClass.toString(), iconclass);
	}

	/**
	 * @return value of HasDocument
	 */
	public final java.lang.Boolean getHasDocument()
	{
		return getHasDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of HasDocument
	 */
	public final java.lang.Boolean getHasDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasDocument.toString());
	}

	/**
	 * Set value of HasDocument
	 * @param hasdocument
	 */
	public final void setHasDocument(java.lang.Boolean hasdocument)
	{
		setHasDocument(getContext(), hasdocument);
	}

	/**
	 * Set value of HasDocument
	 * @param context
	 * @param hasdocument
	 */
	public final void setHasDocument(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasdocument)
	{
		getMendixObject().setValue(context, MemberNames.HasDocument.toString(), hasdocument);
	}

	/**
	 * @return value of Template_Grant
	 */
	public final dynamicform.proxies.Grant getTemplate_Grant() throws com.mendix.core.CoreException
	{
		return getTemplate_Grant(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Grant
	 */
	public final dynamicform.proxies.Grant getTemplate_Grant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Grant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_Grant.toString());
		if (identifier != null)
			result = dynamicform.proxies.Grant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_Grant
	 * @param template_grant
	 */
	public final void setTemplate_Grant(dynamicform.proxies.Grant template_grant)
	{
		setTemplate_Grant(getContext(), template_grant);
	}

	/**
	 * Set value of Template_Grant
	 * @param context
	 * @param template_grant
	 */
	public final void setTemplate_Grant(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Grant template_grant)
	{
		if (template_grant == null)
			getMendixObject().setValue(context, MemberNames.Template_Grant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_Grant.toString(), template_grant.getMendixObject().getId());
	}

	/**
	 * @return value of Template_Icons
	 */
	public final dynamicform.proxies.Icons getTemplate_Icons() throws com.mendix.core.CoreException
	{
		return getTemplate_Icons(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Icons
	 */
	public final dynamicform.proxies.Icons getTemplate_Icons(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Icons result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_Icons.toString());
		if (identifier != null)
			result = dynamicform.proxies.Icons.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_Icons
	 * @param template_icons
	 */
	public final void setTemplate_Icons(dynamicform.proxies.Icons template_icons)
	{
		setTemplate_Icons(getContext(), template_icons);
	}

	/**
	 * Set value of Template_Icons
	 * @param context
	 * @param template_icons
	 */
	public final void setTemplate_Icons(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Icons template_icons)
	{
		if (template_icons == null)
			getMendixObject().setValue(context, MemberNames.Template_Icons.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_Icons.toString(), template_icons.getMendixObject().getId());
	}

	/**
	 * @return value of Template_ApplicationForm
	 */
	public final dynamicform.proxies.ApplicationForm getTemplate_ApplicationForm() throws com.mendix.core.CoreException
	{
		return getTemplate_ApplicationForm(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_ApplicationForm
	 */
	public final dynamicform.proxies.ApplicationForm getTemplate_ApplicationForm(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.ApplicationForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_ApplicationForm.toString());
		if (identifier != null)
			result = dynamicform.proxies.ApplicationForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_ApplicationForm
	 * @param template_applicationform
	 */
	public final void setTemplate_ApplicationForm(dynamicform.proxies.ApplicationForm template_applicationform)
	{
		setTemplate_ApplicationForm(getContext(), template_applicationform);
	}

	/**
	 * Set value of Template_ApplicationForm
	 * @param context
	 * @param template_applicationform
	 */
	public final void setTemplate_ApplicationForm(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.ApplicationForm template_applicationform)
	{
		if (template_applicationform == null)
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm.toString(), template_applicationform.getMendixObject().getId());
	}

	/**
	 * @return value of Template_ApplicationForm_Dummy
	 */
	public final dynamicform.proxies.ApplicationForm getTemplate_ApplicationForm_Dummy() throws com.mendix.core.CoreException
	{
		return getTemplate_ApplicationForm_Dummy(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_ApplicationForm_Dummy
	 */
	public final dynamicform.proxies.ApplicationForm getTemplate_ApplicationForm_Dummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.ApplicationForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_ApplicationForm_Dummy.toString());
		if (identifier != null)
			result = dynamicform.proxies.ApplicationForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_ApplicationForm_Dummy
	 * @param template_applicationform_dummy
	 */
	public final void setTemplate_ApplicationForm_Dummy(dynamicform.proxies.ApplicationForm template_applicationform_dummy)
	{
		setTemplate_ApplicationForm_Dummy(getContext(), template_applicationform_dummy);
	}

	/**
	 * Set value of Template_ApplicationForm_Dummy
	 * @param context
	 * @param template_applicationform_dummy
	 */
	public final void setTemplate_ApplicationForm_Dummy(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.ApplicationForm template_applicationform_dummy)
	{
		if (template_applicationform_dummy == null)
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm_Dummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_ApplicationForm_Dummy.toString(), template_applicationform_dummy.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_TemplateDummy
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_TemplateDummy() throws com.mendix.core.CoreException
	{
		return getGrantSystem_TemplateDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_TemplateDummy
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_TemplateDummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_TemplateDummy.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_TemplateDummy
	 * @param grantsystem_templatedummy
	 */
	public final void setGrantSystem_TemplateDummy(ugs.proxies.GrantSystem grantsystem_templatedummy)
	{
		setGrantSystem_TemplateDummy(getContext(), grantsystem_templatedummy);
	}

	/**
	 * Set value of GrantSystem_TemplateDummy
	 * @param context
	 * @param grantsystem_templatedummy
	 */
	public final void setGrantSystem_TemplateDummy(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem grantsystem_templatedummy)
	{
		if (grantsystem_templatedummy == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_TemplateDummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_TemplateDummy.toString(), grantsystem_templatedummy.getMendixObject().getId());
	}

	/**
	 * @return value of Formowner
	 */
	public final administration.proxies.Account getFormowner() throws com.mendix.core.CoreException
	{
		return getFormowner(getContext());
	}

	/**
	 * @param context
	 * @return value of Formowner
	 */
	public final administration.proxies.Account getFormowner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Formowner.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Formowner
	 * @param formowner
	 */
	public final void setFormowner(administration.proxies.Account formowner)
	{
		setFormowner(getContext(), formowner);
	}

	/**
	 * Set value of Formowner
	 * @param context
	 * @param formowner
	 */
	public final void setFormowner(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account formowner)
	{
		if (formowner == null)
			getMendixObject().setValue(context, MemberNames.Formowner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Formowner.toString(), formowner.getMendixObject().getId());
	}

	/**
	 * @return value of Template_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getTemplate_WorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getTemplate_WorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getTemplate_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_WorkflowUserTask.toString());
		if (identifier != null)
			result = system.proxies.WorkflowUserTask.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_WorkflowUserTask
	 * @param template_workflowusertask
	 */
	public final void setTemplate_WorkflowUserTask(system.proxies.WorkflowUserTask template_workflowusertask)
	{
		setTemplate_WorkflowUserTask(getContext(), template_workflowusertask);
	}

	/**
	 * Set value of Template_WorkflowUserTask
	 * @param context
	 * @param template_workflowusertask
	 */
	public final void setTemplate_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTask template_workflowusertask)
	{
		if (template_workflowusertask == null)
			getMendixObject().setValue(context, MemberNames.Template_WorkflowUserTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_WorkflowUserTask.toString(), template_workflowusertask.getMendixObject().getId());
	}

	/**
	 * @return value of Template_AllWorkflowUserTask
	 */
	public final java.util.List<system.proxies.WorkflowUserTask> getTemplate_AllWorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getTemplate_AllWorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_AllWorkflowUserTask
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.WorkflowUserTask> getTemplate_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.WorkflowUserTask> result = new java.util.ArrayList<system.proxies.WorkflowUserTask>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Template_AllWorkflowUserTask.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(system.proxies.WorkflowUserTask.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Template_AllWorkflowUserTask
	 * @param template_allworkflowusertask
	 */
	public final void setTemplate_AllWorkflowUserTask(java.util.List<system.proxies.WorkflowUserTask> template_allworkflowusertask)
	{
		setTemplate_AllWorkflowUserTask(getContext(), template_allworkflowusertask);
	}

	/**
	 * Set value of Template_AllWorkflowUserTask
	 * @param context
	 * @param template_allworkflowusertask
	 */
	public final void setTemplate_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.WorkflowUserTask> template_allworkflowusertask)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (system.proxies.WorkflowUserTask proxyObject : template_allworkflowusertask)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Template_AllWorkflowUserTask.toString(), identifiers);
	}

	/**
	 * @return value of Template_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getTemplate_GrantSystem() throws com.mendix.core.CoreException
	{
		return getTemplate_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getTemplate_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_GrantSystem
	 * @param template_grantsystem
	 */
	public final void setTemplate_GrantSystem(ugs.proxies.GrantSystem template_grantsystem)
	{
		setTemplate_GrantSystem(getContext(), template_grantsystem);
	}

	/**
	 * Set value of Template_GrantSystem
	 * @param context
	 * @param template_grantsystem
	 */
	public final void setTemplate_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem template_grantsystem)
	{
		if (template_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Template_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_GrantSystem.toString(), template_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Template that = (dynamicform.proxies.Template) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.Template";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
