// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class WorkflowRoles
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowRolesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.WorkflowRoles";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RoleName("RoleName"),
		Order("Order"),
		Status_To_Change_To("Status_To_Change_To"),
		Task_Description("Task_Description"),
		DueDate("DueDate"),
		Editable("Editable"),
		Current_Stage("Current_Stage"),
		check("check"),
		EmailBody("EmailBody"),
		Tokens("Tokens"),
		ExternalStatus("ExternalStatus"),
		InternalStatus("InternalStatus"),
		UseEmailAction("UseEmailAction"),
		UseStatusChnageAction("UseStatusChnageAction"),
		RatingType("RatingType"),
		ReviewType("ReviewType"),
		StaticValue("StaticValue"),
		InterviewSchdule("InterviewSchdule"),
		WorkflowRoles_Template("DynamicForm.WorkflowRoles_Template"),
		WorkflowRoles_Grant("DynamicForm.WorkflowRoles_Grant"),
		Status_WorkflowRoles("DynamicForm.Status_WorkflowRoles"),
		GrantSystem_WorkflowRolesDummy("UGS.GrantSystem_WorkflowRolesDummy"),
		ReviewForm_WorkflowRoles("UGS.ReviewForm_WorkflowRoles"),
		ReviewForm_WorkflowRoles_Dummy("UGS.ReviewForm_WorkflowRoles_Dummy"),
		WorkflowRoles_UserRole("DynamicForm.WorkflowRoles_UserRole"),
		WorkflowRoles_GrantSystem("DynamicForm.WorkflowRoles_GrantSystem"),
		WorkflowRoles_EmailTemplate("DynamicForm.WorkflowRoles_EmailTemplate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.WorkflowRoles"));
	}

	protected WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowRolesMendixObject)
	{
		if (workflowRolesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.WorkflowRoles", workflowRolesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.WorkflowRoles");

		this.workflowRolesMendixObject = workflowRolesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowRoles.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.WorkflowRoles initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.WorkflowRoles.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.WorkflowRoles initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.WorkflowRoles(context, mendixObject);
	}

	public static dynamicform.proxies.WorkflowRoles load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.WorkflowRoles.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.WorkflowRoles> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<dynamicform.proxies.WorkflowRoles> result = new java.util.ArrayList<dynamicform.proxies.WorkflowRoles>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DynamicForm.WorkflowRoles" + xpathConstraint))
			result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RoleName
	 */
	public final java.lang.String getRoleName()
	{
		return getRoleName(getContext());
	}

	/**
	 * @param context
	 * @return value of RoleName
	 */
	public final java.lang.String getRoleName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoleName.toString());
	}

	/**
	 * Set value of RoleName
	 * @param rolename
	 */
	public final void setRoleName(java.lang.String rolename)
	{
		setRoleName(getContext(), rolename);
	}

	/**
	 * Set value of RoleName
	 * @param context
	 * @param rolename
	 */
	public final void setRoleName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rolename)
	{
		getMendixObject().setValue(context, MemberNames.RoleName.toString(), rolename);
	}

	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * @return value of Status_To_Change_To
	 */
	public final java.lang.String getStatus_To_Change_To()
	{
		return getStatus_To_Change_To(getContext());
	}

	/**
	 * @param context
	 * @return value of Status_To_Change_To
	 */
	public final java.lang.String getStatus_To_Change_To(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status_To_Change_To.toString());
	}

	/**
	 * Set value of Status_To_Change_To
	 * @param status_to_change_to
	 */
	public final void setStatus_To_Change_To(java.lang.String status_to_change_to)
	{
		setStatus_To_Change_To(getContext(), status_to_change_to);
	}

	/**
	 * Set value of Status_To_Change_To
	 * @param context
	 * @param status_to_change_to
	 */
	public final void setStatus_To_Change_To(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status_to_change_to)
	{
		getMendixObject().setValue(context, MemberNames.Status_To_Change_To.toString(), status_to_change_to);
	}

	/**
	 * @return value of Task_Description
	 */
	public final java.lang.String getTask_Description()
	{
		return getTask_Description(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Description
	 */
	public final java.lang.String getTask_Description(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Task_Description.toString());
	}

	/**
	 * Set value of Task_Description
	 * @param task_description
	 */
	public final void setTask_Description(java.lang.String task_description)
	{
		setTask_Description(getContext(), task_description);
	}

	/**
	 * Set value of Task_Description
	 * @param context
	 * @param task_description
	 */
	public final void setTask_Description(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String task_description)
	{
		getMendixObject().setValue(context, MemberNames.Task_Description.toString(), task_description);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of Editable
	 */
	public final java.lang.Boolean getEditable()
	{
		return getEditable(getContext());
	}

	/**
	 * @param context
	 * @return value of Editable
	 */
	public final java.lang.Boolean getEditable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Editable.toString());
	}

	/**
	 * Set value of Editable
	 * @param editable
	 */
	public final void setEditable(java.lang.Boolean editable)
	{
		setEditable(getContext(), editable);
	}

	/**
	 * Set value of Editable
	 * @param context
	 * @param editable
	 */
	public final void setEditable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean editable)
	{
		getMendixObject().setValue(context, MemberNames.Editable.toString(), editable);
	}

	/**
	 * Set value of Current_Stage
	 * @param current_stage
	 */
	public final dynamicform.proxies.Enum_WFstage getCurrent_Stage()
	{
		return getCurrent_Stage(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Stage
	 */
	public final dynamicform.proxies.Enum_WFstage getCurrent_Stage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Current_Stage.toString());
		if (obj == null)
			return null;

		return dynamicform.proxies.Enum_WFstage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Current_Stage
	 * @param current_stage
	 */
	public final void setCurrent_Stage(dynamicform.proxies.Enum_WFstage current_stage)
	{
		setCurrent_Stage(getContext(), current_stage);
	}

	/**
	 * Set value of Current_Stage
	 * @param context
	 * @param current_stage
	 */
	public final void setCurrent_Stage(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Enum_WFstage current_stage)
	{
		if (current_stage != null)
			getMendixObject().setValue(context, MemberNames.Current_Stage.toString(), current_stage.toString());
		else
			getMendixObject().setValue(context, MemberNames.Current_Stage.toString(), null);
	}

	/**
	 * @return value of check
	 */
	public final java.lang.Boolean getcheck()
	{
		return getcheck(getContext());
	}

	/**
	 * @param context
	 * @return value of check
	 */
	public final java.lang.Boolean getcheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.check.toString());
	}

	/**
	 * Set value of check
	 * @param check
	 */
	public final void setcheck(java.lang.Boolean check)
	{
		setcheck(getContext(), check);
	}

	/**
	 * Set value of check
	 * @param context
	 * @param check
	 */
	public final void setcheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean check)
	{
		getMendixObject().setValue(context, MemberNames.check.toString(), check);
	}

	/**
	 * @return value of EmailBody
	 */
	public final java.lang.String getEmailBody()
	{
		return getEmailBody(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailBody
	 */
	public final java.lang.String getEmailBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailBody.toString());
	}

	/**
	 * Set value of EmailBody
	 * @param emailbody
	 */
	public final void setEmailBody(java.lang.String emailbody)
	{
		setEmailBody(getContext(), emailbody);
	}

	/**
	 * Set value of EmailBody
	 * @param context
	 * @param emailbody
	 */
	public final void setEmailBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailbody)
	{
		getMendixObject().setValue(context, MemberNames.EmailBody.toString(), emailbody);
	}

	/**
	 * @return value of Tokens
	 */
	public final java.lang.Boolean getTokens()
	{
		return getTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of Tokens
	 */
	public final java.lang.Boolean getTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Tokens.toString());
	}

	/**
	 * Set value of Tokens
	 * @param tokens
	 */
	public final void setTokens(java.lang.Boolean tokens)
	{
		setTokens(getContext(), tokens);
	}

	/**
	 * Set value of Tokens
	 * @param context
	 * @param tokens
	 */
	public final void setTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tokens)
	{
		getMendixObject().setValue(context, MemberNames.Tokens.toString(), tokens);
	}

	/**
	 * Set value of ExternalStatus
	 * @param externalstatus
	 */
	public final ugs.proxies.Enum_ExternalStatus getExternalStatus()
	{
		return getExternalStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalStatus
	 */
	public final ugs.proxies.Enum_ExternalStatus getExternalStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ExternalStatus.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ExternalStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ExternalStatus
	 * @param externalstatus
	 */
	public final void setExternalStatus(ugs.proxies.Enum_ExternalStatus externalstatus)
	{
		setExternalStatus(getContext(), externalstatus);
	}

	/**
	 * Set value of ExternalStatus
	 * @param context
	 * @param externalstatus
	 */
	public final void setExternalStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ExternalStatus externalstatus)
	{
		if (externalstatus != null)
			getMendixObject().setValue(context, MemberNames.ExternalStatus.toString(), externalstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.ExternalStatus.toString(), null);
	}

	/**
	 * Set value of InternalStatus
	 * @param internalstatus
	 */
	public final ugs.proxies.Enum_WorkflowStages getInternalStatus()
	{
		return getInternalStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of InternalStatus
	 */
	public final ugs.proxies.Enum_WorkflowStages getInternalStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InternalStatus.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_WorkflowStages.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InternalStatus
	 * @param internalstatus
	 */
	public final void setInternalStatus(ugs.proxies.Enum_WorkflowStages internalstatus)
	{
		setInternalStatus(getContext(), internalstatus);
	}

	/**
	 * Set value of InternalStatus
	 * @param context
	 * @param internalstatus
	 */
	public final void setInternalStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_WorkflowStages internalstatus)
	{
		if (internalstatus != null)
			getMendixObject().setValue(context, MemberNames.InternalStatus.toString(), internalstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.InternalStatus.toString(), null);
	}

	/**
	 * @return value of UseEmailAction
	 */
	public final java.lang.Boolean getUseEmailAction()
	{
		return getUseEmailAction(getContext());
	}

	/**
	 * @param context
	 * @return value of UseEmailAction
	 */
	public final java.lang.Boolean getUseEmailAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseEmailAction.toString());
	}

	/**
	 * Set value of UseEmailAction
	 * @param useemailaction
	 */
	public final void setUseEmailAction(java.lang.Boolean useemailaction)
	{
		setUseEmailAction(getContext(), useemailaction);
	}

	/**
	 * Set value of UseEmailAction
	 * @param context
	 * @param useemailaction
	 */
	public final void setUseEmailAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useemailaction)
	{
		getMendixObject().setValue(context, MemberNames.UseEmailAction.toString(), useemailaction);
	}

	/**
	 * @return value of UseStatusChnageAction
	 */
	public final java.lang.Boolean getUseStatusChnageAction()
	{
		return getUseStatusChnageAction(getContext());
	}

	/**
	 * @param context
	 * @return value of UseStatusChnageAction
	 */
	public final java.lang.Boolean getUseStatusChnageAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseStatusChnageAction.toString());
	}

	/**
	 * Set value of UseStatusChnageAction
	 * @param usestatuschnageaction
	 */
	public final void setUseStatusChnageAction(java.lang.Boolean usestatuschnageaction)
	{
		setUseStatusChnageAction(getContext(), usestatuschnageaction);
	}

	/**
	 * Set value of UseStatusChnageAction
	 * @param context
	 * @param usestatuschnageaction
	 */
	public final void setUseStatusChnageAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usestatuschnageaction)
	{
		getMendixObject().setValue(context, MemberNames.UseStatusChnageAction.toString(), usestatuschnageaction);
	}

	/**
	 * Set value of RatingType
	 * @param ratingtype
	 */
	public final ugs.proxies.Enum_ReviewTypes getRatingType()
	{
		return getRatingType(getContext());
	}

	/**
	 * @param context
	 * @return value of RatingType
	 */
	public final ugs.proxies.Enum_ReviewTypes getRatingType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RatingType.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ReviewTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RatingType
	 * @param ratingtype
	 */
	public final void setRatingType(ugs.proxies.Enum_ReviewTypes ratingtype)
	{
		setRatingType(getContext(), ratingtype);
	}

	/**
	 * Set value of RatingType
	 * @param context
	 * @param ratingtype
	 */
	public final void setRatingType(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ReviewTypes ratingtype)
	{
		if (ratingtype != null)
			getMendixObject().setValue(context, MemberNames.RatingType.toString(), ratingtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RatingType.toString(), null);
	}

	/**
	 * Set value of ReviewType
	 * @param reviewtype
	 */
	public final dynamicform.proxies.Enum_ReviewType getReviewType()
	{
		return getReviewType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewType
	 */
	public final dynamicform.proxies.Enum_ReviewType getReviewType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReviewType.toString());
		if (obj == null)
			return null;

		return dynamicform.proxies.Enum_ReviewType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ReviewType
	 * @param reviewtype
	 */
	public final void setReviewType(dynamicform.proxies.Enum_ReviewType reviewtype)
	{
		setReviewType(getContext(), reviewtype);
	}

	/**
	 * Set value of ReviewType
	 * @param context
	 * @param reviewtype
	 */
	public final void setReviewType(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Enum_ReviewType reviewtype)
	{
		if (reviewtype != null)
			getMendixObject().setValue(context, MemberNames.ReviewType.toString(), reviewtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ReviewType.toString(), null);
	}

	/**
	 * @return value of StaticValue
	 */
	public final java.lang.Boolean getStaticValue()
	{
		return getStaticValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StaticValue
	 */
	public final java.lang.Boolean getStaticValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StaticValue.toString());
	}

	/**
	 * Set value of StaticValue
	 * @param staticvalue
	 */
	public final void setStaticValue(java.lang.Boolean staticvalue)
	{
		setStaticValue(getContext(), staticvalue);
	}

	/**
	 * Set value of StaticValue
	 * @param context
	 * @param staticvalue
	 */
	public final void setStaticValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean staticvalue)
	{
		getMendixObject().setValue(context, MemberNames.StaticValue.toString(), staticvalue);
	}

	/**
	 * @return value of InterviewSchdule
	 */
	public final java.lang.Boolean getInterviewSchdule()
	{
		return getInterviewSchdule(getContext());
	}

	/**
	 * @param context
	 * @return value of InterviewSchdule
	 */
	public final java.lang.Boolean getInterviewSchdule(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.InterviewSchdule.toString());
	}

	/**
	 * Set value of InterviewSchdule
	 * @param interviewschdule
	 */
	public final void setInterviewSchdule(java.lang.Boolean interviewschdule)
	{
		setInterviewSchdule(getContext(), interviewschdule);
	}

	/**
	 * Set value of InterviewSchdule
	 * @param context
	 * @param interviewschdule
	 */
	public final void setInterviewSchdule(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean interviewschdule)
	{
		getMendixObject().setValue(context, MemberNames.InterviewSchdule.toString(), interviewschdule);
	}

	/**
	 * @return value of WorkflowRoles_Template
	 */
	public final dynamicform.proxies.Template getWorkflowRoles_Template() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_Template
	 */
	public final dynamicform.proxies.Template getWorkflowRoles_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_Template.toString());
		if (identifier != null)
			result = dynamicform.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_Template
	 * @param workflowroles_template
	 */
	public final void setWorkflowRoles_Template(dynamicform.proxies.Template workflowroles_template)
	{
		setWorkflowRoles_Template(getContext(), workflowroles_template);
	}

	/**
	 * Set value of WorkflowRoles_Template
	 * @param context
	 * @param workflowroles_template
	 */
	public final void setWorkflowRoles_Template(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Template workflowroles_template)
	{
		if (workflowroles_template == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_Template.toString(), workflowroles_template.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowRoles_Grant
	 */
	public final dynamicform.proxies.Grant getWorkflowRoles_Grant() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_Grant(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_Grant
	 */
	public final dynamicform.proxies.Grant getWorkflowRoles_Grant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Grant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_Grant.toString());
		if (identifier != null)
			result = dynamicform.proxies.Grant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_Grant
	 * @param workflowroles_grant
	 */
	public final void setWorkflowRoles_Grant(dynamicform.proxies.Grant workflowroles_grant)
	{
		setWorkflowRoles_Grant(getContext(), workflowroles_grant);
	}

	/**
	 * Set value of WorkflowRoles_Grant
	 * @param context
	 * @param workflowroles_grant
	 */
	public final void setWorkflowRoles_Grant(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Grant workflowroles_grant)
	{
		if (workflowroles_grant == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_Grant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_Grant.toString(), workflowroles_grant.getMendixObject().getId());
	}

	/**
	 * @return value of Status_WorkflowRoles
	 */
	public final dynamicform.proxies.Status getStatus_WorkflowRoles() throws com.mendix.core.CoreException
	{
		return getStatus_WorkflowRoles(getContext());
	}

	/**
	 * @param context
	 * @return value of Status_WorkflowRoles
	 */
	public final dynamicform.proxies.Status getStatus_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Status result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Status_WorkflowRoles.toString());
		if (identifier != null)
			result = dynamicform.proxies.Status.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Status_WorkflowRoles
	 * @param status_workflowroles
	 */
	public final void setStatus_WorkflowRoles(dynamicform.proxies.Status status_workflowroles)
	{
		setStatus_WorkflowRoles(getContext(), status_workflowroles);
	}

	/**
	 * Set value of Status_WorkflowRoles
	 * @param context
	 * @param status_workflowroles
	 */
	public final void setStatus_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Status status_workflowroles)
	{
		if (status_workflowroles == null)
			getMendixObject().setValue(context, MemberNames.Status_WorkflowRoles.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Status_WorkflowRoles.toString(), status_workflowroles.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_WorkflowRolesDummy
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_WorkflowRolesDummy() throws com.mendix.core.CoreException
	{
		return getGrantSystem_WorkflowRolesDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_WorkflowRolesDummy
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_WorkflowRolesDummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_WorkflowRolesDummy
	 * @param grantsystem_workflowrolesdummy
	 */
	public final void setGrantSystem_WorkflowRolesDummy(ugs.proxies.GrantSystem grantsystem_workflowrolesdummy)
	{
		setGrantSystem_WorkflowRolesDummy(getContext(), grantsystem_workflowrolesdummy);
	}

	/**
	 * Set value of GrantSystem_WorkflowRolesDummy
	 * @param context
	 * @param grantsystem_workflowrolesdummy
	 */
	public final void setGrantSystem_WorkflowRolesDummy(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem grantsystem_workflowrolesdummy)
	{
		if (grantsystem_workflowrolesdummy == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString(), grantsystem_workflowrolesdummy.getMendixObject().getId());
	}

	/**
	 * @return value of ReviewForm_WorkflowRoles
	 */
	public final java.util.List<ugs.proxies.ReviewForm> getReviewForm_WorkflowRoles() throws com.mendix.core.CoreException
	{
		return getReviewForm_WorkflowRoles(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewForm_WorkflowRoles
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ugs.proxies.ReviewForm> getReviewForm_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.ReviewForm> result = new java.util.ArrayList<ugs.proxies.ReviewForm>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ReviewForm_WorkflowRoles.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ugs.proxies.ReviewForm.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ReviewForm_WorkflowRoles
	 * @param reviewform_workflowroles
	 */
	public final void setReviewForm_WorkflowRoles(java.util.List<ugs.proxies.ReviewForm> reviewform_workflowroles)
	{
		setReviewForm_WorkflowRoles(getContext(), reviewform_workflowroles);
	}

	/**
	 * Set value of ReviewForm_WorkflowRoles
	 * @param context
	 * @param reviewform_workflowroles
	 */
	public final void setReviewForm_WorkflowRoles(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ugs.proxies.ReviewForm> reviewform_workflowroles)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ugs.proxies.ReviewForm proxyObject : reviewform_workflowroles)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ReviewForm_WorkflowRoles.toString(), identifiers);
	}

	/**
	 * @return value of ReviewForm_WorkflowRoles_Dummy
	 */
	public final ugs.proxies.ReviewForm getReviewForm_WorkflowRoles_Dummy() throws com.mendix.core.CoreException
	{
		return getReviewForm_WorkflowRoles_Dummy(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewForm_WorkflowRoles_Dummy
	 */
	public final ugs.proxies.ReviewForm getReviewForm_WorkflowRoles_Dummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.ReviewForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReviewForm_WorkflowRoles_Dummy.toString());
		if (identifier != null)
			result = ugs.proxies.ReviewForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReviewForm_WorkflowRoles_Dummy
	 * @param reviewform_workflowroles_dummy
	 */
	public final void setReviewForm_WorkflowRoles_Dummy(ugs.proxies.ReviewForm reviewform_workflowroles_dummy)
	{
		setReviewForm_WorkflowRoles_Dummy(getContext(), reviewform_workflowroles_dummy);
	}

	/**
	 * Set value of ReviewForm_WorkflowRoles_Dummy
	 * @param context
	 * @param reviewform_workflowroles_dummy
	 */
	public final void setReviewForm_WorkflowRoles_Dummy(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.ReviewForm reviewform_workflowroles_dummy)
	{
		if (reviewform_workflowroles_dummy == null)
			getMendixObject().setValue(context, MemberNames.ReviewForm_WorkflowRoles_Dummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReviewForm_WorkflowRoles_Dummy.toString(), reviewform_workflowroles_dummy.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowRoles_UserRole
	 */
	public final system.proxies.UserRole getWorkflowRoles_UserRole() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_UserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_UserRole
	 */
	public final system.proxies.UserRole getWorkflowRoles_UserRole(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.UserRole result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_UserRole.toString());
		if (identifier != null)
			result = system.proxies.UserRole.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_UserRole
	 * @param workflowroles_userrole
	 */
	public final void setWorkflowRoles_UserRole(system.proxies.UserRole workflowroles_userrole)
	{
		setWorkflowRoles_UserRole(getContext(), workflowroles_userrole);
	}

	/**
	 * Set value of WorkflowRoles_UserRole
	 * @param context
	 * @param workflowroles_userrole
	 */
	public final void setWorkflowRoles_UserRole(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.UserRole workflowroles_userrole)
	{
		if (workflowroles_userrole == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_UserRole.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_UserRole.toString(), workflowroles_userrole.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowRoles_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getWorkflowRoles_GrantSystem() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getWorkflowRoles_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_GrantSystem
	 * @param workflowroles_grantsystem
	 */
	public final void setWorkflowRoles_GrantSystem(ugs.proxies.GrantSystem workflowroles_grantsystem)
	{
		setWorkflowRoles_GrantSystem(getContext(), workflowroles_grantsystem);
	}

	/**
	 * Set value of WorkflowRoles_GrantSystem
	 * @param context
	 * @param workflowroles_grantsystem
	 */
	public final void setWorkflowRoles_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem workflowroles_grantsystem)
	{
		if (workflowroles_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_GrantSystem.toString(), workflowroles_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowRoles_EmailTemplate
	 */
	public final emailtemplate.proxies.EmailTemplate getWorkflowRoles_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_EmailTemplate
	 */
	public final emailtemplate.proxies.EmailTemplate getWorkflowRoles_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_EmailTemplate.toString());
		if (identifier != null)
			result = emailtemplate.proxies.EmailTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_EmailTemplate
	 * @param workflowroles_emailtemplate
	 */
	public final void setWorkflowRoles_EmailTemplate(emailtemplate.proxies.EmailTemplate workflowroles_emailtemplate)
	{
		setWorkflowRoles_EmailTemplate(getContext(), workflowroles_emailtemplate);
	}

	/**
	 * Set value of WorkflowRoles_EmailTemplate
	 * @param context
	 * @param workflowroles_emailtemplate
	 */
	public final void setWorkflowRoles_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailTemplate workflowroles_emailtemplate)
	{
		if (workflowroles_emailtemplate == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_EmailTemplate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_EmailTemplate.toString(), workflowroles_emailtemplate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowRolesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.WorkflowRoles that = (dynamicform.proxies.WorkflowRoles) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.WorkflowRoles";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
