// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class WorkflowRoles_DnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowRoles_DnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.WorkflowRoles_DnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkflowRoles_DnD_Dragged("DynamicForm.WorkflowRoles_DnD_Dragged"),
		WorkflowRoles_DnD_DroTarget("DynamicForm.WorkflowRoles_DnD_DroTarget");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowRoles_DnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DynamicForm.WorkflowRoles_DnD"));
	}

	protected WorkflowRoles_DnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowRoles_DnDMendixObject)
	{
		if (workflowRoles_DnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DynamicForm.WorkflowRoles_DnD", workflowRoles_DnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DynamicForm.WorkflowRoles_DnD");

		this.workflowRoles_DnDMendixObject = workflowRoles_DnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowRoles_DnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.WorkflowRoles_DnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.WorkflowRoles_DnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dynamicform.proxies.WorkflowRoles_DnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.WorkflowRoles_DnD(context, mendixObject);
	}

	public static dynamicform.proxies.WorkflowRoles_DnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.WorkflowRoles_DnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of WorkflowRoles_DnD_Dragged
	 */
	public final dynamicform.proxies.WorkflowRoles getWorkflowRoles_DnD_Dragged() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_DnD_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_DnD_Dragged
	 */
	public final dynamicform.proxies.WorkflowRoles getWorkflowRoles_DnD_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.WorkflowRoles result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_DnD_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.WorkflowRoles.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_DnD_Dragged
	 * @param workflowroles_dnd_dragged
	 */
	public final void setWorkflowRoles_DnD_Dragged(dynamicform.proxies.WorkflowRoles workflowroles_dnd_dragged)
	{
		setWorkflowRoles_DnD_Dragged(getContext(), workflowroles_dnd_dragged);
	}

	/**
	 * Set value of WorkflowRoles_DnD_Dragged
	 * @param context
	 * @param workflowroles_dnd_dragged
	 */
	public final void setWorkflowRoles_DnD_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.WorkflowRoles workflowroles_dnd_dragged)
	{
		if (workflowroles_dnd_dragged == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_DnD_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_DnD_Dragged.toString(), workflowroles_dnd_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowRoles_DnD_DroTarget
	 */
	public final dynamicform.proxies.WorkflowRoles getWorkflowRoles_DnD_DroTarget() throws com.mendix.core.CoreException
	{
		return getWorkflowRoles_DnD_DroTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRoles_DnD_DroTarget
	 */
	public final dynamicform.proxies.WorkflowRoles getWorkflowRoles_DnD_DroTarget(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.WorkflowRoles result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRoles_DnD_DroTarget.toString());
		if (identifier != null)
			result = dynamicform.proxies.WorkflowRoles.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowRoles_DnD_DroTarget
	 * @param workflowroles_dnd_drotarget
	 */
	public final void setWorkflowRoles_DnD_DroTarget(dynamicform.proxies.WorkflowRoles workflowroles_dnd_drotarget)
	{
		setWorkflowRoles_DnD_DroTarget(getContext(), workflowroles_dnd_drotarget);
	}

	/**
	 * Set value of WorkflowRoles_DnD_DroTarget
	 * @param context
	 * @param workflowroles_dnd_drotarget
	 */
	public final void setWorkflowRoles_DnD_DroTarget(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.WorkflowRoles workflowroles_dnd_drotarget)
	{
		if (workflowroles_dnd_drotarget == null)
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_DnD_DroTarget.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowRoles_DnD_DroTarget.toString(), workflowroles_dnd_drotarget.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowRoles_DnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.WorkflowRoles_DnD that = (dynamicform.proxies.WorkflowRoles_DnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DynamicForm.WorkflowRoles_DnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
