// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Activity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject activityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Activity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActivityName("ActivityName"),
		Schedule("Schedule"),
		Remarks("Remarks"),
		AdditionalInput("AdditionalInput"),
		Activity_GrantSystem("UGS.Activity_GrantSystem"),
		Test_Activity("UGS.Test_Activity"),
		Activity_Interview("UGS.Activity_Interview");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Activity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Activity"));
	}

	protected Activity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject activityMendixObject)
	{
		if (activityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Activity", activityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Activity");

		this.activityMendixObject = activityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Activity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Activity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Activity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Activity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Activity(context, mendixObject);
	}

	public static ugs.proxies.Activity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Activity.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Activity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Activity> result = new java.util.ArrayList<ugs.proxies.Activity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Activity" + xpathConstraint))
			result.add(ugs.proxies.Activity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ActivityName
	 */
	public final java.lang.String getActivityName()
	{
		return getActivityName(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityName
	 */
	public final java.lang.String getActivityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActivityName.toString());
	}

	/**
	 * Set value of ActivityName
	 * @param activityname
	 */
	public final void setActivityName(java.lang.String activityname)
	{
		setActivityName(getContext(), activityname);
	}

	/**
	 * Set value of ActivityName
	 * @param context
	 * @param activityname
	 */
	public final void setActivityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String activityname)
	{
		getMendixObject().setValue(context, MemberNames.ActivityName.toString(), activityname);
	}

	/**
	 * @return value of Schedule
	 */
	public final java.util.Date getSchedule()
	{
		return getSchedule(getContext());
	}

	/**
	 * @param context
	 * @return value of Schedule
	 */
	public final java.util.Date getSchedule(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Schedule.toString());
	}

	/**
	 * Set value of Schedule
	 * @param schedule
	 */
	public final void setSchedule(java.util.Date schedule)
	{
		setSchedule(getContext(), schedule);
	}

	/**
	 * Set value of Schedule
	 * @param context
	 * @param schedule
	 */
	public final void setSchedule(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date schedule)
	{
		getMendixObject().setValue(context, MemberNames.Schedule.toString(), schedule);
	}

	/**
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks()
	{
		return getRemarks(getContext());
	}

	/**
	 * @param context
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Remarks.toString());
	}

	/**
	 * Set value of Remarks
	 * @param remarks
	 */
	public final void setRemarks(java.lang.String remarks)
	{
		setRemarks(getContext(), remarks);
	}

	/**
	 * Set value of Remarks
	 * @param context
	 * @param remarks
	 */
	public final void setRemarks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remarks)
	{
		getMendixObject().setValue(context, MemberNames.Remarks.toString(), remarks);
	}

	/**
	 * @return value of AdditionalInput
	 */
	public final java.lang.String getAdditionalInput()
	{
		return getAdditionalInput(getContext());
	}

	/**
	 * @param context
	 * @return value of AdditionalInput
	 */
	public final java.lang.String getAdditionalInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdditionalInput.toString());
	}

	/**
	 * Set value of AdditionalInput
	 * @param additionalinput
	 */
	public final void setAdditionalInput(java.lang.String additionalinput)
	{
		setAdditionalInput(getContext(), additionalinput);
	}

	/**
	 * Set value of AdditionalInput
	 * @param context
	 * @param additionalinput
	 */
	public final void setAdditionalInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String additionalinput)
	{
		getMendixObject().setValue(context, MemberNames.AdditionalInput.toString(), additionalinput);
	}

	/**
	 * @return value of Activity_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getActivity_GrantSystem() throws com.mendix.core.CoreException
	{
		return getActivity_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Activity_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getActivity_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Activity_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Activity_GrantSystem
	 * @param activity_grantsystem
	 */
	public final void setActivity_GrantSystem(ugs.proxies.GrantSystem activity_grantsystem)
	{
		setActivity_GrantSystem(getContext(), activity_grantsystem);
	}

	/**
	 * Set value of Activity_GrantSystem
	 * @param context
	 * @param activity_grantsystem
	 */
	public final void setActivity_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem activity_grantsystem)
	{
		if (activity_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Activity_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Activity_GrantSystem.toString(), activity_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of Test_Activity
	 */
	public final ugs.proxies.Test getTest_Activity() throws com.mendix.core.CoreException
	{
		return getTest_Activity(getContext());
	}

	/**
	 * @param context
	 * @return value of Test_Activity
	 */
	public final ugs.proxies.Test getTest_Activity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Test_Activity.toString());
		if (identifier != null)
			result = ugs.proxies.Test.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Test_Activity
	 * @param test_activity
	 */
	public final void setTest_Activity(ugs.proxies.Test test_activity)
	{
		setTest_Activity(getContext(), test_activity);
	}

	/**
	 * Set value of Test_Activity
	 * @param context
	 * @param test_activity
	 */
	public final void setTest_Activity(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Test test_activity)
	{
		if (test_activity == null)
			getMendixObject().setValue(context, MemberNames.Test_Activity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Test_Activity.toString(), test_activity.getMendixObject().getId());
	}

	/**
	 * @return value of Activity_Interview
	 */
	public final ugs.proxies.Interview getActivity_Interview() throws com.mendix.core.CoreException
	{
		return getActivity_Interview(getContext());
	}

	/**
	 * @param context
	 * @return value of Activity_Interview
	 */
	public final ugs.proxies.Interview getActivity_Interview(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Interview result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Activity_Interview.toString());
		if (identifier != null)
			result = ugs.proxies.Interview.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Activity_Interview
	 * @param activity_interview
	 */
	public final void setActivity_Interview(ugs.proxies.Interview activity_interview)
	{
		setActivity_Interview(getContext(), activity_interview);
	}

	/**
	 * Set value of Activity_Interview
	 * @param context
	 * @param activity_interview
	 */
	public final void setActivity_Interview(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Interview activity_interview)
	{
		if (activity_interview == null)
			getMendixObject().setValue(context, MemberNames.Activity_Interview.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Activity_Interview.toString(), activity_interview.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return activityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Activity that = (ugs.proxies.Activity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Activity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
