// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Aggrement_ extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Aggrement_";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Terms_and_Conditions("Terms_and_Conditions"),
		Content("Content"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		GrantSystem_Aggrement_("UGS.GrantSystem_Aggrement_");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Aggrement_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Aggrement_"));
	}

	protected Aggrement_(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aggrement_MendixObject)
	{
		super(context, aggrement_MendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.Aggrement_", aggrement_MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Aggrement_");
	}

	/**
	 * @deprecated Use 'Aggrement_.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Aggrement_ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Aggrement_.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Aggrement_ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Aggrement_(context, mendixObject);
	}

	public static ugs.proxies.Aggrement_ load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Aggrement_.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Aggrement_> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Aggrement_> result = new java.util.ArrayList<ugs.proxies.Aggrement_>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Aggrement_" + xpathConstraint))
			result.add(ugs.proxies.Aggrement_.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Terms_and_Conditions
	 */
	public final java.lang.String getTerms_and_Conditions()
	{
		return getTerms_and_Conditions(getContext());
	}

	/**
	 * @param context
	 * @return value of Terms_and_Conditions
	 */
	public final java.lang.String getTerms_and_Conditions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Terms_and_Conditions.toString());
	}

	/**
	 * Set value of Terms_and_Conditions
	 * @param terms_and_conditions
	 */
	public final void setTerms_and_Conditions(java.lang.String terms_and_conditions)
	{
		setTerms_and_Conditions(getContext(), terms_and_conditions);
	}

	/**
	 * Set value of Terms_and_Conditions
	 * @param context
	 * @param terms_and_conditions
	 */
	public final void setTerms_and_Conditions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String terms_and_conditions)
	{
		getMendixObject().setValue(context, MemberNames.Terms_and_Conditions.toString(), terms_and_conditions);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of GrantSystem_Aggrement_
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_Aggrement_() throws com.mendix.core.CoreException
	{
		return getGrantSystem_Aggrement_(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_Aggrement_
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_Aggrement_(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_Aggrement_.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_Aggrement_
	 * @param grantsystem_aggrement_
	 */
	public final void setGrantSystem_Aggrement_(ugs.proxies.GrantSystem grantsystem_aggrement_)
	{
		setGrantSystem_Aggrement_(getContext(), grantsystem_aggrement_);
	}

	/**
	 * Set value of GrantSystem_Aggrement_
	 * @param context
	 * @param grantsystem_aggrement_
	 */
	public final void setGrantSystem_Aggrement_(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem grantsystem_aggrement_)
	{
		if (grantsystem_aggrement_ == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_Aggrement_.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_Aggrement_.toString(), grantsystem_aggrement_.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Aggrement_ that = (ugs.proxies.Aggrement_) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Aggrement_";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
