// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class CaseHistory
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject caseHistoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.CaseHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sender("Sender"),
		Reciever("Reciever"),
		Recieved_Date("Recieved_Date"),
		Processed_Date("Processed_Date"),
		Status("Status"),
		RefNo("RefNo"),
		History("History"),
		CaseHistory_CaseMangement("UGS.CaseHistory_CaseMangement");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CaseHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.CaseHistory"));
	}

	protected CaseHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject caseHistoryMendixObject)
	{
		if (caseHistoryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.CaseHistory", caseHistoryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.CaseHistory");

		this.caseHistoryMendixObject = caseHistoryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CaseHistory.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.CaseHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.CaseHistory.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.CaseHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.CaseHistory(context, mendixObject);
	}

	public static ugs.proxies.CaseHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.CaseHistory.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.CaseHistory> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.CaseHistory> result = new java.util.ArrayList<ugs.proxies.CaseHistory>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.CaseHistory" + xpathConstraint))
			result.add(ugs.proxies.CaseHistory.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sender
	 */
	public final java.lang.String getSender()
	{
		return getSender(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender
	 */
	public final java.lang.String getSender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sender.toString());
	}

	/**
	 * Set value of Sender
	 * @param sender
	 */
	public final void setSender(java.lang.String sender)
	{
		setSender(getContext(), sender);
	}

	/**
	 * Set value of Sender
	 * @param context
	 * @param sender
	 */
	public final void setSender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sender)
	{
		getMendixObject().setValue(context, MemberNames.Sender.toString(), sender);
	}

	/**
	 * @return value of Reciever
	 */
	public final java.lang.String getReciever()
	{
		return getReciever(getContext());
	}

	/**
	 * @param context
	 * @return value of Reciever
	 */
	public final java.lang.String getReciever(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reciever.toString());
	}

	/**
	 * Set value of Reciever
	 * @param reciever
	 */
	public final void setReciever(java.lang.String reciever)
	{
		setReciever(getContext(), reciever);
	}

	/**
	 * Set value of Reciever
	 * @param context
	 * @param reciever
	 */
	public final void setReciever(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reciever)
	{
		getMendixObject().setValue(context, MemberNames.Reciever.toString(), reciever);
	}

	/**
	 * @return value of Recieved_Date
	 */
	public final java.util.Date getRecieved_Date()
	{
		return getRecieved_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Recieved_Date
	 */
	public final java.util.Date getRecieved_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Recieved_Date.toString());
	}

	/**
	 * Set value of Recieved_Date
	 * @param recieved_date
	 */
	public final void setRecieved_Date(java.util.Date recieved_date)
	{
		setRecieved_Date(getContext(), recieved_date);
	}

	/**
	 * Set value of Recieved_Date
	 * @param context
	 * @param recieved_date
	 */
	public final void setRecieved_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date recieved_date)
	{
		getMendixObject().setValue(context, MemberNames.Recieved_Date.toString(), recieved_date);
	}

	/**
	 * @return value of Processed_Date
	 */
	public final java.util.Date getProcessed_Date()
	{
		return getProcessed_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Processed_Date
	 */
	public final java.util.Date getProcessed_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Processed_Date.toString());
	}

	/**
	 * Set value of Processed_Date
	 * @param processed_date
	 */
	public final void setProcessed_Date(java.util.Date processed_date)
	{
		setProcessed_Date(getContext(), processed_date);
	}

	/**
	 * Set value of Processed_Date
	 * @param context
	 * @param processed_date
	 */
	public final void setProcessed_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date processed_date)
	{
		getMendixObject().setValue(context, MemberNames.Processed_Date.toString(), processed_date);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of RefNo
	 */
	public final java.lang.Integer getRefNo()
	{
		return getRefNo(getContext());
	}

	/**
	 * @param context
	 * @return value of RefNo
	 */
	public final java.lang.Integer getRefNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RefNo.toString());
	}

	/**
	 * Set value of RefNo
	 * @param refno
	 */
	public final void setRefNo(java.lang.Integer refno)
	{
		setRefNo(getContext(), refno);
	}

	/**
	 * Set value of RefNo
	 * @param context
	 * @param refno
	 */
	public final void setRefNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer refno)
	{
		getMendixObject().setValue(context, MemberNames.RefNo.toString(), refno);
	}

	/**
	 * @return value of History
	 */
	public final java.lang.String getHistory()
	{
		return getHistory(getContext());
	}

	/**
	 * @param context
	 * @return value of History
	 */
	public final java.lang.String getHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.History.toString());
	}

	/**
	 * Set value of History
	 * @param history
	 */
	public final void setHistory(java.lang.String history)
	{
		setHistory(getContext(), history);
	}

	/**
	 * Set value of History
	 * @param context
	 * @param history
	 */
	public final void setHistory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String history)
	{
		getMendixObject().setValue(context, MemberNames.History.toString(), history);
	}

	/**
	 * @return value of CaseHistory_CaseMangement
	 */
	public final ugs.proxies.CaseMangement getCaseHistory_CaseMangement() throws com.mendix.core.CoreException
	{
		return getCaseHistory_CaseMangement(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseHistory_CaseMangement
	 */
	public final ugs.proxies.CaseMangement getCaseHistory_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.CaseMangement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaseHistory_CaseMangement.toString());
		if (identifier != null)
			result = ugs.proxies.CaseMangement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CaseHistory_CaseMangement
	 * @param casehistory_casemangement
	 */
	public final void setCaseHistory_CaseMangement(ugs.proxies.CaseMangement casehistory_casemangement)
	{
		setCaseHistory_CaseMangement(getContext(), casehistory_casemangement);
	}

	/**
	 * Set value of CaseHistory_CaseMangement
	 * @param context
	 * @param casehistory_casemangement
	 */
	public final void setCaseHistory_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.CaseMangement casehistory_casemangement)
	{
		if (casehistory_casemangement == null)
			getMendixObject().setValue(context, MemberNames.CaseHistory_CaseMangement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CaseHistory_CaseMangement.toString(), casehistory_casemangement.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return caseHistoryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.CaseHistory that = (ugs.proxies.CaseHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.CaseHistory";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
