// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class CaseMangement
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject caseMangementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.CaseMangement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		CaseStatement("CaseStatement"),
		Amount("Amount"),
		CaseTypes("CaseTypes"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		CaseTypesGM("CaseTypesGM"),
		ForwardStatus("ForwardStatus"),
		GM_Comments("GM_Comments"),
		Finace_Comments("Finace_Comments"),
		InvestigationOfficer_Comments("InvestigationOfficer_Comments"),
		GM_HQComments("GM_HQComments"),
		Return_FA("Return_FA"),
		Return_GMHQ("Return_GMHQ"),
		Request("Request"),
		StudyPhase("StudyPhase"),
		Dynamic("Dynamic"),
		CurrentOrder("CurrentOrder"),
		Ref_No("Ref_No"),
		History("History"),
		Submit("Submit"),
		SubmitGM("SubmitGM"),
		Phase("Phase"),
		CaseMangement_GrantSystem("UGS.CaseMangement_GrantSystem"),
		FileDocument_CaseMangement("UGS.FileDocument_CaseMangement"),
		Applicant_Case("UGS.Applicant_Case"),
		CaseMangement_CurrentHoldingAccount("UGS.CaseMangement_CurrentHoldingAccount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CaseMangement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.CaseMangement"));
	}

	protected CaseMangement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject caseMangementMendixObject)
	{
		if (caseMangementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.CaseMangement", caseMangementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.CaseMangement");

		this.caseMangementMendixObject = caseMangementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CaseMangement.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.CaseMangement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.CaseMangement.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.CaseMangement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.CaseMangement(context, mendixObject);
	}

	public static ugs.proxies.CaseMangement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.CaseMangement.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.CaseMangement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.CaseMangement> result = new java.util.ArrayList<ugs.proxies.CaseMangement>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.CaseMangement" + xpathConstraint))
			result.add(ugs.proxies.CaseMangement.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Status
	 * @param status
	 */
	public final ugs.proxies.Enum_CaseStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final ugs.proxies.Enum_CaseStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(ugs.proxies.Enum_CaseStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of CaseStatement
	 */
	public final java.lang.String getCaseStatement()
	{
		return getCaseStatement(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseStatement
	 */
	public final java.lang.String getCaseStatement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CaseStatement.toString());
	}

	/**
	 * Set value of CaseStatement
	 * @param casestatement
	 */
	public final void setCaseStatement(java.lang.String casestatement)
	{
		setCaseStatement(getContext(), casestatement);
	}

	/**
	 * Set value of CaseStatement
	 * @param context
	 * @param casestatement
	 */
	public final void setCaseStatement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String casestatement)
	{
		getMendixObject().setValue(context, MemberNames.CaseStatement.toString(), casestatement);
	}

	/**
	 * @return value of Amount
	 */
	public final java.lang.Long getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.Long getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.Long amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * Set value of CaseTypes
	 * @param casetypes
	 */
	public final ugs.proxies.Enum_CaseTypes getCaseTypes()
	{
		return getCaseTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseTypes
	 */
	public final ugs.proxies.Enum_CaseTypes getCaseTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CaseTypes.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CaseTypes
	 * @param casetypes
	 */
	public final void setCaseTypes(ugs.proxies.Enum_CaseTypes casetypes)
	{
		setCaseTypes(getContext(), casetypes);
	}

	/**
	 * Set value of CaseTypes
	 * @param context
	 * @param casetypes
	 */
	public final void setCaseTypes(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseTypes casetypes)
	{
		if (casetypes != null)
			getMendixObject().setValue(context, MemberNames.CaseTypes.toString(), casetypes.toString());
		else
			getMendixObject().setValue(context, MemberNames.CaseTypes.toString(), null);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param casetypesgm
	 */
	public final ugs.proxies.Enum_CaseTypesGM getCaseTypesGM()
	{
		return getCaseTypesGM(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseTypesGM
	 */
	public final ugs.proxies.Enum_CaseTypesGM getCaseTypesGM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CaseTypesGM.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseTypesGM.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param casetypesgm
	 */
	public final void setCaseTypesGM(ugs.proxies.Enum_CaseTypesGM casetypesgm)
	{
		setCaseTypesGM(getContext(), casetypesgm);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param context
	 * @param casetypesgm
	 */
	public final void setCaseTypesGM(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseTypesGM casetypesgm)
	{
		if (casetypesgm != null)
			getMendixObject().setValue(context, MemberNames.CaseTypesGM.toString(), casetypesgm.toString());
		else
			getMendixObject().setValue(context, MemberNames.CaseTypesGM.toString(), null);
	}

	/**
	 * Set value of ForwardStatus
	 * @param forwardstatus
	 */
	public final ugs.proxies.Enum_ForwardStatus getForwardStatus()
	{
		return getForwardStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ForwardStatus
	 */
	public final ugs.proxies.Enum_ForwardStatus getForwardStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ForwardStatus.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ForwardStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ForwardStatus
	 * @param forwardstatus
	 */
	public final void setForwardStatus(ugs.proxies.Enum_ForwardStatus forwardstatus)
	{
		setForwardStatus(getContext(), forwardstatus);
	}

	/**
	 * Set value of ForwardStatus
	 * @param context
	 * @param forwardstatus
	 */
	public final void setForwardStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ForwardStatus forwardstatus)
	{
		if (forwardstatus != null)
			getMendixObject().setValue(context, MemberNames.ForwardStatus.toString(), forwardstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.ForwardStatus.toString(), null);
	}

	/**
	 * @return value of GM_Comments
	 */
	public final java.lang.String getGM_Comments()
	{
		return getGM_Comments(getContext());
	}

	/**
	 * @param context
	 * @return value of GM_Comments
	 */
	public final java.lang.String getGM_Comments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GM_Comments.toString());
	}

	/**
	 * Set value of GM_Comments
	 * @param gm_comments
	 */
	public final void setGM_Comments(java.lang.String gm_comments)
	{
		setGM_Comments(getContext(), gm_comments);
	}

	/**
	 * Set value of GM_Comments
	 * @param context
	 * @param gm_comments
	 */
	public final void setGM_Comments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gm_comments)
	{
		getMendixObject().setValue(context, MemberNames.GM_Comments.toString(), gm_comments);
	}

	/**
	 * @return value of Finace_Comments
	 */
	public final java.lang.String getFinace_Comments()
	{
		return getFinace_Comments(getContext());
	}

	/**
	 * @param context
	 * @return value of Finace_Comments
	 */
	public final java.lang.String getFinace_Comments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Finace_Comments.toString());
	}

	/**
	 * Set value of Finace_Comments
	 * @param finace_comments
	 */
	public final void setFinace_Comments(java.lang.String finace_comments)
	{
		setFinace_Comments(getContext(), finace_comments);
	}

	/**
	 * Set value of Finace_Comments
	 * @param context
	 * @param finace_comments
	 */
	public final void setFinace_Comments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finace_comments)
	{
		getMendixObject().setValue(context, MemberNames.Finace_Comments.toString(), finace_comments);
	}

	/**
	 * @return value of InvestigationOfficer_Comments
	 */
	public final java.lang.String getInvestigationOfficer_Comments()
	{
		return getInvestigationOfficer_Comments(getContext());
	}

	/**
	 * @param context
	 * @return value of InvestigationOfficer_Comments
	 */
	public final java.lang.String getInvestigationOfficer_Comments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InvestigationOfficer_Comments.toString());
	}

	/**
	 * Set value of InvestigationOfficer_Comments
	 * @param investigationofficer_comments
	 */
	public final void setInvestigationOfficer_Comments(java.lang.String investigationofficer_comments)
	{
		setInvestigationOfficer_Comments(getContext(), investigationofficer_comments);
	}

	/**
	 * Set value of InvestigationOfficer_Comments
	 * @param context
	 * @param investigationofficer_comments
	 */
	public final void setInvestigationOfficer_Comments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String investigationofficer_comments)
	{
		getMendixObject().setValue(context, MemberNames.InvestigationOfficer_Comments.toString(), investigationofficer_comments);
	}

	/**
	 * @return value of GM_HQComments
	 */
	public final java.lang.String getGM_HQComments()
	{
		return getGM_HQComments(getContext());
	}

	/**
	 * @param context
	 * @return value of GM_HQComments
	 */
	public final java.lang.String getGM_HQComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GM_HQComments.toString());
	}

	/**
	 * Set value of GM_HQComments
	 * @param gm_hqcomments
	 */
	public final void setGM_HQComments(java.lang.String gm_hqcomments)
	{
		setGM_HQComments(getContext(), gm_hqcomments);
	}

	/**
	 * Set value of GM_HQComments
	 * @param context
	 * @param gm_hqcomments
	 */
	public final void setGM_HQComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gm_hqcomments)
	{
		getMendixObject().setValue(context, MemberNames.GM_HQComments.toString(), gm_hqcomments);
	}

	/**
	 * Set value of Return_FA
	 * @param return_fa
	 */
	public final ugs.proxies.Enum_ReturnFinanceAdmin getReturn_FA()
	{
		return getReturn_FA(getContext());
	}

	/**
	 * @param context
	 * @return value of Return_FA
	 */
	public final ugs.proxies.Enum_ReturnFinanceAdmin getReturn_FA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Return_FA.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ReturnFinanceAdmin.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Return_FA
	 * @param return_fa
	 */
	public final void setReturn_FA(ugs.proxies.Enum_ReturnFinanceAdmin return_fa)
	{
		setReturn_FA(getContext(), return_fa);
	}

	/**
	 * Set value of Return_FA
	 * @param context
	 * @param return_fa
	 */
	public final void setReturn_FA(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ReturnFinanceAdmin return_fa)
	{
		if (return_fa != null)
			getMendixObject().setValue(context, MemberNames.Return_FA.toString(), return_fa.toString());
		else
			getMendixObject().setValue(context, MemberNames.Return_FA.toString(), null);
	}

	/**
	 * Set value of Return_GMHQ
	 * @param return_gmhq
	 */
	public final ugs.proxies.Enum_ReturnGM_HQ getReturn_GMHQ()
	{
		return getReturn_GMHQ(getContext());
	}

	/**
	 * @param context
	 * @return value of Return_GMHQ
	 */
	public final ugs.proxies.Enum_ReturnGM_HQ getReturn_GMHQ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Return_GMHQ.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ReturnGM_HQ.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Return_GMHQ
	 * @param return_gmhq
	 */
	public final void setReturn_GMHQ(ugs.proxies.Enum_ReturnGM_HQ return_gmhq)
	{
		setReturn_GMHQ(getContext(), return_gmhq);
	}

	/**
	 * Set value of Return_GMHQ
	 * @param context
	 * @param return_gmhq
	 */
	public final void setReturn_GMHQ(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ReturnGM_HQ return_gmhq)
	{
		if (return_gmhq != null)
			getMendixObject().setValue(context, MemberNames.Return_GMHQ.toString(), return_gmhq.toString());
		else
			getMendixObject().setValue(context, MemberNames.Return_GMHQ.toString(), null);
	}

	/**
	 * @return value of Request
	 */
	public final java.lang.Boolean getRequest()
	{
		return getRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Request
	 */
	public final java.lang.Boolean getRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Request.toString());
	}

	/**
	 * Set value of Request
	 * @param request
	 */
	public final void setRequest(java.lang.Boolean request)
	{
		setRequest(getContext(), request);
	}

	/**
	 * Set value of Request
	 * @param context
	 * @param request
	 */
	public final void setRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean request)
	{
		getMendixObject().setValue(context, MemberNames.Request.toString(), request);
	}

	/**
	 * @return value of StudyPhase
	 */
	public final java.lang.Boolean getStudyPhase()
	{
		return getStudyPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of StudyPhase
	 */
	public final java.lang.Boolean getStudyPhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StudyPhase.toString());
	}

	/**
	 * Set value of StudyPhase
	 * @param studyphase
	 */
	public final void setStudyPhase(java.lang.Boolean studyphase)
	{
		setStudyPhase(getContext(), studyphase);
	}

	/**
	 * Set value of StudyPhase
	 * @param context
	 * @param studyphase
	 */
	public final void setStudyPhase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean studyphase)
	{
		getMendixObject().setValue(context, MemberNames.StudyPhase.toString(), studyphase);
	}

	/**
	 * @return value of Dynamic
	 */
	public final java.lang.Boolean getDynamic()
	{
		return getDynamic(getContext());
	}

	/**
	 * @param context
	 * @return value of Dynamic
	 */
	public final java.lang.Boolean getDynamic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Dynamic.toString());
	}

	/**
	 * Set value of Dynamic
	 * @param dynamic
	 */
	public final void setDynamic(java.lang.Boolean dynamic)
	{
		setDynamic(getContext(), dynamic);
	}

	/**
	 * Set value of Dynamic
	 * @param context
	 * @param dynamic
	 */
	public final void setDynamic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean dynamic)
	{
		getMendixObject().setValue(context, MemberNames.Dynamic.toString(), dynamic);
	}

	/**
	 * @return value of CurrentOrder
	 */
	public final java.lang.Integer getCurrentOrder()
	{
		return getCurrentOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentOrder
	 */
	public final java.lang.Integer getCurrentOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentOrder.toString());
	}

	/**
	 * Set value of CurrentOrder
	 * @param currentorder
	 */
	public final void setCurrentOrder(java.lang.Integer currentorder)
	{
		setCurrentOrder(getContext(), currentorder);
	}

	/**
	 * Set value of CurrentOrder
	 * @param context
	 * @param currentorder
	 */
	public final void setCurrentOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentorder)
	{
		getMendixObject().setValue(context, MemberNames.CurrentOrder.toString(), currentorder);
	}

	/**
	 * @return value of Ref_No
	 */
	public final java.lang.Long getRef_No()
	{
		return getRef_No(getContext());
	}

	/**
	 * @param context
	 * @return value of Ref_No
	 */
	public final java.lang.Long getRef_No(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Ref_No.toString());
	}

	/**
	 * Set value of Ref_No
	 * @param ref_no
	 */
	public final void setRef_No(java.lang.Long ref_no)
	{
		setRef_No(getContext(), ref_no);
	}

	/**
	 * Set value of Ref_No
	 * @param context
	 * @param ref_no
	 */
	public final void setRef_No(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ref_no)
	{
		getMendixObject().setValue(context, MemberNames.Ref_No.toString(), ref_no);
	}

	/**
	 * @return value of History
	 */
	public final java.lang.String getHistory()
	{
		return getHistory(getContext());
	}

	/**
	 * @param context
	 * @return value of History
	 */
	public final java.lang.String getHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.History.toString());
	}

	/**
	 * Set value of History
	 * @param history
	 */
	public final void setHistory(java.lang.String history)
	{
		setHistory(getContext(), history);
	}

	/**
	 * Set value of History
	 * @param context
	 * @param history
	 */
	public final void setHistory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String history)
	{
		getMendixObject().setValue(context, MemberNames.History.toString(), history);
	}

	/**
	 * @return value of Submit
	 */
	public final java.lang.Boolean getSubmit()
	{
		return getSubmit(getContext());
	}

	/**
	 * @param context
	 * @return value of Submit
	 */
	public final java.lang.Boolean getSubmit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Submit.toString());
	}

	/**
	 * Set value of Submit
	 * @param submit
	 */
	public final void setSubmit(java.lang.Boolean submit)
	{
		setSubmit(getContext(), submit);
	}

	/**
	 * Set value of Submit
	 * @param context
	 * @param submit
	 */
	public final void setSubmit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean submit)
	{
		getMendixObject().setValue(context, MemberNames.Submit.toString(), submit);
	}

	/**
	 * @return value of SubmitGM
	 */
	public final java.lang.Boolean getSubmitGM()
	{
		return getSubmitGM(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmitGM
	 */
	public final java.lang.Boolean getSubmitGM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SubmitGM.toString());
	}

	/**
	 * Set value of SubmitGM
	 * @param submitgm
	 */
	public final void setSubmitGM(java.lang.Boolean submitgm)
	{
		setSubmitGM(getContext(), submitgm);
	}

	/**
	 * Set value of SubmitGM
	 * @param context
	 * @param submitgm
	 */
	public final void setSubmitGM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean submitgm)
	{
		getMendixObject().setValue(context, MemberNames.SubmitGM.toString(), submitgm);
	}

	/**
	 * Set value of Phase
	 * @param phase
	 */
	public final ugs.proxies.Enum_CasePhase getPhase()
	{
		return getPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of Phase
	 */
	public final ugs.proxies.Enum_CasePhase getPhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Phase.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CasePhase.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Phase
	 * @param phase
	 */
	public final void setPhase(ugs.proxies.Enum_CasePhase phase)
	{
		setPhase(getContext(), phase);
	}

	/**
	 * Set value of Phase
	 * @param context
	 * @param phase
	 */
	public final void setPhase(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CasePhase phase)
	{
		if (phase != null)
			getMendixObject().setValue(context, MemberNames.Phase.toString(), phase.toString());
		else
			getMendixObject().setValue(context, MemberNames.Phase.toString(), null);
	}

	/**
	 * @return value of CaseMangement_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getCaseMangement_GrantSystem() throws com.mendix.core.CoreException
	{
		return getCaseMangement_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseMangement_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getCaseMangement_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaseMangement_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CaseMangement_GrantSystem
	 * @param casemangement_grantsystem
	 */
	public final void setCaseMangement_GrantSystem(ugs.proxies.GrantSystem casemangement_grantsystem)
	{
		setCaseMangement_GrantSystem(getContext(), casemangement_grantsystem);
	}

	/**
	 * Set value of CaseMangement_GrantSystem
	 * @param context
	 * @param casemangement_grantsystem
	 */
	public final void setCaseMangement_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem casemangement_grantsystem)
	{
		if (casemangement_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.CaseMangement_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CaseMangement_GrantSystem.toString(), casemangement_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of FileDocument_CaseMangement
	 */
	public final ugs.proxies.FileDocument getFileDocument_CaseMangement() throws com.mendix.core.CoreException
	{
		return getFileDocument_CaseMangement(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocument_CaseMangement
	 */
	public final ugs.proxies.FileDocument getFileDocument_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileDocument_CaseMangement.toString());
		if (identifier != null)
			result = ugs.proxies.FileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FileDocument_CaseMangement
	 * @param filedocument_casemangement
	 */
	public final void setFileDocument_CaseMangement(ugs.proxies.FileDocument filedocument_casemangement)
	{
		setFileDocument_CaseMangement(getContext(), filedocument_casemangement);
	}

	/**
	 * Set value of FileDocument_CaseMangement
	 * @param context
	 * @param filedocument_casemangement
	 */
	public final void setFileDocument_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.FileDocument filedocument_casemangement)
	{
		if (filedocument_casemangement == null)
			getMendixObject().setValue(context, MemberNames.FileDocument_CaseMangement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FileDocument_CaseMangement.toString(), filedocument_casemangement.getMendixObject().getId());
	}

	/**
	 * @return value of Applicant_Case
	 */
	public final administration.proxies.Account getApplicant_Case() throws com.mendix.core.CoreException
	{
		return getApplicant_Case(getContext());
	}

	/**
	 * @param context
	 * @return value of Applicant_Case
	 */
	public final administration.proxies.Account getApplicant_Case(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Applicant_Case.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Applicant_Case
	 * @param applicant_case
	 */
	public final void setApplicant_Case(administration.proxies.Account applicant_case)
	{
		setApplicant_Case(getContext(), applicant_case);
	}

	/**
	 * Set value of Applicant_Case
	 * @param context
	 * @param applicant_case
	 */
	public final void setApplicant_Case(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account applicant_case)
	{
		if (applicant_case == null)
			getMendixObject().setValue(context, MemberNames.Applicant_Case.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Applicant_Case.toString(), applicant_case.getMendixObject().getId());
	}

	/**
	 * @return value of CaseMangement_CurrentHoldingAccount
	 */
	public final administration.proxies.Account getCaseMangement_CurrentHoldingAccount() throws com.mendix.core.CoreException
	{
		return getCaseMangement_CurrentHoldingAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseMangement_CurrentHoldingAccount
	 */
	public final administration.proxies.Account getCaseMangement_CurrentHoldingAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaseMangement_CurrentHoldingAccount.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CaseMangement_CurrentHoldingAccount
	 * @param casemangement_currentholdingaccount
	 */
	public final void setCaseMangement_CurrentHoldingAccount(administration.proxies.Account casemangement_currentholdingaccount)
	{
		setCaseMangement_CurrentHoldingAccount(getContext(), casemangement_currentholdingaccount);
	}

	/**
	 * Set value of CaseMangement_CurrentHoldingAccount
	 * @param context
	 * @param casemangement_currentholdingaccount
	 */
	public final void setCaseMangement_CurrentHoldingAccount(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account casemangement_currentholdingaccount)
	{
		if (casemangement_currentholdingaccount == null)
			getMendixObject().setValue(context, MemberNames.CaseMangement_CurrentHoldingAccount.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CaseMangement_CurrentHoldingAccount.toString(), casemangement_currentholdingaccount.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return caseMangementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.CaseMangement that = (ugs.proxies.CaseMangement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.CaseMangement";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
