// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class CaseMangement_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject caseMangement_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.CaseMangement_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		CaseStatement("CaseStatement"),
		Amount("Amount"),
		CaseTypes("CaseTypes"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		CaseTypesGM("CaseTypesGM"),
		ForwardStatus("ForwardStatus"),
		Request("Request"),
		StudyPhase("StudyPhase"),
		Dynamic("Dynamic"),
		Ref_No("Ref_No"),
		History("History"),
		Submit("Submit"),
		Phase("Phase"),
		Remarks("Remarks"),
		StatusApplicant("StatusApplicant"),
		ApplicantName("ApplicantName"),
		InvOfficer("InvOfficer"),
		GrantName("GrantName"),
		GrantID("GrantID"),
		PermanentID("PermanentID"),
		CaseMangement_2_Root_ProcessHelper("UGS.CaseMangement_2_Root_ProcessHelper");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CaseMangement_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.CaseMangement_2"));
	}

	protected CaseMangement_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject caseMangement_2MendixObject)
	{
		if (caseMangement_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.CaseMangement_2", caseMangement_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.CaseMangement_2");

		this.caseMangement_2MendixObject = caseMangement_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CaseMangement_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.CaseMangement_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.CaseMangement_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.CaseMangement_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.CaseMangement_2(context, mendixObject);
	}

	public static ugs.proxies.CaseMangement_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.CaseMangement_2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of CaseStatement
	 */
	public final java.lang.String getCaseStatement()
	{
		return getCaseStatement(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseStatement
	 */
	public final java.lang.String getCaseStatement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CaseStatement.toString());
	}

	/**
	 * Set value of CaseStatement
	 * @param casestatement
	 */
	public final void setCaseStatement(java.lang.String casestatement)
	{
		setCaseStatement(getContext(), casestatement);
	}

	/**
	 * Set value of CaseStatement
	 * @param context
	 * @param casestatement
	 */
	public final void setCaseStatement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String casestatement)
	{
		getMendixObject().setValue(context, MemberNames.CaseStatement.toString(), casestatement);
	}

	/**
	 * @return value of Amount
	 */
	public final java.lang.Long getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.Long getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.Long amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * Set value of CaseTypes
	 * @param casetypes
	 */
	public final ugs.proxies.Enum_CaseTypes getCaseTypes()
	{
		return getCaseTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseTypes
	 */
	public final ugs.proxies.Enum_CaseTypes getCaseTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CaseTypes.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CaseTypes
	 * @param casetypes
	 */
	public final void setCaseTypes(ugs.proxies.Enum_CaseTypes casetypes)
	{
		setCaseTypes(getContext(), casetypes);
	}

	/**
	 * Set value of CaseTypes
	 * @param context
	 * @param casetypes
	 */
	public final void setCaseTypes(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseTypes casetypes)
	{
		if (casetypes != null)
			getMendixObject().setValue(context, MemberNames.CaseTypes.toString(), casetypes.toString());
		else
			getMendixObject().setValue(context, MemberNames.CaseTypes.toString(), null);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param casetypesgm
	 */
	public final ugs.proxies.Enum_CaseTypesGM getCaseTypesGM()
	{
		return getCaseTypesGM(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseTypesGM
	 */
	public final ugs.proxies.Enum_CaseTypesGM getCaseTypesGM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CaseTypesGM.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseTypesGM.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param casetypesgm
	 */
	public final void setCaseTypesGM(ugs.proxies.Enum_CaseTypesGM casetypesgm)
	{
		setCaseTypesGM(getContext(), casetypesgm);
	}

	/**
	 * Set value of CaseTypesGM
	 * @param context
	 * @param casetypesgm
	 */
	public final void setCaseTypesGM(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseTypesGM casetypesgm)
	{
		if (casetypesgm != null)
			getMendixObject().setValue(context, MemberNames.CaseTypesGM.toString(), casetypesgm.toString());
		else
			getMendixObject().setValue(context, MemberNames.CaseTypesGM.toString(), null);
	}

	/**
	 * Set value of ForwardStatus
	 * @param forwardstatus
	 */
	public final ugs.proxies.Enum_ForwardStatus getForwardStatus()
	{
		return getForwardStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ForwardStatus
	 */
	public final ugs.proxies.Enum_ForwardStatus getForwardStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ForwardStatus.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ForwardStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ForwardStatus
	 * @param forwardstatus
	 */
	public final void setForwardStatus(ugs.proxies.Enum_ForwardStatus forwardstatus)
	{
		setForwardStatus(getContext(), forwardstatus);
	}

	/**
	 * Set value of ForwardStatus
	 * @param context
	 * @param forwardstatus
	 */
	public final void setForwardStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ForwardStatus forwardstatus)
	{
		if (forwardstatus != null)
			getMendixObject().setValue(context, MemberNames.ForwardStatus.toString(), forwardstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.ForwardStatus.toString(), null);
	}

	/**
	 * @return value of Request
	 */
	public final java.lang.Boolean getRequest()
	{
		return getRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Request
	 */
	public final java.lang.Boolean getRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Request.toString());
	}

	/**
	 * Set value of Request
	 * @param request
	 */
	public final void setRequest(java.lang.Boolean request)
	{
		setRequest(getContext(), request);
	}

	/**
	 * Set value of Request
	 * @param context
	 * @param request
	 */
	public final void setRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean request)
	{
		getMendixObject().setValue(context, MemberNames.Request.toString(), request);
	}

	/**
	 * @return value of StudyPhase
	 */
	public final java.lang.Boolean getStudyPhase()
	{
		return getStudyPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of StudyPhase
	 */
	public final java.lang.Boolean getStudyPhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StudyPhase.toString());
	}

	/**
	 * Set value of StudyPhase
	 * @param studyphase
	 */
	public final void setStudyPhase(java.lang.Boolean studyphase)
	{
		setStudyPhase(getContext(), studyphase);
	}

	/**
	 * Set value of StudyPhase
	 * @param context
	 * @param studyphase
	 */
	public final void setStudyPhase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean studyphase)
	{
		getMendixObject().setValue(context, MemberNames.StudyPhase.toString(), studyphase);
	}

	/**
	 * @return value of Dynamic
	 */
	public final java.lang.Boolean getDynamic()
	{
		return getDynamic(getContext());
	}

	/**
	 * @param context
	 * @return value of Dynamic
	 */
	public final java.lang.Boolean getDynamic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Dynamic.toString());
	}

	/**
	 * Set value of Dynamic
	 * @param dynamic
	 */
	public final void setDynamic(java.lang.Boolean dynamic)
	{
		setDynamic(getContext(), dynamic);
	}

	/**
	 * Set value of Dynamic
	 * @param context
	 * @param dynamic
	 */
	public final void setDynamic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean dynamic)
	{
		getMendixObject().setValue(context, MemberNames.Dynamic.toString(), dynamic);
	}

	/**
	 * @return value of Ref_No
	 */
	public final java.lang.Integer getRef_No()
	{
		return getRef_No(getContext());
	}

	/**
	 * @param context
	 * @return value of Ref_No
	 */
	public final java.lang.Integer getRef_No(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ref_No.toString());
	}

	/**
	 * Set value of Ref_No
	 * @param ref_no
	 */
	public final void setRef_No(java.lang.Integer ref_no)
	{
		setRef_No(getContext(), ref_no);
	}

	/**
	 * Set value of Ref_No
	 * @param context
	 * @param ref_no
	 */
	public final void setRef_No(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ref_no)
	{
		getMendixObject().setValue(context, MemberNames.Ref_No.toString(), ref_no);
	}

	/**
	 * @return value of History
	 */
	public final java.lang.String getHistory()
	{
		return getHistory(getContext());
	}

	/**
	 * @param context
	 * @return value of History
	 */
	public final java.lang.String getHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.History.toString());
	}

	/**
	 * Set value of History
	 * @param history
	 */
	public final void setHistory(java.lang.String history)
	{
		setHistory(getContext(), history);
	}

	/**
	 * Set value of History
	 * @param context
	 * @param history
	 */
	public final void setHistory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String history)
	{
		getMendixObject().setValue(context, MemberNames.History.toString(), history);
	}

	/**
	 * @return value of Submit
	 */
	public final java.lang.Boolean getSubmit()
	{
		return getSubmit(getContext());
	}

	/**
	 * @param context
	 * @return value of Submit
	 */
	public final java.lang.Boolean getSubmit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Submit.toString());
	}

	/**
	 * Set value of Submit
	 * @param submit
	 */
	public final void setSubmit(java.lang.Boolean submit)
	{
		setSubmit(getContext(), submit);
	}

	/**
	 * Set value of Submit
	 * @param context
	 * @param submit
	 */
	public final void setSubmit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean submit)
	{
		getMendixObject().setValue(context, MemberNames.Submit.toString(), submit);
	}

	/**
	 * Set value of Phase
	 * @param phase
	 */
	public final ugs.proxies.Enum_CasePhase getPhase()
	{
		return getPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of Phase
	 */
	public final ugs.proxies.Enum_CasePhase getPhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Phase.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CasePhase.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Phase
	 * @param phase
	 */
	public final void setPhase(ugs.proxies.Enum_CasePhase phase)
	{
		setPhase(getContext(), phase);
	}

	/**
	 * Set value of Phase
	 * @param context
	 * @param phase
	 */
	public final void setPhase(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CasePhase phase)
	{
		if (phase != null)
			getMendixObject().setValue(context, MemberNames.Phase.toString(), phase.toString());
		else
			getMendixObject().setValue(context, MemberNames.Phase.toString(), null);
	}

	/**
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks()
	{
		return getRemarks(getContext());
	}

	/**
	 * @param context
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Remarks.toString());
	}

	/**
	 * Set value of Remarks
	 * @param remarks
	 */
	public final void setRemarks(java.lang.String remarks)
	{
		setRemarks(getContext(), remarks);
	}

	/**
	 * Set value of Remarks
	 * @param context
	 * @param remarks
	 */
	public final void setRemarks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remarks)
	{
		getMendixObject().setValue(context, MemberNames.Remarks.toString(), remarks);
	}

	/**
	 * Set value of StatusApplicant
	 * @param statusapplicant
	 */
	public final ugs.proxies.Enum_CaseStatusApplicant getStatusApplicant()
	{
		return getStatusApplicant(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusApplicant
	 */
	public final ugs.proxies.Enum_CaseStatusApplicant getStatusApplicant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.StatusApplicant.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_CaseStatusApplicant.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of StatusApplicant
	 * @param statusapplicant
	 */
	public final void setStatusApplicant(ugs.proxies.Enum_CaseStatusApplicant statusapplicant)
	{
		setStatusApplicant(getContext(), statusapplicant);
	}

	/**
	 * Set value of StatusApplicant
	 * @param context
	 * @param statusapplicant
	 */
	public final void setStatusApplicant(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_CaseStatusApplicant statusapplicant)
	{
		if (statusapplicant != null)
			getMendixObject().setValue(context, MemberNames.StatusApplicant.toString(), statusapplicant.toString());
		else
			getMendixObject().setValue(context, MemberNames.StatusApplicant.toString(), null);
	}

	/**
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName()
	{
		return getApplicantName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicantName.toString());
	}

	/**
	 * Set value of ApplicantName
	 * @param applicantname
	 */
	public final void setApplicantName(java.lang.String applicantname)
	{
		setApplicantName(getContext(), applicantname);
	}

	/**
	 * Set value of ApplicantName
	 * @param context
	 * @param applicantname
	 */
	public final void setApplicantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicantname)
	{
		getMendixObject().setValue(context, MemberNames.ApplicantName.toString(), applicantname);
	}

	/**
	 * @return value of InvOfficer
	 */
	public final java.lang.String getInvOfficer()
	{
		return getInvOfficer(getContext());
	}

	/**
	 * @param context
	 * @return value of InvOfficer
	 */
	public final java.lang.String getInvOfficer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InvOfficer.toString());
	}

	/**
	 * Set value of InvOfficer
	 * @param invofficer
	 */
	public final void setInvOfficer(java.lang.String invofficer)
	{
		setInvOfficer(getContext(), invofficer);
	}

	/**
	 * Set value of InvOfficer
	 * @param context
	 * @param invofficer
	 */
	public final void setInvOfficer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String invofficer)
	{
		getMendixObject().setValue(context, MemberNames.InvOfficer.toString(), invofficer);
	}

	/**
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName()
	{
		return getGrantName(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GrantName.toString());
	}

	/**
	 * Set value of GrantName
	 * @param grantname
	 */
	public final void setGrantName(java.lang.String grantname)
	{
		setGrantName(getContext(), grantname);
	}

	/**
	 * Set value of GrantName
	 * @param context
	 * @param grantname
	 */
	public final void setGrantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grantname)
	{
		getMendixObject().setValue(context, MemberNames.GrantName.toString(), grantname);
	}

	/**
	 * @return value of GrantID
	 */
	public final java.lang.Integer getGrantID()
	{
		return getGrantID(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantID
	 */
	public final java.lang.Integer getGrantID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.GrantID.toString());
	}

	/**
	 * Set value of GrantID
	 * @param grantid
	 */
	public final void setGrantID(java.lang.Integer grantid)
	{
		setGrantID(getContext(), grantid);
	}

	/**
	 * Set value of GrantID
	 * @param context
	 * @param grantid
	 */
	public final void setGrantID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer grantid)
	{
		getMendixObject().setValue(context, MemberNames.GrantID.toString(), grantid);
	}

	/**
	 * @return value of PermanentID
	 */
	public final java.lang.Integer getPermanentID()
	{
		return getPermanentID(getContext());
	}

	/**
	 * @param context
	 * @return value of PermanentID
	 */
	public final java.lang.Integer getPermanentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PermanentID.toString());
	}

	/**
	 * Set value of PermanentID
	 * @param permanentid
	 */
	public final void setPermanentID(java.lang.Integer permanentid)
	{
		setPermanentID(getContext(), permanentid);
	}

	/**
	 * Set value of PermanentID
	 * @param context
	 * @param permanentid
	 */
	public final void setPermanentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer permanentid)
	{
		getMendixObject().setValue(context, MemberNames.PermanentID.toString(), permanentid);
	}

	/**
	 * @return value of CaseMangement_2_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getCaseMangement_2_Root_ProcessHelper() throws com.mendix.core.CoreException
	{
		return getCaseMangement_2_Root_ProcessHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseMangement_2_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getCaseMangement_2_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Root_ProcessHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaseMangement_2_Root_ProcessHelper.toString());
		if (identifier != null)
			result = ugs.proxies.Root_ProcessHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CaseMangement_2_Root_ProcessHelper
	 * @param casemangement_2_root_processhelper
	 */
	public final void setCaseMangement_2_Root_ProcessHelper(ugs.proxies.Root_ProcessHelper casemangement_2_root_processhelper)
	{
		setCaseMangement_2_Root_ProcessHelper(getContext(), casemangement_2_root_processhelper);
	}

	/**
	 * Set value of CaseMangement_2_Root_ProcessHelper
	 * @param context
	 * @param casemangement_2_root_processhelper
	 */
	public final void setCaseMangement_2_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Root_ProcessHelper casemangement_2_root_processhelper)
	{
		if (casemangement_2_root_processhelper == null)
			getMendixObject().setValue(context, MemberNames.CaseMangement_2_Root_ProcessHelper.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CaseMangement_2_Root_ProcessHelper.toString(), casemangement_2_root_processhelper.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return caseMangement_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.CaseMangement_2 that = (ugs.proxies.CaseMangement_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.CaseMangement_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
