// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class ChartData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.ChartData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SingaporeCitizenCount("SingaporeCitizenCount"),
		InternationalCitizenCount("InternationalCitizenCount"),
		Funding_AwardedCount("Funding_AwardedCount"),
		Funding_PaidCount("Funding_PaidCount"),
		Cases_InProgressCount("Cases_InProgressCount"),
		Cases_ResolvedCount("Cases_ResolvedCount"),
		Cases_PendingCount("Cases_PendingCount"),
		Cases_ReturnedCount("Cases_ReturnedCount"),
		FundingDetails("FundingDetails"),
		InitialScreening("InitialScreening"),
		TestSentToApplicant("TestSentToApplicant"),
		TestResultsRecieved("TestResultsRecieved"),
		TestReviewed("TestReviewed"),
		ApplicantReviewedByInterviewer("ApplicantReviewedByInterviewer"),
		ApprovedByBoard("ApprovedByBoard"),
		AggrementLetterSentToApplicant("AggrementLetterSentToApplicant"),
		ApplicantAccepted("ApplicantAccepted"),
		Forwarded_to_FA_Cases("Forwarded_to_FA_Cases"),
		Forwarded_to_IO_Cases("Forwarded_to_IO_Cases"),
		Forwarded_to_GMHQ_Cases("Forwarded_to_GMHQ_Cases"),
		FundingInPorgress("FundingInPorgress"),
		Name("Name"),
		ValueStr("ValueStr"),
		ValueCount("ValueCount"),
		ChartData_Root_ProcessHelper("UGS.ChartData_Root_ProcessHelper");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChartData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.ChartData"));
	}

	protected ChartData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartDataMendixObject)
	{
		if (chartDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.ChartData", chartDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.ChartData");

		this.chartDataMendixObject = chartDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChartData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.ChartData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.ChartData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.ChartData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.ChartData(context, mendixObject);
	}

	public static ugs.proxies.ChartData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.ChartData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SingaporeCitizenCount
	 */
	public final java.lang.Integer getSingaporeCitizenCount()
	{
		return getSingaporeCitizenCount(getContext());
	}

	/**
	 * @param context
	 * @return value of SingaporeCitizenCount
	 */
	public final java.lang.Integer getSingaporeCitizenCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SingaporeCitizenCount.toString());
	}

	/**
	 * Set value of SingaporeCitizenCount
	 * @param singaporecitizencount
	 */
	public final void setSingaporeCitizenCount(java.lang.Integer singaporecitizencount)
	{
		setSingaporeCitizenCount(getContext(), singaporecitizencount);
	}

	/**
	 * Set value of SingaporeCitizenCount
	 * @param context
	 * @param singaporecitizencount
	 */
	public final void setSingaporeCitizenCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer singaporecitizencount)
	{
		getMendixObject().setValue(context, MemberNames.SingaporeCitizenCount.toString(), singaporecitizencount);
	}

	/**
	 * @return value of InternationalCitizenCount
	 */
	public final java.lang.Integer getInternationalCitizenCount()
	{
		return getInternationalCitizenCount(getContext());
	}

	/**
	 * @param context
	 * @return value of InternationalCitizenCount
	 */
	public final java.lang.Integer getInternationalCitizenCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InternationalCitizenCount.toString());
	}

	/**
	 * Set value of InternationalCitizenCount
	 * @param internationalcitizencount
	 */
	public final void setInternationalCitizenCount(java.lang.Integer internationalcitizencount)
	{
		setInternationalCitizenCount(getContext(), internationalcitizencount);
	}

	/**
	 * Set value of InternationalCitizenCount
	 * @param context
	 * @param internationalcitizencount
	 */
	public final void setInternationalCitizenCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer internationalcitizencount)
	{
		getMendixObject().setValue(context, MemberNames.InternationalCitizenCount.toString(), internationalcitizencount);
	}

	/**
	 * @return value of Funding_AwardedCount
	 */
	public final java.lang.Integer getFunding_AwardedCount()
	{
		return getFunding_AwardedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Funding_AwardedCount
	 */
	public final java.lang.Integer getFunding_AwardedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Funding_AwardedCount.toString());
	}

	/**
	 * Set value of Funding_AwardedCount
	 * @param funding_awardedcount
	 */
	public final void setFunding_AwardedCount(java.lang.Integer funding_awardedcount)
	{
		setFunding_AwardedCount(getContext(), funding_awardedcount);
	}

	/**
	 * Set value of Funding_AwardedCount
	 * @param context
	 * @param funding_awardedcount
	 */
	public final void setFunding_AwardedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer funding_awardedcount)
	{
		getMendixObject().setValue(context, MemberNames.Funding_AwardedCount.toString(), funding_awardedcount);
	}

	/**
	 * @return value of Funding_PaidCount
	 */
	public final java.lang.Integer getFunding_PaidCount()
	{
		return getFunding_PaidCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Funding_PaidCount
	 */
	public final java.lang.Integer getFunding_PaidCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Funding_PaidCount.toString());
	}

	/**
	 * Set value of Funding_PaidCount
	 * @param funding_paidcount
	 */
	public final void setFunding_PaidCount(java.lang.Integer funding_paidcount)
	{
		setFunding_PaidCount(getContext(), funding_paidcount);
	}

	/**
	 * Set value of Funding_PaidCount
	 * @param context
	 * @param funding_paidcount
	 */
	public final void setFunding_PaidCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer funding_paidcount)
	{
		getMendixObject().setValue(context, MemberNames.Funding_PaidCount.toString(), funding_paidcount);
	}

	/**
	 * @return value of Cases_InProgressCount
	 */
	public final java.lang.Integer getCases_InProgressCount()
	{
		return getCases_InProgressCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Cases_InProgressCount
	 */
	public final java.lang.Integer getCases_InProgressCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cases_InProgressCount.toString());
	}

	/**
	 * Set value of Cases_InProgressCount
	 * @param cases_inprogresscount
	 */
	public final void setCases_InProgressCount(java.lang.Integer cases_inprogresscount)
	{
		setCases_InProgressCount(getContext(), cases_inprogresscount);
	}

	/**
	 * Set value of Cases_InProgressCount
	 * @param context
	 * @param cases_inprogresscount
	 */
	public final void setCases_InProgressCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cases_inprogresscount)
	{
		getMendixObject().setValue(context, MemberNames.Cases_InProgressCount.toString(), cases_inprogresscount);
	}

	/**
	 * @return value of Cases_ResolvedCount
	 */
	public final java.lang.Integer getCases_ResolvedCount()
	{
		return getCases_ResolvedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Cases_ResolvedCount
	 */
	public final java.lang.Integer getCases_ResolvedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cases_ResolvedCount.toString());
	}

	/**
	 * Set value of Cases_ResolvedCount
	 * @param cases_resolvedcount
	 */
	public final void setCases_ResolvedCount(java.lang.Integer cases_resolvedcount)
	{
		setCases_ResolvedCount(getContext(), cases_resolvedcount);
	}

	/**
	 * Set value of Cases_ResolvedCount
	 * @param context
	 * @param cases_resolvedcount
	 */
	public final void setCases_ResolvedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cases_resolvedcount)
	{
		getMendixObject().setValue(context, MemberNames.Cases_ResolvedCount.toString(), cases_resolvedcount);
	}

	/**
	 * @return value of Cases_PendingCount
	 */
	public final java.lang.Integer getCases_PendingCount()
	{
		return getCases_PendingCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Cases_PendingCount
	 */
	public final java.lang.Integer getCases_PendingCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cases_PendingCount.toString());
	}

	/**
	 * Set value of Cases_PendingCount
	 * @param cases_pendingcount
	 */
	public final void setCases_PendingCount(java.lang.Integer cases_pendingcount)
	{
		setCases_PendingCount(getContext(), cases_pendingcount);
	}

	/**
	 * Set value of Cases_PendingCount
	 * @param context
	 * @param cases_pendingcount
	 */
	public final void setCases_PendingCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cases_pendingcount)
	{
		getMendixObject().setValue(context, MemberNames.Cases_PendingCount.toString(), cases_pendingcount);
	}

	/**
	 * @return value of Cases_ReturnedCount
	 */
	public final java.lang.Integer getCases_ReturnedCount()
	{
		return getCases_ReturnedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Cases_ReturnedCount
	 */
	public final java.lang.Integer getCases_ReturnedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cases_ReturnedCount.toString());
	}

	/**
	 * Set value of Cases_ReturnedCount
	 * @param cases_returnedcount
	 */
	public final void setCases_ReturnedCount(java.lang.Integer cases_returnedcount)
	{
		setCases_ReturnedCount(getContext(), cases_returnedcount);
	}

	/**
	 * Set value of Cases_ReturnedCount
	 * @param context
	 * @param cases_returnedcount
	 */
	public final void setCases_ReturnedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cases_returnedcount)
	{
		getMendixObject().setValue(context, MemberNames.Cases_ReturnedCount.toString(), cases_returnedcount);
	}

	/**
	 * @return value of FundingDetails
	 */
	public final java.lang.String getFundingDetails()
	{
		return getFundingDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of FundingDetails
	 */
	public final java.lang.String getFundingDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FundingDetails.toString());
	}

	/**
	 * Set value of FundingDetails
	 * @param fundingdetails
	 */
	public final void setFundingDetails(java.lang.String fundingdetails)
	{
		setFundingDetails(getContext(), fundingdetails);
	}

	/**
	 * Set value of FundingDetails
	 * @param context
	 * @param fundingdetails
	 */
	public final void setFundingDetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fundingdetails)
	{
		getMendixObject().setValue(context, MemberNames.FundingDetails.toString(), fundingdetails);
	}

	/**
	 * @return value of InitialScreening
	 */
	public final java.lang.Integer getInitialScreening()
	{
		return getInitialScreening(getContext());
	}

	/**
	 * @param context
	 * @return value of InitialScreening
	 */
	public final java.lang.Integer getInitialScreening(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InitialScreening.toString());
	}

	/**
	 * Set value of InitialScreening
	 * @param initialscreening
	 */
	public final void setInitialScreening(java.lang.Integer initialscreening)
	{
		setInitialScreening(getContext(), initialscreening);
	}

	/**
	 * Set value of InitialScreening
	 * @param context
	 * @param initialscreening
	 */
	public final void setInitialScreening(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer initialscreening)
	{
		getMendixObject().setValue(context, MemberNames.InitialScreening.toString(), initialscreening);
	}

	/**
	 * @return value of TestSentToApplicant
	 */
	public final java.lang.Integer getTestSentToApplicant()
	{
		return getTestSentToApplicant(getContext());
	}

	/**
	 * @param context
	 * @return value of TestSentToApplicant
	 */
	public final java.lang.Integer getTestSentToApplicant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestSentToApplicant.toString());
	}

	/**
	 * Set value of TestSentToApplicant
	 * @param testsenttoapplicant
	 */
	public final void setTestSentToApplicant(java.lang.Integer testsenttoapplicant)
	{
		setTestSentToApplicant(getContext(), testsenttoapplicant);
	}

	/**
	 * Set value of TestSentToApplicant
	 * @param context
	 * @param testsenttoapplicant
	 */
	public final void setTestSentToApplicant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testsenttoapplicant)
	{
		getMendixObject().setValue(context, MemberNames.TestSentToApplicant.toString(), testsenttoapplicant);
	}

	/**
	 * @return value of TestResultsRecieved
	 */
	public final java.lang.Integer getTestResultsRecieved()
	{
		return getTestResultsRecieved(getContext());
	}

	/**
	 * @param context
	 * @return value of TestResultsRecieved
	 */
	public final java.lang.Integer getTestResultsRecieved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestResultsRecieved.toString());
	}

	/**
	 * Set value of TestResultsRecieved
	 * @param testresultsrecieved
	 */
	public final void setTestResultsRecieved(java.lang.Integer testresultsrecieved)
	{
		setTestResultsRecieved(getContext(), testresultsrecieved);
	}

	/**
	 * Set value of TestResultsRecieved
	 * @param context
	 * @param testresultsrecieved
	 */
	public final void setTestResultsRecieved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testresultsrecieved)
	{
		getMendixObject().setValue(context, MemberNames.TestResultsRecieved.toString(), testresultsrecieved);
	}

	/**
	 * @return value of TestReviewed
	 */
	public final java.lang.Integer getTestReviewed()
	{
		return getTestReviewed(getContext());
	}

	/**
	 * @param context
	 * @return value of TestReviewed
	 */
	public final java.lang.Integer getTestReviewed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestReviewed.toString());
	}

	/**
	 * Set value of TestReviewed
	 * @param testreviewed
	 */
	public final void setTestReviewed(java.lang.Integer testreviewed)
	{
		setTestReviewed(getContext(), testreviewed);
	}

	/**
	 * Set value of TestReviewed
	 * @param context
	 * @param testreviewed
	 */
	public final void setTestReviewed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testreviewed)
	{
		getMendixObject().setValue(context, MemberNames.TestReviewed.toString(), testreviewed);
	}

	/**
	 * @return value of ApplicantReviewedByInterviewer
	 */
	public final java.lang.Integer getApplicantReviewedByInterviewer()
	{
		return getApplicantReviewedByInterviewer(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicantReviewedByInterviewer
	 */
	public final java.lang.Integer getApplicantReviewedByInterviewer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApplicantReviewedByInterviewer.toString());
	}

	/**
	 * Set value of ApplicantReviewedByInterviewer
	 * @param applicantreviewedbyinterviewer
	 */
	public final void setApplicantReviewedByInterviewer(java.lang.Integer applicantreviewedbyinterviewer)
	{
		setApplicantReviewedByInterviewer(getContext(), applicantreviewedbyinterviewer);
	}

	/**
	 * Set value of ApplicantReviewedByInterviewer
	 * @param context
	 * @param applicantreviewedbyinterviewer
	 */
	public final void setApplicantReviewedByInterviewer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer applicantreviewedbyinterviewer)
	{
		getMendixObject().setValue(context, MemberNames.ApplicantReviewedByInterviewer.toString(), applicantreviewedbyinterviewer);
	}

	/**
	 * @return value of ApprovedByBoard
	 */
	public final java.lang.Integer getApprovedByBoard()
	{
		return getApprovedByBoard(getContext());
	}

	/**
	 * @param context
	 * @return value of ApprovedByBoard
	 */
	public final java.lang.Integer getApprovedByBoard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApprovedByBoard.toString());
	}

	/**
	 * Set value of ApprovedByBoard
	 * @param approvedbyboard
	 */
	public final void setApprovedByBoard(java.lang.Integer approvedbyboard)
	{
		setApprovedByBoard(getContext(), approvedbyboard);
	}

	/**
	 * Set value of ApprovedByBoard
	 * @param context
	 * @param approvedbyboard
	 */
	public final void setApprovedByBoard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approvedbyboard)
	{
		getMendixObject().setValue(context, MemberNames.ApprovedByBoard.toString(), approvedbyboard);
	}

	/**
	 * @return value of AggrementLetterSentToApplicant
	 */
	public final java.lang.Integer getAggrementLetterSentToApplicant()
	{
		return getAggrementLetterSentToApplicant(getContext());
	}

	/**
	 * @param context
	 * @return value of AggrementLetterSentToApplicant
	 */
	public final java.lang.Integer getAggrementLetterSentToApplicant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AggrementLetterSentToApplicant.toString());
	}

	/**
	 * Set value of AggrementLetterSentToApplicant
	 * @param aggrementlettersenttoapplicant
	 */
	public final void setAggrementLetterSentToApplicant(java.lang.Integer aggrementlettersenttoapplicant)
	{
		setAggrementLetterSentToApplicant(getContext(), aggrementlettersenttoapplicant);
	}

	/**
	 * Set value of AggrementLetterSentToApplicant
	 * @param context
	 * @param aggrementlettersenttoapplicant
	 */
	public final void setAggrementLetterSentToApplicant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer aggrementlettersenttoapplicant)
	{
		getMendixObject().setValue(context, MemberNames.AggrementLetterSentToApplicant.toString(), aggrementlettersenttoapplicant);
	}

	/**
	 * @return value of ApplicantAccepted
	 */
	public final java.lang.Integer getApplicantAccepted()
	{
		return getApplicantAccepted(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicantAccepted
	 */
	public final java.lang.Integer getApplicantAccepted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApplicantAccepted.toString());
	}

	/**
	 * Set value of ApplicantAccepted
	 * @param applicantaccepted
	 */
	public final void setApplicantAccepted(java.lang.Integer applicantaccepted)
	{
		setApplicantAccepted(getContext(), applicantaccepted);
	}

	/**
	 * Set value of ApplicantAccepted
	 * @param context
	 * @param applicantaccepted
	 */
	public final void setApplicantAccepted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer applicantaccepted)
	{
		getMendixObject().setValue(context, MemberNames.ApplicantAccepted.toString(), applicantaccepted);
	}

	/**
	 * @return value of Forwarded_to_FA_Cases
	 */
	public final java.lang.Integer getForwarded_to_FA_Cases()
	{
		return getForwarded_to_FA_Cases(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_to_FA_Cases
	 */
	public final java.lang.Integer getForwarded_to_FA_Cases(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_to_FA_Cases.toString());
	}

	/**
	 * Set value of Forwarded_to_FA_Cases
	 * @param forwarded_to_fa_cases
	 */
	public final void setForwarded_to_FA_Cases(java.lang.Integer forwarded_to_fa_cases)
	{
		setForwarded_to_FA_Cases(getContext(), forwarded_to_fa_cases);
	}

	/**
	 * Set value of Forwarded_to_FA_Cases
	 * @param context
	 * @param forwarded_to_fa_cases
	 */
	public final void setForwarded_to_FA_Cases(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_to_fa_cases)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_to_FA_Cases.toString(), forwarded_to_fa_cases);
	}

	/**
	 * @return value of Forwarded_to_IO_Cases
	 */
	public final java.lang.Integer getForwarded_to_IO_Cases()
	{
		return getForwarded_to_IO_Cases(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_to_IO_Cases
	 */
	public final java.lang.Integer getForwarded_to_IO_Cases(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_to_IO_Cases.toString());
	}

	/**
	 * Set value of Forwarded_to_IO_Cases
	 * @param forwarded_to_io_cases
	 */
	public final void setForwarded_to_IO_Cases(java.lang.Integer forwarded_to_io_cases)
	{
		setForwarded_to_IO_Cases(getContext(), forwarded_to_io_cases);
	}

	/**
	 * Set value of Forwarded_to_IO_Cases
	 * @param context
	 * @param forwarded_to_io_cases
	 */
	public final void setForwarded_to_IO_Cases(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_to_io_cases)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_to_IO_Cases.toString(), forwarded_to_io_cases);
	}

	/**
	 * @return value of Forwarded_to_GMHQ_Cases
	 */
	public final java.lang.Integer getForwarded_to_GMHQ_Cases()
	{
		return getForwarded_to_GMHQ_Cases(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_to_GMHQ_Cases
	 */
	public final java.lang.Integer getForwarded_to_GMHQ_Cases(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_to_GMHQ_Cases.toString());
	}

	/**
	 * Set value of Forwarded_to_GMHQ_Cases
	 * @param forwarded_to_gmhq_cases
	 */
	public final void setForwarded_to_GMHQ_Cases(java.lang.Integer forwarded_to_gmhq_cases)
	{
		setForwarded_to_GMHQ_Cases(getContext(), forwarded_to_gmhq_cases);
	}

	/**
	 * Set value of Forwarded_to_GMHQ_Cases
	 * @param context
	 * @param forwarded_to_gmhq_cases
	 */
	public final void setForwarded_to_GMHQ_Cases(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_to_gmhq_cases)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_to_GMHQ_Cases.toString(), forwarded_to_gmhq_cases);
	}

	/**
	 * @return value of FundingInPorgress
	 */
	public final java.lang.Integer getFundingInPorgress()
	{
		return getFundingInPorgress(getContext());
	}

	/**
	 * @param context
	 * @return value of FundingInPorgress
	 */
	public final java.lang.Integer getFundingInPorgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FundingInPorgress.toString());
	}

	/**
	 * Set value of FundingInPorgress
	 * @param fundinginporgress
	 */
	public final void setFundingInPorgress(java.lang.Integer fundinginporgress)
	{
		setFundingInPorgress(getContext(), fundinginporgress);
	}

	/**
	 * Set value of FundingInPorgress
	 * @param context
	 * @param fundinginporgress
	 */
	public final void setFundingInPorgress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer fundinginporgress)
	{
		getMendixObject().setValue(context, MemberNames.FundingInPorgress.toString(), fundinginporgress);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ValueStr
	 */
	public final java.lang.String getValueStr()
	{
		return getValueStr(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueStr
	 */
	public final java.lang.String getValueStr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueStr.toString());
	}

	/**
	 * Set value of ValueStr
	 * @param valuestr
	 */
	public final void setValueStr(java.lang.String valuestr)
	{
		setValueStr(getContext(), valuestr);
	}

	/**
	 * Set value of ValueStr
	 * @param context
	 * @param valuestr
	 */
	public final void setValueStr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuestr)
	{
		getMendixObject().setValue(context, MemberNames.ValueStr.toString(), valuestr);
	}

	/**
	 * @return value of ValueCount
	 */
	public final java.lang.Integer getValueCount()
	{
		return getValueCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueCount
	 */
	public final java.lang.Integer getValueCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ValueCount.toString());
	}

	/**
	 * Set value of ValueCount
	 * @param valuecount
	 */
	public final void setValueCount(java.lang.Integer valuecount)
	{
		setValueCount(getContext(), valuecount);
	}

	/**
	 * Set value of ValueCount
	 * @param context
	 * @param valuecount
	 */
	public final void setValueCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer valuecount)
	{
		getMendixObject().setValue(context, MemberNames.ValueCount.toString(), valuecount);
	}

	/**
	 * @return value of ChartData_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getChartData_Root_ProcessHelper() throws com.mendix.core.CoreException
	{
		return getChartData_Root_ProcessHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartData_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getChartData_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Root_ProcessHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartData_Root_ProcessHelper.toString());
		if (identifier != null)
			result = ugs.proxies.Root_ProcessHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChartData_Root_ProcessHelper
	 * @param chartdata_root_processhelper
	 */
	public final void setChartData_Root_ProcessHelper(ugs.proxies.Root_ProcessHelper chartdata_root_processhelper)
	{
		setChartData_Root_ProcessHelper(getContext(), chartdata_root_processhelper);
	}

	/**
	 * Set value of ChartData_Root_ProcessHelper
	 * @param context
	 * @param chartdata_root_processhelper
	 */
	public final void setChartData_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Root_ProcessHelper chartdata_root_processhelper)
	{
		if (chartdata_root_processhelper == null)
			getMendixObject().setValue(context, MemberNames.ChartData_Root_ProcessHelper.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChartData_Root_ProcessHelper.toString(), chartdata_root_processhelper.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.ChartData that = (ugs.proxies.ChartData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.ChartData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
