// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class count
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.count";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Approved("Approved"),
		Rejected("Rejected"),
		UnderReview("UnderReview"),
		MyApplication("MyApplication"),
		Resolved("Resolved"),
		Returned("Returned"),
		Inprogress("Inprogress"),
		cases("cases"),
		Forwarded_IO("Forwarded_IO"),
		Forwarded_FA("Forwarded_FA"),
		Forwarded_GMHQ("Forwarded_GMHQ");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.count"));
	}

	protected count(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countMendixObject)
	{
		if (countMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.count", countMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.count");

		this.countMendixObject = countMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'count.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.count.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.count(context, mendixObject);
	}

	public static ugs.proxies.count load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.count.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.count> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.count> result = new java.util.ArrayList<ugs.proxies.count>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.count" + xpathConstraint))
			result.add(ugs.proxies.count.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.Integer approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected()
	{
		return getRejected(getContext());
	}

	/**
	 * @param context
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rejected.toString());
	}

	/**
	 * Set value of Rejected
	 * @param rejected
	 */
	public final void setRejected(java.lang.Integer rejected)
	{
		setRejected(getContext(), rejected);
	}

	/**
	 * Set value of Rejected
	 * @param context
	 * @param rejected
	 */
	public final void setRejected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rejected)
	{
		getMendixObject().setValue(context, MemberNames.Rejected.toString(), rejected);
	}

	/**
	 * @return value of UnderReview
	 */
	public final java.lang.Integer getUnderReview()
	{
		return getUnderReview(getContext());
	}

	/**
	 * @param context
	 * @return value of UnderReview
	 */
	public final java.lang.Integer getUnderReview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.UnderReview.toString());
	}

	/**
	 * Set value of UnderReview
	 * @param underreview
	 */
	public final void setUnderReview(java.lang.Integer underreview)
	{
		setUnderReview(getContext(), underreview);
	}

	/**
	 * Set value of UnderReview
	 * @param context
	 * @param underreview
	 */
	public final void setUnderReview(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer underreview)
	{
		getMendixObject().setValue(context, MemberNames.UnderReview.toString(), underreview);
	}

	/**
	 * @return value of MyApplication
	 */
	public final java.lang.Integer getMyApplication()
	{
		return getMyApplication(getContext());
	}

	/**
	 * @param context
	 * @return value of MyApplication
	 */
	public final java.lang.Integer getMyApplication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MyApplication.toString());
	}

	/**
	 * Set value of MyApplication
	 * @param myapplication
	 */
	public final void setMyApplication(java.lang.Integer myapplication)
	{
		setMyApplication(getContext(), myapplication);
	}

	/**
	 * Set value of MyApplication
	 * @param context
	 * @param myapplication
	 */
	public final void setMyApplication(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer myapplication)
	{
		getMendixObject().setValue(context, MemberNames.MyApplication.toString(), myapplication);
	}

	/**
	 * @return value of Resolved
	 */
	public final java.lang.Integer getResolved()
	{
		return getResolved(getContext());
	}

	/**
	 * @param context
	 * @return value of Resolved
	 */
	public final java.lang.Integer getResolved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Resolved.toString());
	}

	/**
	 * Set value of Resolved
	 * @param resolved
	 */
	public final void setResolved(java.lang.Integer resolved)
	{
		setResolved(getContext(), resolved);
	}

	/**
	 * Set value of Resolved
	 * @param context
	 * @param resolved
	 */
	public final void setResolved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer resolved)
	{
		getMendixObject().setValue(context, MemberNames.Resolved.toString(), resolved);
	}

	/**
	 * @return value of Returned
	 */
	public final java.lang.Integer getReturned()
	{
		return getReturned(getContext());
	}

	/**
	 * @param context
	 * @return value of Returned
	 */
	public final java.lang.Integer getReturned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Returned.toString());
	}

	/**
	 * Set value of Returned
	 * @param returned
	 */
	public final void setReturned(java.lang.Integer returned)
	{
		setReturned(getContext(), returned);
	}

	/**
	 * Set value of Returned
	 * @param context
	 * @param returned
	 */
	public final void setReturned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer returned)
	{
		getMendixObject().setValue(context, MemberNames.Returned.toString(), returned);
	}

	/**
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress()
	{
		return getInprogress(getContext());
	}

	/**
	 * @param context
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Inprogress.toString());
	}

	/**
	 * Set value of Inprogress
	 * @param inprogress
	 */
	public final void setInprogress(java.lang.Integer inprogress)
	{
		setInprogress(getContext(), inprogress);
	}

	/**
	 * Set value of Inprogress
	 * @param context
	 * @param inprogress
	 */
	public final void setInprogress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inprogress)
	{
		getMendixObject().setValue(context, MemberNames.Inprogress.toString(), inprogress);
	}

	/**
	 * @return value of cases
	 */
	public final java.lang.Integer getcases()
	{
		return getcases(getContext());
	}

	/**
	 * @param context
	 * @return value of cases
	 */
	public final java.lang.Integer getcases(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.cases.toString());
	}

	/**
	 * Set value of cases
	 * @param cases
	 */
	public final void setcases(java.lang.Integer cases)
	{
		setcases(getContext(), cases);
	}

	/**
	 * Set value of cases
	 * @param context
	 * @param cases
	 */
	public final void setcases(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cases)
	{
		getMendixObject().setValue(context, MemberNames.cases.toString(), cases);
	}

	/**
	 * @return value of Forwarded_IO
	 */
	public final java.lang.Integer getForwarded_IO()
	{
		return getForwarded_IO(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_IO
	 */
	public final java.lang.Integer getForwarded_IO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_IO.toString());
	}

	/**
	 * Set value of Forwarded_IO
	 * @param forwarded_io
	 */
	public final void setForwarded_IO(java.lang.Integer forwarded_io)
	{
		setForwarded_IO(getContext(), forwarded_io);
	}

	/**
	 * Set value of Forwarded_IO
	 * @param context
	 * @param forwarded_io
	 */
	public final void setForwarded_IO(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_io)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_IO.toString(), forwarded_io);
	}

	/**
	 * @return value of Forwarded_FA
	 */
	public final java.lang.Integer getForwarded_FA()
	{
		return getForwarded_FA(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_FA
	 */
	public final java.lang.Integer getForwarded_FA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_FA.toString());
	}

	/**
	 * Set value of Forwarded_FA
	 * @param forwarded_fa
	 */
	public final void setForwarded_FA(java.lang.Integer forwarded_fa)
	{
		setForwarded_FA(getContext(), forwarded_fa);
	}

	/**
	 * Set value of Forwarded_FA
	 * @param context
	 * @param forwarded_fa
	 */
	public final void setForwarded_FA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_fa)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_FA.toString(), forwarded_fa);
	}

	/**
	 * @return value of Forwarded_GMHQ
	 */
	public final java.lang.Integer getForwarded_GMHQ()
	{
		return getForwarded_GMHQ(getContext());
	}

	/**
	 * @param context
	 * @return value of Forwarded_GMHQ
	 */
	public final java.lang.Integer getForwarded_GMHQ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Forwarded_GMHQ.toString());
	}

	/**
	 * Set value of Forwarded_GMHQ
	 * @param forwarded_gmhq
	 */
	public final void setForwarded_GMHQ(java.lang.Integer forwarded_gmhq)
	{
		setForwarded_GMHQ(getContext(), forwarded_gmhq);
	}

	/**
	 * Set value of Forwarded_GMHQ
	 * @param context
	 * @param forwarded_gmhq
	 */
	public final void setForwarded_GMHQ(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer forwarded_gmhq)
	{
		getMendixObject().setValue(context, MemberNames.Forwarded_GMHQ.toString(), forwarded_gmhq);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.count that = (ugs.proxies.count) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.count";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
