// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public enum Enum_CaseStatus
{
	Inprogress(new java.lang.String[][] { new java.lang.String[] { "en_US", "Inprogress" } }),
	Resolved(new java.lang.String[][] { new java.lang.String[] { "en_US", "Resolved" } }),
	Pending(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pending" } }),
	_return(new java.lang.String[][] { new java.lang.String[] { "en_US", "return" } }),
	Forwarded_to_FA(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded_to_FA" } }),
	Forwarded_to_IO(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded_to_IO" } }),
	Forwarded_to_GMHQ(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded_to_GMHQ" } }),
	Draft(new java.lang.String[][] { new java.lang.String[] { "en_US", "Draft" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_CaseStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
