// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public enum Enum_CaseTypesGM
{
	Withdrawal_of_Grant_Terminate_Grantee(new java.lang.String[][] { new java.lang.String[] { "en_US", "Withdrawal of Grant/Terminate Grantee" } }),
	Graduate_Tracking(new java.lang.String[][] { new java.lang.String[] { "en_US", "Graduate Tracking" } }),
	Disciplinary_action(new java.lang.String[][] { new java.lang.String[] { "en_US", "Disciplinary action" } }),
	Adhoc_Request(new java.lang.String[][] { new java.lang.String[] { "en_US", "Adhoc Request" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_CaseTypesGM(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
