// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public enum Enum_WorkflowStages
{
	Stage_1(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 1" } }),
	Stage_2(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 2" } }),
	Stage_3(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 3" } }),
	Stage_4(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 4" } }),
	Stage_5(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 5" } }),
	Stage_6(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 6" } }),
	Stage_7(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 7" } }),
	Stage_8(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 8" } }),
	Stage_9(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stage 9" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_WorkflowStages(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
