// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class ExcelExport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.ExcelExport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ExcelExport_GrantSystem("UGS.ExcelExport_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExcelExport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.ExcelExport"));
	}

	protected ExcelExport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject excelExportMendixObject)
	{
		super(context, excelExportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.ExcelExport", excelExportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.ExcelExport");
	}

	/**
	 * @deprecated Use 'ExcelExport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.ExcelExport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.ExcelExport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.ExcelExport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.ExcelExport(context, mendixObject);
	}

	public static ugs.proxies.ExcelExport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.ExcelExport.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.ExcelExport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.ExcelExport> result = new java.util.ArrayList<ugs.proxies.ExcelExport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.ExcelExport" + xpathConstraint))
			result.add(ugs.proxies.ExcelExport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ExcelExport_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getExcelExport_GrantSystem() throws com.mendix.core.CoreException
	{
		return getExcelExport_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcelExport_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getExcelExport_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExcelExport_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExcelExport_GrantSystem
	 * @param excelexport_grantsystem
	 */
	public final void setExcelExport_GrantSystem(ugs.proxies.GrantSystem excelexport_grantsystem)
	{
		setExcelExport_GrantSystem(getContext(), excelexport_grantsystem);
	}

	/**
	 * Set value of ExcelExport_GrantSystem
	 * @param context
	 * @param excelexport_grantsystem
	 */
	public final void setExcelExport_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem excelexport_grantsystem)
	{
		if (excelexport_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.ExcelExport_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExcelExport_GrantSystem.toString(), excelexport_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.ExcelExport that = (ugs.proxies.ExcelExport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.ExcelExport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
