// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class FAQ extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.FAQ";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Questions("Questions"),
		Answers("Answers"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FAQ_GrantSystem("UGS.FAQ_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FAQ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.FAQ"));
	}

	protected FAQ(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fAQMendixObject)
	{
		super(context, fAQMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.FAQ", fAQMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.FAQ");
	}

	/**
	 * @deprecated Use 'FAQ.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.FAQ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.FAQ.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.FAQ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.FAQ(context, mendixObject);
	}

	public static ugs.proxies.FAQ load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.FAQ.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.FAQ> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.FAQ> result = new java.util.ArrayList<ugs.proxies.FAQ>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.FAQ" + xpathConstraint))
			result.add(ugs.proxies.FAQ.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Questions
	 */
	public final java.lang.String getQuestions()
	{
		return getQuestions(getContext());
	}

	/**
	 * @param context
	 * @return value of Questions
	 */
	public final java.lang.String getQuestions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Questions.toString());
	}

	/**
	 * Set value of Questions
	 * @param questions
	 */
	public final void setQuestions(java.lang.String questions)
	{
		setQuestions(getContext(), questions);
	}

	/**
	 * Set value of Questions
	 * @param context
	 * @param questions
	 */
	public final void setQuestions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String questions)
	{
		getMendixObject().setValue(context, MemberNames.Questions.toString(), questions);
	}

	/**
	 * @return value of Answers
	 */
	public final java.lang.String getAnswers()
	{
		return getAnswers(getContext());
	}

	/**
	 * @param context
	 * @return value of Answers
	 */
	public final java.lang.String getAnswers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Answers.toString());
	}

	/**
	 * Set value of Answers
	 * @param answers
	 */
	public final void setAnswers(java.lang.String answers)
	{
		setAnswers(getContext(), answers);
	}

	/**
	 * Set value of Answers
	 * @param context
	 * @param answers
	 */
	public final void setAnswers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String answers)
	{
		getMendixObject().setValue(context, MemberNames.Answers.toString(), answers);
	}

	/**
	 * @return value of FAQ_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getFAQ_GrantSystem() throws com.mendix.core.CoreException
	{
		return getFAQ_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of FAQ_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getFAQ_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FAQ_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FAQ_GrantSystem
	 * @param faq_grantsystem
	 */
	public final void setFAQ_GrantSystem(ugs.proxies.GrantSystem faq_grantsystem)
	{
		setFAQ_GrantSystem(getContext(), faq_grantsystem);
	}

	/**
	 * Set value of FAQ_GrantSystem
	 * @param context
	 * @param faq_grantsystem
	 */
	public final void setFAQ_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem faq_grantsystem)
	{
		if (faq_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.FAQ_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FAQ_GrantSystem.toString(), faq_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.FAQ that = (ugs.proxies.FAQ) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.FAQ";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
