// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class FileDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.FileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FileDocument_CaseMangement("UGS.FileDocument_CaseMangement");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.FileDocument"));
	}

	protected FileDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileDocumentMendixObject)
	{
		super(context, fileDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.FileDocument", fileDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.FileDocument");
	}

	/**
	 * @deprecated Use 'FileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.FileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.FileDocument(context, mendixObject);
	}

	public static ugs.proxies.FileDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.FileDocument.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.FileDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.FileDocument> result = new java.util.ArrayList<ugs.proxies.FileDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.FileDocument" + xpathConstraint))
			result.add(ugs.proxies.FileDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FileDocument_CaseMangement
	 */
	public final ugs.proxies.CaseMangement getFileDocument_CaseMangement() throws com.mendix.core.CoreException
	{
		return getFileDocument_CaseMangement(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocument_CaseMangement
	 */
	public final ugs.proxies.CaseMangement getFileDocument_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.CaseMangement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileDocument_CaseMangement.toString());
		if (identifier != null)
			result = ugs.proxies.CaseMangement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FileDocument_CaseMangement
	 * @param filedocument_casemangement
	 */
	public final void setFileDocument_CaseMangement(ugs.proxies.CaseMangement filedocument_casemangement)
	{
		setFileDocument_CaseMangement(getContext(), filedocument_casemangement);
	}

	/**
	 * Set value of FileDocument_CaseMangement
	 * @param context
	 * @param filedocument_casemangement
	 */
	public final void setFileDocument_CaseMangement(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.CaseMangement filedocument_casemangement)
	{
		if (filedocument_casemangement == null)
			getMendixObject().setValue(context, MemberNames.FileDocument_CaseMangement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FileDocument_CaseMangement.toString(), filedocument_casemangement.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.FileDocument that = (ugs.proxies.FileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.FileDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
