// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Funds
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fundsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Funds";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FundName("FundName"),
		GrantID("GrantID"),
		GrantID_Permanent("GrantID_Permanent"),
		GrantName("GrantName"),
		TotalFundAmount("TotalFundAmount"),
		AvailableAmount("AvailableAmount"),
		FundingStatus("FundingStatus"),
		Frequencies("Frequencies"),
		Funds_Root_ProcessHelper("UGS.Funds_Root_ProcessHelper");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Funds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Funds"));
	}

	protected Funds(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fundsMendixObject)
	{
		if (fundsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Funds", fundsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Funds");

		this.fundsMendixObject = fundsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Funds.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Funds initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Funds.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Funds initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Funds(context, mendixObject);
	}

	public static ugs.proxies.Funds load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Funds.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FundName
	 */
	public final java.lang.String getFundName()
	{
		return getFundName(getContext());
	}

	/**
	 * @param context
	 * @return value of FundName
	 */
	public final java.lang.String getFundName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FundName.toString());
	}

	/**
	 * Set value of FundName
	 * @param fundname
	 */
	public final void setFundName(java.lang.String fundname)
	{
		setFundName(getContext(), fundname);
	}

	/**
	 * Set value of FundName
	 * @param context
	 * @param fundname
	 */
	public final void setFundName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fundname)
	{
		getMendixObject().setValue(context, MemberNames.FundName.toString(), fundname);
	}

	/**
	 * @return value of GrantID
	 */
	public final java.lang.Long getGrantID()
	{
		return getGrantID(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantID
	 */
	public final java.lang.Long getGrantID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.GrantID.toString());
	}

	/**
	 * Set value of GrantID
	 * @param grantid
	 */
	public final void setGrantID(java.lang.Long grantid)
	{
		setGrantID(getContext(), grantid);
	}

	/**
	 * Set value of GrantID
	 * @param context
	 * @param grantid
	 */
	public final void setGrantID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long grantid)
	{
		getMendixObject().setValue(context, MemberNames.GrantID.toString(), grantid);
	}

	/**
	 * @return value of GrantID_Permanent
	 */
	public final java.lang.Long getGrantID_Permanent()
	{
		return getGrantID_Permanent(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantID_Permanent
	 */
	public final java.lang.Long getGrantID_Permanent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.GrantID_Permanent.toString());
	}

	/**
	 * Set value of GrantID_Permanent
	 * @param grantid_permanent
	 */
	public final void setGrantID_Permanent(java.lang.Long grantid_permanent)
	{
		setGrantID_Permanent(getContext(), grantid_permanent);
	}

	/**
	 * Set value of GrantID_Permanent
	 * @param context
	 * @param grantid_permanent
	 */
	public final void setGrantID_Permanent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long grantid_permanent)
	{
		getMendixObject().setValue(context, MemberNames.GrantID_Permanent.toString(), grantid_permanent);
	}

	/**
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName()
	{
		return getGrantName(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GrantName.toString());
	}

	/**
	 * Set value of GrantName
	 * @param grantname
	 */
	public final void setGrantName(java.lang.String grantname)
	{
		setGrantName(getContext(), grantname);
	}

	/**
	 * Set value of GrantName
	 * @param context
	 * @param grantname
	 */
	public final void setGrantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grantname)
	{
		getMendixObject().setValue(context, MemberNames.GrantName.toString(), grantname);
	}

	/**
	 * @return value of TotalFundAmount
	 */
	public final java.math.BigDecimal getTotalFundAmount()
	{
		return getTotalFundAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalFundAmount
	 */
	public final java.math.BigDecimal getTotalFundAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalFundAmount.toString());
	}

	/**
	 * Set value of TotalFundAmount
	 * @param totalfundamount
	 */
	public final void setTotalFundAmount(java.math.BigDecimal totalfundamount)
	{
		setTotalFundAmount(getContext(), totalfundamount);
	}

	/**
	 * Set value of TotalFundAmount
	 * @param context
	 * @param totalfundamount
	 */
	public final void setTotalFundAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalfundamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalFundAmount.toString(), totalfundamount);
	}

	/**
	 * @return value of AvailableAmount
	 */
	public final java.math.BigDecimal getAvailableAmount()
	{
		return getAvailableAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of AvailableAmount
	 */
	public final java.math.BigDecimal getAvailableAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AvailableAmount.toString());
	}

	/**
	 * Set value of AvailableAmount
	 * @param availableamount
	 */
	public final void setAvailableAmount(java.math.BigDecimal availableamount)
	{
		setAvailableAmount(getContext(), availableamount);
	}

	/**
	 * Set value of AvailableAmount
	 * @param context
	 * @param availableamount
	 */
	public final void setAvailableAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal availableamount)
	{
		getMendixObject().setValue(context, MemberNames.AvailableAmount.toString(), availableamount);
	}

	/**
	 * @return value of FundingStatus
	 */
	public final java.lang.String getFundingStatus()
	{
		return getFundingStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of FundingStatus
	 */
	public final java.lang.String getFundingStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FundingStatus.toString());
	}

	/**
	 * Set value of FundingStatus
	 * @param fundingstatus
	 */
	public final void setFundingStatus(java.lang.String fundingstatus)
	{
		setFundingStatus(getContext(), fundingstatus);
	}

	/**
	 * Set value of FundingStatus
	 * @param context
	 * @param fundingstatus
	 */
	public final void setFundingStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fundingstatus)
	{
		getMendixObject().setValue(context, MemberNames.FundingStatus.toString(), fundingstatus);
	}

	/**
	 * @return value of Frequencies
	 */
	public final java.lang.String getFrequencies()
	{
		return getFrequencies(getContext());
	}

	/**
	 * @param context
	 * @return value of Frequencies
	 */
	public final java.lang.String getFrequencies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Frequencies.toString());
	}

	/**
	 * Set value of Frequencies
	 * @param frequencies
	 */
	public final void setFrequencies(java.lang.String frequencies)
	{
		setFrequencies(getContext(), frequencies);
	}

	/**
	 * Set value of Frequencies
	 * @param context
	 * @param frequencies
	 */
	public final void setFrequencies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String frequencies)
	{
		getMendixObject().setValue(context, MemberNames.Frequencies.toString(), frequencies);
	}

	/**
	 * @return value of Funds_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getFunds_Root_ProcessHelper() throws com.mendix.core.CoreException
	{
		return getFunds_Root_ProcessHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Funds_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getFunds_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Root_ProcessHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Funds_Root_ProcessHelper.toString());
		if (identifier != null)
			result = ugs.proxies.Root_ProcessHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Funds_Root_ProcessHelper
	 * @param funds_root_processhelper
	 */
	public final void setFunds_Root_ProcessHelper(ugs.proxies.Root_ProcessHelper funds_root_processhelper)
	{
		setFunds_Root_ProcessHelper(getContext(), funds_root_processhelper);
	}

	/**
	 * Set value of Funds_Root_ProcessHelper
	 * @param context
	 * @param funds_root_processhelper
	 */
	public final void setFunds_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Root_ProcessHelper funds_root_processhelper)
	{
		if (funds_root_processhelper == null)
			getMendixObject().setValue(context, MemberNames.Funds_Root_ProcessHelper.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Funds_Root_ProcessHelper.toString(), funds_root_processhelper.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fundsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Funds that = (ugs.proxies.Funds) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Funds";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
