// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Funding_ChartData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject funding_ChartDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Funding_ChartData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Values("Values"),
		Funding_ChartData_Root_ProcessHelper("UGS.Funding_ChartData_Root_ProcessHelper");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Funding_ChartData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Funding_ChartData"));
	}

	protected Funding_ChartData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject funding_ChartDataMendixObject)
	{
		if (funding_ChartDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Funding_ChartData", funding_ChartDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Funding_ChartData");

		this.funding_ChartDataMendixObject = funding_ChartDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Funding_ChartData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Funding_ChartData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Funding_ChartData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Funding_ChartData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Funding_ChartData(context, mendixObject);
	}

	public static ugs.proxies.Funding_ChartData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Funding_ChartData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Values
	 */
	public final java.lang.String getValues()
	{
		return getValues(getContext());
	}

	/**
	 * @param context
	 * @return value of Values
	 */
	public final java.lang.String getValues(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Values.toString());
	}

	/**
	 * Set value of Values
	 * @param values
	 */
	public final void setValues(java.lang.String values)
	{
		setValues(getContext(), values);
	}

	/**
	 * Set value of Values
	 * @param context
	 * @param values
	 */
	public final void setValues(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String values)
	{
		getMendixObject().setValue(context, MemberNames.Values.toString(), values);
	}

	/**
	 * @return value of Funding_ChartData_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getFunding_ChartData_Root_ProcessHelper() throws com.mendix.core.CoreException
	{
		return getFunding_ChartData_Root_ProcessHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Funding_ChartData_Root_ProcessHelper
	 */
	public final ugs.proxies.Root_ProcessHelper getFunding_ChartData_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Root_ProcessHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Funding_ChartData_Root_ProcessHelper.toString());
		if (identifier != null)
			result = ugs.proxies.Root_ProcessHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Funding_ChartData_Root_ProcessHelper
	 * @param funding_chartdata_root_processhelper
	 */
	public final void setFunding_ChartData_Root_ProcessHelper(ugs.proxies.Root_ProcessHelper funding_chartdata_root_processhelper)
	{
		setFunding_ChartData_Root_ProcessHelper(getContext(), funding_chartdata_root_processhelper);
	}

	/**
	 * Set value of Funding_ChartData_Root_ProcessHelper
	 * @param context
	 * @param funding_chartdata_root_processhelper
	 */
	public final void setFunding_ChartData_Root_ProcessHelper(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Root_ProcessHelper funding_chartdata_root_processhelper)
	{
		if (funding_chartdata_root_processhelper == null)
			getMendixObject().setValue(context, MemberNames.Funding_ChartData_Root_ProcessHelper.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Funding_ChartData_Root_ProcessHelper.toString(), funding_chartdata_root_processhelper.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return funding_ChartDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Funding_ChartData that = (ugs.proxies.Funding_ChartData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Funding_ChartData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
