// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Fundings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fundingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Fundings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FundName("FundName"),
		FundAmount("FundAmount"),
		Description("Description"),
		Fundings_Status("Fundings_Status"),
		Date("Date"),
		AvailableAmounts("AvailableAmounts"),
		RequestedAmount("RequestedAmount"),
		Fundings_GrantSystem("UGS.Fundings_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Fundings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Fundings"));
	}

	protected Fundings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fundingsMendixObject)
	{
		if (fundingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Fundings", fundingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Fundings");

		this.fundingsMendixObject = fundingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Fundings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Fundings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Fundings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Fundings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Fundings(context, mendixObject);
	}

	public static ugs.proxies.Fundings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Fundings.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Fundings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Fundings> result = new java.util.ArrayList<ugs.proxies.Fundings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Fundings" + xpathConstraint))
			result.add(ugs.proxies.Fundings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FundName
	 */
	public final java.lang.String getFundName()
	{
		return getFundName(getContext());
	}

	/**
	 * @param context
	 * @return value of FundName
	 */
	public final java.lang.String getFundName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FundName.toString());
	}

	/**
	 * Set value of FundName
	 * @param fundname
	 */
	public final void setFundName(java.lang.String fundname)
	{
		setFundName(getContext(), fundname);
	}

	/**
	 * Set value of FundName
	 * @param context
	 * @param fundname
	 */
	public final void setFundName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fundname)
	{
		getMendixObject().setValue(context, MemberNames.FundName.toString(), fundname);
	}

	/**
	 * @return value of FundAmount
	 */
	public final java.math.BigDecimal getFundAmount()
	{
		return getFundAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of FundAmount
	 */
	public final java.math.BigDecimal getFundAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FundAmount.toString());
	}

	/**
	 * Set value of FundAmount
	 * @param fundamount
	 */
	public final void setFundAmount(java.math.BigDecimal fundamount)
	{
		setFundAmount(getContext(), fundamount);
	}

	/**
	 * Set value of FundAmount
	 * @param context
	 * @param fundamount
	 */
	public final void setFundAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal fundamount)
	{
		getMendixObject().setValue(context, MemberNames.FundAmount.toString(), fundamount);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Fundings_Status
	 * @param fundings_status
	 */
	public final ugs.proxies.Enum_Fund getFundings_Status()
	{
		return getFundings_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Fundings_Status
	 */
	public final ugs.proxies.Enum_Fund getFundings_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Fundings_Status.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_Fund.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Fundings_Status
	 * @param fundings_status
	 */
	public final void setFundings_Status(ugs.proxies.Enum_Fund fundings_status)
	{
		setFundings_Status(getContext(), fundings_status);
	}

	/**
	 * Set value of Fundings_Status
	 * @param context
	 * @param fundings_status
	 */
	public final void setFundings_Status(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_Fund fundings_status)
	{
		if (fundings_status != null)
			getMendixObject().setValue(context, MemberNames.Fundings_Status.toString(), fundings_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Fundings_Status.toString(), null);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of AvailableAmounts
	 */
	public final java.math.BigDecimal getAvailableAmounts()
	{
		return getAvailableAmounts(getContext());
	}

	/**
	 * @param context
	 * @return value of AvailableAmounts
	 */
	public final java.math.BigDecimal getAvailableAmounts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AvailableAmounts.toString());
	}

	/**
	 * Set value of AvailableAmounts
	 * @param availableamounts
	 */
	public final void setAvailableAmounts(java.math.BigDecimal availableamounts)
	{
		setAvailableAmounts(getContext(), availableamounts);
	}

	/**
	 * Set value of AvailableAmounts
	 * @param context
	 * @param availableamounts
	 */
	public final void setAvailableAmounts(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal availableamounts)
	{
		getMendixObject().setValue(context, MemberNames.AvailableAmounts.toString(), availableamounts);
	}

	/**
	 * @return value of RequestedAmount
	 */
	public final java.math.BigDecimal getRequestedAmount()
	{
		return getRequestedAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestedAmount
	 */
	public final java.math.BigDecimal getRequestedAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RequestedAmount.toString());
	}

	/**
	 * Set value of RequestedAmount
	 * @param requestedamount
	 */
	public final void setRequestedAmount(java.math.BigDecimal requestedamount)
	{
		setRequestedAmount(getContext(), requestedamount);
	}

	/**
	 * Set value of RequestedAmount
	 * @param context
	 * @param requestedamount
	 */
	public final void setRequestedAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal requestedamount)
	{
		getMendixObject().setValue(context, MemberNames.RequestedAmount.toString(), requestedamount);
	}

	/**
	 * @return value of Fundings_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getFundings_GrantSystem() throws com.mendix.core.CoreException
	{
		return getFundings_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Fundings_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getFundings_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fundings_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Fundings_GrantSystem
	 * @param fundings_grantsystem
	 */
	public final void setFundings_GrantSystem(ugs.proxies.GrantSystem fundings_grantsystem)
	{
		setFundings_GrantSystem(getContext(), fundings_grantsystem);
	}

	/**
	 * Set value of Fundings_GrantSystem
	 * @param context
	 * @param fundings_grantsystem
	 */
	public final void setFundings_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem fundings_grantsystem)
	{
		if (fundings_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Fundings_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Fundings_GrantSystem.toString(), fundings_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fundingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Fundings that = (ugs.proxies.Fundings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Fundings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
