// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class GrantSystem extends system.proxies.WorkflowContext
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.GrantSystem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Grant_Name("Grant_Name"),
		Grant_ID("Grant_ID"),
		Award_Value_Enum("Award_Value_Enum"),
		Limit1("Limit1"),
		Limit2("Limit2"),
		No_Of_Awards("No_Of_Awards"),
		Open_Date("Open_Date"),
		Open_Time("Open_Time"),
		Close_Date("Close_Date"),
		Close_Time("Close_Time"),
		grace_period("grace_period"),
		Summary("Summary"),
		Full_discription("Full_discription"),
		Application_limit("Application_limit"),
		Eligibilty("Eligibilty"),
		Flowchart_String("Flowchart_String"),
		DaysLeft("DaysLeft"),
		CurrentOrderNumber("CurrentOrderNumber"),
		editable("editable"),
		Notification_Content("Notification_Content"),
		Email("Email"),
		CurrentFormNumber("CurrentFormNumber"),
		Main("Main"),
		Status("Status"),
		Oneclick_Content("Oneclick_Content"),
		ToAddress("ToAddress"),
		Subject("Subject"),
		PermanentID("PermanentID"),
		ReviewType("ReviewType"),
		OverAllRating("OverAllRating"),
		ReviewComments("ReviewComments"),
		TotalScore("TotalScore"),
		OverAllRating_Decimal("OverAllRating_Decimal"),
		oneE("oneE"),
		UseTokens("UseTokens"),
		TwoE("TwoE"),
		ThreeE("ThreeE"),
		FourE("FourE"),
		FiveE("FiveE"),
		FundingAmount("FundingAmount"),
		AwardingAmount("AwardingAmount"),
		RequestingAmount("RequestingAmount"),
		Internal_Status("Internal_Status"),
		TotalRquestedAmount("TotalRquestedAmount"),
		RequestedDate("RequestedDate"),
		NoOfRequest("NoOfRequest"),
		AvailableBlc("AvailableBlc"),
		TestScore("TestScore"),
		WorkflowEnd("WorkflowEnd"),
		Frequency("Frequency"),
		Q1_Amount("Q1_Amount"),
		Q2Amount("Q2Amount"),
		Q3_Amount("Q3_Amount"),
		Q4_Amount("Q4_Amount"),
		Q1_Date("Q1_Date"),
		Q2_Date("Q2_Date"),
		Q3_Date("Q3_Date"),
		Q4_Date("Q4_Date"),
		FrequencyYear("FrequencyYear"),
		Signature_GrantSystem_Clone("UGS.Signature_GrantSystem_Clone"),
		GrantSystem_Aggrement_("UGS.GrantSystem_Aggrement_"),
		GrantSystem_Printout("UGS.GrantSystem_Printout"),
		Signature_GrantSystem_main("UGS.Signature_GrantSystem_main"),
		Fundings_GrantSystem("UGS.Fundings_GrantSystem"),
		History_GrantSystem("UGS.History_GrantSystem"),
		Test_GrantSystem("UGS.Test_GrantSystem"),
		Interview_GrantSystem("UGS.Interview_GrantSystem"),
		GrantSystem_Organization("UGS.GrantSystem_Organization"),
		ReviewForm_GrantSystem_CurrentReviewForm("UGS.ReviewForm_GrantSystem_CurrentReviewForm"),
		Voucher_GrantSystem("UGS.Voucher_GrantSystem"),
		GrantSystem_WorkflowUserTask("UGS.GrantSystem_WorkflowUserTask"),
		GrantSystem_AllWorkflowUserTask("UGS.GrantSystem_AllWorkflowUserTask"),
		GrantSystem_EmailTemplate("UGS.GrantSystem_EmailTemplate"),
		GrantSystem_AllAccounts("UGS.GrantSystem_AllAccounts"),
		GrantSystem_CurrentHoldingAccount("UGS.GrantSystem_CurrentHoldingAccount"),
		GrantSystem_ApplicantAccount("UGS.GrantSystem_ApplicantAccount"),
		GrantSystem_WorkflowRolesDummy("UGS.GrantSystem_WorkflowRolesDummy"),
		GrantSystem_TemplateDummy("UGS.GrantSystem_TemplateDummy"),
		ApplicationForm_GrantSystem("DynamicForm.ApplicationForm_GrantSystem"),
		WorkflowInstance_WorkflowContext("System.WorkflowInstance_WorkflowContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GrantSystem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.GrantSystem"));
	}

	protected GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject grantSystemMendixObject)
	{
		super(context, grantSystemMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.GrantSystem", grantSystemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.GrantSystem");
	}

	/**
	 * @deprecated Use 'GrantSystem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.GrantSystem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.GrantSystem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.GrantSystem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.GrantSystem(context, mendixObject);
	}

	public static ugs.proxies.GrantSystem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.GrantSystem.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.GrantSystem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.GrantSystem> result = new java.util.ArrayList<ugs.proxies.GrantSystem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.GrantSystem" + xpathConstraint))
			result.add(ugs.proxies.GrantSystem.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Grant_Name
	 */
	public final java.lang.String getGrant_Name()
	{
		return getGrant_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Grant_Name
	 */
	public final java.lang.String getGrant_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Grant_Name.toString());
	}

	/**
	 * Set value of Grant_Name
	 * @param grant_name
	 */
	public final void setGrant_Name(java.lang.String grant_name)
	{
		setGrant_Name(getContext(), grant_name);
	}

	/**
	 * Set value of Grant_Name
	 * @param context
	 * @param grant_name
	 */
	public final void setGrant_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grant_name)
	{
		getMendixObject().setValue(context, MemberNames.Grant_Name.toString(), grant_name);
	}

	/**
	 * @return value of Grant_ID
	 */
	public final java.lang.Long getGrant_ID()
	{
		return getGrant_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Grant_ID
	 */
	public final java.lang.Long getGrant_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Grant_ID.toString());
	}

	/**
	 * Set value of Grant_ID
	 * @param grant_id
	 */
	public final void setGrant_ID(java.lang.Long grant_id)
	{
		setGrant_ID(getContext(), grant_id);
	}

	/**
	 * Set value of Grant_ID
	 * @param context
	 * @param grant_id
	 */
	public final void setGrant_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long grant_id)
	{
		getMendixObject().setValue(context, MemberNames.Grant_ID.toString(), grant_id);
	}

	/**
	 * Set value of Award_Value_Enum
	 * @param award_value_enum
	 */
	public final ugs.proxies.Enum_AwardValueRange getAward_Value_Enum()
	{
		return getAward_Value_Enum(getContext());
	}

	/**
	 * @param context
	 * @return value of Award_Value_Enum
	 */
	public final ugs.proxies.Enum_AwardValueRange getAward_Value_Enum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Award_Value_Enum.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_AwardValueRange.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Award_Value_Enum
	 * @param award_value_enum
	 */
	public final void setAward_Value_Enum(ugs.proxies.Enum_AwardValueRange award_value_enum)
	{
		setAward_Value_Enum(getContext(), award_value_enum);
	}

	/**
	 * Set value of Award_Value_Enum
	 * @param context
	 * @param award_value_enum
	 */
	public final void setAward_Value_Enum(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_AwardValueRange award_value_enum)
	{
		if (award_value_enum != null)
			getMendixObject().setValue(context, MemberNames.Award_Value_Enum.toString(), award_value_enum.toString());
		else
			getMendixObject().setValue(context, MemberNames.Award_Value_Enum.toString(), null);
	}

	/**
	 * @return value of Limit1
	 */
	public final java.lang.Integer getLimit1()
	{
		return getLimit1(getContext());
	}

	/**
	 * @param context
	 * @return value of Limit1
	 */
	public final java.lang.Integer getLimit1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Limit1.toString());
	}

	/**
	 * Set value of Limit1
	 * @param limit1
	 */
	public final void setLimit1(java.lang.Integer limit1)
	{
		setLimit1(getContext(), limit1);
	}

	/**
	 * Set value of Limit1
	 * @param context
	 * @param limit1
	 */
	public final void setLimit1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer limit1)
	{
		getMendixObject().setValue(context, MemberNames.Limit1.toString(), limit1);
	}

	/**
	 * @return value of Limit2
	 */
	public final java.lang.Integer getLimit2()
	{
		return getLimit2(getContext());
	}

	/**
	 * @param context
	 * @return value of Limit2
	 */
	public final java.lang.Integer getLimit2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Limit2.toString());
	}

	/**
	 * Set value of Limit2
	 * @param limit2
	 */
	public final void setLimit2(java.lang.Integer limit2)
	{
		setLimit2(getContext(), limit2);
	}

	/**
	 * Set value of Limit2
	 * @param context
	 * @param limit2
	 */
	public final void setLimit2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer limit2)
	{
		getMendixObject().setValue(context, MemberNames.Limit2.toString(), limit2);
	}

	/**
	 * @return value of No_Of_Awards
	 */
	public final java.lang.Integer getNo_Of_Awards()
	{
		return getNo_Of_Awards(getContext());
	}

	/**
	 * @param context
	 * @return value of No_Of_Awards
	 */
	public final java.lang.Integer getNo_Of_Awards(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_Of_Awards.toString());
	}

	/**
	 * Set value of No_Of_Awards
	 * @param no_of_awards
	 */
	public final void setNo_Of_Awards(java.lang.Integer no_of_awards)
	{
		setNo_Of_Awards(getContext(), no_of_awards);
	}

	/**
	 * Set value of No_Of_Awards
	 * @param context
	 * @param no_of_awards
	 */
	public final void setNo_Of_Awards(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_awards)
	{
		getMendixObject().setValue(context, MemberNames.No_Of_Awards.toString(), no_of_awards);
	}

	/**
	 * @return value of Open_Date
	 */
	public final java.util.Date getOpen_Date()
	{
		return getOpen_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Open_Date
	 */
	public final java.util.Date getOpen_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Open_Date.toString());
	}

	/**
	 * Set value of Open_Date
	 * @param open_date
	 */
	public final void setOpen_Date(java.util.Date open_date)
	{
		setOpen_Date(getContext(), open_date);
	}

	/**
	 * Set value of Open_Date
	 * @param context
	 * @param open_date
	 */
	public final void setOpen_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date open_date)
	{
		getMendixObject().setValue(context, MemberNames.Open_Date.toString(), open_date);
	}

	/**
	 * @return value of Open_Time
	 */
	public final java.util.Date getOpen_Time()
	{
		return getOpen_Time(getContext());
	}

	/**
	 * @param context
	 * @return value of Open_Time
	 */
	public final java.util.Date getOpen_Time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Open_Time.toString());
	}

	/**
	 * Set value of Open_Time
	 * @param open_time
	 */
	public final void setOpen_Time(java.util.Date open_time)
	{
		setOpen_Time(getContext(), open_time);
	}

	/**
	 * Set value of Open_Time
	 * @param context
	 * @param open_time
	 */
	public final void setOpen_Time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date open_time)
	{
		getMendixObject().setValue(context, MemberNames.Open_Time.toString(), open_time);
	}

	/**
	 * @return value of Close_Date
	 */
	public final java.util.Date getClose_Date()
	{
		return getClose_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Close_Date
	 */
	public final java.util.Date getClose_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Close_Date.toString());
	}

	/**
	 * Set value of Close_Date
	 * @param close_date
	 */
	public final void setClose_Date(java.util.Date close_date)
	{
		setClose_Date(getContext(), close_date);
	}

	/**
	 * Set value of Close_Date
	 * @param context
	 * @param close_date
	 */
	public final void setClose_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date close_date)
	{
		getMendixObject().setValue(context, MemberNames.Close_Date.toString(), close_date);
	}

	/**
	 * @return value of Close_Time
	 */
	public final java.util.Date getClose_Time()
	{
		return getClose_Time(getContext());
	}

	/**
	 * @param context
	 * @return value of Close_Time
	 */
	public final java.util.Date getClose_Time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Close_Time.toString());
	}

	/**
	 * Set value of Close_Time
	 * @param close_time
	 */
	public final void setClose_Time(java.util.Date close_time)
	{
		setClose_Time(getContext(), close_time);
	}

	/**
	 * Set value of Close_Time
	 * @param context
	 * @param close_time
	 */
	public final void setClose_Time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date close_time)
	{
		getMendixObject().setValue(context, MemberNames.Close_Time.toString(), close_time);
	}

	/**
	 * @return value of grace_period
	 */
	public final java.util.Date getgrace_period()
	{
		return getgrace_period(getContext());
	}

	/**
	 * @param context
	 * @return value of grace_period
	 */
	public final java.util.Date getgrace_period(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.grace_period.toString());
	}

	/**
	 * Set value of grace_period
	 * @param grace_period
	 */
	public final void setgrace_period(java.util.Date grace_period)
	{
		setgrace_period(getContext(), grace_period);
	}

	/**
	 * Set value of grace_period
	 * @param context
	 * @param grace_period
	 */
	public final void setgrace_period(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date grace_period)
	{
		getMendixObject().setValue(context, MemberNames.grace_period.toString(), grace_period);
	}

	/**
	 * @return value of Summary
	 */
	public final java.lang.String getSummary()
	{
		return getSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of Summary
	 */
	public final java.lang.String getSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Summary.toString());
	}

	/**
	 * Set value of Summary
	 * @param summary
	 */
	public final void setSummary(java.lang.String summary)
	{
		setSummary(getContext(), summary);
	}

	/**
	 * Set value of Summary
	 * @param context
	 * @param summary
	 */
	public final void setSummary(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String summary)
	{
		getMendixObject().setValue(context, MemberNames.Summary.toString(), summary);
	}

	/**
	 * @return value of Full_discription
	 */
	public final java.lang.String getFull_discription()
	{
		return getFull_discription(getContext());
	}

	/**
	 * @param context
	 * @return value of Full_discription
	 */
	public final java.lang.String getFull_discription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Full_discription.toString());
	}

	/**
	 * Set value of Full_discription
	 * @param full_discription
	 */
	public final void setFull_discription(java.lang.String full_discription)
	{
		setFull_discription(getContext(), full_discription);
	}

	/**
	 * Set value of Full_discription
	 * @param context
	 * @param full_discription
	 */
	public final void setFull_discription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String full_discription)
	{
		getMendixObject().setValue(context, MemberNames.Full_discription.toString(), full_discription);
	}

	/**
	 * @return value of Application_limit
	 */
	public final java.lang.Integer getApplication_limit()
	{
		return getApplication_limit(getContext());
	}

	/**
	 * @param context
	 * @return value of Application_limit
	 */
	public final java.lang.Integer getApplication_limit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Application_limit.toString());
	}

	/**
	 * Set value of Application_limit
	 * @param application_limit
	 */
	public final void setApplication_limit(java.lang.Integer application_limit)
	{
		setApplication_limit(getContext(), application_limit);
	}

	/**
	 * Set value of Application_limit
	 * @param context
	 * @param application_limit
	 */
	public final void setApplication_limit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer application_limit)
	{
		getMendixObject().setValue(context, MemberNames.Application_limit.toString(), application_limit);
	}

	/**
	 * @return value of Eligibilty
	 */
	public final java.lang.Boolean getEligibilty()
	{
		return getEligibilty(getContext());
	}

	/**
	 * @param context
	 * @return value of Eligibilty
	 */
	public final java.lang.Boolean getEligibilty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Eligibilty.toString());
	}

	/**
	 * Set value of Eligibilty
	 * @param eligibilty
	 */
	public final void setEligibilty(java.lang.Boolean eligibilty)
	{
		setEligibilty(getContext(), eligibilty);
	}

	/**
	 * Set value of Eligibilty
	 * @param context
	 * @param eligibilty
	 */
	public final void setEligibilty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean eligibilty)
	{
		getMendixObject().setValue(context, MemberNames.Eligibilty.toString(), eligibilty);
	}

	/**
	 * @return value of Flowchart_String
	 */
	public final java.lang.String getFlowchart_String()
	{
		return getFlowchart_String(getContext());
	}

	/**
	 * @param context
	 * @return value of Flowchart_String
	 */
	public final java.lang.String getFlowchart_String(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Flowchart_String.toString());
	}

	/**
	 * Set value of Flowchart_String
	 * @param flowchart_string
	 */
	public final void setFlowchart_String(java.lang.String flowchart_string)
	{
		setFlowchart_String(getContext(), flowchart_string);
	}

	/**
	 * Set value of Flowchart_String
	 * @param context
	 * @param flowchart_string
	 */
	public final void setFlowchart_String(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flowchart_string)
	{
		getMendixObject().setValue(context, MemberNames.Flowchart_String.toString(), flowchart_string);
	}

	/**
	 * @return value of DaysLeft
	 */
	public final java.math.BigDecimal getDaysLeft()
	{
		return getDaysLeft(getContext());
	}

	/**
	 * @param context
	 * @return value of DaysLeft
	 */
	public final java.math.BigDecimal getDaysLeft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DaysLeft.toString());
	}

	/**
	 * Set value of DaysLeft
	 * @param daysleft
	 */
	public final void setDaysLeft(java.math.BigDecimal daysleft)
	{
		setDaysLeft(getContext(), daysleft);
	}

	/**
	 * Set value of DaysLeft
	 * @param context
	 * @param daysleft
	 */
	public final void setDaysLeft(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal daysleft)
	{
		getMendixObject().setValue(context, MemberNames.DaysLeft.toString(), daysleft);
	}

	/**
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber()
	{
		return getCurrentOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentOrderNumber
	 */
	public final java.lang.Integer getCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentOrderNumber.toString());
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(java.lang.Integer currentordernumber)
	{
		setCurrentOrderNumber(getContext(), currentordernumber);
	}

	/**
	 * Set value of CurrentOrderNumber
	 * @param context
	 * @param currentordernumber
	 */
	public final void setCurrentOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentordernumber)
	{
		getMendixObject().setValue(context, MemberNames.CurrentOrderNumber.toString(), currentordernumber);
	}

	/**
	 * @return value of editable
	 */
	public final java.lang.Boolean geteditable()
	{
		return geteditable(getContext());
	}

	/**
	 * @param context
	 * @return value of editable
	 */
	public final java.lang.Boolean geteditable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.editable.toString());
	}

	/**
	 * Set value of editable
	 * @param editable
	 */
	public final void seteditable(java.lang.Boolean editable)
	{
		seteditable(getContext(), editable);
	}

	/**
	 * Set value of editable
	 * @param context
	 * @param editable
	 */
	public final void seteditable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean editable)
	{
		getMendixObject().setValue(context, MemberNames.editable.toString(), editable);
	}

	/**
	 * @return value of Notification_Content
	 */
	public final java.lang.String getNotification_Content()
	{
		return getNotification_Content(getContext());
	}

	/**
	 * @param context
	 * @return value of Notification_Content
	 */
	public final java.lang.String getNotification_Content(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Notification_Content.toString());
	}

	/**
	 * Set value of Notification_Content
	 * @param notification_content
	 */
	public final void setNotification_Content(java.lang.String notification_content)
	{
		setNotification_Content(getContext(), notification_content);
	}

	/**
	 * Set value of Notification_Content
	 * @param context
	 * @param notification_content
	 */
	public final void setNotification_Content(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notification_content)
	{
		getMendixObject().setValue(context, MemberNames.Notification_Content.toString(), notification_content);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of CurrentFormNumber
	 */
	public final java.lang.Integer getCurrentFormNumber()
	{
		return getCurrentFormNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentFormNumber
	 */
	public final java.lang.Integer getCurrentFormNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentFormNumber.toString());
	}

	/**
	 * Set value of CurrentFormNumber
	 * @param currentformnumber
	 */
	public final void setCurrentFormNumber(java.lang.Integer currentformnumber)
	{
		setCurrentFormNumber(getContext(), currentformnumber);
	}

	/**
	 * Set value of CurrentFormNumber
	 * @param context
	 * @param currentformnumber
	 */
	public final void setCurrentFormNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentformnumber)
	{
		getMendixObject().setValue(context, MemberNames.CurrentFormNumber.toString(), currentformnumber);
	}

	/**
	 * @return value of Main
	 */
	public final java.lang.Boolean getMain()
	{
		return getMain(getContext());
	}

	/**
	 * @param context
	 * @return value of Main
	 */
	public final java.lang.Boolean getMain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Main.toString());
	}

	/**
	 * Set value of Main
	 * @param main
	 */
	public final void setMain(java.lang.Boolean main)
	{
		setMain(getContext(), main);
	}

	/**
	 * Set value of Main
	 * @param context
	 * @param main
	 */
	public final void setMain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean main)
	{
		getMendixObject().setValue(context, MemberNames.Main.toString(), main);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Oneclick_Content
	 */
	public final java.lang.String getOneclick_Content()
	{
		return getOneclick_Content(getContext());
	}

	/**
	 * @param context
	 * @return value of Oneclick_Content
	 */
	public final java.lang.String getOneclick_Content(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Oneclick_Content.toString());
	}

	/**
	 * Set value of Oneclick_Content
	 * @param oneclick_content
	 */
	public final void setOneclick_Content(java.lang.String oneclick_content)
	{
		setOneclick_Content(getContext(), oneclick_content);
	}

	/**
	 * Set value of Oneclick_Content
	 * @param context
	 * @param oneclick_content
	 */
	public final void setOneclick_Content(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oneclick_content)
	{
		getMendixObject().setValue(context, MemberNames.Oneclick_Content.toString(), oneclick_content);
	}

	/**
	 * @return value of ToAddress
	 */
	public final java.lang.String getToAddress()
	{
		return getToAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of ToAddress
	 */
	public final java.lang.String getToAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToAddress.toString());
	}

	/**
	 * Set value of ToAddress
	 * @param toaddress
	 */
	public final void setToAddress(java.lang.String toaddress)
	{
		setToAddress(getContext(), toaddress);
	}

	/**
	 * Set value of ToAddress
	 * @param context
	 * @param toaddress
	 */
	public final void setToAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String toaddress)
	{
		getMendixObject().setValue(context, MemberNames.ToAddress.toString(), toaddress);
	}

	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of PermanentID
	 */
	public final java.lang.Integer getPermanentID()
	{
		return getPermanentID(getContext());
	}

	/**
	 * @param context
	 * @return value of PermanentID
	 */
	public final java.lang.Integer getPermanentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PermanentID.toString());
	}

	/**
	 * Set value of PermanentID
	 * @param permanentid
	 */
	public final void setPermanentID(java.lang.Integer permanentid)
	{
		setPermanentID(getContext(), permanentid);
	}

	/**
	 * Set value of PermanentID
	 * @param context
	 * @param permanentid
	 */
	public final void setPermanentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer permanentid)
	{
		getMendixObject().setValue(context, MemberNames.PermanentID.toString(), permanentid);
	}

	/**
	 * Set value of ReviewType
	 * @param reviewtype
	 */
	public final ugs.proxies.Enum_ReviewTypes getReviewType()
	{
		return getReviewType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewType
	 */
	public final ugs.proxies.Enum_ReviewTypes getReviewType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReviewType.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_ReviewTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ReviewType
	 * @param reviewtype
	 */
	public final void setReviewType(ugs.proxies.Enum_ReviewTypes reviewtype)
	{
		setReviewType(getContext(), reviewtype);
	}

	/**
	 * Set value of ReviewType
	 * @param context
	 * @param reviewtype
	 */
	public final void setReviewType(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_ReviewTypes reviewtype)
	{
		if (reviewtype != null)
			getMendixObject().setValue(context, MemberNames.ReviewType.toString(), reviewtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ReviewType.toString(), null);
	}

	/**
	 * Set value of OverAllRating
	 * @param overallrating
	 */
	public final ugs.proxies.Enum_score getOverAllRating()
	{
		return getOverAllRating(getContext());
	}

	/**
	 * @param context
	 * @return value of OverAllRating
	 */
	public final ugs.proxies.Enum_score getOverAllRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OverAllRating.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_score.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OverAllRating
	 * @param overallrating
	 */
	public final void setOverAllRating(ugs.proxies.Enum_score overallrating)
	{
		setOverAllRating(getContext(), overallrating);
	}

	/**
	 * Set value of OverAllRating
	 * @param context
	 * @param overallrating
	 */
	public final void setOverAllRating(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_score overallrating)
	{
		if (overallrating != null)
			getMendixObject().setValue(context, MemberNames.OverAllRating.toString(), overallrating.toString());
		else
			getMendixObject().setValue(context, MemberNames.OverAllRating.toString(), null);
	}

	/**
	 * @return value of ReviewComments
	 */
	public final java.lang.String getReviewComments()
	{
		return getReviewComments(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewComments
	 */
	public final java.lang.String getReviewComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReviewComments.toString());
	}

	/**
	 * Set value of ReviewComments
	 * @param reviewcomments
	 */
	public final void setReviewComments(java.lang.String reviewcomments)
	{
		setReviewComments(getContext(), reviewcomments);
	}

	/**
	 * Set value of ReviewComments
	 * @param context
	 * @param reviewcomments
	 */
	public final void setReviewComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reviewcomments)
	{
		getMendixObject().setValue(context, MemberNames.ReviewComments.toString(), reviewcomments);
	}

	/**
	 * @return value of TotalScore
	 */
	public final java.lang.Integer getTotalScore()
	{
		return getTotalScore(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalScore
	 */
	public final java.lang.Integer getTotalScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalScore.toString());
	}

	/**
	 * Set value of TotalScore
	 * @param totalscore
	 */
	public final void setTotalScore(java.lang.Integer totalscore)
	{
		setTotalScore(getContext(), totalscore);
	}

	/**
	 * Set value of TotalScore
	 * @param context
	 * @param totalscore
	 */
	public final void setTotalScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalscore)
	{
		getMendixObject().setValue(context, MemberNames.TotalScore.toString(), totalscore);
	}

	/**
	 * @return value of OverAllRating_Decimal
	 */
	public final java.math.BigDecimal getOverAllRating_Decimal()
	{
		return getOverAllRating_Decimal(getContext());
	}

	/**
	 * @param context
	 * @return value of OverAllRating_Decimal
	 */
	public final java.math.BigDecimal getOverAllRating_Decimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OverAllRating_Decimal.toString());
	}

	/**
	 * Set value of OverAllRating_Decimal
	 * @param overallrating_decimal
	 */
	public final void setOverAllRating_Decimal(java.math.BigDecimal overallrating_decimal)
	{
		setOverAllRating_Decimal(getContext(), overallrating_decimal);
	}

	/**
	 * Set value of OverAllRating_Decimal
	 * @param context
	 * @param overallrating_decimal
	 */
	public final void setOverAllRating_Decimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal overallrating_decimal)
	{
		getMendixObject().setValue(context, MemberNames.OverAllRating_Decimal.toString(), overallrating_decimal);
	}

	/**
	 * @return value of oneE
	 */
	public final java.lang.Boolean getoneE()
	{
		return getoneE(getContext());
	}

	/**
	 * @param context
	 * @return value of oneE
	 */
	public final java.lang.Boolean getoneE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.oneE.toString());
	}

	/**
	 * Set value of oneE
	 * @param onee
	 */
	public final void setoneE(java.lang.Boolean onee)
	{
		setoneE(getContext(), onee);
	}

	/**
	 * Set value of oneE
	 * @param context
	 * @param onee
	 */
	public final void setoneE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean onee)
	{
		getMendixObject().setValue(context, MemberNames.oneE.toString(), onee);
	}

	/**
	 * @return value of UseTokens
	 */
	public final java.lang.Boolean getUseTokens()
	{
		return getUseTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of UseTokens
	 */
	public final java.lang.Boolean getUseTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseTokens.toString());
	}

	/**
	 * Set value of UseTokens
	 * @param usetokens
	 */
	public final void setUseTokens(java.lang.Boolean usetokens)
	{
		setUseTokens(getContext(), usetokens);
	}

	/**
	 * Set value of UseTokens
	 * @param context
	 * @param usetokens
	 */
	public final void setUseTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usetokens)
	{
		getMendixObject().setValue(context, MemberNames.UseTokens.toString(), usetokens);
	}

	/**
	 * @return value of TwoE
	 */
	public final java.lang.Boolean getTwoE()
	{
		return getTwoE(getContext());
	}

	/**
	 * @param context
	 * @return value of TwoE
	 */
	public final java.lang.Boolean getTwoE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TwoE.toString());
	}

	/**
	 * Set value of TwoE
	 * @param twoe
	 */
	public final void setTwoE(java.lang.Boolean twoe)
	{
		setTwoE(getContext(), twoe);
	}

	/**
	 * Set value of TwoE
	 * @param context
	 * @param twoe
	 */
	public final void setTwoE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean twoe)
	{
		getMendixObject().setValue(context, MemberNames.TwoE.toString(), twoe);
	}

	/**
	 * @return value of ThreeE
	 */
	public final java.lang.Boolean getThreeE()
	{
		return getThreeE(getContext());
	}

	/**
	 * @param context
	 * @return value of ThreeE
	 */
	public final java.lang.Boolean getThreeE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ThreeE.toString());
	}

	/**
	 * Set value of ThreeE
	 * @param threee
	 */
	public final void setThreeE(java.lang.Boolean threee)
	{
		setThreeE(getContext(), threee);
	}

	/**
	 * Set value of ThreeE
	 * @param context
	 * @param threee
	 */
	public final void setThreeE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean threee)
	{
		getMendixObject().setValue(context, MemberNames.ThreeE.toString(), threee);
	}

	/**
	 * @return value of FourE
	 */
	public final java.lang.Boolean getFourE()
	{
		return getFourE(getContext());
	}

	/**
	 * @param context
	 * @return value of FourE
	 */
	public final java.lang.Boolean getFourE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FourE.toString());
	}

	/**
	 * Set value of FourE
	 * @param foure
	 */
	public final void setFourE(java.lang.Boolean foure)
	{
		setFourE(getContext(), foure);
	}

	/**
	 * Set value of FourE
	 * @param context
	 * @param foure
	 */
	public final void setFourE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean foure)
	{
		getMendixObject().setValue(context, MemberNames.FourE.toString(), foure);
	}

	/**
	 * @return value of FiveE
	 */
	public final java.lang.Boolean getFiveE()
	{
		return getFiveE(getContext());
	}

	/**
	 * @param context
	 * @return value of FiveE
	 */
	public final java.lang.Boolean getFiveE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FiveE.toString());
	}

	/**
	 * Set value of FiveE
	 * @param fivee
	 */
	public final void setFiveE(java.lang.Boolean fivee)
	{
		setFiveE(getContext(), fivee);
	}

	/**
	 * Set value of FiveE
	 * @param context
	 * @param fivee
	 */
	public final void setFiveE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean fivee)
	{
		getMendixObject().setValue(context, MemberNames.FiveE.toString(), fivee);
	}

	/**
	 * @return value of FundingAmount
	 */
	public final java.math.BigDecimal getFundingAmount()
	{
		return getFundingAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of FundingAmount
	 */
	public final java.math.BigDecimal getFundingAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FundingAmount.toString());
	}

	/**
	 * Set value of FundingAmount
	 * @param fundingamount
	 */
	public final void setFundingAmount(java.math.BigDecimal fundingamount)
	{
		setFundingAmount(getContext(), fundingamount);
	}

	/**
	 * Set value of FundingAmount
	 * @param context
	 * @param fundingamount
	 */
	public final void setFundingAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal fundingamount)
	{
		getMendixObject().setValue(context, MemberNames.FundingAmount.toString(), fundingamount);
	}

	/**
	 * @return value of AwardingAmount
	 */
	public final java.math.BigDecimal getAwardingAmount()
	{
		return getAwardingAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of AwardingAmount
	 */
	public final java.math.BigDecimal getAwardingAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AwardingAmount.toString());
	}

	/**
	 * Set value of AwardingAmount
	 * @param awardingamount
	 */
	public final void setAwardingAmount(java.math.BigDecimal awardingamount)
	{
		setAwardingAmount(getContext(), awardingamount);
	}

	/**
	 * Set value of AwardingAmount
	 * @param context
	 * @param awardingamount
	 */
	public final void setAwardingAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal awardingamount)
	{
		getMendixObject().setValue(context, MemberNames.AwardingAmount.toString(), awardingamount);
	}

	/**
	 * @return value of RequestingAmount
	 */
	public final java.math.BigDecimal getRequestingAmount()
	{
		return getRequestingAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestingAmount
	 */
	public final java.math.BigDecimal getRequestingAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RequestingAmount.toString());
	}

	/**
	 * Set value of RequestingAmount
	 * @param requestingamount
	 */
	public final void setRequestingAmount(java.math.BigDecimal requestingamount)
	{
		setRequestingAmount(getContext(), requestingamount);
	}

	/**
	 * Set value of RequestingAmount
	 * @param context
	 * @param requestingamount
	 */
	public final void setRequestingAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal requestingamount)
	{
		getMendixObject().setValue(context, MemberNames.RequestingAmount.toString(), requestingamount);
	}

	/**
	 * Set value of Internal_Status
	 * @param internal_status
	 */
	public final ugs.proxies.Enum_WorkflowStages getInternal_Status()
	{
		return getInternal_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Internal_Status
	 */
	public final ugs.proxies.Enum_WorkflowStages getInternal_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Internal_Status.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_WorkflowStages.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Internal_Status
	 * @param internal_status
	 */
	public final void setInternal_Status(ugs.proxies.Enum_WorkflowStages internal_status)
	{
		setInternal_Status(getContext(), internal_status);
	}

	/**
	 * Set value of Internal_Status
	 * @param context
	 * @param internal_status
	 */
	public final void setInternal_Status(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_WorkflowStages internal_status)
	{
		if (internal_status != null)
			getMendixObject().setValue(context, MemberNames.Internal_Status.toString(), internal_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Internal_Status.toString(), null);
	}

	/**
	 * @return value of TotalRquestedAmount
	 */
	public final java.math.BigDecimal getTotalRquestedAmount()
	{
		return getTotalRquestedAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalRquestedAmount
	 */
	public final java.math.BigDecimal getTotalRquestedAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalRquestedAmount.toString());
	}

	/**
	 * Set value of TotalRquestedAmount
	 * @param totalrquestedamount
	 */
	public final void setTotalRquestedAmount(java.math.BigDecimal totalrquestedamount)
	{
		setTotalRquestedAmount(getContext(), totalrquestedamount);
	}

	/**
	 * Set value of TotalRquestedAmount
	 * @param context
	 * @param totalrquestedamount
	 */
	public final void setTotalRquestedAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalrquestedamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalRquestedAmount.toString(), totalrquestedamount);
	}

	/**
	 * @return value of RequestedDate
	 */
	public final java.util.Date getRequestedDate()
	{
		return getRequestedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestedDate
	 */
	public final java.util.Date getRequestedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestedDate.toString());
	}

	/**
	 * Set value of RequestedDate
	 * @param requesteddate
	 */
	public final void setRequestedDate(java.util.Date requesteddate)
	{
		setRequestedDate(getContext(), requesteddate);
	}

	/**
	 * Set value of RequestedDate
	 * @param context
	 * @param requesteddate
	 */
	public final void setRequestedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requesteddate)
	{
		getMendixObject().setValue(context, MemberNames.RequestedDate.toString(), requesteddate);
	}

	/**
	 * @return value of NoOfRequest
	 */
	public final java.lang.Integer getNoOfRequest()
	{
		return getNoOfRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfRequest
	 */
	public final java.lang.Integer getNoOfRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfRequest.toString());
	}

	/**
	 * Set value of NoOfRequest
	 * @param noofrequest
	 */
	public final void setNoOfRequest(java.lang.Integer noofrequest)
	{
		setNoOfRequest(getContext(), noofrequest);
	}

	/**
	 * Set value of NoOfRequest
	 * @param context
	 * @param noofrequest
	 */
	public final void setNoOfRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofrequest)
	{
		getMendixObject().setValue(context, MemberNames.NoOfRequest.toString(), noofrequest);
	}

	/**
	 * @return value of AvailableBlc
	 */
	public final java.math.BigDecimal getAvailableBlc()
	{
		return getAvailableBlc(getContext());
	}

	/**
	 * @param context
	 * @return value of AvailableBlc
	 */
	public final java.math.BigDecimal getAvailableBlc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AvailableBlc.toString());
	}

	/**
	 * Set value of AvailableBlc
	 * @param availableblc
	 */
	public final void setAvailableBlc(java.math.BigDecimal availableblc)
	{
		setAvailableBlc(getContext(), availableblc);
	}

	/**
	 * Set value of AvailableBlc
	 * @param context
	 * @param availableblc
	 */
	public final void setAvailableBlc(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal availableblc)
	{
		getMendixObject().setValue(context, MemberNames.AvailableBlc.toString(), availableblc);
	}

	/**
	 * @return value of TestScore
	 */
	public final java.lang.String getTestScore()
	{
		return getTestScore(getContext());
	}

	/**
	 * @param context
	 * @return value of TestScore
	 */
	public final java.lang.String getTestScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestScore.toString());
	}

	/**
	 * Set value of TestScore
	 * @param testscore
	 */
	public final void setTestScore(java.lang.String testscore)
	{
		setTestScore(getContext(), testscore);
	}

	/**
	 * Set value of TestScore
	 * @param context
	 * @param testscore
	 */
	public final void setTestScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String testscore)
	{
		getMendixObject().setValue(context, MemberNames.TestScore.toString(), testscore);
	}

	/**
	 * @return value of WorkflowEnd
	 */
	public final java.lang.Boolean getWorkflowEnd()
	{
		return getWorkflowEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEnd
	 */
	public final java.lang.Boolean getWorkflowEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WorkflowEnd.toString());
	}

	/**
	 * Set value of WorkflowEnd
	 * @param workflowend
	 */
	public final void setWorkflowEnd(java.lang.Boolean workflowend)
	{
		setWorkflowEnd(getContext(), workflowend);
	}

	/**
	 * Set value of WorkflowEnd
	 * @param context
	 * @param workflowend
	 */
	public final void setWorkflowEnd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean workflowend)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowEnd.toString(), workflowend);
	}

	/**
	 * Set value of Frequency
	 * @param frequency
	 */
	public final ugs.proxies.Enum_Frequency getFrequency()
	{
		return getFrequency(getContext());
	}

	/**
	 * @param context
	 * @return value of Frequency
	 */
	public final ugs.proxies.Enum_Frequency getFrequency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Frequency.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_Frequency.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Frequency
	 * @param frequency
	 */
	public final void setFrequency(ugs.proxies.Enum_Frequency frequency)
	{
		setFrequency(getContext(), frequency);
	}

	/**
	 * Set value of Frequency
	 * @param context
	 * @param frequency
	 */
	public final void setFrequency(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_Frequency frequency)
	{
		if (frequency != null)
			getMendixObject().setValue(context, MemberNames.Frequency.toString(), frequency.toString());
		else
			getMendixObject().setValue(context, MemberNames.Frequency.toString(), null);
	}

	/**
	 * @return value of Q1_Amount
	 */
	public final java.math.BigDecimal getQ1_Amount()
	{
		return getQ1_Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Q1_Amount
	 */
	public final java.math.BigDecimal getQ1_Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Q1_Amount.toString());
	}

	/**
	 * Set value of Q1_Amount
	 * @param q1_amount
	 */
	public final void setQ1_Amount(java.math.BigDecimal q1_amount)
	{
		setQ1_Amount(getContext(), q1_amount);
	}

	/**
	 * Set value of Q1_Amount
	 * @param context
	 * @param q1_amount
	 */
	public final void setQ1_Amount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal q1_amount)
	{
		getMendixObject().setValue(context, MemberNames.Q1_Amount.toString(), q1_amount);
	}

	/**
	 * @return value of Q2Amount
	 */
	public final java.math.BigDecimal getQ2Amount()
	{
		return getQ2Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Q2Amount
	 */
	public final java.math.BigDecimal getQ2Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Q2Amount.toString());
	}

	/**
	 * Set value of Q2Amount
	 * @param q2amount
	 */
	public final void setQ2Amount(java.math.BigDecimal q2amount)
	{
		setQ2Amount(getContext(), q2amount);
	}

	/**
	 * Set value of Q2Amount
	 * @param context
	 * @param q2amount
	 */
	public final void setQ2Amount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal q2amount)
	{
		getMendixObject().setValue(context, MemberNames.Q2Amount.toString(), q2amount);
	}

	/**
	 * @return value of Q3_Amount
	 */
	public final java.math.BigDecimal getQ3_Amount()
	{
		return getQ3_Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Q3_Amount
	 */
	public final java.math.BigDecimal getQ3_Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Q3_Amount.toString());
	}

	/**
	 * Set value of Q3_Amount
	 * @param q3_amount
	 */
	public final void setQ3_Amount(java.math.BigDecimal q3_amount)
	{
		setQ3_Amount(getContext(), q3_amount);
	}

	/**
	 * Set value of Q3_Amount
	 * @param context
	 * @param q3_amount
	 */
	public final void setQ3_Amount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal q3_amount)
	{
		getMendixObject().setValue(context, MemberNames.Q3_Amount.toString(), q3_amount);
	}

	/**
	 * @return value of Q4_Amount
	 */
	public final java.math.BigDecimal getQ4_Amount()
	{
		return getQ4_Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Q4_Amount
	 */
	public final java.math.BigDecimal getQ4_Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Q4_Amount.toString());
	}

	/**
	 * Set value of Q4_Amount
	 * @param q4_amount
	 */
	public final void setQ4_Amount(java.math.BigDecimal q4_amount)
	{
		setQ4_Amount(getContext(), q4_amount);
	}

	/**
	 * Set value of Q4_Amount
	 * @param context
	 * @param q4_amount
	 */
	public final void setQ4_Amount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal q4_amount)
	{
		getMendixObject().setValue(context, MemberNames.Q4_Amount.toString(), q4_amount);
	}

	/**
	 * @return value of Q1_Date
	 */
	public final java.util.Date getQ1_Date()
	{
		return getQ1_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Q1_Date
	 */
	public final java.util.Date getQ1_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Q1_Date.toString());
	}

	/**
	 * Set value of Q1_Date
	 * @param q1_date
	 */
	public final void setQ1_Date(java.util.Date q1_date)
	{
		setQ1_Date(getContext(), q1_date);
	}

	/**
	 * Set value of Q1_Date
	 * @param context
	 * @param q1_date
	 */
	public final void setQ1_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date q1_date)
	{
		getMendixObject().setValue(context, MemberNames.Q1_Date.toString(), q1_date);
	}

	/**
	 * @return value of Q2_Date
	 */
	public final java.util.Date getQ2_Date()
	{
		return getQ2_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Q2_Date
	 */
	public final java.util.Date getQ2_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Q2_Date.toString());
	}

	/**
	 * Set value of Q2_Date
	 * @param q2_date
	 */
	public final void setQ2_Date(java.util.Date q2_date)
	{
		setQ2_Date(getContext(), q2_date);
	}

	/**
	 * Set value of Q2_Date
	 * @param context
	 * @param q2_date
	 */
	public final void setQ2_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date q2_date)
	{
		getMendixObject().setValue(context, MemberNames.Q2_Date.toString(), q2_date);
	}

	/**
	 * @return value of Q3_Date
	 */
	public final java.util.Date getQ3_Date()
	{
		return getQ3_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Q3_Date
	 */
	public final java.util.Date getQ3_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Q3_Date.toString());
	}

	/**
	 * Set value of Q3_Date
	 * @param q3_date
	 */
	public final void setQ3_Date(java.util.Date q3_date)
	{
		setQ3_Date(getContext(), q3_date);
	}

	/**
	 * Set value of Q3_Date
	 * @param context
	 * @param q3_date
	 */
	public final void setQ3_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date q3_date)
	{
		getMendixObject().setValue(context, MemberNames.Q3_Date.toString(), q3_date);
	}

	/**
	 * @return value of Q4_Date
	 */
	public final java.util.Date getQ4_Date()
	{
		return getQ4_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Q4_Date
	 */
	public final java.util.Date getQ4_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Q4_Date.toString());
	}

	/**
	 * Set value of Q4_Date
	 * @param q4_date
	 */
	public final void setQ4_Date(java.util.Date q4_date)
	{
		setQ4_Date(getContext(), q4_date);
	}

	/**
	 * Set value of Q4_Date
	 * @param context
	 * @param q4_date
	 */
	public final void setQ4_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date q4_date)
	{
		getMendixObject().setValue(context, MemberNames.Q4_Date.toString(), q4_date);
	}

	/**
	 * @return value of FrequencyYear
	 */
	public final java.lang.String getFrequencyYear()
	{
		return getFrequencyYear(getContext());
	}

	/**
	 * @param context
	 * @return value of FrequencyYear
	 */
	public final java.lang.String getFrequencyYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FrequencyYear.toString());
	}

	/**
	 * Set value of FrequencyYear
	 * @param frequencyyear
	 */
	public final void setFrequencyYear(java.lang.String frequencyyear)
	{
		setFrequencyYear(getContext(), frequencyyear);
	}

	/**
	 * Set value of FrequencyYear
	 * @param context
	 * @param frequencyyear
	 */
	public final void setFrequencyYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String frequencyyear)
	{
		getMendixObject().setValue(context, MemberNames.FrequencyYear.toString(), frequencyyear);
	}

	/**
	 * @return value of Signature_GrantSystem_Clone
	 */
	public final ugs.proxies.Signature getSignature_GrantSystem_Clone() throws com.mendix.core.CoreException
	{
		return getSignature_GrantSystem_Clone(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature_GrantSystem_Clone
	 */
	public final ugs.proxies.Signature getSignature_GrantSystem_Clone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Signature result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signature_GrantSystem_Clone.toString());
		if (identifier != null)
			result = ugs.proxies.Signature.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Signature_GrantSystem_Clone
	 * @param signature_grantsystem_clone
	 */
	public final void setSignature_GrantSystem_Clone(ugs.proxies.Signature signature_grantsystem_clone)
	{
		setSignature_GrantSystem_Clone(getContext(), signature_grantsystem_clone);
	}

	/**
	 * Set value of Signature_GrantSystem_Clone
	 * @param context
	 * @param signature_grantsystem_clone
	 */
	public final void setSignature_GrantSystem_Clone(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Signature signature_grantsystem_clone)
	{
		if (signature_grantsystem_clone == null)
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_Clone.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_Clone.toString(), signature_grantsystem_clone.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_Aggrement_
	 */
	public final ugs.proxies.Aggrement_ getGrantSystem_Aggrement_() throws com.mendix.core.CoreException
	{
		return getGrantSystem_Aggrement_(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_Aggrement_
	 */
	public final ugs.proxies.Aggrement_ getGrantSystem_Aggrement_(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Aggrement_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_Aggrement_.toString());
		if (identifier != null)
			result = ugs.proxies.Aggrement_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_Aggrement_
	 * @param grantsystem_aggrement_
	 */
	public final void setGrantSystem_Aggrement_(ugs.proxies.Aggrement_ grantsystem_aggrement_)
	{
		setGrantSystem_Aggrement_(getContext(), grantsystem_aggrement_);
	}

	/**
	 * Set value of GrantSystem_Aggrement_
	 * @param context
	 * @param grantsystem_aggrement_
	 */
	public final void setGrantSystem_Aggrement_(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Aggrement_ grantsystem_aggrement_)
	{
		if (grantsystem_aggrement_ == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_Aggrement_.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_Aggrement_.toString(), grantsystem_aggrement_.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_Printout
	 */
	public final ugs.proxies.Printout getGrantSystem_Printout() throws com.mendix.core.CoreException
	{
		return getGrantSystem_Printout(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_Printout
	 */
	public final ugs.proxies.Printout getGrantSystem_Printout(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Printout result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_Printout.toString());
		if (identifier != null)
			result = ugs.proxies.Printout.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_Printout
	 * @param grantsystem_printout
	 */
	public final void setGrantSystem_Printout(ugs.proxies.Printout grantsystem_printout)
	{
		setGrantSystem_Printout(getContext(), grantsystem_printout);
	}

	/**
	 * Set value of GrantSystem_Printout
	 * @param context
	 * @param grantsystem_printout
	 */
	public final void setGrantSystem_Printout(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Printout grantsystem_printout)
	{
		if (grantsystem_printout == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_Printout.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_Printout.toString(), grantsystem_printout.getMendixObject().getId());
	}

	/**
	 * @return value of Signature_GrantSystem_main
	 */
	public final ugs.proxies.Signature getSignature_GrantSystem_main() throws com.mendix.core.CoreException
	{
		return getSignature_GrantSystem_main(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature_GrantSystem_main
	 */
	public final ugs.proxies.Signature getSignature_GrantSystem_main(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Signature result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signature_GrantSystem_main.toString());
		if (identifier != null)
			result = ugs.proxies.Signature.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Signature_GrantSystem_main
	 * @param signature_grantsystem_main
	 */
	public final void setSignature_GrantSystem_main(ugs.proxies.Signature signature_grantsystem_main)
	{
		setSignature_GrantSystem_main(getContext(), signature_grantsystem_main);
	}

	/**
	 * Set value of Signature_GrantSystem_main
	 * @param context
	 * @param signature_grantsystem_main
	 */
	public final void setSignature_GrantSystem_main(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Signature signature_grantsystem_main)
	{
		if (signature_grantsystem_main == null)
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_main.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_main.toString(), signature_grantsystem_main.getMendixObject().getId());
	}

	/**
	 * @return value of Fundings_GrantSystem
	 */
	public final ugs.proxies.Fundings getFundings_GrantSystem() throws com.mendix.core.CoreException
	{
		return getFundings_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Fundings_GrantSystem
	 */
	public final ugs.proxies.Fundings getFundings_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Fundings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fundings_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.Fundings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Fundings_GrantSystem
	 * @param fundings_grantsystem
	 */
	public final void setFundings_GrantSystem(ugs.proxies.Fundings fundings_grantsystem)
	{
		setFundings_GrantSystem(getContext(), fundings_grantsystem);
	}

	/**
	 * Set value of Fundings_GrantSystem
	 * @param context
	 * @param fundings_grantsystem
	 */
	public final void setFundings_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Fundings fundings_grantsystem)
	{
		if (fundings_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Fundings_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Fundings_GrantSystem.toString(), fundings_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of History_GrantSystem
	 */
	public final ugs.proxies.History getHistory_GrantSystem() throws com.mendix.core.CoreException
	{
		return getHistory_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of History_GrantSystem
	 */
	public final ugs.proxies.History getHistory_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.History result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.History.load(context, identifier);
		return result;
	}

	/**
	 * Set value of History_GrantSystem
	 * @param history_grantsystem
	 */
	public final void setHistory_GrantSystem(ugs.proxies.History history_grantsystem)
	{
		setHistory_GrantSystem(getContext(), history_grantsystem);
	}

	/**
	 * Set value of History_GrantSystem
	 * @param context
	 * @param history_grantsystem
	 */
	public final void setHistory_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.History history_grantsystem)
	{
		if (history_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.History_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.History_GrantSystem.toString(), history_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of Test_GrantSystem
	 */
	public final ugs.proxies.Test getTest_GrantSystem() throws com.mendix.core.CoreException
	{
		return getTest_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Test_GrantSystem
	 */
	public final ugs.proxies.Test getTest_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Test_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.Test.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Test_GrantSystem
	 * @param test_grantsystem
	 */
	public final void setTest_GrantSystem(ugs.proxies.Test test_grantsystem)
	{
		setTest_GrantSystem(getContext(), test_grantsystem);
	}

	/**
	 * Set value of Test_GrantSystem
	 * @param context
	 * @param test_grantsystem
	 */
	public final void setTest_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Test test_grantsystem)
	{
		if (test_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Test_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Test_GrantSystem.toString(), test_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of Interview_GrantSystem
	 */
	public final ugs.proxies.Interview getInterview_GrantSystem() throws com.mendix.core.CoreException
	{
		return getInterview_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Interview_GrantSystem
	 */
	public final ugs.proxies.Interview getInterview_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Interview result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Interview_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.Interview.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Interview_GrantSystem
	 * @param interview_grantsystem
	 */
	public final void setInterview_GrantSystem(ugs.proxies.Interview interview_grantsystem)
	{
		setInterview_GrantSystem(getContext(), interview_grantsystem);
	}

	/**
	 * Set value of Interview_GrantSystem
	 * @param context
	 * @param interview_grantsystem
	 */
	public final void setInterview_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Interview interview_grantsystem)
	{
		if (interview_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Interview_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Interview_GrantSystem.toString(), interview_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_Organization
	 */
	public final ugs.proxies.Organization getGrantSystem_Organization() throws com.mendix.core.CoreException
	{
		return getGrantSystem_Organization(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_Organization
	 */
	public final ugs.proxies.Organization getGrantSystem_Organization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Organization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_Organization.toString());
		if (identifier != null)
			result = ugs.proxies.Organization.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_Organization
	 * @param grantsystem_organization
	 */
	public final void setGrantSystem_Organization(ugs.proxies.Organization grantsystem_organization)
	{
		setGrantSystem_Organization(getContext(), grantsystem_organization);
	}

	/**
	 * Set value of GrantSystem_Organization
	 * @param context
	 * @param grantsystem_organization
	 */
	public final void setGrantSystem_Organization(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Organization grantsystem_organization)
	{
		if (grantsystem_organization == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_Organization.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_Organization.toString(), grantsystem_organization.getMendixObject().getId());
	}

	/**
	 * @return value of ReviewForm_GrantSystem_CurrentReviewForm
	 */
	public final ugs.proxies.ReviewForm getReviewForm_GrantSystem_CurrentReviewForm() throws com.mendix.core.CoreException
	{
		return getReviewForm_GrantSystem_CurrentReviewForm(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewForm_GrantSystem_CurrentReviewForm
	 */
	public final ugs.proxies.ReviewForm getReviewForm_GrantSystem_CurrentReviewForm(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.ReviewForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReviewForm_GrantSystem_CurrentReviewForm.toString());
		if (identifier != null)
			result = ugs.proxies.ReviewForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReviewForm_GrantSystem_CurrentReviewForm
	 * @param reviewform_grantsystem_currentreviewform
	 */
	public final void setReviewForm_GrantSystem_CurrentReviewForm(ugs.proxies.ReviewForm reviewform_grantsystem_currentreviewform)
	{
		setReviewForm_GrantSystem_CurrentReviewForm(getContext(), reviewform_grantsystem_currentreviewform);
	}

	/**
	 * Set value of ReviewForm_GrantSystem_CurrentReviewForm
	 * @param context
	 * @param reviewform_grantsystem_currentreviewform
	 */
	public final void setReviewForm_GrantSystem_CurrentReviewForm(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.ReviewForm reviewform_grantsystem_currentreviewform)
	{
		if (reviewform_grantsystem_currentreviewform == null)
			getMendixObject().setValue(context, MemberNames.ReviewForm_GrantSystem_CurrentReviewForm.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReviewForm_GrantSystem_CurrentReviewForm.toString(), reviewform_grantsystem_currentreviewform.getMendixObject().getId());
	}

	/**
	 * @return value of Voucher_GrantSystem
	 */
	public final ugs.proxies.Voucher getVoucher_GrantSystem() throws com.mendix.core.CoreException
	{
		return getVoucher_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Voucher_GrantSystem
	 */
	public final ugs.proxies.Voucher getVoucher_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Voucher result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Voucher_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.Voucher.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Voucher_GrantSystem
	 * @param voucher_grantsystem
	 */
	public final void setVoucher_GrantSystem(ugs.proxies.Voucher voucher_grantsystem)
	{
		setVoucher_GrantSystem(getContext(), voucher_grantsystem);
	}

	/**
	 * Set value of Voucher_GrantSystem
	 * @param context
	 * @param voucher_grantsystem
	 */
	public final void setVoucher_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Voucher voucher_grantsystem)
	{
		if (voucher_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Voucher_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Voucher_GrantSystem.toString(), voucher_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrantSystem_WorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getGrantSystem_WorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getGrantSystem_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_WorkflowUserTask.toString());
		if (identifier != null)
			result = system.proxies.WorkflowUserTask.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_WorkflowUserTask
	 * @param grantsystem_workflowusertask
	 */
	public final void setGrantSystem_WorkflowUserTask(system.proxies.WorkflowUserTask grantsystem_workflowusertask)
	{
		setGrantSystem_WorkflowUserTask(getContext(), grantsystem_workflowusertask);
	}

	/**
	 * Set value of GrantSystem_WorkflowUserTask
	 * @param context
	 * @param grantsystem_workflowusertask
	 */
	public final void setGrantSystem_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTask grantsystem_workflowusertask)
	{
		if (grantsystem_workflowusertask == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowUserTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowUserTask.toString(), grantsystem_workflowusertask.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_AllWorkflowUserTask
	 */
	public final java.util.List<system.proxies.WorkflowUserTask> getGrantSystem_AllWorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getGrantSystem_AllWorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_AllWorkflowUserTask
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.WorkflowUserTask> getGrantSystem_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.WorkflowUserTask> result = new java.util.ArrayList<system.proxies.WorkflowUserTask>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GrantSystem_AllWorkflowUserTask.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(system.proxies.WorkflowUserTask.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GrantSystem_AllWorkflowUserTask
	 * @param grantsystem_allworkflowusertask
	 */
	public final void setGrantSystem_AllWorkflowUserTask(java.util.List<system.proxies.WorkflowUserTask> grantsystem_allworkflowusertask)
	{
		setGrantSystem_AllWorkflowUserTask(getContext(), grantsystem_allworkflowusertask);
	}

	/**
	 * Set value of GrantSystem_AllWorkflowUserTask
	 * @param context
	 * @param grantsystem_allworkflowusertask
	 */
	public final void setGrantSystem_AllWorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.WorkflowUserTask> grantsystem_allworkflowusertask)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (system.proxies.WorkflowUserTask proxyObject : grantsystem_allworkflowusertask)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GrantSystem_AllWorkflowUserTask.toString(), identifiers);
	}

	/**
	 * @return value of GrantSystem_EmailTemplate
	 */
	public final emailtemplate.proxies.EmailTemplate getGrantSystem_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getGrantSystem_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_EmailTemplate
	 */
	public final emailtemplate.proxies.EmailTemplate getGrantSystem_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_EmailTemplate.toString());
		if (identifier != null)
			result = emailtemplate.proxies.EmailTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_EmailTemplate
	 * @param grantsystem_emailtemplate
	 */
	public final void setGrantSystem_EmailTemplate(emailtemplate.proxies.EmailTemplate grantsystem_emailtemplate)
	{
		setGrantSystem_EmailTemplate(getContext(), grantsystem_emailtemplate);
	}

	/**
	 * Set value of GrantSystem_EmailTemplate
	 * @param context
	 * @param grantsystem_emailtemplate
	 */
	public final void setGrantSystem_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailTemplate grantsystem_emailtemplate)
	{
		if (grantsystem_emailtemplate == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_EmailTemplate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_EmailTemplate.toString(), grantsystem_emailtemplate.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_AllAccounts
	 */
	public final java.util.List<administration.proxies.Account> getGrantSystem_AllAccounts() throws com.mendix.core.CoreException
	{
		return getGrantSystem_AllAccounts(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_AllAccounts
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<administration.proxies.Account> getGrantSystem_AllAccounts(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<administration.proxies.Account>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GrantSystem_AllAccounts.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(administration.proxies.Account.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GrantSystem_AllAccounts
	 * @param grantsystem_allaccounts
	 */
	public final void setGrantSystem_AllAccounts(java.util.List<administration.proxies.Account> grantsystem_allaccounts)
	{
		setGrantSystem_AllAccounts(getContext(), grantsystem_allaccounts);
	}

	/**
	 * Set value of GrantSystem_AllAccounts
	 * @param context
	 * @param grantsystem_allaccounts
	 */
	public final void setGrantSystem_AllAccounts(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<administration.proxies.Account> grantsystem_allaccounts)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (administration.proxies.Account proxyObject : grantsystem_allaccounts)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GrantSystem_AllAccounts.toString(), identifiers);
	}

	/**
	 * @return value of GrantSystem_CurrentHoldingAccount
	 */
	public final java.util.List<administration.proxies.Account> getGrantSystem_CurrentHoldingAccount() throws com.mendix.core.CoreException
	{
		return getGrantSystem_CurrentHoldingAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_CurrentHoldingAccount
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<administration.proxies.Account> getGrantSystem_CurrentHoldingAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<administration.proxies.Account>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GrantSystem_CurrentHoldingAccount.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(administration.proxies.Account.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GrantSystem_CurrentHoldingAccount
	 * @param grantsystem_currentholdingaccount
	 */
	public final void setGrantSystem_CurrentHoldingAccount(java.util.List<administration.proxies.Account> grantsystem_currentholdingaccount)
	{
		setGrantSystem_CurrentHoldingAccount(getContext(), grantsystem_currentholdingaccount);
	}

	/**
	 * Set value of GrantSystem_CurrentHoldingAccount
	 * @param context
	 * @param grantsystem_currentholdingaccount
	 */
	public final void setGrantSystem_CurrentHoldingAccount(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<administration.proxies.Account> grantsystem_currentholdingaccount)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (administration.proxies.Account proxyObject : grantsystem_currentholdingaccount)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GrantSystem_CurrentHoldingAccount.toString(), identifiers);
	}

	/**
	 * @return value of GrantSystem_ApplicantAccount
	 */
	public final administration.proxies.Account getGrantSystem_ApplicantAccount() throws com.mendix.core.CoreException
	{
		return getGrantSystem_ApplicantAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_ApplicantAccount
	 */
	public final administration.proxies.Account getGrantSystem_ApplicantAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_ApplicantAccount.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_ApplicantAccount
	 * @param grantsystem_applicantaccount
	 */
	public final void setGrantSystem_ApplicantAccount(administration.proxies.Account grantsystem_applicantaccount)
	{
		setGrantSystem_ApplicantAccount(getContext(), grantsystem_applicantaccount);
	}

	/**
	 * Set value of GrantSystem_ApplicantAccount
	 * @param context
	 * @param grantsystem_applicantaccount
	 */
	public final void setGrantSystem_ApplicantAccount(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account grantsystem_applicantaccount)
	{
		if (grantsystem_applicantaccount == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_ApplicantAccount.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_ApplicantAccount.toString(), grantsystem_applicantaccount.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_WorkflowRolesDummy
	 */
	public final dynamicform.proxies.WorkflowRoles getGrantSystem_WorkflowRolesDummy() throws com.mendix.core.CoreException
	{
		return getGrantSystem_WorkflowRolesDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_WorkflowRolesDummy
	 */
	public final dynamicform.proxies.WorkflowRoles getGrantSystem_WorkflowRolesDummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.WorkflowRoles result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString());
		if (identifier != null)
			result = dynamicform.proxies.WorkflowRoles.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_WorkflowRolesDummy
	 * @param grantsystem_workflowrolesdummy
	 */
	public final void setGrantSystem_WorkflowRolesDummy(dynamicform.proxies.WorkflowRoles grantsystem_workflowrolesdummy)
	{
		setGrantSystem_WorkflowRolesDummy(getContext(), grantsystem_workflowrolesdummy);
	}

	/**
	 * Set value of GrantSystem_WorkflowRolesDummy
	 * @param context
	 * @param grantsystem_workflowrolesdummy
	 */
	public final void setGrantSystem_WorkflowRolesDummy(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.WorkflowRoles grantsystem_workflowrolesdummy)
	{
		if (grantsystem_workflowrolesdummy == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_WorkflowRolesDummy.toString(), grantsystem_workflowrolesdummy.getMendixObject().getId());
	}

	/**
	 * @return value of GrantSystem_TemplateDummy
	 */
	public final dynamicform.proxies.Template getGrantSystem_TemplateDummy() throws com.mendix.core.CoreException
	{
		return getGrantSystem_TemplateDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_TemplateDummy
	 */
	public final dynamicform.proxies.Template getGrantSystem_TemplateDummy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_TemplateDummy.toString());
		if (identifier != null)
			result = dynamicform.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_TemplateDummy
	 * @param grantsystem_templatedummy
	 */
	public final void setGrantSystem_TemplateDummy(dynamicform.proxies.Template grantsystem_templatedummy)
	{
		setGrantSystem_TemplateDummy(getContext(), grantsystem_templatedummy);
	}

	/**
	 * Set value of GrantSystem_TemplateDummy
	 * @param context
	 * @param grantsystem_templatedummy
	 */
	public final void setGrantSystem_TemplateDummy(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Template grantsystem_templatedummy)
	{
		if (grantsystem_templatedummy == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_TemplateDummy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_TemplateDummy.toString(), grantsystem_templatedummy.getMendixObject().getId());
	}

	/**
	 * @return value of ApplicationForm_GrantSystem
	 */
	public final dynamicform.proxies.ApplicationForm getApplicationForm_GrantSystem() throws com.mendix.core.CoreException
	{
		return getApplicationForm_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationForm_GrantSystem
	 */
	public final dynamicform.proxies.ApplicationForm getApplicationForm_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.ApplicationForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApplicationForm_GrantSystem.toString());
		if (identifier != null)
			result = dynamicform.proxies.ApplicationForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ApplicationForm_GrantSystem
	 * @param applicationform_grantsystem
	 */
	public final void setApplicationForm_GrantSystem(dynamicform.proxies.ApplicationForm applicationform_grantsystem)
	{
		setApplicationForm_GrantSystem(getContext(), applicationform_grantsystem);
	}

	/**
	 * Set value of ApplicationForm_GrantSystem
	 * @param context
	 * @param applicationform_grantsystem
	 */
	public final void setApplicationForm_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.ApplicationForm applicationform_grantsystem)
	{
		if (applicationform_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.ApplicationForm_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ApplicationForm_GrantSystem.toString(), applicationform_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.GrantSystem that = (ugs.proxies.GrantSystem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.GrantSystem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
