// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Grant_
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject grant_MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Grant_";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GrantName("GrantName"),
		GrantID("GrantID"),
		ApplicantName("ApplicantName"),
		Status("Status"),
		ClosedDate("ClosedDate"),
		Summary("Summary"),
		Nationality("Nationality"),
		Gender("Gender"),
		DataTable("DataTable"),
		Xpath("Xpath");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Grant_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Grant_"));
	}

	protected Grant_(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject grant_MendixObject)
	{
		if (grant_MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Grant_", grant_MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Grant_");

		this.grant_MendixObject = grant_MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Grant_.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Grant_ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Grant_.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Grant_ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Grant_(context, mendixObject);
	}

	public static ugs.proxies.Grant_ load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Grant_.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Grant_> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Grant_> result = new java.util.ArrayList<ugs.proxies.Grant_>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Grant_" + xpathConstraint))
			result.add(ugs.proxies.Grant_.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName()
	{
		return getGrantName(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GrantName.toString());
	}

	/**
	 * Set value of GrantName
	 * @param grantname
	 */
	public final void setGrantName(java.lang.String grantname)
	{
		setGrantName(getContext(), grantname);
	}

	/**
	 * Set value of GrantName
	 * @param context
	 * @param grantname
	 */
	public final void setGrantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grantname)
	{
		getMendixObject().setValue(context, MemberNames.GrantName.toString(), grantname);
	}

	/**
	 * @return value of GrantID
	 */
	public final java.lang.Integer getGrantID()
	{
		return getGrantID(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantID
	 */
	public final java.lang.Integer getGrantID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.GrantID.toString());
	}

	/**
	 * Set value of GrantID
	 * @param grantid
	 */
	public final void setGrantID(java.lang.Integer grantid)
	{
		setGrantID(getContext(), grantid);
	}

	/**
	 * Set value of GrantID
	 * @param context
	 * @param grantid
	 */
	public final void setGrantID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer grantid)
	{
		getMendixObject().setValue(context, MemberNames.GrantID.toString(), grantid);
	}

	/**
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName()
	{
		return getApplicantName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicantName.toString());
	}

	/**
	 * Set value of ApplicantName
	 * @param applicantname
	 */
	public final void setApplicantName(java.lang.String applicantname)
	{
		setApplicantName(getContext(), applicantname);
	}

	/**
	 * Set value of ApplicantName
	 * @param context
	 * @param applicantname
	 */
	public final void setApplicantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicantname)
	{
		getMendixObject().setValue(context, MemberNames.ApplicantName.toString(), applicantname);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of ClosedDate
	 */
	public final java.util.Date getClosedDate()
	{
		return getClosedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ClosedDate
	 */
	public final java.util.Date getClosedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ClosedDate.toString());
	}

	/**
	 * Set value of ClosedDate
	 * @param closeddate
	 */
	public final void setClosedDate(java.util.Date closeddate)
	{
		setClosedDate(getContext(), closeddate);
	}

	/**
	 * Set value of ClosedDate
	 * @param context
	 * @param closeddate
	 */
	public final void setClosedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date closeddate)
	{
		getMendixObject().setValue(context, MemberNames.ClosedDate.toString(), closeddate);
	}

	/**
	 * @return value of Summary
	 */
	public final java.lang.String getSummary()
	{
		return getSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of Summary
	 */
	public final java.lang.String getSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Summary.toString());
	}

	/**
	 * Set value of Summary
	 * @param summary
	 */
	public final void setSummary(java.lang.String summary)
	{
		setSummary(getContext(), summary);
	}

	/**
	 * Set value of Summary
	 * @param context
	 * @param summary
	 */
	public final void setSummary(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String summary)
	{
		getMendixObject().setValue(context, MemberNames.Summary.toString(), summary);
	}

	/**
	 * @return value of Nationality
	 */
	public final java.lang.String getNationality()
	{
		return getNationality(getContext());
	}

	/**
	 * @param context
	 * @return value of Nationality
	 */
	public final java.lang.String getNationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nationality.toString());
	}

	/**
	 * Set value of Nationality
	 * @param nationality
	 */
	public final void setNationality(java.lang.String nationality)
	{
		setNationality(getContext(), nationality);
	}

	/**
	 * Set value of Nationality
	 * @param context
	 * @param nationality
	 */
	public final void setNationality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nationality)
	{
		getMendixObject().setValue(context, MemberNames.Nationality.toString(), nationality);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final ugs.proxies.Enum_Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final ugs.proxies.Enum_Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(ugs.proxies.Enum_Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_Gender gender)
	{
		if (gender != null)
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		else
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
	}

	/**
	 * @return value of DataTable
	 */
	public final java.lang.Boolean getDataTable()
	{
		return getDataTable(getContext());
	}

	/**
	 * @param context
	 * @return value of DataTable
	 */
	public final java.lang.Boolean getDataTable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DataTable.toString());
	}

	/**
	 * Set value of DataTable
	 * @param datatable
	 */
	public final void setDataTable(java.lang.Boolean datatable)
	{
		setDataTable(getContext(), datatable);
	}

	/**
	 * Set value of DataTable
	 * @param context
	 * @param datatable
	 */
	public final void setDataTable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean datatable)
	{
		getMendixObject().setValue(context, MemberNames.DataTable.toString(), datatable);
	}

	/**
	 * @return value of Xpath
	 */
	public final java.lang.String getXpath()
	{
		return getXpath(getContext());
	}

	/**
	 * @param context
	 * @return value of Xpath
	 */
	public final java.lang.String getXpath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Xpath.toString());
	}

	/**
	 * Set value of Xpath
	 * @param xpath
	 */
	public final void setXpath(java.lang.String xpath)
	{
		setXpath(getContext(), xpath);
	}

	/**
	 * Set value of Xpath
	 * @param context
	 * @param xpath
	 */
	public final void setXpath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpath)
	{
		getMendixObject().setValue(context, MemberNames.Xpath.toString(), xpath);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return grant_MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Grant_ that = (ugs.proxies.Grant_) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Grant_";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
