// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Header_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject header_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Header_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Header("Header"),
		Selected("Selected"),
		GrantSystem_Header_2("UGS.GrantSystem_Header_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Header_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Header_2"));
	}

	protected Header_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject header_2MendixObject)
	{
		if (header_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Header_2", header_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Header_2");

		this.header_2MendixObject = header_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Header_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Header_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Header_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Header_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Header_2(context, mendixObject);
	}

	public static ugs.proxies.Header_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Header_2.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Header_2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Header_2> result = new java.util.ArrayList<ugs.proxies.Header_2>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Header_2" + xpathConstraint))
			result.add(ugs.proxies.Header_2.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Header
	 */
	public final java.lang.String getHeader()
	{
		return getHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Header
	 */
	public final java.lang.String getHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header.toString());
	}

	/**
	 * Set value of Header
	 * @param header
	 */
	public final void setHeader(java.lang.String header)
	{
		setHeader(getContext(), header);
	}

	/**
	 * Set value of Header
	 * @param context
	 * @param header
	 */
	public final void setHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header)
	{
		getMendixObject().setValue(context, MemberNames.Header.toString(), header);
	}

	/**
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected()
	{
		return getSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Selected.toString());
	}

	/**
	 * Set value of Selected
	 * @param selected
	 */
	public final void setSelected(java.lang.Boolean selected)
	{
		setSelected(getContext(), selected);
	}

	/**
	 * Set value of Selected
	 * @param context
	 * @param selected
	 */
	public final void setSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selected)
	{
		getMendixObject().setValue(context, MemberNames.Selected.toString(), selected);
	}

	/**
	 * @return value of GrantSystem_Header_2
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_Header_2() throws com.mendix.core.CoreException
	{
		return getGrantSystem_Header_2(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_Header_2
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_Header_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_Header_2.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_Header_2
	 * @param grantsystem_header_2
	 */
	public final void setGrantSystem_Header_2(ugs.proxies.GrantSystem grantsystem_header_2)
	{
		setGrantSystem_Header_2(getContext(), grantsystem_header_2);
	}

	/**
	 * Set value of GrantSystem_Header_2
	 * @param context
	 * @param grantsystem_header_2
	 */
	public final void setGrantSystem_Header_2(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem grantsystem_header_2)
	{
		if (grantsystem_header_2 == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_Header_2.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_Header_2.toString(), grantsystem_header_2.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return header_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Header_2 that = (ugs.proxies.Header_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Header_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
