// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class History
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.History";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sender("Sender"),
		Reciever("Reciever"),
		RecievedDate("RecievedDate"),
		ProcessedDate("ProcessedDate"),
		Status("Status"),
		SLA_Timetaken("SLA_Timetaken"),
		SLA_Deadline("SLA_Deadline"),
		SLA_Complaince("SLA_Complaince"),
		Reference_No("Reference_No"),
		status1("status1"),
		Review("Review"),
		Rfund_B("Rfund_B"),
		Frequency("Frequency"),
		CurrentUser_("CurrentUser_"),
		History_GrantSystem("UGS.History_GrantSystem"),
		Review_History("UGS.Review_History");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public History(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.History"));
	}

	protected History(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject)
	{
		if (historyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.History", historyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.History");

		this.historyMendixObject = historyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'History.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.History.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.History(context, mendixObject);
	}

	public static ugs.proxies.History load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.History.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.History> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.History> result = new java.util.ArrayList<ugs.proxies.History>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.History" + xpathConstraint))
			result.add(ugs.proxies.History.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sender
	 */
	public final java.lang.String getSender()
	{
		return getSender(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender
	 */
	public final java.lang.String getSender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sender.toString());
	}

	/**
	 * Set value of Sender
	 * @param sender
	 */
	public final void setSender(java.lang.String sender)
	{
		setSender(getContext(), sender);
	}

	/**
	 * Set value of Sender
	 * @param context
	 * @param sender
	 */
	public final void setSender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sender)
	{
		getMendixObject().setValue(context, MemberNames.Sender.toString(), sender);
	}

	/**
	 * @return value of Reciever
	 */
	public final java.lang.String getReciever()
	{
		return getReciever(getContext());
	}

	/**
	 * @param context
	 * @return value of Reciever
	 */
	public final java.lang.String getReciever(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reciever.toString());
	}

	/**
	 * Set value of Reciever
	 * @param reciever
	 */
	public final void setReciever(java.lang.String reciever)
	{
		setReciever(getContext(), reciever);
	}

	/**
	 * Set value of Reciever
	 * @param context
	 * @param reciever
	 */
	public final void setReciever(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reciever)
	{
		getMendixObject().setValue(context, MemberNames.Reciever.toString(), reciever);
	}

	/**
	 * @return value of RecievedDate
	 */
	public final java.util.Date getRecievedDate()
	{
		return getRecievedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RecievedDate
	 */
	public final java.util.Date getRecievedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RecievedDate.toString());
	}

	/**
	 * Set value of RecievedDate
	 * @param recieveddate
	 */
	public final void setRecievedDate(java.util.Date recieveddate)
	{
		setRecievedDate(getContext(), recieveddate);
	}

	/**
	 * Set value of RecievedDate
	 * @param context
	 * @param recieveddate
	 */
	public final void setRecievedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date recieveddate)
	{
		getMendixObject().setValue(context, MemberNames.RecievedDate.toString(), recieveddate);
	}

	/**
	 * @return value of ProcessedDate
	 */
	public final java.util.Date getProcessedDate()
	{
		return getProcessedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessedDate
	 */
	public final java.util.Date getProcessedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProcessedDate.toString());
	}

	/**
	 * Set value of ProcessedDate
	 * @param processeddate
	 */
	public final void setProcessedDate(java.util.Date processeddate)
	{
		setProcessedDate(getContext(), processeddate);
	}

	/**
	 * Set value of ProcessedDate
	 * @param context
	 * @param processeddate
	 */
	public final void setProcessedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date processeddate)
	{
		getMendixObject().setValue(context, MemberNames.ProcessedDate.toString(), processeddate);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final ugs.proxies.Enum_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final ugs.proxies.Enum_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(ugs.proxies.Enum_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of SLA_Timetaken
	 */
	public final java.lang.String getSLA_Timetaken()
	{
		return getSLA_Timetaken(getContext());
	}

	/**
	 * @param context
	 * @return value of SLA_Timetaken
	 */
	public final java.lang.String getSLA_Timetaken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SLA_Timetaken.toString());
	}

	/**
	 * Set value of SLA_Timetaken
	 * @param sla_timetaken
	 */
	public final void setSLA_Timetaken(java.lang.String sla_timetaken)
	{
		setSLA_Timetaken(getContext(), sla_timetaken);
	}

	/**
	 * Set value of SLA_Timetaken
	 * @param context
	 * @param sla_timetaken
	 */
	public final void setSLA_Timetaken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sla_timetaken)
	{
		getMendixObject().setValue(context, MemberNames.SLA_Timetaken.toString(), sla_timetaken);
	}

	/**
	 * @return value of SLA_Deadline
	 */
	public final java.util.Date getSLA_Deadline()
	{
		return getSLA_Deadline(getContext());
	}

	/**
	 * @param context
	 * @return value of SLA_Deadline
	 */
	public final java.util.Date getSLA_Deadline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SLA_Deadline.toString());
	}

	/**
	 * Set value of SLA_Deadline
	 * @param sla_deadline
	 */
	public final void setSLA_Deadline(java.util.Date sla_deadline)
	{
		setSLA_Deadline(getContext(), sla_deadline);
	}

	/**
	 * Set value of SLA_Deadline
	 * @param context
	 * @param sla_deadline
	 */
	public final void setSLA_Deadline(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sla_deadline)
	{
		getMendixObject().setValue(context, MemberNames.SLA_Deadline.toString(), sla_deadline);
	}

	/**
	 * Set value of SLA_Complaince
	 * @param sla_complaince
	 */
	public final ugs.proxies.Enum_SLA_Status getSLA_Complaince()
	{
		return getSLA_Complaince(getContext());
	}

	/**
	 * @param context
	 * @return value of SLA_Complaince
	 */
	public final ugs.proxies.Enum_SLA_Status getSLA_Complaince(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SLA_Complaince.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_SLA_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SLA_Complaince
	 * @param sla_complaince
	 */
	public final void setSLA_Complaince(ugs.proxies.Enum_SLA_Status sla_complaince)
	{
		setSLA_Complaince(getContext(), sla_complaince);
	}

	/**
	 * Set value of SLA_Complaince
	 * @param context
	 * @param sla_complaince
	 */
	public final void setSLA_Complaince(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_SLA_Status sla_complaince)
	{
		if (sla_complaince != null)
			getMendixObject().setValue(context, MemberNames.SLA_Complaince.toString(), sla_complaince.toString());
		else
			getMendixObject().setValue(context, MemberNames.SLA_Complaince.toString(), null);
	}

	/**
	 * @return value of Reference_No
	 */
	public final java.lang.Integer getReference_No()
	{
		return getReference_No(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference_No
	 */
	public final java.lang.Integer getReference_No(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Reference_No.toString());
	}

	/**
	 * Set value of Reference_No
	 * @param reference_no
	 */
	public final void setReference_No(java.lang.Integer reference_no)
	{
		setReference_No(getContext(), reference_no);
	}

	/**
	 * Set value of Reference_No
	 * @param context
	 * @param reference_no
	 */
	public final void setReference_No(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer reference_no)
	{
		getMendixObject().setValue(context, MemberNames.Reference_No.toString(), reference_no);
	}

	/**
	 * @return value of status1
	 */
	public final java.lang.String getstatus1()
	{
		return getstatus1(getContext());
	}

	/**
	 * @param context
	 * @return value of status1
	 */
	public final java.lang.String getstatus1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.status1.toString());
	}

	/**
	 * Set value of status1
	 * @param status1
	 */
	public final void setstatus1(java.lang.String status1)
	{
		setstatus1(getContext(), status1);
	}

	/**
	 * Set value of status1
	 * @param context
	 * @param status1
	 */
	public final void setstatus1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status1)
	{
		getMendixObject().setValue(context, MemberNames.status1.toString(), status1);
	}

	/**
	 * @return value of Review
	 */
	public final java.lang.Boolean getReview()
	{
		return getReview(getContext());
	}

	/**
	 * @param context
	 * @return value of Review
	 */
	public final java.lang.Boolean getReview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Review.toString());
	}

	/**
	 * Set value of Review
	 * @param review
	 */
	public final void setReview(java.lang.Boolean review)
	{
		setReview(getContext(), review);
	}

	/**
	 * Set value of Review
	 * @param context
	 * @param review
	 */
	public final void setReview(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean review)
	{
		getMendixObject().setValue(context, MemberNames.Review.toString(), review);
	}

	/**
	 * @return value of Rfund_B
	 */
	public final java.lang.Boolean getRfund_B()
	{
		return getRfund_B(getContext());
	}

	/**
	 * @param context
	 * @return value of Rfund_B
	 */
	public final java.lang.Boolean getRfund_B(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Rfund_B.toString());
	}

	/**
	 * Set value of Rfund_B
	 * @param rfund_b
	 */
	public final void setRfund_B(java.lang.Boolean rfund_b)
	{
		setRfund_B(getContext(), rfund_b);
	}

	/**
	 * Set value of Rfund_B
	 * @param context
	 * @param rfund_b
	 */
	public final void setRfund_B(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean rfund_b)
	{
		getMendixObject().setValue(context, MemberNames.Rfund_B.toString(), rfund_b);
	}

	/**
	 * @return value of Frequency
	 */
	public final java.lang.Integer getFrequency()
	{
		return getFrequency(getContext());
	}

	/**
	 * @param context
	 * @return value of Frequency
	 */
	public final java.lang.Integer getFrequency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Frequency.toString());
	}

	/**
	 * Set value of Frequency
	 * @param frequency
	 */
	public final void setFrequency(java.lang.Integer frequency)
	{
		setFrequency(getContext(), frequency);
	}

	/**
	 * Set value of Frequency
	 * @param context
	 * @param frequency
	 */
	public final void setFrequency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer frequency)
	{
		getMendixObject().setValue(context, MemberNames.Frequency.toString(), frequency);
	}

	/**
	 * @return value of CurrentUser_
	 */
	public final java.lang.String getCurrentUser_()
	{
		return getCurrentUser_(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentUser_
	 */
	public final java.lang.String getCurrentUser_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentUser_.toString());
	}

	/**
	 * Set value of CurrentUser_
	 * @param currentuser_
	 */
	public final void setCurrentUser_(java.lang.String currentuser_)
	{
		setCurrentUser_(getContext(), currentuser_);
	}

	/**
	 * Set value of CurrentUser_
	 * @param context
	 * @param currentuser_
	 */
	public final void setCurrentUser_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentuser_)
	{
		getMendixObject().setValue(context, MemberNames.CurrentUser_.toString(), currentuser_);
	}

	/**
	 * @return value of History_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getHistory_GrantSystem() throws com.mendix.core.CoreException
	{
		return getHistory_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of History_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getHistory_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of History_GrantSystem
	 * @param history_grantsystem
	 */
	public final void setHistory_GrantSystem(ugs.proxies.GrantSystem history_grantsystem)
	{
		setHistory_GrantSystem(getContext(), history_grantsystem);
	}

	/**
	 * Set value of History_GrantSystem
	 * @param context
	 * @param history_grantsystem
	 */
	public final void setHistory_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem history_grantsystem)
	{
		if (history_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.History_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.History_GrantSystem.toString(), history_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of Review_History
	 */
	public final ugs.proxies.GrantSystem getReview_History() throws com.mendix.core.CoreException
	{
		return getReview_History(getContext());
	}

	/**
	 * @param context
	 * @return value of Review_History
	 */
	public final ugs.proxies.GrantSystem getReview_History(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Review_History.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Review_History
	 * @param review_history
	 */
	public final void setReview_History(ugs.proxies.GrantSystem review_history)
	{
		setReview_History(getContext(), review_history);
	}

	/**
	 * Set value of Review_History
	 * @param context
	 * @param review_history
	 */
	public final void setReview_History(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem review_history)
	{
		if (review_history == null)
			getMendixObject().setValue(context, MemberNames.Review_History.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Review_History.toString(), review_history.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return historyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.History that = (ugs.proxies.History) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.History";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
