// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Marks
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject marksMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Marks";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		Discription("Discription"),
		Marks_ProgressUpdate("UGS.Marks_ProgressUpdate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Marks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Marks"));
	}

	protected Marks(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject marksMendixObject)
	{
		if (marksMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.Marks", marksMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Marks");

		this.marksMendixObject = marksMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Marks.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Marks initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Marks.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Marks initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Marks(context, mendixObject);
	}

	public static ugs.proxies.Marks load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Marks.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Marks> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Marks> result = new java.util.ArrayList<ugs.proxies.Marks>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Marks" + xpathConstraint))
			result.add(ugs.proxies.Marks.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of Discription
	 */
	public final java.lang.String getDiscription()
	{
		return getDiscription(getContext());
	}

	/**
	 * @param context
	 * @return value of Discription
	 */
	public final java.lang.String getDiscription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Discription.toString());
	}

	/**
	 * Set value of Discription
	 * @param discription
	 */
	public final void setDiscription(java.lang.String discription)
	{
		setDiscription(getContext(), discription);
	}

	/**
	 * Set value of Discription
	 * @param context
	 * @param discription
	 */
	public final void setDiscription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String discription)
	{
		getMendixObject().setValue(context, MemberNames.Discription.toString(), discription);
	}

	/**
	 * @return value of Marks_ProgressUpdate
	 */
	public final ugs.proxies.ProgressUpdate getMarks_ProgressUpdate() throws com.mendix.core.CoreException
	{
		return getMarks_ProgressUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of Marks_ProgressUpdate
	 */
	public final ugs.proxies.ProgressUpdate getMarks_ProgressUpdate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.ProgressUpdate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Marks_ProgressUpdate.toString());
		if (identifier != null)
			result = ugs.proxies.ProgressUpdate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Marks_ProgressUpdate
	 * @param marks_progressupdate
	 */
	public final void setMarks_ProgressUpdate(ugs.proxies.ProgressUpdate marks_progressupdate)
	{
		setMarks_ProgressUpdate(getContext(), marks_progressupdate);
	}

	/**
	 * Set value of Marks_ProgressUpdate
	 * @param context
	 * @param marks_progressupdate
	 */
	public final void setMarks_ProgressUpdate(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.ProgressUpdate marks_progressupdate)
	{
		if (marks_progressupdate == null)
			getMendixObject().setValue(context, MemberNames.Marks_ProgressUpdate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Marks_ProgressUpdate.toString(), marks_progressupdate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return marksMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Marks that = (ugs.proxies.Marks) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Marks";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
