// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class PowerBI_Tokens
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject powerBI_TokensMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.PowerBI_Tokens";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GroupId("GroupId"),
		ReportId("ReportId"),
		EmbedUrl("EmbedUrl"),
		AccessToken("AccessToken"),
		RefNo("RefNo"),
		DataSetId("DataSetId"),
		EmbedToken("EmbedToken");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PowerBI_Tokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.PowerBI_Tokens"));
	}

	protected PowerBI_Tokens(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject powerBI_TokensMendixObject)
	{
		if (powerBI_TokensMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.PowerBI_Tokens", powerBI_TokensMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.PowerBI_Tokens");

		this.powerBI_TokensMendixObject = powerBI_TokensMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PowerBI_Tokens.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.PowerBI_Tokens initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.PowerBI_Tokens.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.PowerBI_Tokens initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.PowerBI_Tokens(context, mendixObject);
	}

	public static ugs.proxies.PowerBI_Tokens load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.PowerBI_Tokens.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.PowerBI_Tokens> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.PowerBI_Tokens> result = new java.util.ArrayList<ugs.proxies.PowerBI_Tokens>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.PowerBI_Tokens" + xpathConstraint))
			result.add(ugs.proxies.PowerBI_Tokens.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GroupId
	 */
	public final java.lang.String getGroupId()
	{
		return getGroupId(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupId
	 */
	public final java.lang.String getGroupId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GroupId.toString());
	}

	/**
	 * Set value of GroupId
	 * @param groupid
	 */
	public final void setGroupId(java.lang.String groupid)
	{
		setGroupId(getContext(), groupid);
	}

	/**
	 * Set value of GroupId
	 * @param context
	 * @param groupid
	 */
	public final void setGroupId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupid)
	{
		getMendixObject().setValue(context, MemberNames.GroupId.toString(), groupid);
	}

	/**
	 * @return value of ReportId
	 */
	public final java.lang.String getReportId()
	{
		return getReportId(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportId
	 */
	public final java.lang.String getReportId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReportId.toString());
	}

	/**
	 * Set value of ReportId
	 * @param reportid
	 */
	public final void setReportId(java.lang.String reportid)
	{
		setReportId(getContext(), reportid);
	}

	/**
	 * Set value of ReportId
	 * @param context
	 * @param reportid
	 */
	public final void setReportId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reportid)
	{
		getMendixObject().setValue(context, MemberNames.ReportId.toString(), reportid);
	}

	/**
	 * @return value of EmbedUrl
	 */
	public final java.lang.String getEmbedUrl()
	{
		return getEmbedUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbedUrl
	 */
	public final java.lang.String getEmbedUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmbedUrl.toString());
	}

	/**
	 * Set value of EmbedUrl
	 * @param embedurl
	 */
	public final void setEmbedUrl(java.lang.String embedurl)
	{
		setEmbedUrl(getContext(), embedurl);
	}

	/**
	 * Set value of EmbedUrl
	 * @param context
	 * @param embedurl
	 */
	public final void setEmbedUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String embedurl)
	{
		getMendixObject().setValue(context, MemberNames.EmbedUrl.toString(), embedurl);
	}

	/**
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken()
	{
		return getAccessToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessToken.toString());
	}

	/**
	 * Set value of AccessToken
	 * @param accesstoken
	 */
	public final void setAccessToken(java.lang.String accesstoken)
	{
		setAccessToken(getContext(), accesstoken);
	}

	/**
	 * Set value of AccessToken
	 * @param context
	 * @param accesstoken
	 */
	public final void setAccessToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesstoken)
	{
		getMendixObject().setValue(context, MemberNames.AccessToken.toString(), accesstoken);
	}

	/**
	 * @return value of RefNo
	 */
	public final java.lang.String getRefNo()
	{
		return getRefNo(getContext());
	}

	/**
	 * @param context
	 * @return value of RefNo
	 */
	public final java.lang.String getRefNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefNo.toString());
	}

	/**
	 * Set value of RefNo
	 * @param refno
	 */
	public final void setRefNo(java.lang.String refno)
	{
		setRefNo(getContext(), refno);
	}

	/**
	 * Set value of RefNo
	 * @param context
	 * @param refno
	 */
	public final void setRefNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refno)
	{
		getMendixObject().setValue(context, MemberNames.RefNo.toString(), refno);
	}

	/**
	 * @return value of DataSetId
	 */
	public final java.lang.String getDataSetId()
	{
		return getDataSetId(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSetId
	 */
	public final java.lang.String getDataSetId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSetId.toString());
	}

	/**
	 * Set value of DataSetId
	 * @param datasetid
	 */
	public final void setDataSetId(java.lang.String datasetid)
	{
		setDataSetId(getContext(), datasetid);
	}

	/**
	 * Set value of DataSetId
	 * @param context
	 * @param datasetid
	 */
	public final void setDataSetId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasetid)
	{
		getMendixObject().setValue(context, MemberNames.DataSetId.toString(), datasetid);
	}

	/**
	 * @return value of EmbedToken
	 */
	public final java.lang.String getEmbedToken()
	{
		return getEmbedToken(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbedToken
	 */
	public final java.lang.String getEmbedToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmbedToken.toString());
	}

	/**
	 * Set value of EmbedToken
	 * @param embedtoken
	 */
	public final void setEmbedToken(java.lang.String embedtoken)
	{
		setEmbedToken(getContext(), embedtoken);
	}

	/**
	 * Set value of EmbedToken
	 * @param context
	 * @param embedtoken
	 */
	public final void setEmbedToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String embedtoken)
	{
		getMendixObject().setValue(context, MemberNames.EmbedToken.toString(), embedtoken);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return powerBI_TokensMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.PowerBI_Tokens that = (ugs.proxies.PowerBI_Tokens) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.PowerBI_Tokens";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
