// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class ProgressUpdate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject progressUpdateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.ProgressUpdate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApplicantName("ApplicantName"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		Reference_No("Reference_No"),
		GrantName("GrantName"),
		Subject("Subject"),
		Remarks("Remarks"),
		Grade("Grade"),
		ProgressUpdate_GrantSystem("UGS.ProgressUpdate_GrantSystem"),
		ProgressUpdate_Account("UGS.ProgressUpdate_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProgressUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.ProgressUpdate"));
	}

	protected ProgressUpdate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject progressUpdateMendixObject)
	{
		if (progressUpdateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.ProgressUpdate", progressUpdateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.ProgressUpdate");

		this.progressUpdateMendixObject = progressUpdateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProgressUpdate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.ProgressUpdate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.ProgressUpdate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.ProgressUpdate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.ProgressUpdate(context, mendixObject);
	}

	public static ugs.proxies.ProgressUpdate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.ProgressUpdate.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.ProgressUpdate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.ProgressUpdate> result = new java.util.ArrayList<ugs.proxies.ProgressUpdate>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.ProgressUpdate" + xpathConstraint))
			result.add(ugs.proxies.ProgressUpdate.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName()
	{
		return getApplicantName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicantName
	 */
	public final java.lang.String getApplicantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicantName.toString());
	}

	/**
	 * Set value of ApplicantName
	 * @param applicantname
	 */
	public final void setApplicantName(java.lang.String applicantname)
	{
		setApplicantName(getContext(), applicantname);
	}

	/**
	 * Set value of ApplicantName
	 * @param context
	 * @param applicantname
	 */
	public final void setApplicantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicantname)
	{
		getMendixObject().setValue(context, MemberNames.ApplicantName.toString(), applicantname);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of Reference_No
	 */
	public final java.lang.Integer getReference_No()
	{
		return getReference_No(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference_No
	 */
	public final java.lang.Integer getReference_No(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Reference_No.toString());
	}

	/**
	 * Set value of Reference_No
	 * @param reference_no
	 */
	public final void setReference_No(java.lang.Integer reference_no)
	{
		setReference_No(getContext(), reference_no);
	}

	/**
	 * Set value of Reference_No
	 * @param context
	 * @param reference_no
	 */
	public final void setReference_No(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer reference_no)
	{
		getMendixObject().setValue(context, MemberNames.Reference_No.toString(), reference_no);
	}

	/**
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName()
	{
		return getGrantName(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantName
	 */
	public final java.lang.String getGrantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GrantName.toString());
	}

	/**
	 * Set value of GrantName
	 * @param grantname
	 */
	public final void setGrantName(java.lang.String grantname)
	{
		setGrantName(getContext(), grantname);
	}

	/**
	 * Set value of GrantName
	 * @param context
	 * @param grantname
	 */
	public final void setGrantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grantname)
	{
		getMendixObject().setValue(context, MemberNames.GrantName.toString(), grantname);
	}

	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks()
	{
		return getRemarks(getContext());
	}

	/**
	 * @param context
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Remarks.toString());
	}

	/**
	 * Set value of Remarks
	 * @param remarks
	 */
	public final void setRemarks(java.lang.String remarks)
	{
		setRemarks(getContext(), remarks);
	}

	/**
	 * Set value of Remarks
	 * @param context
	 * @param remarks
	 */
	public final void setRemarks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remarks)
	{
		getMendixObject().setValue(context, MemberNames.Remarks.toString(), remarks);
	}

	/**
	 * @return value of Grade
	 */
	public final java.lang.String getGrade()
	{
		return getGrade(getContext());
	}

	/**
	 * @param context
	 * @return value of Grade
	 */
	public final java.lang.String getGrade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Grade.toString());
	}

	/**
	 * Set value of Grade
	 * @param grade
	 */
	public final void setGrade(java.lang.String grade)
	{
		setGrade(getContext(), grade);
	}

	/**
	 * Set value of Grade
	 * @param context
	 * @param grade
	 */
	public final void setGrade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grade)
	{
		getMendixObject().setValue(context, MemberNames.Grade.toString(), grade);
	}

	/**
	 * @return value of ProgressUpdate_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getProgressUpdate_GrantSystem() throws com.mendix.core.CoreException
	{
		return getProgressUpdate_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgressUpdate_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getProgressUpdate_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProgressUpdate_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProgressUpdate_GrantSystem
	 * @param progressupdate_grantsystem
	 */
	public final void setProgressUpdate_GrantSystem(ugs.proxies.GrantSystem progressupdate_grantsystem)
	{
		setProgressUpdate_GrantSystem(getContext(), progressupdate_grantsystem);
	}

	/**
	 * Set value of ProgressUpdate_GrantSystem
	 * @param context
	 * @param progressupdate_grantsystem
	 */
	public final void setProgressUpdate_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem progressupdate_grantsystem)
	{
		if (progressupdate_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.ProgressUpdate_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProgressUpdate_GrantSystem.toString(), progressupdate_grantsystem.getMendixObject().getId());
	}

	/**
	 * @return value of ProgressUpdate_Account
	 */
	public final administration.proxies.Account getProgressUpdate_Account() throws com.mendix.core.CoreException
	{
		return getProgressUpdate_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgressUpdate_Account
	 */
	public final administration.proxies.Account getProgressUpdate_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProgressUpdate_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProgressUpdate_Account
	 * @param progressupdate_account
	 */
	public final void setProgressUpdate_Account(administration.proxies.Account progressupdate_account)
	{
		setProgressUpdate_Account(getContext(), progressupdate_account);
	}

	/**
	 * Set value of ProgressUpdate_Account
	 * @param context
	 * @param progressupdate_account
	 */
	public final void setProgressUpdate_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account progressupdate_account)
	{
		if (progressupdate_account == null)
			getMendixObject().setValue(context, MemberNames.ProgressUpdate_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProgressUpdate_Account.toString(), progressupdate_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return progressUpdateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.ProgressUpdate that = (ugs.proxies.ProgressUpdate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.ProgressUpdate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
