// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Provider extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Provider";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		FirstName("FirstName"),
		LastName("LastName"),
		AddressLine1("AddressLine1"),
		AddressLine2("AddressLine2"),
		City("City"),
		State("State"),
		Zip_Code("Zip_Code"),
		Country("Country"),
		Phone("Phone"),
		email("email"),
		Employeer("Employeer"),
		Relationship("Relationship"),
		status("status"),
		RequestedDate("RequestedDate"),
		CompletedDate("CompletedDate"),
		Content("Content"),
		Email_("Email_"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Provider_GrantSystem("UGS.Provider_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Provider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Provider"));
	}

	protected Provider(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject providerMendixObject)
	{
		super(context, providerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.Provider", providerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Provider");
	}

	/**
	 * @deprecated Use 'Provider.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Provider initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Provider.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Provider initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Provider(context, mendixObject);
	}

	public static ugs.proxies.Provider load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Provider.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Provider> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Provider> result = new java.util.ArrayList<ugs.proxies.Provider>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Provider" + xpathConstraint))
			result.add(ugs.proxies.Provider.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of AddressLine1
	 */
	public final java.lang.String getAddressLine1()
	{
		return getAddressLine1(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressLine1
	 */
	public final java.lang.String getAddressLine1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressLine1.toString());
	}

	/**
	 * Set value of AddressLine1
	 * @param addressline1
	 */
	public final void setAddressLine1(java.lang.String addressline1)
	{
		setAddressLine1(getContext(), addressline1);
	}

	/**
	 * Set value of AddressLine1
	 * @param context
	 * @param addressline1
	 */
	public final void setAddressLine1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addressline1)
	{
		getMendixObject().setValue(context, MemberNames.AddressLine1.toString(), addressline1);
	}

	/**
	 * @return value of AddressLine2
	 */
	public final java.lang.String getAddressLine2()
	{
		return getAddressLine2(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressLine2
	 */
	public final java.lang.String getAddressLine2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressLine2.toString());
	}

	/**
	 * Set value of AddressLine2
	 * @param addressline2
	 */
	public final void setAddressLine2(java.lang.String addressline2)
	{
		setAddressLine2(getContext(), addressline2);
	}

	/**
	 * Set value of AddressLine2
	 * @param context
	 * @param addressline2
	 */
	public final void setAddressLine2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addressline2)
	{
		getMendixObject().setValue(context, MemberNames.AddressLine2.toString(), addressline2);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Zip_Code
	 */
	public final java.lang.Integer getZip_Code()
	{
		return getZip_Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Zip_Code
	 */
	public final java.lang.Integer getZip_Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Zip_Code.toString());
	}

	/**
	 * Set value of Zip_Code
	 * @param zip_code
	 */
	public final void setZip_Code(java.lang.Integer zip_code)
	{
		setZip_Code(getContext(), zip_code);
	}

	/**
	 * Set value of Zip_Code
	 * @param context
	 * @param zip_code
	 */
	public final void setZip_Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer zip_code)
	{
		getMendixObject().setValue(context, MemberNames.Zip_Code.toString(), zip_code);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of Employeer
	 */
	public final java.lang.String getEmployeer()
	{
		return getEmployeer(getContext());
	}

	/**
	 * @param context
	 * @return value of Employeer
	 */
	public final java.lang.String getEmployeer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Employeer.toString());
	}

	/**
	 * Set value of Employeer
	 * @param employeer
	 */
	public final void setEmployeer(java.lang.String employeer)
	{
		setEmployeer(getContext(), employeer);
	}

	/**
	 * Set value of Employeer
	 * @param context
	 * @param employeer
	 */
	public final void setEmployeer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeer)
	{
		getMendixObject().setValue(context, MemberNames.Employeer.toString(), employeer);
	}

	/**
	 * @return value of Relationship
	 */
	public final java.lang.String getRelationship()
	{
		return getRelationship(getContext());
	}

	/**
	 * @param context
	 * @return value of Relationship
	 */
	public final java.lang.String getRelationship(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Relationship.toString());
	}

	/**
	 * Set value of Relationship
	 * @param relationship
	 */
	public final void setRelationship(java.lang.String relationship)
	{
		setRelationship(getContext(), relationship);
	}

	/**
	 * Set value of Relationship
	 * @param context
	 * @param relationship
	 */
	public final void setRelationship(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationship)
	{
		getMendixObject().setValue(context, MemberNames.Relationship.toString(), relationship);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final dynamicform.proxies.Enum_Template_Status getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final dynamicform.proxies.Enum_Template_Status getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.status.toString());
		if (obj == null)
			return null;

		return dynamicform.proxies.Enum_Template_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(dynamicform.proxies.Enum_Template_Status status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Enum_Template_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.status.toString(), null);
	}

	/**
	 * @return value of RequestedDate
	 */
	public final java.util.Date getRequestedDate()
	{
		return getRequestedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestedDate
	 */
	public final java.util.Date getRequestedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestedDate.toString());
	}

	/**
	 * Set value of RequestedDate
	 * @param requesteddate
	 */
	public final void setRequestedDate(java.util.Date requesteddate)
	{
		setRequestedDate(getContext(), requesteddate);
	}

	/**
	 * Set value of RequestedDate
	 * @param context
	 * @param requesteddate
	 */
	public final void setRequestedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requesteddate)
	{
		getMendixObject().setValue(context, MemberNames.RequestedDate.toString(), requesteddate);
	}

	/**
	 * @return value of CompletedDate
	 */
	public final java.util.Date getCompletedDate()
	{
		return getCompletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedDate
	 */
	public final java.util.Date getCompletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletedDate.toString());
	}

	/**
	 * Set value of CompletedDate
	 * @param completeddate
	 */
	public final void setCompletedDate(java.util.Date completeddate)
	{
		setCompletedDate(getContext(), completeddate);
	}

	/**
	 * Set value of CompletedDate
	 * @param context
	 * @param completeddate
	 */
	public final void setCompletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completeddate)
	{
		getMendixObject().setValue(context, MemberNames.CompletedDate.toString(), completeddate);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Email_
	 */
	public final java.lang.String getEmail_()
	{
		return getEmail_(getContext());
	}

	/**
	 * @param context
	 * @return value of Email_
	 */
	public final java.lang.String getEmail_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email_.toString());
	}

	/**
	 * Set value of Email_
	 * @param email_
	 */
	public final void setEmail_(java.lang.String email_)
	{
		setEmail_(getContext(), email_);
	}

	/**
	 * Set value of Email_
	 * @param context
	 * @param email_
	 */
	public final void setEmail_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email_)
	{
		getMendixObject().setValue(context, MemberNames.Email_.toString(), email_);
	}

	/**
	 * @return value of Provider_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getProvider_GrantSystem() throws com.mendix.core.CoreException
	{
		return getProvider_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Provider_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getProvider_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Provider_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Provider_GrantSystem
	 * @param provider_grantsystem
	 */
	public final void setProvider_GrantSystem(ugs.proxies.GrantSystem provider_grantsystem)
	{
		setProvider_GrantSystem(getContext(), provider_grantsystem);
	}

	/**
	 * Set value of Provider_GrantSystem
	 * @param context
	 * @param provider_grantsystem
	 */
	public final void setProvider_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem provider_grantsystem)
	{
		if (provider_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Provider_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Provider_GrantSystem.toString(), provider_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Provider that = (ugs.proxies.Provider) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Provider";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
