// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class ReportsProcessHelper_Header
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reportsProcessHelper_HeaderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.ReportsProcessHelper_Header";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Header("Header"),
		Selected("Selected"),
		ProcessHelper_Header("UGS.ProcessHelper_Header");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReportsProcessHelper_Header(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.ReportsProcessHelper_Header"));
	}

	protected ReportsProcessHelper_Header(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reportsProcessHelper_HeaderMendixObject)
	{
		if (reportsProcessHelper_HeaderMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.ReportsProcessHelper_Header", reportsProcessHelper_HeaderMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.ReportsProcessHelper_Header");

		this.reportsProcessHelper_HeaderMendixObject = reportsProcessHelper_HeaderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ReportsProcessHelper_Header.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.ReportsProcessHelper_Header initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.ReportsProcessHelper_Header.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.ReportsProcessHelper_Header initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.ReportsProcessHelper_Header(context, mendixObject);
	}

	public static ugs.proxies.ReportsProcessHelper_Header load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.ReportsProcessHelper_Header.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Header
	 */
	public final java.lang.String getHeader()
	{
		return getHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Header
	 */
	public final java.lang.String getHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header.toString());
	}

	/**
	 * Set value of Header
	 * @param header
	 */
	public final void setHeader(java.lang.String header)
	{
		setHeader(getContext(), header);
	}

	/**
	 * Set value of Header
	 * @param context
	 * @param header
	 */
	public final void setHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header)
	{
		getMendixObject().setValue(context, MemberNames.Header.toString(), header);
	}

	/**
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected()
	{
		return getSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Selected.toString());
	}

	/**
	 * Set value of Selected
	 * @param selected
	 */
	public final void setSelected(java.lang.Boolean selected)
	{
		setSelected(getContext(), selected);
	}

	/**
	 * Set value of Selected
	 * @param context
	 * @param selected
	 */
	public final void setSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selected)
	{
		getMendixObject().setValue(context, MemberNames.Selected.toString(), selected);
	}

	/**
	 * @return value of ProcessHelper_Header
	 */
	public final ugs.proxies.ReportsProcessHelper getProcessHelper_Header() throws com.mendix.core.CoreException
	{
		return getProcessHelper_Header(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessHelper_Header
	 */
	public final ugs.proxies.ReportsProcessHelper getProcessHelper_Header(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.ReportsProcessHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProcessHelper_Header.toString());
		if (identifier != null)
			result = ugs.proxies.ReportsProcessHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProcessHelper_Header
	 * @param processhelper_header
	 */
	public final void setProcessHelper_Header(ugs.proxies.ReportsProcessHelper processhelper_header)
	{
		setProcessHelper_Header(getContext(), processhelper_header);
	}

	/**
	 * Set value of ProcessHelper_Header
	 * @param context
	 * @param processhelper_header
	 */
	public final void setProcessHelper_Header(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.ReportsProcessHelper processhelper_header)
	{
		if (processhelper_header == null)
			getMendixObject().setValue(context, MemberNames.ProcessHelper_Header.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProcessHelper_Header.toString(), processhelper_header.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reportsProcessHelper_HeaderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.ReportsProcessHelper_Header that = (ugs.proxies.ReportsProcessHelper_Header) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.ReportsProcessHelper_Header";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
