// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class ReviewQuestion
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reviewQuestionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.ReviewQuestion";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Question("Question"),
		ReviewQuestion_ReviewQ("UGS.ReviewQuestion_ReviewQ");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReviewQuestion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.ReviewQuestion"));
	}

	protected ReviewQuestion(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reviewQuestionMendixObject)
	{
		if (reviewQuestionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.ReviewQuestion", reviewQuestionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.ReviewQuestion");

		this.reviewQuestionMendixObject = reviewQuestionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ReviewQuestion.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.ReviewQuestion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.ReviewQuestion.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.ReviewQuestion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.ReviewQuestion(context, mendixObject);
	}

	public static ugs.proxies.ReviewQuestion load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.ReviewQuestion.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.ReviewQuestion> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.ReviewQuestion> result = new java.util.ArrayList<ugs.proxies.ReviewQuestion>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.ReviewQuestion" + xpathConstraint))
			result.add(ugs.proxies.ReviewQuestion.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Question
	 */
	public final java.lang.String getQuestion()
	{
		return getQuestion(getContext());
	}

	/**
	 * @param context
	 * @return value of Question
	 */
	public final java.lang.String getQuestion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Question.toString());
	}

	/**
	 * Set value of Question
	 * @param question
	 */
	public final void setQuestion(java.lang.String question)
	{
		setQuestion(getContext(), question);
	}

	/**
	 * Set value of Question
	 * @param context
	 * @param question
	 */
	public final void setQuestion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String question)
	{
		getMendixObject().setValue(context, MemberNames.Question.toString(), question);
	}

	/**
	 * @return value of ReviewQuestion_ReviewQ
	 */
	public final ugs.proxies.ReviewQ getReviewQuestion_ReviewQ() throws com.mendix.core.CoreException
	{
		return getReviewQuestion_ReviewQ(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewQuestion_ReviewQ
	 */
	public final ugs.proxies.ReviewQ getReviewQuestion_ReviewQ(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.ReviewQ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReviewQuestion_ReviewQ.toString());
		if (identifier != null)
			result = ugs.proxies.ReviewQ.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReviewQuestion_ReviewQ
	 * @param reviewquestion_reviewq
	 */
	public final void setReviewQuestion_ReviewQ(ugs.proxies.ReviewQ reviewquestion_reviewq)
	{
		setReviewQuestion_ReviewQ(getContext(), reviewquestion_reviewq);
	}

	/**
	 * Set value of ReviewQuestion_ReviewQ
	 * @param context
	 * @param reviewquestion_reviewq
	 */
	public final void setReviewQuestion_ReviewQ(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.ReviewQ reviewquestion_reviewq)
	{
		if (reviewquestion_reviewq == null)
			getMendixObject().setValue(context, MemberNames.ReviewQuestion_ReviewQ.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReviewQuestion_ReviewQ.toString(), reviewquestion_reviewq.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reviewQuestionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.ReviewQuestion that = (ugs.proxies.ReviewQuestion) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.ReviewQuestion";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
