// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class SaveSearchResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject saveSearchResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.SaveSearchResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Xpath("Xpath"),
		GrantSystem_SaveSearchResult("UGS.GrantSystem_SaveSearchResult"),
		SaveSearchResult_Account("UGS.SaveSearchResult_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SaveSearchResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.SaveSearchResult"));
	}

	protected SaveSearchResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject saveSearchResultMendixObject)
	{
		if (saveSearchResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.SaveSearchResult", saveSearchResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.SaveSearchResult");

		this.saveSearchResultMendixObject = saveSearchResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SaveSearchResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.SaveSearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.SaveSearchResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.SaveSearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.SaveSearchResult(context, mendixObject);
	}

	public static ugs.proxies.SaveSearchResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.SaveSearchResult.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.SaveSearchResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.SaveSearchResult> result = new java.util.ArrayList<ugs.proxies.SaveSearchResult>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.SaveSearchResult" + xpathConstraint))
			result.add(ugs.proxies.SaveSearchResult.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Xpath
	 */
	public final java.lang.String getXpath()
	{
		return getXpath(getContext());
	}

	/**
	 * @param context
	 * @return value of Xpath
	 */
	public final java.lang.String getXpath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Xpath.toString());
	}

	/**
	 * Set value of Xpath
	 * @param xpath
	 */
	public final void setXpath(java.lang.String xpath)
	{
		setXpath(getContext(), xpath);
	}

	/**
	 * Set value of Xpath
	 * @param context
	 * @param xpath
	 */
	public final void setXpath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpath)
	{
		getMendixObject().setValue(context, MemberNames.Xpath.toString(), xpath);
	}

	/**
	 * @return value of GrantSystem_SaveSearchResult
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_SaveSearchResult() throws com.mendix.core.CoreException
	{
		return getGrantSystem_SaveSearchResult(getContext());
	}

	/**
	 * @param context
	 * @return value of GrantSystem_SaveSearchResult
	 */
	public final ugs.proxies.GrantSystem getGrantSystem_SaveSearchResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GrantSystem_SaveSearchResult.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GrantSystem_SaveSearchResult
	 * @param grantsystem_savesearchresult
	 */
	public final void setGrantSystem_SaveSearchResult(ugs.proxies.GrantSystem grantsystem_savesearchresult)
	{
		setGrantSystem_SaveSearchResult(getContext(), grantsystem_savesearchresult);
	}

	/**
	 * Set value of GrantSystem_SaveSearchResult
	 * @param context
	 * @param grantsystem_savesearchresult
	 */
	public final void setGrantSystem_SaveSearchResult(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem grantsystem_savesearchresult)
	{
		if (grantsystem_savesearchresult == null)
			getMendixObject().setValue(context, MemberNames.GrantSystem_SaveSearchResult.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GrantSystem_SaveSearchResult.toString(), grantsystem_savesearchresult.getMendixObject().getId());
	}

	/**
	 * @return value of SaveSearchResult_Account
	 */
	public final administration.proxies.Account getSaveSearchResult_Account() throws com.mendix.core.CoreException
	{
		return getSaveSearchResult_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of SaveSearchResult_Account
	 */
	public final administration.proxies.Account getSaveSearchResult_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SaveSearchResult_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SaveSearchResult_Account
	 * @param savesearchresult_account
	 */
	public final void setSaveSearchResult_Account(administration.proxies.Account savesearchresult_account)
	{
		setSaveSearchResult_Account(getContext(), savesearchresult_account);
	}

	/**
	 * Set value of SaveSearchResult_Account
	 * @param context
	 * @param savesearchresult_account
	 */
	public final void setSaveSearchResult_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account savesearchresult_account)
	{
		if (savesearchresult_account == null)
			getMendixObject().setValue(context, MemberNames.SaveSearchResult_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SaveSearchResult_Account.toString(), savesearchresult_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return saveSearchResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.SaveSearchResult that = (ugs.proxies.SaveSearchResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.SaveSearchResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
