// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Signature extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Signature";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Signature_GrantSystem_Clone("UGS.Signature_GrantSystem_Clone"),
		Signature_GrantSystem_main("UGS.Signature_GrantSystem_main");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Signature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Signature"));
	}

	protected Signature(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signatureMendixObject)
	{
		super(context, signatureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.Signature", signatureMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Signature");
	}

	/**
	 * @deprecated Use 'Signature.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Signature initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Signature.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Signature initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Signature(context, mendixObject);
	}

	public static ugs.proxies.Signature load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Signature.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Signature> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Signature> result = new java.util.ArrayList<ugs.proxies.Signature>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Signature" + xpathConstraint))
			result.add(ugs.proxies.Signature.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Signature_GrantSystem_Clone
	 */
	public final ugs.proxies.GrantSystem getSignature_GrantSystem_Clone() throws com.mendix.core.CoreException
	{
		return getSignature_GrantSystem_Clone(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature_GrantSystem_Clone
	 */
	public final ugs.proxies.GrantSystem getSignature_GrantSystem_Clone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signature_GrantSystem_Clone.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Signature_GrantSystem_Clone
	 * @param signature_grantsystem_clone
	 */
	public final void setSignature_GrantSystem_Clone(ugs.proxies.GrantSystem signature_grantsystem_clone)
	{
		setSignature_GrantSystem_Clone(getContext(), signature_grantsystem_clone);
	}

	/**
	 * Set value of Signature_GrantSystem_Clone
	 * @param context
	 * @param signature_grantsystem_clone
	 */
	public final void setSignature_GrantSystem_Clone(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem signature_grantsystem_clone)
	{
		if (signature_grantsystem_clone == null)
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_Clone.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_Clone.toString(), signature_grantsystem_clone.getMendixObject().getId());
	}

	/**
	 * @return value of Signature_GrantSystem_main
	 */
	public final ugs.proxies.GrantSystem getSignature_GrantSystem_main() throws com.mendix.core.CoreException
	{
		return getSignature_GrantSystem_main(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature_GrantSystem_main
	 */
	public final ugs.proxies.GrantSystem getSignature_GrantSystem_main(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signature_GrantSystem_main.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Signature_GrantSystem_main
	 * @param signature_grantsystem_main
	 */
	public final void setSignature_GrantSystem_main(ugs.proxies.GrantSystem signature_grantsystem_main)
	{
		setSignature_GrantSystem_main(getContext(), signature_grantsystem_main);
	}

	/**
	 * Set value of Signature_GrantSystem_main
	 * @param context
	 * @param signature_grantsystem_main
	 */
	public final void setSignature_GrantSystem_main(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem signature_grantsystem_main)
	{
		if (signature_grantsystem_main == null)
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_main.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Signature_GrantSystem_main.toString(), signature_grantsystem_main.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Signature that = (ugs.proxies.Signature) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Signature";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
