// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class SignUp
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject signUpMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.SignUp";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		UserName("UserName"),
		Password("Password"),
		EmailID("EmailID"),
		MobileNumber("MobileNumber"),
		Role("Role"),
		OrganisationName("OrganisationName"),
		SignUp_Account("UGS.SignUp_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SignUp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.SignUp"));
	}

	protected SignUp(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signUpMendixObject)
	{
		if (signUpMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.SignUp", signUpMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.SignUp");

		this.signUpMendixObject = signUpMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SignUp.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.SignUp initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.SignUp.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.SignUp initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.SignUp(context, mendixObject);
	}

	public static ugs.proxies.SignUp load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.SignUp.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of EmailID
	 */
	public final java.lang.String getEmailID()
	{
		return getEmailID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailID
	 */
	public final java.lang.String getEmailID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailID.toString());
	}

	/**
	 * Set value of EmailID
	 * @param emailid
	 */
	public final void setEmailID(java.lang.String emailid)
	{
		setEmailID(getContext(), emailid);
	}

	/**
	 * Set value of EmailID
	 * @param context
	 * @param emailid
	 */
	public final void setEmailID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailid)
	{
		getMendixObject().setValue(context, MemberNames.EmailID.toString(), emailid);
	}

	/**
	 * @return value of MobileNumber
	 */
	public final java.lang.String getMobileNumber()
	{
		return getMobileNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MobileNumber
	 */
	public final java.lang.String getMobileNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MobileNumber.toString());
	}

	/**
	 * Set value of MobileNumber
	 * @param mobilenumber
	 */
	public final void setMobileNumber(java.lang.String mobilenumber)
	{
		setMobileNumber(getContext(), mobilenumber);
	}

	/**
	 * Set value of MobileNumber
	 * @param context
	 * @param mobilenumber
	 */
	public final void setMobileNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mobilenumber)
	{
		getMendixObject().setValue(context, MemberNames.MobileNumber.toString(), mobilenumber);
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final ugs.proxies.Enum_UserRoles getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final ugs.proxies.Enum_UserRoles getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Role.toString());
		if (obj == null)
			return null;

		return ugs.proxies.Enum_UserRoles.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(ugs.proxies.Enum_UserRoles role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Enum_UserRoles role)
	{
		if (role != null)
			getMendixObject().setValue(context, MemberNames.Role.toString(), role.toString());
		else
			getMendixObject().setValue(context, MemberNames.Role.toString(), null);
	}

	/**
	 * @return value of OrganisationName
	 */
	public final java.lang.String getOrganisationName()
	{
		return getOrganisationName(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganisationName
	 */
	public final java.lang.String getOrganisationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganisationName.toString());
	}

	/**
	 * Set value of OrganisationName
	 * @param organisationname
	 */
	public final void setOrganisationName(java.lang.String organisationname)
	{
		setOrganisationName(getContext(), organisationname);
	}

	/**
	 * Set value of OrganisationName
	 * @param context
	 * @param organisationname
	 */
	public final void setOrganisationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organisationname)
	{
		getMendixObject().setValue(context, MemberNames.OrganisationName.toString(), organisationname);
	}

	/**
	 * @return value of SignUp_Account
	 */
	public final administration.proxies.Account getSignUp_Account() throws com.mendix.core.CoreException
	{
		return getSignUp_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of SignUp_Account
	 */
	public final administration.proxies.Account getSignUp_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SignUp_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SignUp_Account
	 * @param signup_account
	 */
	public final void setSignUp_Account(administration.proxies.Account signup_account)
	{
		setSignUp_Account(getContext(), signup_account);
	}

	/**
	 * Set value of SignUp_Account
	 * @param context
	 * @param signup_account
	 */
	public final void setSignUp_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account signup_account)
	{
		if (signup_account == null)
			getMendixObject().setValue(context, MemberNames.SignUp_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SignUp_Account.toString(), signup_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return signUpMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.SignUp that = (ugs.proxies.SignUp) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.SignUp";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
