// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class TestQuestions
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testQuestionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.TestQuestions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Question("Question"),
		Answer("Answer"),
		Option_A_Value("Option_A_Value"),
		Option_B_Value("Option_B_Value"),
		Option_C_Value("Option_C_Value"),
		Option_D_Value("Option_D_Value"),
		RightAnswer("RightAnswer"),
		ChosenAnswer("ChosenAnswer"),
		QNumber("QNumber"),
		TestQuestions_Test("UGS.TestQuestions_Test");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestQuestions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.TestQuestions"));
	}

	protected TestQuestions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testQuestionsMendixObject)
	{
		if (testQuestionsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UGS.TestQuestions", testQuestionsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.TestQuestions");

		this.testQuestionsMendixObject = testQuestionsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestQuestions.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.TestQuestions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.TestQuestions.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.TestQuestions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.TestQuestions(context, mendixObject);
	}

	public static ugs.proxies.TestQuestions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.TestQuestions.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.TestQuestions> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.TestQuestions> result = new java.util.ArrayList<ugs.proxies.TestQuestions>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.TestQuestions" + xpathConstraint))
			result.add(ugs.proxies.TestQuestions.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Question
	 */
	public final java.lang.String getQuestion()
	{
		return getQuestion(getContext());
	}

	/**
	 * @param context
	 * @return value of Question
	 */
	public final java.lang.String getQuestion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Question.toString());
	}

	/**
	 * Set value of Question
	 * @param question
	 */
	public final void setQuestion(java.lang.String question)
	{
		setQuestion(getContext(), question);
	}

	/**
	 * Set value of Question
	 * @param context
	 * @param question
	 */
	public final void setQuestion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String question)
	{
		getMendixObject().setValue(context, MemberNames.Question.toString(), question);
	}

	/**
	 * @return value of Answer
	 */
	public final java.lang.Integer getAnswer()
	{
		return getAnswer(getContext());
	}

	/**
	 * @param context
	 * @return value of Answer
	 */
	public final java.lang.Integer getAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Answer.toString());
	}

	/**
	 * Set value of Answer
	 * @param answer
	 */
	public final void setAnswer(java.lang.Integer answer)
	{
		setAnswer(getContext(), answer);
	}

	/**
	 * Set value of Answer
	 * @param context
	 * @param answer
	 */
	public final void setAnswer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer answer)
	{
		getMendixObject().setValue(context, MemberNames.Answer.toString(), answer);
	}

	/**
	 * @return value of Option_A_Value
	 */
	public final java.lang.String getOption_A_Value()
	{
		return getOption_A_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_A_Value
	 */
	public final java.lang.String getOption_A_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Option_A_Value.toString());
	}

	/**
	 * Set value of Option_A_Value
	 * @param option_a_value
	 */
	public final void setOption_A_Value(java.lang.String option_a_value)
	{
		setOption_A_Value(getContext(), option_a_value);
	}

	/**
	 * Set value of Option_A_Value
	 * @param context
	 * @param option_a_value
	 */
	public final void setOption_A_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String option_a_value)
	{
		getMendixObject().setValue(context, MemberNames.Option_A_Value.toString(), option_a_value);
	}

	/**
	 * @return value of Option_B_Value
	 */
	public final java.lang.String getOption_B_Value()
	{
		return getOption_B_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_B_Value
	 */
	public final java.lang.String getOption_B_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Option_B_Value.toString());
	}

	/**
	 * Set value of Option_B_Value
	 * @param option_b_value
	 */
	public final void setOption_B_Value(java.lang.String option_b_value)
	{
		setOption_B_Value(getContext(), option_b_value);
	}

	/**
	 * Set value of Option_B_Value
	 * @param context
	 * @param option_b_value
	 */
	public final void setOption_B_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String option_b_value)
	{
		getMendixObject().setValue(context, MemberNames.Option_B_Value.toString(), option_b_value);
	}

	/**
	 * @return value of Option_C_Value
	 */
	public final java.lang.String getOption_C_Value()
	{
		return getOption_C_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_C_Value
	 */
	public final java.lang.String getOption_C_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Option_C_Value.toString());
	}

	/**
	 * Set value of Option_C_Value
	 * @param option_c_value
	 */
	public final void setOption_C_Value(java.lang.String option_c_value)
	{
		setOption_C_Value(getContext(), option_c_value);
	}

	/**
	 * Set value of Option_C_Value
	 * @param context
	 * @param option_c_value
	 */
	public final void setOption_C_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String option_c_value)
	{
		getMendixObject().setValue(context, MemberNames.Option_C_Value.toString(), option_c_value);
	}

	/**
	 * @return value of Option_D_Value
	 */
	public final java.lang.String getOption_D_Value()
	{
		return getOption_D_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_D_Value
	 */
	public final java.lang.String getOption_D_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Option_D_Value.toString());
	}

	/**
	 * Set value of Option_D_Value
	 * @param option_d_value
	 */
	public final void setOption_D_Value(java.lang.String option_d_value)
	{
		setOption_D_Value(getContext(), option_d_value);
	}

	/**
	 * Set value of Option_D_Value
	 * @param context
	 * @param option_d_value
	 */
	public final void setOption_D_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String option_d_value)
	{
		getMendixObject().setValue(context, MemberNames.Option_D_Value.toString(), option_d_value);
	}

	/**
	 * Set value of RightAnswer
	 * @param rightanswer
	 */
	public final ugs.proxies.TestQuestion_Enum getRightAnswer()
	{
		return getRightAnswer(getContext());
	}

	/**
	 * @param context
	 * @return value of RightAnswer
	 */
	public final ugs.proxies.TestQuestion_Enum getRightAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RightAnswer.toString());
		if (obj == null)
			return null;

		return ugs.proxies.TestQuestion_Enum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RightAnswer
	 * @param rightanswer
	 */
	public final void setRightAnswer(ugs.proxies.TestQuestion_Enum rightanswer)
	{
		setRightAnswer(getContext(), rightanswer);
	}

	/**
	 * Set value of RightAnswer
	 * @param context
	 * @param rightanswer
	 */
	public final void setRightAnswer(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.TestQuestion_Enum rightanswer)
	{
		if (rightanswer != null)
			getMendixObject().setValue(context, MemberNames.RightAnswer.toString(), rightanswer.toString());
		else
			getMendixObject().setValue(context, MemberNames.RightAnswer.toString(), null);
	}

	/**
	 * Set value of ChosenAnswer
	 * @param chosenanswer
	 */
	public final ugs.proxies.TestQuestion_Enum getChosenAnswer()
	{
		return getChosenAnswer(getContext());
	}

	/**
	 * @param context
	 * @return value of ChosenAnswer
	 */
	public final ugs.proxies.TestQuestion_Enum getChosenAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ChosenAnswer.toString());
		if (obj == null)
			return null;

		return ugs.proxies.TestQuestion_Enum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ChosenAnswer
	 * @param chosenanswer
	 */
	public final void setChosenAnswer(ugs.proxies.TestQuestion_Enum chosenanswer)
	{
		setChosenAnswer(getContext(), chosenanswer);
	}

	/**
	 * Set value of ChosenAnswer
	 * @param context
	 * @param chosenanswer
	 */
	public final void setChosenAnswer(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.TestQuestion_Enum chosenanswer)
	{
		if (chosenanswer != null)
			getMendixObject().setValue(context, MemberNames.ChosenAnswer.toString(), chosenanswer.toString());
		else
			getMendixObject().setValue(context, MemberNames.ChosenAnswer.toString(), null);
	}

	/**
	 * @return value of QNumber
	 */
	public final java.lang.Integer getQNumber()
	{
		return getQNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of QNumber
	 */
	public final java.lang.Integer getQNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.QNumber.toString());
	}

	/**
	 * Set value of QNumber
	 * @param qnumber
	 */
	public final void setQNumber(java.lang.Integer qnumber)
	{
		setQNumber(getContext(), qnumber);
	}

	/**
	 * Set value of QNumber
	 * @param context
	 * @param qnumber
	 */
	public final void setQNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer qnumber)
	{
		getMendixObject().setValue(context, MemberNames.QNumber.toString(), qnumber);
	}

	/**
	 * @return value of TestQuestions_Test
	 */
	public final ugs.proxies.Test getTestQuestions_Test() throws com.mendix.core.CoreException
	{
		return getTestQuestions_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of TestQuestions_Test
	 */
	public final ugs.proxies.Test getTestQuestions_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestQuestions_Test.toString());
		if (identifier != null)
			result = ugs.proxies.Test.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestQuestions_Test
	 * @param testquestions_test
	 */
	public final void setTestQuestions_Test(ugs.proxies.Test testquestions_test)
	{
		setTestQuestions_Test(getContext(), testquestions_test);
	}

	/**
	 * Set value of TestQuestions_Test
	 * @param context
	 * @param testquestions_test
	 */
	public final void setTestQuestions_Test(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.Test testquestions_test)
	{
		if (testquestions_test == null)
			getMendixObject().setValue(context, MemberNames.TestQuestions_Test.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestQuestions_Test.toString(), testquestions_test.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testQuestionsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.TestQuestions that = (ugs.proxies.TestQuestions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.TestQuestions";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
