// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies;

public class Voucher extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UGS.Voucher";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Id_("Id_"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Voucher_GrantSystem("UGS.Voucher_GrantSystem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Voucher(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UGS.Voucher"));
	}

	protected Voucher(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject voucherMendixObject)
	{
		super(context, voucherMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("UGS.Voucher", voucherMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UGS.Voucher");
	}

	/**
	 * @deprecated Use 'Voucher.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ugs.proxies.Voucher initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ugs.proxies.Voucher.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ugs.proxies.Voucher initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ugs.proxies.Voucher(context, mendixObject);
	}

	public static ugs.proxies.Voucher load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ugs.proxies.Voucher.initialize(context, mendixObject);
	}

	public static java.util.List<ugs.proxies.Voucher> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ugs.proxies.Voucher> result = new java.util.ArrayList<ugs.proxies.Voucher>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UGS.Voucher" + xpathConstraint))
			result.add(ugs.proxies.Voucher.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Id_
	 */
	public final java.lang.Long getId_()
	{
		return getId_(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_
	 */
	public final java.lang.Long getId_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Id_.toString());
	}

	/**
	 * Set value of Id_
	 * @param id_
	 */
	public final void setId_(java.lang.Long id_)
	{
		setId_(getContext(), id_);
	}

	/**
	 * Set value of Id_
	 * @param context
	 * @param id_
	 */
	public final void setId_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_)
	{
		getMendixObject().setValue(context, MemberNames.Id_.toString(), id_);
	}

	/**
	 * @return value of Voucher_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getVoucher_GrantSystem() throws com.mendix.core.CoreException
	{
		return getVoucher_GrantSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of Voucher_GrantSystem
	 */
	public final ugs.proxies.GrantSystem getVoucher_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ugs.proxies.GrantSystem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Voucher_GrantSystem.toString());
		if (identifier != null)
			result = ugs.proxies.GrantSystem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Voucher_GrantSystem
	 * @param voucher_grantsystem
	 */
	public final void setVoucher_GrantSystem(ugs.proxies.GrantSystem voucher_grantsystem)
	{
		setVoucher_GrantSystem(getContext(), voucher_grantsystem);
	}

	/**
	 * Set value of Voucher_GrantSystem
	 * @param context
	 * @param voucher_grantsystem
	 */
	public final void setVoucher_GrantSystem(com.mendix.systemwideinterfaces.core.IContext context, ugs.proxies.GrantSystem voucher_grantsystem)
	{
		if (voucher_grantsystem == null)
			getMendixObject().setValue(context, MemberNames.Voucher_GrantSystem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Voucher_GrantSystem.toString(), voucher_grantsystem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ugs.proxies.Voucher that = (ugs.proxies.Voucher) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UGS.Voucher";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
