// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ugs.actions;

import datatablesexportdata.ExportDataImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ugs.proxies.ExcelExport;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ExportData extends CustomJavaAction<IMendixObject>
{
	private java.lang.String configData;
	private java.lang.String xpath;
	private java.lang.Long limit;

	public ExportData(IContext context, java.lang.String configData, java.lang.String xpath, java.lang.Long limit)
	{
		super(context);
		this.configData = configData;
		this.xpath = xpath;
		this.limit = limit;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ExcelExport exportDocument = new ExportDataImpl(getContext(), configData, xpath, limit).export();
		if (exportDocument != null) {
			return exportDocument.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportData";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
