define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js":
/*!******************************************************************************************************************************!*\
  !*** ../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js ***!
  \******************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "RedirectPage": () => (/* binding */ RedirectPage)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uUID
 * @returns {Promise.<void>}
 */

async function RedirectPage(uUID) {
  // BEGIN USER CODE
  var form = document.createElement('form');
  document.body.appendChild(form);
  form.method = 'post';
  form.action = '/signin/';
  var input = document.createElement('input');
  input.type = 'hidden';
  input.name = 'uuid';
  input.value = uUID;
  form.appendChild(input);
  form.submit();
  return; // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js":
/*!*******************************************************************************************************************!*\
  !*** ../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js ***!
  \*******************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_ClipBoard": () => (/* binding */ JS_ClipBoard)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} token
 * @returns {Promise.<void>}
 */

async function JS_ClipBoard(token) {
  // BEGIN USER CODE
  function dv() {
    var copyText = document.getElementById("test");
    copyText.value = token;
    copyText.select();
    copyText.setSelectionRange(0, 99999);
    document.execCommand("copy");
  }

  dv();
  let timeout = document.getElementById('testt');
  timeout.style.display = 'block';
  setTimeout(hideElement, 3000); //milliseconds until timeout//

  function hideElement() {
    timeout.style.display = 'none';
  } // END USER CODE

}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!**************************************************************************************************!*\
  !*** ../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/deployment/tmp/jsactions.js ***!
  \**************************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "UGS$JS_ClipBoard": () => (/* binding */ UGS$JS_ClipBoard),
/* harmony export */   "ForgotPassword$RedirectPage": () => (/* binding */ ForgotPassword$RedirectPage)
/* harmony export */ });
const UGS$JS_ClipBoard = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard */ "../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js"))).JS_ClipBoard;
const ForgotPassword$RedirectPage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage */ "../../../../../../Users/girid/Documents/Mendix/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js"))).RedirectPage;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vVXNlcnMvZ2lyaWQvRG9jdW1lbnRzL01lbmRpeC9SYXBpZEdyYW50LW1haW4vamF2YXNjcmlwdHNvdXJjZS9mb3Jnb3RwYXNzd29yZC9hY3Rpb25zL1JlZGlyZWN0UGFnZS5qcyIsIndlYnBhY2s6Ly8vLi4vVXNlcnMvZ2lyaWQvRG9jdW1lbnRzL01lbmRpeC9SYXBpZEdyYW50LW1haW4vamF2YXNjcmlwdHNvdXJjZS91Z3MvYWN0aW9ucy9KU19DbGlwQm9hcmQuanMiLCJ3ZWJwYWNrOi8vL2V4dGVybmFsIFwiYmlnLmpzXCIiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svYm9vdHN0cmFwIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvY29tcGF0IGdldCBkZWZhdWx0IGV4cG9ydCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2RlZmluZSBwcm9wZXJ0eSBnZXR0ZXJzIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvaGFzT3duUHJvcGVydHkgc2hvcnRoYW5kIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvbWFrZSBuYW1lc3BhY2Ugb2JqZWN0Iiwid2VicGFjazovLy8uLi9Vc2Vycy9naXJpZC9Eb2N1bWVudHMvTWVuZGl4L1JhcGlkR3JhbnQtbWFpbi9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwibmFtZXMiOlsiUmVkaXJlY3RQYWdlIiwidVVJRCIsImZvcm0iLCJkb2N1bWVudCIsImNyZWF0ZUVsZW1lbnQiLCJib2R5IiwiYXBwZW5kQ2hpbGQiLCJtZXRob2QiLCJhY3Rpb24iLCJpbnB1dCIsInR5cGUiLCJuYW1lIiwidmFsdWUiLCJzdWJtaXQiLCJKU19DbGlwQm9hcmQiLCJ0b2tlbiIsImR2IiwiY29weVRleHQiLCJnZXRFbGVtZW50QnlJZCIsInNlbGVjdCIsInNldFNlbGVjdGlvblJhbmdlIiwiZXhlY0NvbW1hbmQiLCJ0aW1lb3V0Iiwic3R5bGUiLCJkaXNwbGF5Iiwic2V0VGltZW91dCIsImhpZGVFbGVtZW50IiwiVUdTJEpTX0NsaXBCb2FyZCIsIkZvcmdvdFBhc3N3b3JkJFJlZGlyZWN0UGFnZSJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQSxZQUFmLENBQTRCQyxJQUE1QixFQUFrQztBQUN4QztBQUVBLE1BQUlDLElBQUksR0FBR0MsUUFBUSxDQUFDQyxhQUFULENBQXVCLE1BQXZCLENBQVg7QUFDR0QsVUFBUSxDQUFDRSxJQUFULENBQWNDLFdBQWQsQ0FBMEJKLElBQTFCO0FBQ0FBLE1BQUksQ0FBQ0ssTUFBTCxHQUFjLE1BQWQ7QUFDQUwsTUFBSSxDQUFDTSxNQUFMLEdBQWMsVUFBZDtBQUNILE1BQUlDLEtBQUssR0FBR04sUUFBUSxDQUFDQyxhQUFULENBQXVCLE9BQXZCLENBQVo7QUFDQ0ssT0FBSyxDQUFDQyxJQUFOLEdBQWEsUUFBYjtBQUNBRCxPQUFLLENBQUNFLElBQU4sR0FBYSxNQUFiO0FBQ01GLE9BQUssQ0FBQ0csS0FBTixHQUFjWCxJQUFkO0FBQ0FDLE1BQUksQ0FBQ0ksV0FBTCxDQUFpQkcsS0FBakI7QUFFSlAsTUFBSSxDQUFDVyxNQUFMO0FBRUgsU0Fmd0MsQ0FnQnhDO0FBQ0EsQzs7Ozs7Ozs7Ozs7Ozs7OztBQ2pDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUMsWUFBZixDQUE0QkMsS0FBNUIsRUFBbUM7QUFDekM7QUFDQSxXQUFTQyxFQUFULEdBQWE7QUFDZCxRQUFJQyxRQUFRLEdBQUdkLFFBQVEsQ0FBQ2UsY0FBVCxDQUF3QixNQUF4QixDQUFmO0FBQ0dELFlBQVEsQ0FBQ0wsS0FBVCxHQUFpQkcsS0FBakI7QUFDREUsWUFBUSxDQUFDRSxNQUFUO0FBQ0FGLFlBQVEsQ0FBQ0csaUJBQVQsQ0FBMkIsQ0FBM0IsRUFBOEIsS0FBOUI7QUFDQWpCLFlBQVEsQ0FBQ2tCLFdBQVQsQ0FBcUIsTUFBckI7QUFDQTs7QUFFRkwsSUFBRTtBQUVGLE1BQUlNLE9BQU8sR0FBR25CLFFBQVEsQ0FBQ2UsY0FBVCxDQUF3QixPQUF4QixDQUFkO0FBQ0dJLFNBQU8sQ0FBQ0MsS0FBUixDQUFjQyxPQUFkLEdBQXdCLE9BQXhCO0FBQ1FDLFlBQVUsQ0FBQ0MsV0FBRCxFQUFjLElBQWQsQ0FBVixDQWQrQixDQWNEOztBQUd4QyxXQUFTQSxXQUFULEdBQXVCO0FBQ1JKLFdBQU8sQ0FBQ0MsS0FBUixDQUFjQyxPQUFkLEdBQXdCLE1BQXhCO0FBQ2UsR0FuQlcsQ0FzQnpDOztBQUNBLEM7Ozs7Ozs7Ozs7QUN2Q0Qsb0Q7Ozs7OztVQ0FBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7O1VBRUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7Ozs7O1dDdEJBO1dBQ0E7V0FDQTtXQUNBO1dBQ0E7V0FDQSxnQ0FBZ0MsWUFBWTtXQUM1QztXQUNBLEU7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx3Q0FBd0MseUNBQXlDO1dBQ2pGO1dBQ0E7V0FDQSxFOzs7OztXQ1BBLHdGOzs7OztXQ0FBO1dBQ0E7V0FDQTtXQUNBLHNEQUFzRCxrQkFBa0I7V0FDeEU7V0FDQSwrQ0FBK0MsY0FBYztXQUM3RCxFOzs7Ozs7Ozs7Ozs7Ozs7QUNOTyxNQUFNRyxnQkFBZ0IsR0FBRyxZQUFZLENBQUMsTUFBTSxtVEFBUCxFQUE0R2IsWUFBako7QUFDQSxNQUFNYywyQkFBMkIsR0FBRyxZQUFZLENBQUMsTUFBTSx5VUFBUCxFQUF1SDVCLFlBQXZLLEMiLCJmaWxlIjoianNhY3Rpb25zLmpzIiwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSB1VUlEXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBSZWRpcmVjdFBhZ2UodVVJRCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cclxuXHR2YXIgZm9ybSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTtcclxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoZm9ybSk7XHJcbiAgICBmb3JtLm1ldGhvZCA9ICdwb3N0JztcclxuICAgIGZvcm0uYWN0aW9uID0gJy9zaWduaW4vJztcclxuXHR2YXIgaW5wdXQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdpbnB1dCcpO1xyXG5cdFx0aW5wdXQudHlwZSA9ICdoaWRkZW4nO1xyXG5cdFx0aW5wdXQubmFtZSA9ICd1dWlkJztcclxuICAgICAgICBpbnB1dC52YWx1ZSA9IHVVSUQ7XHJcbiAgICAgICAgZm9ybS5hcHBlbmRDaGlsZChpbnB1dCk7XHJcbiAgICBcclxuICAgIGZvcm0uc3VibWl0KCk7XHJcblxyXG5cdHJldHVybjtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSB0b2tlblxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfQ2xpcEJvYXJkKHRva2VuKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiBmdW5jdGlvbiBkdigpe1xyXG52YXIgY29weVRleHQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcInRlc3RcIik7XHJcbiAgIGNvcHlUZXh0LnZhbHVlID0gdG9rZW47XHJcbiAgY29weVRleHQuc2VsZWN0KCk7XHJcbiAgY29weVRleHQuc2V0U2VsZWN0aW9uUmFuZ2UoMCwgOTk5OTkpXHJcbiAgZG9jdW1lbnQuZXhlY0NvbW1hbmQoXCJjb3B5XCIpO1xyXG4gfSAgXHJcblxyXG5kdigpO1xyXG5cclxubGV0IHRpbWVvdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndGVzdHQnKTtcclxuICAgdGltZW91dC5zdHlsZS5kaXNwbGF5ID0gJ2Jsb2NrJyA7XHJcbiAgICAgICAgICAgc2V0VGltZW91dChoaWRlRWxlbWVudCwgMzAwMCkgLy9taWxsaXNlY29uZHMgdW50aWwgdGltZW91dC8vXHJcbiAgICAgIFxyXG5cclxuIGZ1bmN0aW9uIGhpZGVFbGVtZW50KCkge1xyXG4gICAgICAgICAgICAgICAgdGltZW91dC5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnIDtcclxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfVxyXG5cclxuXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIm1vZHVsZS5leHBvcnRzID0gX19XRUJQQUNLX0VYVEVSTkFMX01PRFVMRV9iaWdfanNfXzsiLCIvLyBUaGUgbW9kdWxlIGNhY2hlXG52YXIgX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fID0ge307XG5cbi8vIFRoZSByZXF1aXJlIGZ1bmN0aW9uXG5mdW5jdGlvbiBfX3dlYnBhY2tfcmVxdWlyZV9fKG1vZHVsZUlkKSB7XG5cdC8vIENoZWNrIGlmIG1vZHVsZSBpcyBpbiBjYWNoZVxuXHR2YXIgY2FjaGVkTW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXTtcblx0aWYgKGNhY2hlZE1vZHVsZSAhPT0gdW5kZWZpbmVkKSB7XG5cdFx0cmV0dXJuIGNhY2hlZE1vZHVsZS5leHBvcnRzO1xuXHR9XG5cdC8vIENyZWF0ZSBhIG5ldyBtb2R1bGUgKGFuZCBwdXQgaXQgaW50byB0aGUgY2FjaGUpXG5cdHZhciBtb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdID0ge1xuXHRcdC8vIG5vIG1vZHVsZS5pZCBuZWVkZWRcblx0XHQvLyBubyBtb2R1bGUubG9hZGVkIG5lZWRlZFxuXHRcdGV4cG9ydHM6IHt9XG5cdH07XG5cblx0Ly8gRXhlY3V0ZSB0aGUgbW9kdWxlIGZ1bmN0aW9uXG5cdF9fd2VicGFja19tb2R1bGVzX19bbW9kdWxlSWRdKG1vZHVsZSwgbW9kdWxlLmV4cG9ydHMsIF9fd2VicGFja19yZXF1aXJlX18pO1xuXG5cdC8vIFJldHVybiB0aGUgZXhwb3J0cyBvZiB0aGUgbW9kdWxlXG5cdHJldHVybiBtb2R1bGUuZXhwb3J0cztcbn1cblxuIiwiLy8gZ2V0RGVmYXVsdEV4cG9ydCBmdW5jdGlvbiBmb3IgY29tcGF0aWJpbGl0eSB3aXRoIG5vbi1oYXJtb255IG1vZHVsZXNcbl9fd2VicGFja19yZXF1aXJlX18ubiA9IChtb2R1bGUpID0+IHtcblx0dmFyIGdldHRlciA9IG1vZHVsZSAmJiBtb2R1bGUuX19lc01vZHVsZSA/XG5cdFx0KCkgPT4gKG1vZHVsZVsnZGVmYXVsdCddKSA6XG5cdFx0KCkgPT4gKG1vZHVsZSk7XG5cdF9fd2VicGFja19yZXF1aXJlX18uZChnZXR0ZXIsIHsgYTogZ2V0dGVyIH0pO1xuXHRyZXR1cm4gZ2V0dGVyO1xufTsiLCIvLyBkZWZpbmUgZ2V0dGVyIGZ1bmN0aW9ucyBmb3IgaGFybW9ueSBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLmQgPSAoZXhwb3J0cywgZGVmaW5pdGlvbikgPT4ge1xuXHRmb3IodmFyIGtleSBpbiBkZWZpbml0aW9uKSB7XG5cdFx0aWYoX193ZWJwYWNrX3JlcXVpcmVfXy5vKGRlZmluaXRpb24sIGtleSkgJiYgIV9fd2VicGFja19yZXF1aXJlX18ubyhleHBvcnRzLCBrZXkpKSB7XG5cdFx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywga2V5LCB7IGVudW1lcmFibGU6IHRydWUsIGdldDogZGVmaW5pdGlvbltrZXldIH0pO1xuXHRcdH1cblx0fVxufTsiLCJfX3dlYnBhY2tfcmVxdWlyZV9fLm8gPSAob2JqLCBwcm9wKSA9PiAoT2JqZWN0LnByb3RvdHlwZS5oYXNPd25Qcm9wZXJ0eS5jYWxsKG9iaiwgcHJvcCkpIiwiLy8gZGVmaW5lIF9fZXNNb2R1bGUgb24gZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5yID0gKGV4cG9ydHMpID0+IHtcblx0aWYodHlwZW9mIFN5bWJvbCAhPT0gJ3VuZGVmaW5lZCcgJiYgU3ltYm9sLnRvU3RyaW5nVGFnKSB7XG5cdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIFN5bWJvbC50b1N0cmluZ1RhZywgeyB2YWx1ZTogJ01vZHVsZScgfSk7XG5cdH1cblx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICdfX2VzTW9kdWxlJywgeyB2YWx1ZTogdHJ1ZSB9KTtcbn07IiwiZXhwb3J0IGNvbnN0IFVHUyRKU19DbGlwQm9hcmQgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvZ2lyaWQvRG9jdW1lbnRzL01lbmRpeC9SYXBpZEdyYW50LW1haW4vamF2YXNjcmlwdHNvdXJjZS91Z3MvYWN0aW9ucy9KU19DbGlwQm9hcmRcIikpLkpTX0NsaXBCb2FyZDtcbmV4cG9ydCBjb25zdCBGb3Jnb3RQYXNzd29yZCRSZWRpcmVjdFBhZ2UgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvZ2lyaWQvRG9jdW1lbnRzL01lbmRpeC9SYXBpZEdyYW50LW1haW4vamF2YXNjcmlwdHNvdXJjZS9mb3Jnb3RwYXNzd29yZC9hY3Rpb25zL1JlZGlyZWN0UGFnZVwiKSkuUmVkaXJlY3RQYWdlO1xuIl0sInNvdXJjZVJvb3QiOiIifQ==