define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../Projects/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js":
/*!*******************************************************************************************************!*\
  !*** ../../../../../Projects/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js ***!
  \*******************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "RedirectPage": () => (/* binding */ RedirectPage)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uUID
 * @returns {Promise.<void>}
 */

async function RedirectPage(uUID) {
  // BEGIN USER CODE
  var form = document.createElement('form');
  document.body.appendChild(form);
  form.method = 'post';
  form.action = '/signin/';
  var input = document.createElement('input');
  input.type = 'hidden';
  input.name = 'uuid';
  input.value = uUID;
  form.appendChild(input);
  form.submit();
  return; // END USER CODE
}

/***/ }),

/***/ "../../../../../Projects/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js":
/*!********************************************************************************************!*\
  !*** ../../../../../Projects/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js ***!
  \********************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_ClipBoard": () => (/* binding */ JS_ClipBoard)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} token
 * @returns {Promise.<void>}
 */

async function JS_ClipBoard(token) {
  // BEGIN USER CODE
  function dv() {
    var copyText = document.getElementById("test");
    copyText.value = token;
    copyText.select();
    copyText.setSelectionRange(0, 99999);
    document.execCommand("copy");
  }

  dv();
  let timeout = document.getElementById('testt');
  timeout.style.display = 'block';
  setTimeout(hideElement, 3000); //milliseconds until timeout//

  function hideElement() {
    timeout.style.display = 'none';
  } // END USER CODE

}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!***************************************************************************!*\
  !*** ../../../../../Projects/RapidGrant-main/deployment/tmp/jsactions.js ***!
  \***************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "ForgotPassword$RedirectPage": () => (/* binding */ ForgotPassword$RedirectPage),
/* harmony export */   "UGS$JS_ClipBoard": () => (/* binding */ UGS$JS_ClipBoard)
/* harmony export */ });
const ForgotPassword$RedirectPage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../Projects/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage */ "../../../../../Projects/RapidGrant-main/javascriptsource/forgotpassword/actions/RedirectPage.js"))).RedirectPage;
const UGS$JS_ClipBoard = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../Projects/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard */ "../../../../../Projects/RapidGrant-main/javascriptsource/ugs/actions/JS_ClipBoard.js"))).JS_ClipBoard;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vUHJvamVjdHMvUmFwaWRHcmFudC1tYWluL2phdmFzY3JpcHRzb3VyY2UvZm9yZ290cGFzc3dvcmQvYWN0aW9ucy9SZWRpcmVjdFBhZ2UuanMiLCJ3ZWJwYWNrOi8vLy4uL1Byb2plY3RzL1JhcGlkR3JhbnQtbWFpbi9qYXZhc2NyaXB0c291cmNlL3Vncy9hY3Rpb25zL0pTX0NsaXBCb2FyZC5qcyIsIndlYnBhY2s6Ly8vZXh0ZXJuYWwgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9jb21wYXQgZ2V0IGRlZmF1bHQgZXhwb3J0Iiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvZGVmaW5lIHByb3BlcnR5IGdldHRlcnMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9oYXNPd25Qcm9wZXJ0eSBzaG9ydGhhbmQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9tYWtlIG5hbWVzcGFjZSBvYmplY3QiLCJ3ZWJwYWNrOi8vLy4uL1Byb2plY3RzL1JhcGlkR3JhbnQtbWFpbi9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwibmFtZXMiOlsiUmVkaXJlY3RQYWdlIiwidVVJRCIsImZvcm0iLCJkb2N1bWVudCIsImNyZWF0ZUVsZW1lbnQiLCJib2R5IiwiYXBwZW5kQ2hpbGQiLCJtZXRob2QiLCJhY3Rpb24iLCJpbnB1dCIsInR5cGUiLCJuYW1lIiwidmFsdWUiLCJzdWJtaXQiLCJKU19DbGlwQm9hcmQiLCJ0b2tlbiIsImR2IiwiY29weVRleHQiLCJnZXRFbGVtZW50QnlJZCIsInNlbGVjdCIsInNldFNlbGVjdGlvblJhbmdlIiwiZXhlY0NvbW1hbmQiLCJ0aW1lb3V0Iiwic3R5bGUiLCJkaXNwbGF5Iiwic2V0VGltZW91dCIsImhpZGVFbGVtZW50IiwiRm9yZ290UGFzc3dvcmQkUmVkaXJlY3RQYWdlIiwiVUdTJEpTX0NsaXBCb2FyZCJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQSxZQUFmLENBQTRCQyxJQUE1QixFQUFrQztBQUN4QztBQUVBLE1BQUlDLElBQUksR0FBR0MsUUFBUSxDQUFDQyxhQUFULENBQXVCLE1BQXZCLENBQVg7QUFDR0QsVUFBUSxDQUFDRSxJQUFULENBQWNDLFdBQWQsQ0FBMEJKLElBQTFCO0FBQ0FBLE1BQUksQ0FBQ0ssTUFBTCxHQUFjLE1BQWQ7QUFDQUwsTUFBSSxDQUFDTSxNQUFMLEdBQWMsVUFBZDtBQUNILE1BQUlDLEtBQUssR0FBR04sUUFBUSxDQUFDQyxhQUFULENBQXVCLE9BQXZCLENBQVo7QUFDQ0ssT0FBSyxDQUFDQyxJQUFOLEdBQWEsUUFBYjtBQUNBRCxPQUFLLENBQUNFLElBQU4sR0FBYSxNQUFiO0FBQ01GLE9BQUssQ0FBQ0csS0FBTixHQUFjWCxJQUFkO0FBQ0FDLE1BQUksQ0FBQ0ksV0FBTCxDQUFpQkcsS0FBakI7QUFFSlAsTUFBSSxDQUFDVyxNQUFMO0FBRUgsU0Fmd0MsQ0FnQnhDO0FBQ0EsQzs7Ozs7Ozs7Ozs7Ozs7OztBQ2pDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUMsWUFBZixDQUE0QkMsS0FBNUIsRUFBbUM7QUFDekM7QUFDQSxXQUFTQyxFQUFULEdBQWE7QUFDZCxRQUFJQyxRQUFRLEdBQUdkLFFBQVEsQ0FBQ2UsY0FBVCxDQUF3QixNQUF4QixDQUFmO0FBQ0dELFlBQVEsQ0FBQ0wsS0FBVCxHQUFpQkcsS0FBakI7QUFDREUsWUFBUSxDQUFDRSxNQUFUO0FBQ0FGLFlBQVEsQ0FBQ0csaUJBQVQsQ0FBMkIsQ0FBM0IsRUFBOEIsS0FBOUI7QUFDQWpCLFlBQVEsQ0FBQ2tCLFdBQVQsQ0FBcUIsTUFBckI7QUFDQTs7QUFFRkwsSUFBRTtBQUVGLE1BQUlNLE9BQU8sR0FBR25CLFFBQVEsQ0FBQ2UsY0FBVCxDQUF3QixPQUF4QixDQUFkO0FBQ0dJLFNBQU8sQ0FBQ0MsS0FBUixDQUFjQyxPQUFkLEdBQXdCLE9BQXhCO0FBQ1FDLFlBQVUsQ0FBQ0MsV0FBRCxFQUFjLElBQWQsQ0FBVixDQWQrQixDQWNEOztBQUd4QyxXQUFTQSxXQUFULEdBQXVCO0FBQ1JKLFdBQU8sQ0FBQ0MsS0FBUixDQUFjQyxPQUFkLEdBQXdCLE1BQXhCO0FBQ2UsR0FuQlcsQ0FzQnpDOztBQUNBLEM7Ozs7Ozs7Ozs7QUN2Q0Qsb0Q7Ozs7OztVQ0FBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7O1VBRUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7Ozs7O1dDdEJBO1dBQ0E7V0FDQTtXQUNBO1dBQ0E7V0FDQSxnQ0FBZ0MsWUFBWTtXQUM1QztXQUNBLEU7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx3Q0FBd0MseUNBQXlDO1dBQ2pGO1dBQ0E7V0FDQSxFOzs7OztXQ1BBLHdGOzs7OztXQ0FBO1dBQ0E7V0FDQTtXQUNBLHNEQUFzRCxrQkFBa0I7V0FDeEU7V0FDQSwrQ0FBK0MsY0FBYztXQUM3RCxFOzs7Ozs7Ozs7Ozs7Ozs7QUNOTyxNQUFNRywyQkFBMkIsR0FBRyxZQUFZLENBQUMsTUFBTSwyUkFBUCxFQUFtRzNCLFlBQW5KO0FBQ0EsTUFBTTRCLGdCQUFnQixHQUFHLFlBQVksQ0FBQyxNQUFNLHFRQUFQLEVBQXdGZCxZQUE3SCxDIiwiZmlsZSI6ImpzYWN0aW9ucy5qcyIsInNvdXJjZXNDb250ZW50IjpbIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcGFyYW0ge3N0cmluZ30gdVVJRFxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gUmVkaXJlY3RQYWdlKHVVSUQpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHJcblx0dmFyIGZvcm0gPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdmb3JtJyk7XHJcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGZvcm0pO1xyXG4gICAgZm9ybS5tZXRob2QgPSAncG9zdCc7XHJcbiAgICBmb3JtLmFjdGlvbiA9ICcvc2lnbmluLyc7XHJcblx0dmFyIGlucHV0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnaW5wdXQnKTtcclxuXHRcdGlucHV0LnR5cGUgPSAnaGlkZGVuJztcclxuXHRcdGlucHV0Lm5hbWUgPSAndXVpZCc7XHJcbiAgICAgICAgaW5wdXQudmFsdWUgPSB1VUlEO1xyXG4gICAgICAgIGZvcm0uYXBwZW5kQ2hpbGQoaW5wdXQpO1xyXG4gICAgXHJcbiAgICBmb3JtLnN1Ym1pdCgpO1xyXG5cclxuXHRyZXR1cm47XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcGFyYW0ge3N0cmluZ30gdG9rZW5cclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX0NsaXBCb2FyZCh0b2tlbikge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG4gZnVuY3Rpb24gZHYoKXtcclxudmFyIGNvcHlUZXh0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJ0ZXN0XCIpO1xyXG4gICBjb3B5VGV4dC52YWx1ZSA9IHRva2VuO1xyXG4gIGNvcHlUZXh0LnNlbGVjdCgpO1xyXG4gIGNvcHlUZXh0LnNldFNlbGVjdGlvblJhbmdlKDAsIDk5OTk5KVxyXG4gIGRvY3VtZW50LmV4ZWNDb21tYW5kKFwiY29weVwiKTtcclxuIH0gIFxyXG5cclxuZHYoKTtcclxuXHJcbmxldCB0aW1lb3V0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Rlc3R0Jyk7XHJcbiAgIHRpbWVvdXQuc3R5bGUuZGlzcGxheSA9ICdibG9jaycgO1xyXG4gICAgICAgICAgIHNldFRpbWVvdXQoaGlkZUVsZW1lbnQsIDMwMDApIC8vbWlsbGlzZWNvbmRzIHVudGlsIHRpbWVvdXQvL1xyXG4gICAgICBcclxuXHJcbiBmdW5jdGlvbiBoaWRlRWxlbWVudCgpIHtcclxuICAgICAgICAgICAgICAgIHRpbWVvdXQuc3R5bGUuZGlzcGxheSA9ICdub25lJyA7XHJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIH1cclxuXHJcblxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCJtb2R1bGUuZXhwb3J0cyA9IF9fV0VCUEFDS19FWFRFUk5BTF9NT0RVTEVfYmlnX2pzX187IiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBGb3Jnb3RQYXNzd29yZCRSZWRpcmVjdFBhZ2UgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRDovUHJvamVjdHMvUmFwaWRHcmFudC1tYWluL2phdmFzY3JpcHRzb3VyY2UvZm9yZ290cGFzc3dvcmQvYWN0aW9ucy9SZWRpcmVjdFBhZ2VcIikpLlJlZGlyZWN0UGFnZTtcbmV4cG9ydCBjb25zdCBVR1MkSlNfQ2xpcEJvYXJkID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkQ6L1Byb2plY3RzL1JhcGlkR3JhbnQtbWFpbi9qYXZhc2NyaXB0c291cmNlL3Vncy9hY3Rpb25zL0pTX0NsaXBCb2FyZFwiKSkuSlNfQ2xpcEJvYXJkO1xuIl0sInNvdXJjZVJvb3QiOiIifQ==