define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\forgotpassword\\actions\\RedirectPage.js":
/*!********************************************************************************************************!*\
  !*** D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\forgotpassword\actions\RedirectPage.js ***!
  \********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "RedirectPage": () => (/* binding */ RedirectPage)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uUID
 * @returns {Promise.<void>}
 */

async function RedirectPage(uUID) {
  // BEGIN USER CODE
  var form = document.createElement('form');
  document.body.appendChild(form);
  form.method = 'post';
  form.action = '/signin/';
  var input = document.createElement('input');
  input.type = 'hidden';
  input.name = 'uuid';
  input.value = uUID;
  form.appendChild(input);
  form.submit();
  return; // END USER CODE
}

/***/ }),

/***/ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\ugs\\actions\\JS_ClipBoard.js":
/*!*********************************************************************************************!*\
  !*** D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\ugs\actions\JS_ClipBoard.js ***!
  \*********************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_ClipBoard": () => (/* binding */ JS_ClipBoard)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} token
 * @returns {Promise.<void>}
 */

async function JS_ClipBoard(token) {
  // BEGIN USER CODE
  function dv() {
    var copyText = document.getElementById("test");
    copyText.value = token;
    copyText.select();
    copyText.setSelectionRange(0, 99999);
    document.execCommand("copy");
  }

  dv();
  let timeout = document.getElementById('testt');
  timeout.style.display = 'block';
  setTimeout(hideElement, 3000); //milliseconds until timeout//

  function hideElement() {
    timeout.style.display = 'none';
  } // END USER CODE

}

/***/ }),

/***/ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\ugs\\actions\\JavaScript_removeParenthesis.js":
/*!*************************************************************************************************************!*\
  !*** D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\ugs\actions\JavaScript_removeParenthesis.js ***!
  \*************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JavaScript_removeParenthesis": () => (/* binding */ JavaScript_removeParenthesis)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} json
 * @returns {Promise.<string>}
 */

async function JavaScript_removeParenthesis(json) {
  // BEGIN USER CODE
  let x = json;
  x = x.replace(/[{()}]/g, '');
  x = x.replace(/:/g, '');
  x = x.replaceAll("title", "");
  x = x.replaceAll('"', '');
  x = x.replace(/[\[\]']+/g, '');
  return x; // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!****************************************************************************!*\
  !*** D:\TECHNICAL_PART\Mendix\RapidGrant-main\deployment\tmp\jsactions.js ***!
  \****************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "ForgotPassword$RedirectPage": () => (/* binding */ ForgotPassword$RedirectPage),
/* harmony export */   "UGS$JavaScript_removeParenthesis": () => (/* binding */ UGS$JavaScript_removeParenthesis),
/* harmony export */   "UGS$JS_ClipBoard": () => (/* binding */ UGS$JS_ClipBoard)
/* harmony export */ });
const ForgotPassword$RedirectPage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\forgotpassword\actions\RedirectPage */ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\forgotpassword\\actions\\RedirectPage.js"))).RedirectPage;
const UGS$JavaScript_removeParenthesis = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\ugs\actions\JavaScript_removeParenthesis */ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\ugs\\actions\\JavaScript_removeParenthesis.js"))).JavaScript_removeParenthesis;
const UGS$JS_ClipBoard = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! D:\TECHNICAL_PART\Mendix\RapidGrant-main\javascriptsource\ugs\actions\JS_ClipBoard */ "D:\\TECHNICAL_PART\\Mendix\\RapidGrant-main\\javascriptsource\\ugs\\actions\\JS_ClipBoard.js"))).JS_ClipBoard;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vRDpcXFRFQ0hOSUNBTF9QQVJUXFxNZW5kaXhcXFJhcGlkR3JhbnQtbWFpblxcamF2YXNjcmlwdHNvdXJjZVxcZm9yZ290cGFzc3dvcmRcXGFjdGlvbnNcXFJlZGlyZWN0UGFnZS5qcyIsIndlYnBhY2s6Ly8vRDpcXFRFQ0hOSUNBTF9QQVJUXFxNZW5kaXhcXFJhcGlkR3JhbnQtbWFpblxcamF2YXNjcmlwdHNvdXJjZVxcdWdzXFxhY3Rpb25zXFxKU19DbGlwQm9hcmQuanMiLCJ3ZWJwYWNrOi8vL0Q6XFxURUNITklDQUxfUEFSVFxcTWVuZGl4XFxSYXBpZEdyYW50LW1haW5cXGphdmFzY3JpcHRzb3VyY2VcXHVnc1xcYWN0aW9uc1xcSmF2YVNjcmlwdF9yZW1vdmVQYXJlbnRoZXNpcy5qcyIsIndlYnBhY2s6Ly8vZXh0ZXJuYWwgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9jb21wYXQgZ2V0IGRlZmF1bHQgZXhwb3J0Iiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvZGVmaW5lIHByb3BlcnR5IGdldHRlcnMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9oYXNPd25Qcm9wZXJ0eSBzaG9ydGhhbmQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9tYWtlIG5hbWVzcGFjZSBvYmplY3QiLCJ3ZWJwYWNrOi8vL0Q6XFxURUNITklDQUxfUEFSVFxcTWVuZGl4XFxSYXBpZEdyYW50LW1haW5cXGRlcGxveW1lbnRcXHRtcFxcanNhY3Rpb25zLmpzIl0sIm5hbWVzIjpbIlJlZGlyZWN0UGFnZSIsInVVSUQiLCJmb3JtIiwiZG9jdW1lbnQiLCJjcmVhdGVFbGVtZW50IiwiYm9keSIsImFwcGVuZENoaWxkIiwibWV0aG9kIiwiYWN0aW9uIiwiaW5wdXQiLCJ0eXBlIiwibmFtZSIsInZhbHVlIiwic3VibWl0IiwiSlNfQ2xpcEJvYXJkIiwidG9rZW4iLCJkdiIsImNvcHlUZXh0IiwiZ2V0RWxlbWVudEJ5SWQiLCJzZWxlY3QiLCJzZXRTZWxlY3Rpb25SYW5nZSIsImV4ZWNDb21tYW5kIiwidGltZW91dCIsInN0eWxlIiwiZGlzcGxheSIsInNldFRpbWVvdXQiLCJoaWRlRWxlbWVudCIsIkphdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXMiLCJqc29uIiwieCIsInJlcGxhY2UiLCJyZXBsYWNlQWxsIiwiRm9yZ290UGFzc3dvcmQkUmVkaXJlY3RQYWdlIiwiVUdTJEphdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXMiLCJVR1MkSlNfQ2xpcEJvYXJkIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBOztBQUNPLGVBQWVBLFlBQWYsQ0FBNEJDLElBQTVCLEVBQWtDO0FBQ3hDO0FBRUEsTUFBSUMsSUFBSSxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsTUFBdkIsQ0FBWDtBQUNHRCxVQUFRLENBQUNFLElBQVQsQ0FBY0MsV0FBZCxDQUEwQkosSUFBMUI7QUFDQUEsTUFBSSxDQUFDSyxNQUFMLEdBQWMsTUFBZDtBQUNBTCxNQUFJLENBQUNNLE1BQUwsR0FBYyxVQUFkO0FBQ0gsTUFBSUMsS0FBSyxHQUFHTixRQUFRLENBQUNDLGFBQVQsQ0FBdUIsT0FBdkIsQ0FBWjtBQUNDSyxPQUFLLENBQUNDLElBQU4sR0FBYSxRQUFiO0FBQ0FELE9BQUssQ0FBQ0UsSUFBTixHQUFhLE1BQWI7QUFDTUYsT0FBSyxDQUFDRyxLQUFOLEdBQWNYLElBQWQ7QUFDQUMsTUFBSSxDQUFDSSxXQUFMLENBQWlCRyxLQUFqQjtBQUVKUCxNQUFJLENBQUNXLE1BQUw7QUFFSCxTQWZ3QyxDQWdCeEM7QUFDQSxDOzs7Ozs7Ozs7Ozs7Ozs7O0FDakNEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQyxZQUFmLENBQTRCQyxLQUE1QixFQUFtQztBQUN6QztBQUNBLFdBQVNDLEVBQVQsR0FBYTtBQUNkLFFBQUlDLFFBQVEsR0FBR2QsUUFBUSxDQUFDZSxjQUFULENBQXdCLE1BQXhCLENBQWY7QUFDR0QsWUFBUSxDQUFDTCxLQUFULEdBQWlCRyxLQUFqQjtBQUNERSxZQUFRLENBQUNFLE1BQVQ7QUFDQUYsWUFBUSxDQUFDRyxpQkFBVCxDQUEyQixDQUEzQixFQUE4QixLQUE5QjtBQUNBakIsWUFBUSxDQUFDa0IsV0FBVCxDQUFxQixNQUFyQjtBQUNBOztBQUVGTCxJQUFFO0FBRUYsTUFBSU0sT0FBTyxHQUFHbkIsUUFBUSxDQUFDZSxjQUFULENBQXdCLE9BQXhCLENBQWQ7QUFDR0ksU0FBTyxDQUFDQyxLQUFSLENBQWNDLE9BQWQsR0FBd0IsT0FBeEI7QUFDUUMsWUFBVSxDQUFDQyxXQUFELEVBQWMsSUFBZCxDQUFWLENBZCtCLENBY0Q7O0FBR3hDLFdBQVNBLFdBQVQsR0FBdUI7QUFDUkosV0FBTyxDQUFDQyxLQUFSLENBQWNDLE9BQWQsR0FBd0IsTUFBeEI7QUFDZSxHQW5CVyxDQXNCekM7O0FBQ0EsQzs7Ozs7Ozs7Ozs7Ozs7OztBQ3ZDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUcsNEJBQWYsQ0FBNENDLElBQTVDLEVBQWtEO0FBQ3hEO0FBQ0EsTUFBSUMsQ0FBQyxHQUFHRCxJQUFSO0FBQ0FDLEdBQUMsR0FBR0EsQ0FBQyxDQUFDQyxPQUFGLENBQVUsU0FBVixFQUFxQixFQUFyQixDQUFKO0FBQ0FELEdBQUMsR0FBR0EsQ0FBQyxDQUFDQyxPQUFGLENBQVUsSUFBVixFQUFlLEVBQWYsQ0FBSjtBQUNBRCxHQUFDLEdBQUdBLENBQUMsQ0FBQ0UsVUFBRixDQUFhLE9BQWIsRUFBcUIsRUFBckIsQ0FBSjtBQUNBRixHQUFDLEdBQUdBLENBQUMsQ0FBQ0UsVUFBRixDQUFhLEdBQWIsRUFBaUIsRUFBakIsQ0FBSjtBQUNBRixHQUFDLEdBQUVBLENBQUMsQ0FBQ0MsT0FBRixDQUFVLFdBQVYsRUFBc0IsRUFBdEIsQ0FBSDtBQUNBLFNBQU9ELENBQVAsQ0FSd0QsQ0FTeEQ7QUFDQSxDOzs7Ozs7Ozs7O0FDMUJELG9EOzs7Ozs7VUNBQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBOztVQUVBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBOzs7OztXQ3RCQTtXQUNBO1dBQ0E7V0FDQTtXQUNBO1dBQ0EsZ0NBQWdDLFlBQVk7V0FDNUM7V0FDQSxFOzs7OztXQ1BBO1dBQ0E7V0FDQTtXQUNBO1dBQ0Esd0NBQXdDLHlDQUF5QztXQUNqRjtXQUNBO1dBQ0EsRTs7Ozs7V0NQQSx3Rjs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSxzREFBc0Qsa0JBQWtCO1dBQ3hFO1dBQ0EsK0NBQStDLGNBQWM7V0FDN0QsRTs7Ozs7Ozs7Ozs7Ozs7OztBQ05PLE1BQU1HLDJCQUEyQixHQUFHLFlBQVksQ0FBQyxNQUFNLG9TQUFQLEVBQWdIaEMsWUFBaEs7QUFDQSxNQUFNaUMsZ0NBQWdDLEdBQUcsWUFBWSxDQUFDLE1BQU0sOFNBQVAsRUFBcUhOLDRCQUExSztBQUNBLE1BQU1PLGdCQUFnQixHQUFHLFlBQVksQ0FBQyxNQUFNLDhRQUFQLEVBQXFHcEIsWUFBMUksQyIsImZpbGUiOiJqc2FjdGlvbnMuanMiLCJzb3VyY2VzQ29udGVudCI6WyIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtzdHJpbmd9IHVVSURcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFJlZGlyZWN0UGFnZSh1VUlEKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblxyXG5cdHZhciBmb3JtID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO1xyXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChmb3JtKTtcclxuICAgIGZvcm0ubWV0aG9kID0gJ3Bvc3QnO1xyXG4gICAgZm9ybS5hY3Rpb24gPSAnL3NpZ25pbi8nO1xyXG5cdHZhciBpbnB1dCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2lucHV0Jyk7XHJcblx0XHRpbnB1dC50eXBlID0gJ2hpZGRlbic7XHJcblx0XHRpbnB1dC5uYW1lID0gJ3V1aWQnO1xyXG4gICAgICAgIGlucHV0LnZhbHVlID0gdVVJRDtcclxuICAgICAgICBmb3JtLmFwcGVuZENoaWxkKGlucHV0KTtcclxuICAgIFxyXG4gICAgZm9ybS5zdWJtaXQoKTtcclxuXHJcblx0cmV0dXJuO1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtzdHJpbmd9IHRva2VuXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19DbGlwQm9hcmQodG9rZW4pIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuIGZ1bmN0aW9uIGR2KCl7XHJcbnZhciBjb3B5VGV4dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwidGVzdFwiKTtcclxuICAgY29weVRleHQudmFsdWUgPSB0b2tlbjtcclxuICBjb3B5VGV4dC5zZWxlY3QoKTtcclxuICBjb3B5VGV4dC5zZXRTZWxlY3Rpb25SYW5nZSgwLCA5OTk5OSlcclxuICBkb2N1bWVudC5leGVjQ29tbWFuZChcImNvcHlcIik7XHJcbiB9ICBcclxuXHJcbmR2KCk7XHJcblxyXG5sZXQgdGltZW91dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd0ZXN0dCcpO1xyXG4gICB0aW1lb3V0LnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snIDtcclxuICAgICAgICAgICBzZXRUaW1lb3V0KGhpZGVFbGVtZW50LCAzMDAwKSAvL21pbGxpc2Vjb25kcyB1bnRpbCB0aW1lb3V0Ly9cclxuICAgICAgXHJcblxyXG4gZnVuY3Rpb24gaGlkZUVsZW1lbnQoKSB7XHJcbiAgICAgICAgICAgICAgICB0aW1lb3V0LnN0eWxlLmRpc3BsYXkgPSAnbm9uZScgO1xyXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9XHJcblxyXG5cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSBqc29uXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxzdHJpbmc+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEphdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXMoanNvbikge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdGxldCB4ID0ganNvbiA7XHJcblx0eCA9IHgucmVwbGFjZSgvW3soKX1dL2csICcnKTtcclxuXHR4ID0geC5yZXBsYWNlKC86L2csJycpO1xyXG5cdHggPSB4LnJlcGxhY2VBbGwoXCJ0aXRsZVwiLFwiXCIpO1xyXG5cdHggPSB4LnJlcGxhY2VBbGwoJ1wiJywnJyk7XHJcblx0eD0geC5yZXBsYWNlKC9bXFxbXFxdJ10rL2csJycpO1xyXG5cdHJldHVybiB4O1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCJtb2R1bGUuZXhwb3J0cyA9IF9fV0VCUEFDS19FWFRFUk5BTF9NT0RVTEVfYmlnX2pzX187IiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBGb3Jnb3RQYXNzd29yZCRSZWRpcmVjdFBhZ2UgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRDovVEVDSE5JQ0FMX1BBUlQvTWVuZGl4L1JhcGlkR3JhbnQtbWFpbi9qYXZhc2NyaXB0c291cmNlL2ZvcmdvdHBhc3N3b3JkL2FjdGlvbnMvUmVkaXJlY3RQYWdlXCIpKS5SZWRpcmVjdFBhZ2U7XG5leHBvcnQgY29uc3QgVUdTJEphdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXMgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRDovVEVDSE5JQ0FMX1BBUlQvTWVuZGl4L1JhcGlkR3JhbnQtbWFpbi9qYXZhc2NyaXB0c291cmNlL3Vncy9hY3Rpb25zL0phdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXNcIikpLkphdmFTY3JpcHRfcmVtb3ZlUGFyZW50aGVzaXM7XG5leHBvcnQgY29uc3QgVUdTJEpTX0NsaXBCb2FyZCA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJEOi9URUNITklDQUxfUEFSVC9NZW5kaXgvUmFwaWRHcmFudC1tYWluL2phdmFzY3JpcHRzb3VyY2UvdWdzL2FjdGlvbnMvSlNfQ2xpcEJvYXJkXCIpKS5KU19DbGlwQm9hcmQ7XG4iXSwic291cmNlUm9vdCI6IiJ9