CREATE TABLE "pushnotifications$notification" (
	"id" BIGINT NOT NULL,
	"notificationdate" TIMESTAMP NULL,
	"message" VARCHAR_IGNORECASE(200) NULL,
	"isread" BOOLEAN NULL,
	"subject" VARCHAR_IGNORECASE(200) NULL,
	"notificationcategory" VARCHAR_IGNORECASE(11) NULL,
	PRIMARY KEY("id"));
INSERT INTO "mendixsystem$entity" ("id", 
"entity_name", 
"table_name", 
"remote", 
"remote_primary_key")
 VALUES ('dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'PushNotifications.Notification', 
'pushnotifications$notification', 
false, 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('ab6b7627-3625-4b15-8fb0-d16df63e08c3', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'NotificationDate', 
'notificationdate', 
20, 
0, 
'', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('20972ebf-f8c2-4d3e-a443-774660233267', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'Message', 
'message', 
30, 
200, 
'', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('454e8cb8-4aa3-4b25-b2cd-c18fa9e77600', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'IsRead', 
'isread', 
10, 
0, 
'false', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('cd36e76c-e0ab-446b-a065-884f284f8713', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'Subject', 
'subject', 
30, 
200, 
'', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('a75c1bec-44d0-48a1-8036-3193eed13296', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'NotificationCategory', 
'notificationcategory', 
40, 
11, 
'', 
false);
CREATE TABLE "pushnotifications$notification_sentfrom" (
	"pushnotifications$notificationid" BIGINT NOT NULL,
	"administration$accountid" BIGINT NOT NULL,
	PRIMARY KEY("pushnotifications$notificationid","administration$accountid"),
	CONSTRAINT "uniq_pushnotifications$notification_sentfrom_pushnotifications$notificationid" UNIQUE ("pushnotifications$notificationid"));
CREATE INDEX "idx_pushnotifications$notification_sentfrom_administration$account_pushnotifications$notification" ON "pushnotifications$notification_sentfrom" ("administration$accountid" ASC,"pushnotifications$notificationid" ASC);
INSERT INTO "mendixsystem$association" ("id", 
"association_name", 
"table_name", 
"parent_entity_id", 
"child_entity_id", 
"parent_column_name", 
"child_column_name", 
"index_name")
 VALUES ('4c365d06-a60a-414d-bb18-6d17edd84117', 
'PushNotifications.Notification_SentFrom', 
'pushnotifications$notification_sentfrom', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'3078a23e-13b2-4a9b-84e4-2881fdee53c6', 
'pushnotifications$notificationid', 
'administration$accountid', 
'idx_pushnotifications$notification_sentfrom_administration$account_pushnotifications$notification');
INSERT INTO "mendixsystem$unique_constraint" ("name", 
"table_id", 
"column_id")
 VALUES ('uniq_pushnotifications$notification_sentfrom_pushnotifications$notificationid', 
'4c365d06-a60a-414d-bb18-6d17edd84117', 
'6a2dc789-4ba1-3fca-a796-3312feaf2a53');
CREATE TABLE "pushnotifications$notification_sentto" (
	"pushnotifications$notificationid" BIGINT NOT NULL,
	"administration$accountid" BIGINT NOT NULL,
	PRIMARY KEY("pushnotifications$notificationid","administration$accountid"),
	CONSTRAINT "uniq_pushnotifications$notification_sentto_pushnotifications$notificationid" UNIQUE ("pushnotifications$notificationid"));
CREATE INDEX "idx_pushnotifications$notification_sentto_administration$account_pushnotifications$notification" ON "pushnotifications$notification_sentto" ("administration$accountid" ASC,"pushnotifications$notificationid" ASC);
INSERT INTO "mendixsystem$association" ("id", 
"association_name", 
"table_name", 
"parent_entity_id", 
"child_entity_id", 
"parent_column_name", 
"child_column_name", 
"index_name")
 VALUES ('4ab588f5-b229-4083-85ca-e8dd6cdbeec8', 
'PushNotifications.Notification_SentTo', 
'pushnotifications$notification_sentto', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'3078a23e-13b2-4a9b-84e4-2881fdee53c6', 
'pushnotifications$notificationid', 
'administration$accountid', 
'idx_pushnotifications$notification_sentto_administration$account_pushnotifications$notification');
INSERT INTO "mendixsystem$unique_constraint" ("name", 
"table_id", 
"column_id")
 VALUES ('uniq_pushnotifications$notification_sentto_pushnotifications$notificationid', 
'4ab588f5-b229-4083-85ca-e8dd6cdbeec8', 
'422e2b91-06da-3219-8a96-f9f720770c30');
CREATE TABLE "pushnotifications$notification_messagetemplate" (
	"pushnotifications$notificationid" BIGINT NOT NULL,
	"pushnotifications$messagetemplateid" BIGINT NOT NULL,
	PRIMARY KEY("pushnotifications$notificationid","pushnotifications$messagetemplateid"),
	CONSTRAINT "uniq_pushnotifications$notification_messagetemplate_pushnotifications$notificationid" UNIQUE ("pushnotifications$notificationid"));
CREATE INDEX "idx_pushnotifications$notification_messagetemplate_pushnotifications$messagetemplate_pushnotifications$notification" ON "pushnotifications$notification_messagetemplate" ("pushnotifications$messagetemplateid" ASC,"pushnotifications$notificationid" ASC);
INSERT INTO "mendixsystem$association" ("id", 
"association_name", 
"table_name", 
"parent_entity_id", 
"child_entity_id", 
"parent_column_name", 
"child_column_name", 
"index_name")
 VALUES ('f191fc77-2320-4a58-a54e-0724cfd14737', 
'PushNotifications.Notification_MessageTemplate', 
'pushnotifications$notification_messagetemplate', 
'dac8d843-1f23-450a-8acb-00ffbc5784e0', 
'b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'pushnotifications$notificationid', 
'pushnotifications$messagetemplateid', 
'idx_pushnotifications$notification_messagetemplate_pushnotifications$messagetemplate_pushnotifications$notification');
INSERT INTO "mendixsystem$unique_constraint" ("name", 
"table_id", 
"column_id")
 VALUES ('uniq_pushnotifications$notification_messagetemplate_pushnotifications$notificationid', 
'f191fc77-2320-4a58-a54e-0724cfd14737', 
'd8932bbb-2676-3181-9edd-931fe851274f');
CREATE TABLE "pushnotifications$messagetemplate" (
	"id" BIGINT NOT NULL,
	"message" VARCHAR_IGNORECASE(2000) NULL,
	"subject" VARCHAR_IGNORECASE(200) NULL,
	"name" VARCHAR_IGNORECASE(200) NULL,
	PRIMARY KEY("id"));
INSERT INTO "mendixsystem$entity" ("id", 
"entity_name", 
"table_name", 
"remote", 
"remote_primary_key")
 VALUES ('b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'PushNotifications.MessageTemplate', 
'pushnotifications$messagetemplate', 
false, 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('fdf3e765-9d83-40d9-9165-156a3c573248', 
'b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'Message', 
'message', 
30, 
2000, 
'', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('39a8dc80-6db0-442a-ad08-4f38763a2c71', 
'b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'Subject', 
'subject', 
30, 
200, 
'', 
false);
INSERT INTO "mendixsystem$attribute" ("id", 
"entity_id", 
"attribute_name", 
"column_name", 
"type", 
"length", 
"default_value", 
"is_auto_number")
 VALUES ('ce30adb2-dbe5-48b4-9bce-de70b5c76897', 
'b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'Name', 
'name', 
30, 
200, 
'', 
false);
CREATE TABLE "pushnotifications$messagetemplate_token" (
	"pushnotifications$messagetemplateid" BIGINT NOT NULL,
	"mxmodelreflection$tokenid" BIGINT NOT NULL,
	PRIMARY KEY("pushnotifications$messagetemplateid","mxmodelreflection$tokenid"));
CREATE INDEX "idx_pushnotifications$messagetemplate_token_mxmodelreflection$token_pushnotifications$messagetemplate" ON "pushnotifications$messagetemplate_token" ("mxmodelreflection$tokenid" ASC,"pushnotifications$messagetemplateid" ASC);
INSERT INTO "mendixsystem$association" ("id", 
"association_name", 
"table_name", 
"parent_entity_id", 
"child_entity_id", 
"parent_column_name", 
"child_column_name", 
"index_name")
 VALUES ('6f22f5fb-b52e-470c-9238-dce3f4e246d1', 
'PushNotifications.MessageTemplate_Token', 
'pushnotifications$messagetemplate_token', 
'b892b63e-77d8-492a-9a49-05e93bd12ae7', 
'29a39ab3-6d01-4e0f-97fa-9c6a459edb4e', 
'pushnotifications$messagetemplateid', 
'mxmodelreflection$tokenid', 
'idx_pushnotifications$messagetemplate_token_mxmodelreflection$token_pushnotifications$messagetemplate');
UPDATE "mendixsystem$version"
 SET "versionnumber" = '4.2', 
"lastsyncdate" = '20210504 17:30:28';
