// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ugs.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the UGS module
	public static administration.proxies.Account account(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Account").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static void act_addAfToGrantee(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Act_addAfToGrantee").withParams(params).execute(context);
	}
	public static void aCT_Approve(IContext context, java.util.List<ugs.proxies.GrantSystem> _grantSystemList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_grantSystemList = null;
		if (_grantSystemList != null)
		{
			listparam_grantSystemList = new java.util.ArrayList<>();
			for (ugs.proxies.GrantSystem obj : _grantSystemList)
				listparam_grantSystemList.add(obj.getMendixObject());
		}
		params.put("GrantSystemList", listparam_grantSystemList);

		Core.microflowCall("UGS.ACT_Approve").withParams(params).execute(context);
	}
	public static void aCT_ApproveRequest(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ApproveRequest").withParams(params).execute(context);
	}
	public static void aCT_Assign_Stage(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Assign_Stage").withParams(params).execute(context);
	}
	public static void act_AssignDummyReviewFormTotheReferenceselector(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Act_AssignDummyReviewFormTotheReferenceselector").withParams(params).execute(context);
	}
	public static boolean act_AssignInterview(IContext context, dynamicform.proxies.WorkflowRoles _currentRole, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CurrentRole", _currentRole == null ? null : _currentRole.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("UGS.Act_AssignInterview").withParams(params).execute(context);
	}
	public static void aCT_CaseManagementCommit(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_CaseManagementCommit").withParams(params).execute(context);
	}
	public static void aCT_CaseManagementPass(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_CaseManagementPass").withParams(params).execute(context);
	}
	public static void aCT_Check_DisbursementAmt(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Check_DisbursementAmt").withParams(params).execute(context);
	}
	public static void act_CheckDocument(IContext context, dynamicform.proxies.Document _document)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Document", _document == null ? null : _document.getMendixObject());
		Core.microflowCall("UGS.Act_CheckDocument").withParams(params).execute(context);
	}
	public static void aCT_CheckEligibility(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_CheckEligibility").withParams(params).execute(context);
	}
	public static void act_CheckGrantTemp(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Act_CheckGrantTemp").withParams(params).execute(context);
	}
	public static void aCT_CloneTest(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_CloneTest").withParams(params).execute(context);
	}
	public static void aCT_CommonReturn(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_CommonReturn").withParams(params).execute(context);
	}
	public static void aCT_Complete_Workflow(IContext context, java.util.List<ugs.proxies.GrantSystem> _grantSystemList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_grantSystemList = null;
		if (_grantSystemList != null)
		{
			listparam_grantSystemList = new java.util.ArrayList<>();
			for (ugs.proxies.GrantSystem obj : _grantSystemList)
				listparam_grantSystemList.add(obj.getMendixObject());
		}
		params.put("GrantSystemList", listparam_grantSystemList);

		Core.microflowCall("UGS.ACT_Complete_Workflow").withParams(params).execute(context);
	}
	public static void aCT_Create_Account(IContext context, ugs.proxies.SignUp _signUp)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SignUp", _signUp == null ? null : _signUp.getMendixObject());
		Core.microflowCall("UGS.ACT_Create_Account").withParams(params).execute(context);
	}
	public static void aCT_Create_ReviewQuestion(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Create_ReviewQuestion").withParams(params).execute(context);
	}
	public static ugs.proxies.SignUp aCT_Create_SignUpObj(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.ACT_Create_SignUpObj").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.SignUp.initialize(context, result);
	}
	public static void aCT_CreateCase(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.ACT_CreateCase").withParams(params).execute(context);
	}
	public static void aCT_CreateCase_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.ACT_CreateCase_2").withParams(params).execute(context);
	}
	public static ugs.proxies.Signature aCT_CreateSign_Obj(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.ACT_CreateSign_Obj").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.Signature.initialize(context, result);
	}
	public static ugs.proxies.Workflow aCT_CreateStage(IContext context, ugs.proxies.Workflow _workflow, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.ACT_CreateStage").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.Workflow.initialize(context, result);
	}
	public static void aCT_CreatNewQues(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_CreatNewQues").withParams(params).execute(context);
	}
	public static void aCT_Doc_View(IContext context, dynamicform.proxies.Document _document, dynamicform.proxies.Doc _doc, dynamicform.proxies.Template _template, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Document", _document == null ? null : _document.getMendixObject());
		params.put("Doc", _doc == null ? null : _doc.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Doc_View").withParams(params).execute(context);
	}
	public static void aCT_DuplicateMF(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_DuplicateMF").withParams(params).execute(context);
	}
	public static void aCT_DuplicateMF_AF(IContext context, dynamicform.proxies.ApplicationForm _aF)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AF", _aF == null ? null : _aF.getMendixObject());
		Core.microflowCall("UGS.ACT_DuplicateMF_AF").withParams(params).execute(context);
	}
	public static void aCT_DynamicWorkflowPassGrant(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_DynamicWorkflowPassGrant").withParams(params).execute(context);
	}
	public static void aCT_DynamicWorkflowPassGrant_2(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_DynamicWorkflowPassGrant_2").withParams(params).execute(context);
	}
	public static void aCT_Eligibilty_Delete(IContext context, ugs.proxies.Eligibility _eligibility, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Eligibility", _eligibility == null ? null : _eligibility.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Eligibilty_Delete").withParams(params).execute(context);
	}
	public static void aCt_ForwardToFA(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACt_ForwardToFA").withParams(params).execute(context);
	}
	public static void aCT_ForwardToFinance(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ForwardToFinance").withParams(params).execute(context);
	}
	public static void aCT_ForwardToGM_HQ(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ForwardToGM_HQ").withParams(params).execute(context);
	}
	public static void aCT_ForwardToInvestigationOfficer(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ForwardToInvestigationOfficer").withParams(params).execute(context);
	}
	public static void aCT_FundSave(IContext context, ugs.proxies.Fundings _fundings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Fundings", _fundings == null ? null : _fundings.getMendixObject());
		Core.microflowCall("UGS.ACT_FundSave").withParams(params).execute(context);
	}
	public static void aCT_GAM_RequestTranscation(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_GAM_RequestTranscation").withParams(params).execute(context);
	}
	public static void aCT_Generate_Document(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Generate_Document").withParams(params).execute(context);
	}
	public static void aCT_GenerateFormPrintout(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_GenerateFormPrintout").withParams(params).execute(context);
	}
	public static administration.proxies.Account aCT_Get_CurrentUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.ACT_Get_CurrentUser").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static java.util.List<ugs.proxies.ReviewQ> act_GetQuestions(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Act_GetQuestions").withParams(params).execute(context);
		java.util.List<ugs.proxies.ReviewQ> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.ReviewQ.initialize(context, obj));
		}
		return result;
	}
	public static void aCT_GMReturn(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_GMReturn").withParams(params).execute(context);
	}
	public static void act_GrantWorkflowsubmit(IContext context, ugs.proxies.GrantSystem _grant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Grant", _grant == null ? null : _grant.getMendixObject());
		Core.microflowCall("UGS.Act_GrantWorkflowsubmit").withParams(params).execute(context);
	}
	public static void aCT_IsDynamic(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_IsDynamic").withParams(params).execute(context);
	}
	public static java.lang.Long aCT_LongAns_WordCount_2(IContext context, dynamicform.proxies.LongAnswer _longAnswer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LongAnswer", _longAnswer == null ? null : _longAnswer.getMendixObject());
		return (java.lang.Long) Core.microflowCall("UGS.ACT_LongAns_WordCount_2").withParams(params).execute(context);
	}
	public static void act_MainReviewForm(IContext context, ugs.proxies.ReviewForm _reviewForm)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		Core.microflowCall("UGS.Act_MainReviewForm").withParams(params).execute(context);
	}
	public static void aCT_NextPage(IContext context, dynamicform.proxies.Template _template, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_NextPage").withParams(params).execute(context);
	}
	public static void aCT_OpenExistingFormPopup(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_OpenExistingFormPopup").withParams(params).execute(context);
	}
	public static void aCT_OpenExistingFormPopupAF(IContext context, dynamicform.proxies.ApplicationForm _aF)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AF", _aF == null ? null : _aF.getMendixObject());
		Core.microflowCall("UGS.ACT_OpenExistingFormPopupAF").withParams(params).execute(context);
	}
	public static void aCT_OpenOrgPopup(IContext context, ugs.proxies.Eligibility _eligibility, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Eligibility", _eligibility == null ? null : _eligibility.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_OpenOrgPopup").withParams(params).execute(context);
	}
	public static void aCT_OpenTestView(IContext context, ugs.proxies.Test _test)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		Core.microflowCall("UGS.ACT_OpenTestView").withParams(params).execute(context);
	}
	public static void act_OpenWorkflowPage(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Act_OpenWorkflowPage").withParams(params).execute(context);
	}
	public static void aCT_Org_Details(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("UGS.ACT_Org_Details").withParams(params).execute(context);
	}
	public static void aCT_Org_Details_2(IContext context, administration.proxies.AccountPasswordData _accountPasswordData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccountPasswordData", _accountPasswordData == null ? null : _accountPasswordData.getMendixObject());
		Core.microflowCall("UGS.ACT_Org_Details_2").withParams(params).execute(context);
	}
	public static void aCT_Prevpage(IContext context, dynamicform.proxies.Template _template, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Prevpage").withParams(params).execute(context);
	}
	public static void aCT_RaiseReuest(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_RaiseReuest").withParams(params).execute(context);
	}
	public static void aCT_Reject_Application(IContext context, java.util.List<ugs.proxies.GrantSystem> _grantSystemList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_grantSystemList = null;
		if (_grantSystemList != null)
		{
			listparam_grantSystemList = new java.util.ArrayList<>();
			for (ugs.proxies.GrantSystem obj : _grantSystemList)
				listparam_grantSystemList.add(obj.getMendixObject());
		}
		params.put("GrantSystemList", listparam_grantSystemList);

		Core.microflowCall("UGS.ACT_Reject_Application").withParams(params).execute(context);
	}
	public static void aCT_ResolveCase(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ResolveCase").withParams(params).execute(context);
	}
	public static void aCT_Reteieve_Reviewform(IContext context, java.util.List<ugs.proxies.GrantSystem> _grantSystemList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_grantSystemList = null;
		if (_grantSystemList != null)
		{
			listparam_grantSystemList = new java.util.ArrayList<>();
			for (ugs.proxies.GrantSystem obj : _grantSystemList)
				listparam_grantSystemList.add(obj.getMendixObject());
		}
		params.put("GrantSystemList", listparam_grantSystemList);

		Core.microflowCall("UGS.ACT_Reteieve_Reviewform").withParams(params).execute(context);
	}
	public static void aCT_Reteieve_Reviewform_2(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Reteieve_Reviewform_2").withParams(params).execute(context);
	}
	public static void aCT_Retrieve_EmailParameter(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Retrieve_EmailParameter").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.History> aCT_Retrieve_FundHistory(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.ACT_Retrieve_FundHistory").withParams(params).execute(context);
		java.util.List<ugs.proxies.History> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.History.initialize(context, obj));
		}
		return result;
	}
	public static void aCT_ReturnForm(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_ReturnForm").withParams(params).execute(context);
	}
	public static void aCT_ReturnToApplicant(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.ACT_ReturnToApplicant").withParams(params).execute(context);
	}
	public static void aCT_Save_Page1(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Save_Page1").withParams(params).execute(context);
	}
	public static void aCT_Save_Page2(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Save_Page2").withParams(params).execute(context);
	}
	public static void aCT_Save_Provider(IContext context, ugs.proxies.Provider _provider)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Provider", _provider == null ? null : _provider.getMendixObject());
		Core.microflowCall("UGS.ACT_Save_Provider").withParams(params).execute(context);
	}
	public static void aCT_Save_ReviewForm(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Save_ReviewForm").withParams(params).execute(context);
	}
	public static void aCT_SaveDraft(IContext context, dynamicform.proxies.Template _template, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_SaveDraft").withParams(params).execute(context);
	}
	public static void act_SaveDummyReviewForm(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.Act_SaveDummyReviewForm").withParams(params).execute(context);
	}
	public static void aCT_SaveQuestion(IContext context, ugs.proxies.TestQuestions _testQuestions)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestQuestions", _testQuestions == null ? null : _testQuestions.getMendixObject());
		Core.microflowCall("UGS.ACT_SaveQuestion").withParams(params).execute(context);
	}
	public static void aCT_SaveTest(IContext context, ugs.proxies.Test _test)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		Core.microflowCall("UGS.ACT_SaveTest").withParams(params).execute(context);
	}
	public static void act_scheduleNewInterview(IContext context, ugs.proxies.Interview _interview)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Interview", _interview == null ? null : _interview.getMendixObject());
		Core.microflowCall("UGS.Act_scheduleNewInterview").withParams(params).execute(context);
	}
	public static void aCT_ScoreTest(IContext context, ugs.proxies.Test _test)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		Core.microflowCall("UGS.ACT_ScoreTest").withParams(params).execute(context);
	}
	public static void aCT_Send_ContractApproval_Mail(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Send_ContractApproval_Mail").withParams(params).execute(context);
	}
	public static void aCT_Send_Email(IContext context, ugs.proxies.Provider _provider)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Provider", _provider == null ? null : _provider.getMendixObject());
		Core.microflowCall("UGS.ACT_Send_Email").withParams(params).execute(context);
	}
	public static java.lang.Long aCT_ShortAns_WordCount_2(IContext context, dynamicform.proxies.ShortAnswer _shortAnswer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ShortAnswer", _shortAnswer == null ? null : _shortAnswer.getMendixObject());
		return (java.lang.Long) Core.microflowCall("UGS.ACT_ShortAns_WordCount_2").withParams(params).execute(context);
	}
	public static void aCT_ShowEdit_Page(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_ShowEdit_Page").withParams(params).execute(context);
	}
	public static void aCT_StartTransaction(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_StartTransaction").withParams(params).execute(context);
	}
	public static void aCT_Submit_ReviewForm(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_Submit_ReviewForm").withParams(params).execute(context);
	}
	public static void aCT_Upload_Docs(IContext context, ugs.proxies.Provider _provider)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Provider", _provider == null ? null : _provider.getMendixObject());
		Core.microflowCall("UGS.ACT_Upload_Docs").withParams(params).execute(context);
	}
	public static void act_UploadNewDocument(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("UGS.Act_UploadNewDocument").withParams(params).execute(context);
	}
	public static void aCT_ViewGrant(IContext context, java.util.List<ugs.proxies.GrantSystem> _grantSystemList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_grantSystemList = null;
		if (_grantSystemList != null)
		{
			listparam_grantSystemList = new java.util.ArrayList<>();
			for (ugs.proxies.GrantSystem obj : _grantSystemList)
				listparam_grantSystemList.add(obj.getMendixObject());
		}
		params.put("GrantSystemList", listparam_grantSystemList);

		Core.microflowCall("UGS.ACT_ViewGrant").withParams(params).execute(context);
	}
	public static void aCT_ViewGrant_GAM(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.ACT_ViewGrant_GAM").withParams(params).execute(context);
	}
	public static void aCT_ViewWorkflow(IContext context, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("UGS.ACT_ViewWorkflow").withParams(params).execute(context);
	}
	public static void aCT_WorkflowCommit(IContext context, ugs.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("UGS.ACT_WorkflowCommit").withParams(params).execute(context);
	}
	public static void add_EligibleCriteria(IContext context, ugs.proxies.Eligibility _eligibility, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Eligibility", _eligibility == null ? null : _eligibility.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Add_EligibleCriteria").withParams(params).execute(context);
	}
	public static void afterstartup_Create_ReviewQuestion(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.Afterstartup_Create_ReviewQuestion").withParams(params).execute(context);
	}
	public static void afterStartUp_Fund(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.AfterStartUp_Fund").withParams(params).execute(context);
	}
	public static ugs.proxies.Eligibility apply_Button_Visible(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Apply_Button_Visible").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.Eligibility.initialize(context, result);
	}
	public static void assign_To_Next_Role(IContext context, ugs.proxies.GrantSystem _grantSystem, java.lang.String _neededUserRole, java.lang.String _current_UserRole)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("NeededUserRole", _neededUserRole);
		params.put("Current_UserRole", _current_UserRole);
		Core.microflowCall("UGS.Assign_To_Next_Role").withParams(params).execute(context);
	}
	public static void availableBalance_Check(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.AvailableBalance_Check").withParams(params).execute(context);
	}
	public static java.lang.String cALC_SetClass(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.String) Core.microflowCall("UGS.CALC_SetClass").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.count> case_count_applicant(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_applicant").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.count> case_count_applicant_2_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_applicant_2_2").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.count> case_count_applicant_2_2_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_applicant_2_2_2").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.count> case_count_FA(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_FA").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.count> case_count_forrwarded(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_forrwarded").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.count> case_count_GM(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.case_count_GM").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static void change_To_Status(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.Change_To_Status").withParams(params).execute(context);
	}
	public static void checkactions(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.checkactions").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template clone_Template_Cloneobject(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Clone_Template_Cloneobject").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void common_History_2(IContext context, ugs.proxies.History _history, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("History", _history == null ? null : _history.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Common_History_2").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.CaseHistory> currentHistory(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.CurrentHistory").withParams(params).execute(context);
		java.util.List<ugs.proxies.CaseHistory> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.CaseHistory.initialize(context, obj));
		}
		return result;
	}
	public static void delete_Grant(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Delete_Grant").withParams(params).execute(context);
	}
	public static void deleteTokens(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.DeleteTokens").withParams(params).execute(context);
	}
	public static void drag_Drop_FormCategories(IContext context, dynamicform.proxies.Template_DnD _template_DnD)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template_DnD", _template_DnD == null ? null : _template_DnD.getMendixObject());
		Core.microflowCall("UGS.Drag_Drop_FormCategories").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.count> dS_Approved_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Approved_Count").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static ugs.proxies.Interview dS_AssignInterviewObject(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.DS_AssignInterviewObject").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.Interview.initialize(context, result);
	}
	public static java.util.List<administration.proxies.Account> dS_Auto_OrganisationName(IContext context, ugs.proxies.SignUp _signUp)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SignUp", _signUp == null ? null : _signUp.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Auto_OrganisationName").withParams(params).execute(context);
		java.util.List<administration.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(administration.proxies.Account.initialize(context, obj));
		}
		return result;
	}
	public static dynamicform.proxies.Template dS_FirstForm(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.DS_FirstForm").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static ugs.proxies.count dS_MyTask_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.DS_MyTask_Count").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.count.initialize(context, result);
	}
	public static java.util.List<ugs.proxies.count> dS_Rejected_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Rejected_Count").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> dS_Retreive_Status(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Retreive_Status").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.Eligibility> dS_Retrieve_Applicant_eligibilitylist(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Retrieve_Applicant_eligibilitylist").withParams(params).execute(context);
		java.util.List<ugs.proxies.Eligibility> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.Eligibility.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.GrantSystem> dS_Retrieve_Grants(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Retrieve_Grants").withParams(params).execute(context);
		java.util.List<ugs.proxies.GrantSystem> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.GrantSystem.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.History> dS_Retrieve_ReviewHistory(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_Retrieve_ReviewHistory").withParams(params).execute(context);
		java.util.List<ugs.proxies.History> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.History.initialize(context, obj));
		}
		return result;
	}
	public static ugs.proxies.count dS_SLA_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.DS_SLA_Count").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.count.initialize(context, result);
	}
	public static java.util.List<ugs.proxies.count> dS_UnderReview_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.DS_UnderReview_Count").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
	public static void eligibilityQuestion(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.EligibilityQuestion").withParams(params).execute(context);
	}
	public static java.util.List<imap_pop3_email.proxies.EmailMessage> emailSubjectFilter(IContext context, imap_pop3_email.proxies.EmailAccount _emailAccount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailAccount", _emailAccount == null ? null : _emailAccount.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.EmailSubjectFilter").withParams(params).execute(context);
		java.util.List<imap_pop3_email.proxies.EmailMessage> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(imap_pop3_email.proxies.EmailMessage.initialize(context, obj));
		}
		return result;
	}
	public static void emoji_rating_2(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.emoji_rating_2").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.History> gET_Current_History(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.GET_Current_History").withParams(params).execute(context);
		java.util.List<ugs.proxies.History> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.History.initialize(context, obj));
		}
		return result;
	}
	public static dynamicform.proxies.WorkflowRoles get_CurrentWorkflow(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Get_CurrentWorkflow").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.WorkflowRoles.initialize(context, result);
	}
	public static system.proxies.UserRole get_Dashboard_Name(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Get_Dashboard_Name").withParams(params).execute(context);
		return result == null ? null : system.proxies.UserRole.initialize(context, result);
	}
	public static void icon_images(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.Icon_images").withParams(params).execute(context);
	}
	public static ugs.proxies.History interview(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Interview").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.History.initialize(context, result);
	}
	public static void iVK_ConfigStep2_2(IContext context, imap_pop3_email.proxies.EmailAccount _emailAccount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailAccount", _emailAccount == null ? null : _emailAccount.getMendixObject());
		Core.microflowCall("UGS.IVK_ConfigStep2_2").withParams(params).execute(context);
	}
	public static void mF_ApplyGrant_2(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.MF_ApplyGrant_2").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Intermediate> microflow(IContext context, dynamicform.proxies.Intermediate _intermediate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Intermediate", _intermediate == null ? null : _intermediate.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Microflow").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Intermediate> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Intermediate.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Element> microflow_2(IContext context, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Microflow_2").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Element> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Element.initialize(context, obj));
		}
		return result;
	}
	public static ugs.proxies.SignUp microflow_pass(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Microflow_pass").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.SignUp.initialize(context, result);
	}
	public static void microflow12(IContext context, dynamicform.proxies.Icons _icons)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Icons", _icons == null ? null : _icons.getMendixObject());
		Core.microflowCall("UGS.Microflow12").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.History> multi_history(IContext context, ugs.proxies.History _history)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("History", _history == null ? null : _history.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.multi_history").withParams(params).execute(context);
		java.util.List<ugs.proxies.History> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.History.initialize(context, obj));
		}
		return result;
	}
	public static void multilevel2(IContext context, ugs.proxies.History _history)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("History", _history == null ? null : _history.getMendixObject());
		Core.microflowCall("UGS.multilevel2").withParams(params).execute(context);
	}
	public static void multiLevelHistory(IContext context, ugs.proxies.CaseHistory _caseHistory)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseHistory", _caseHistory == null ? null : _caseHistory.getMendixObject());
		Core.microflowCall("UGS.MultiLevelHistory").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.CaseHistory> multiLevelHistory1(IContext context, ugs.proxies.CaseHistory _caseHistory)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseHistory", _caseHistory == null ? null : _caseHistory.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.MultiLevelHistory1").withParams(params).execute(context);
		java.util.List<ugs.proxies.CaseHistory> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.CaseHistory.initialize(context, obj));
		}
		return result;
	}
	public static void oCE_Case_AppicantCommit(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.OCE_Case_AppicantCommit").withParams(params).execute(context);
	}
	public static void oCH_ActivateTokens2(IContext context, ugs.proxies.GrantSystem _grantSystem, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.OCH_ActivateTokens2").withParams(params).execute(context);
	}
	public static void oCH_ActivateTokens3(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_ActivateTokens3").withParams(params).execute(context);
	}
	public static void oCH_Check_AvaliableFundAmound(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_Check_AvaliableFundAmound").withParams(params).execute(context);
	}
	public static void oCH_Check_Disbursement(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_Check_Disbursement").withParams(params).execute(context);
	}
	public static void oCH_Check_Status_Others(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.OCH_Check_Status_Others").withParams(params).execute(context);
	}
	public static void oCH_Commit(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.OCH_Commit").withParams(params).execute(context);
	}
	public static void oCH_Dividing_Amount(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_Dividing_Amount").withParams(params).execute(context);
	}
	public static void oCH_five(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_five").withParams(params).execute(context);
	}
	public static void oCH_four(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_four").withParams(params).execute(context);
	}
	public static void oCH_FundingAmount_Display(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_FundingAmount_Display").withParams(params).execute(context);
	}
	public static void oCH_Get_DialCode(IContext context, dynamicform.proxies.Country _country, dynamicform.proxies.Template _template, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Country", _country == null ? null : _country.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_Get_DialCode").withParams(params).execute(context);
	}
	public static void oCH_NumberRating_Avg(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_NumberRating_Avg").withParams(params).execute(context);
	}
	public static void oCH_One(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_One").withParams(params).execute(context);
	}
	public static void oCH_OtherQuestion(IContext context, ugs.proxies.ReviewQ _reviewForm)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		Core.microflowCall("UGS.OCH_OtherQuestion").withParams(params).execute(context);
	}
	public static void oCH_RatingType(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.OCH_RatingType").withParams(params).execute(context);
	}
	public static void oCH_StarRating_Avg(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_StarRating_Avg").withParams(params).execute(context);
	}
	public static void oCH_three(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_three").withParams(params).execute(context);
	}
	public static void oCH_two(IContext context, ugs.proxies.ReviewQ _reviewForm, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ReviewForm", _reviewForm == null ? null : _reviewForm.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.OCH_two").withParams(params).execute(context);
	}
	public static void oCK_FormViewer(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("UGS.OCK_FormViewer").withParams(params).execute(context);
	}
	public static ugs.proxies.CaseMangement popUpCaseManagementGM(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.PopUpCaseManagementGM").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.CaseMangement.initialize(context, result);
	}
	public static java.util.List<ugs.proxies.Test> rET_AllTests(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.RET_AllTests").withParams(params).execute(context);
		java.util.List<ugs.proxies.Test> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.Test.initialize(context, obj));
		}
		return result;
	}
	public static ugs.proxies.GrantSystem rET_ApplicantDetails(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.RET_ApplicantDetails").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.GrantSystem.initialize(context, result);
	}
	public static java.util.List<administration.proxies.Account> ret_ApplicantName(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Ret_ApplicantName").withParams(params).execute(context);
		java.util.List<administration.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(administration.proxies.Account.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<ugs.proxies.GrantSystem> ret_ExistingGrantName(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Ret_ExistingGrantName").withParams(params).execute(context);
		java.util.List<ugs.proxies.GrantSystem> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.GrantSystem.initialize(context, obj));
		}
		return result;
	}
	public static ugs.proxies.FileDocument ret_FileDocuments(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.Ret_FileDocuments").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.FileDocument.initialize(context, result);
	}
	public static java.util.List<dynamicform.proxies.Template> rET_ListOfTemplates(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.RET_ListOfTemplates").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Template> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Template.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Template> rET_ListOfTemplates_AF(IContext context, dynamicform.proxies.ApplicationForm _aF)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AF", _aF == null ? null : _aF.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.RET_ListOfTemplates_AF").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Template> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Template.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> rET_PrevStatus(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.RET_PrevStatus").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.WorkflowRoles> rET_PrevStatus_Stages(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.RET_PrevStatus_Stages").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.WorkflowRoles> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.WorkflowRoles.initialize(context, obj));
		}
		return result;
	}
	public static void retrieve_CountryCode(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.Retrieve_CountryCode").withParams(params).execute(context);
	}
	public static void retrieve_Email_Content(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Retrieve_Email_Content").withParams(params).execute(context);
	}
	public static void retrieve_Email_Content_Actions(IContext context, dynamicform.proxies.WorkflowRoles _workflowRoles)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles", _workflowRoles == null ? null : _workflowRoles.getMendixObject());
		Core.microflowCall("UGS.Retrieve_Email_Content_Actions").withParams(params).execute(context);
	}
	public static void retrieve_Email_Template(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Retrieve_Email_Template").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.History> retrieve_funds(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Retrieve_funds").withParams(params).execute(context);
		java.util.List<ugs.proxies.History> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.History.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<dynamicform.proxies.Template> retrieve_SortedTemplates(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Retrieve_SortedTemplates").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Template> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Template.initialize(context, obj));
		}
		return result;
	}
	public static void rollBack_Score(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.RollBack_Score").withParams(params).execute(context);
	}
	public static void sE_Microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.SE_Microflow").withParams(params).execute(context);
	}
	public static void send_Contract_ForProvider(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Send_Contract_ForProvider").withParams(params).execute(context);
	}
	public static void send_Remider(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("UGS.Send_Remider").withParams(params).execute(context);
	}
	public static void slipScreen(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.SlipScreen").withParams(params).execute(context);
	}
	public static void sub_AssignInterviewer(IContext context, dynamicform.proxies.WorkflowRoles _currentRole, ugs.proxies.GrantSystem _grantSystem, ugs.proxies.Interview _interview)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CurrentRole", _currentRole == null ? null : _currentRole.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		params.put("Interview", _interview == null ? null : _interview.getMendixObject());
		Core.microflowCall("UGS.Sub_AssignInterviewer").withParams(params).execute(context);
	}
	public static boolean sub_AssignInterviewers(IContext context, dynamicform.proxies.WorkflowRoles _currentRole, ugs.proxies.Interview _interview, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CurrentRole", _currentRole == null ? null : _currentRole.getMendixObject());
		params.put("Interview", _interview == null ? null : _interview.getMendixObject());
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("UGS.Sub_AssignInterviewers").withParams(params).execute(context);
	}
	public static void sUB_AssignToNextRole(IContext context, ugs.proxies.CaseMangement _caseMangement, java.lang.String _nextRole, java.lang.String _currentRole)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		params.put("NextRole", _nextRole);
		params.put("CurrentRole", _currentRole);
		Core.microflowCall("UGS.SUB_AssignToNextRole").withParams(params).execute(context);
	}
	public static void sUB_CaseManagmentReturn(IContext context, ugs.proxies.CaseMangement _caseMangement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseMangement", _caseMangement == null ? null : _caseMangement.getMendixObject());
		Core.microflowCall("UGS.SUB_CaseManagmentReturn").withParams(params).execute(context);
	}
	public static void sub_CloneElementObjects(IContext context, dynamicform.proxies.Element _element, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("UGS.Sub_CloneElementObjects").withParams(params).execute(context);
	}
	public static ugs.proxies.ReviewForm sUB_CloneReview(IContext context, dynamicform.proxies.WorkflowRoles _nextRole)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NextRole", _nextRole == null ? null : _nextRole.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("UGS.SUB_CloneReview").withParams(params).execute(context);
		return result == null ? null : ugs.proxies.ReviewForm.initialize(context, result);
	}
	public static java.util.List<dynamicform.proxies.Intermediate> sUB_ConvertToIntermediate_2(IContext context, dynamicform.proxies.Intermediate _intermediate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Intermediate", _intermediate == null ? null : _intermediate.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.SUB_ConvertToIntermediate_2").withParams(params).execute(context);
		java.util.List<dynamicform.proxies.Intermediate> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(dynamicform.proxies.Intermediate.initialize(context, obj));
		}
		return result;
	}
	public static void sUB_DynamicWorkflowPassGrant(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.SUB_DynamicWorkflowPassGrant").withParams(params).execute(context);
	}
	public static boolean sUB_SaveDraft(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("UGS.SUB_SaveDraft").withParams(params).execute(context);
	}
	public static void test_Assoc_reviewForm(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.Test_Assoc_reviewForm").withParams(params).execute(context);
	}
	public static void view_ContractPage(IContext context, ugs.proxies.GrantSystem _grantSystem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GrantSystem", _grantSystem == null ? null : _grantSystem.getMendixObject());
		Core.microflowCall("UGS.View_ContractPage").withParams(params).execute(context);
	}
	public static void workflow_DragAndDrop(IContext context, dynamicform.proxies.WorkflowRoles_DnD _workflowRoles_DnD)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowRoles_DnD", _workflowRoles_DnD == null ? null : _workflowRoles_DnD.getMendixObject());
		Core.microflowCall("UGS.Workflow_DragAndDrop").withParams(params).execute(context);
	}
	public static java.util.List<ugs.proxies.count> year_Month_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("UGS.Year_Month_Count").withParams(params).execute(context);
		java.util.List<ugs.proxies.count> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(ugs.proxies.count.initialize(context, obj));
		}
		return result;
	}
}