// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddrop.proxies;

public class Decimal_DnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject decimal_DnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDrop.Decimal_DnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Decimal_DnD_Drag("DragAndDrop.Decimal_DnD_Drag"),
		Decimal_DnD_Drop("DragAndDrop.Decimal_DnD_Drop"),
		Decimal_DnD_Dragged("DragAndDrop.Decimal_DnD_Dragged"),
		Decimal_DnD_String_Dragged("DragAndDrop.Decimal_DnD_String_Dragged"),
		Decimal_DnD_Number_Dragged("DragAndDrop.Decimal_DnD_Number_Dragged"),
		Decimal_DnD_Boolean_Dragged("DragAndDrop.Decimal_DnD_Boolean_Dragged"),
		Decimal_DnD_Doc_Dragged("DragAndDrop.Decimal_DnD_Doc_Dragged");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Decimal_DnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDrop.Decimal_DnD"));
	}

	protected Decimal_DnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject decimal_DnDMendixObject)
	{
		if (decimal_DnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDrop.Decimal_DnD", decimal_DnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDrop.Decimal_DnD");

		this.decimal_DnDMendixObject = decimal_DnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Decimal_DnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddrop.proxies.Decimal_DnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddrop.proxies.Decimal_DnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddrop.proxies.Decimal_DnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddrop.proxies.Decimal_DnD(context, mendixObject);
	}

	public static draganddrop.proxies.Decimal_DnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddrop.proxies.Decimal_DnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Decimal_DnD_Drag
	 */
	public final dynamicform.proxies.Decimal getDecimal_DnD_Drag() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Drag(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Drag
	 */
	public final dynamicform.proxies.Decimal getDecimal_DnD_Drag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Decimal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Drag.toString());
		if (identifier != null)
			result = dynamicform.proxies.Decimal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Drag
	 * @param decimal_dnd_drag
	 */
	public final void setDecimal_DnD_Drag(dynamicform.proxies.Decimal decimal_dnd_drag)
	{
		setDecimal_DnD_Drag(getContext(), decimal_dnd_drag);
	}

	/**
	 * Set value of Decimal_DnD_Drag
	 * @param context
	 * @param decimal_dnd_drag
	 */
	public final void setDecimal_DnD_Drag(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Decimal decimal_dnd_drag)
	{
		if (decimal_dnd_drag == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Drag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Drag.toString(), decimal_dnd_drag.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_Drop
	 */
	public final dynamicform.proxies.Decimal getDecimal_DnD_Drop() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Drop(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Drop
	 */
	public final dynamicform.proxies.Decimal getDecimal_DnD_Drop(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Decimal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Drop.toString());
		if (identifier != null)
			result = dynamicform.proxies.Decimal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Drop
	 * @param decimal_dnd_drop
	 */
	public final void setDecimal_DnD_Drop(dynamicform.proxies.Decimal decimal_dnd_drop)
	{
		setDecimal_DnD_Drop(getContext(), decimal_dnd_drop);
	}

	/**
	 * Set value of Decimal_DnD_Drop
	 * @param context
	 * @param decimal_dnd_drop
	 */
	public final void setDecimal_DnD_Drop(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Decimal decimal_dnd_drop)
	{
		if (decimal_dnd_drop == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Drop.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Drop.toString(), decimal_dnd_drop.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getDecimal_DnD_Dragged() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getDecimal_DnD_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.DateAndTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.DateAndTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Dragged
	 * @param decimal_dnd_dragged
	 */
	public final void setDecimal_DnD_Dragged(dynamicform.proxies.DateAndTime decimal_dnd_dragged)
	{
		setDecimal_DnD_Dragged(getContext(), decimal_dnd_dragged);
	}

	/**
	 * Set value of Decimal_DnD_Dragged
	 * @param context
	 * @param decimal_dnd_dragged
	 */
	public final void setDecimal_DnD_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.DateAndTime decimal_dnd_dragged)
	{
		if (decimal_dnd_dragged == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Dragged.toString(), decimal_dnd_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_String_Dragged
	 */
	public final dynamicform.proxies.String getDecimal_DnD_String_Dragged() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_String_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_String_Dragged
	 */
	public final dynamicform.proxies.String getDecimal_DnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.String result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_String_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.String.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_String_Dragged
	 * @param decimal_dnd_string_dragged
	 */
	public final void setDecimal_DnD_String_Dragged(dynamicform.proxies.String decimal_dnd_string_dragged)
	{
		setDecimal_DnD_String_Dragged(getContext(), decimal_dnd_string_dragged);
	}

	/**
	 * Set value of Decimal_DnD_String_Dragged
	 * @param context
	 * @param decimal_dnd_string_dragged
	 */
	public final void setDecimal_DnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.String decimal_dnd_string_dragged)
	{
		if (decimal_dnd_string_dragged == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_String_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_String_Dragged.toString(), decimal_dnd_string_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getDecimal_DnD_Number_Dragged() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Number_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getDecimal_DnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Number result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Number_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Number.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Number_Dragged
	 * @param decimal_dnd_number_dragged
	 */
	public final void setDecimal_DnD_Number_Dragged(dynamicform.proxies.Number decimal_dnd_number_dragged)
	{
		setDecimal_DnD_Number_Dragged(getContext(), decimal_dnd_number_dragged);
	}

	/**
	 * Set value of Decimal_DnD_Number_Dragged
	 * @param context
	 * @param decimal_dnd_number_dragged
	 */
	public final void setDecimal_DnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Number decimal_dnd_number_dragged)
	{
		if (decimal_dnd_number_dragged == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Number_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Number_Dragged.toString(), decimal_dnd_number_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getDecimal_DnD_Boolean_Dragged() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Boolean_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getDecimal_DnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Boolean_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Boolean_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Boolean_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Boolean_Dragged
	 * @param decimal_dnd_boolean_dragged
	 */
	public final void setDecimal_DnD_Boolean_Dragged(dynamicform.proxies.Boolean_ decimal_dnd_boolean_dragged)
	{
		setDecimal_DnD_Boolean_Dragged(getContext(), decimal_dnd_boolean_dragged);
	}

	/**
	 * Set value of Decimal_DnD_Boolean_Dragged
	 * @param context
	 * @param decimal_dnd_boolean_dragged
	 */
	public final void setDecimal_DnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Boolean_ decimal_dnd_boolean_dragged)
	{
		if (decimal_dnd_boolean_dragged == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Boolean_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Boolean_Dragged.toString(), decimal_dnd_boolean_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of Decimal_DnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getDecimal_DnD_Doc_Dragged() throws com.mendix.core.CoreException
	{
		return getDecimal_DnD_Doc_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal_DnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getDecimal_DnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Doc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Decimal_DnD_Doc_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Doc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Decimal_DnD_Doc_Dragged
	 * @param decimal_dnd_doc_dragged
	 */
	public final void setDecimal_DnD_Doc_Dragged(dynamicform.proxies.Doc decimal_dnd_doc_dragged)
	{
		setDecimal_DnD_Doc_Dragged(getContext(), decimal_dnd_doc_dragged);
	}

	/**
	 * Set value of Decimal_DnD_Doc_Dragged
	 * @param context
	 * @param decimal_dnd_doc_dragged
	 */
	public final void setDecimal_DnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Doc decimal_dnd_doc_dragged)
	{
		if (decimal_dnd_doc_dragged == null)
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Doc_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Decimal_DnD_Doc_Dragged.toString(), decimal_dnd_doc_dragged.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return decimal_DnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddrop.proxies.Decimal_DnD that = (draganddrop.proxies.Decimal_DnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDrop.Decimal_DnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
