// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddrop.proxies;

public class DocDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject docDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDrop.DocDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DocDnD_Doc_Drag("DragAndDrop.DocDnD_Doc_Drag"),
		DocDnD_Doc_Drop("DragAndDrop.DocDnD_Doc_Drop"),
		DocDnD_String_Dragged("DragAndDrop.DocDnD_String_Dragged"),
		DocDnD_DateAndTime_Dragged("DragAndDrop.DocDnD_DateAndTime_Dragged"),
		DocDnD_Number_Dragged("DragAndDrop.DocDnD_Number_Dragged"),
		DocDnD_Decimal_Dragged("DragAndDrop.DocDnD_Decimal_Dragged"),
		DocDnD_Boolean_Dragged("DragAndDrop.DocDnD_Boolean_Dragged");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDrop.DocDnD"));
	}

	protected DocDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject docDnDMendixObject)
	{
		if (docDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDrop.DocDnD", docDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDrop.DocDnD");

		this.docDnDMendixObject = docDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DocDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddrop.proxies.DocDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddrop.proxies.DocDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddrop.proxies.DocDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddrop.proxies.DocDnD(context, mendixObject);
	}

	public static draganddrop.proxies.DocDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddrop.proxies.DocDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DocDnD_Doc_Drag
	 */
	public final dynamicform.proxies.Doc getDocDnD_Doc_Drag() throws com.mendix.core.CoreException
	{
		return getDocDnD_Doc_Drag(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_Doc_Drag
	 */
	public final dynamicform.proxies.Doc getDocDnD_Doc_Drag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Doc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_Doc_Drag.toString());
		if (identifier != null)
			result = dynamicform.proxies.Doc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_Doc_Drag
	 * @param docdnd_doc_drag
	 */
	public final void setDocDnD_Doc_Drag(dynamicform.proxies.Doc docdnd_doc_drag)
	{
		setDocDnD_Doc_Drag(getContext(), docdnd_doc_drag);
	}

	/**
	 * Set value of DocDnD_Doc_Drag
	 * @param context
	 * @param docdnd_doc_drag
	 */
	public final void setDocDnD_Doc_Drag(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Doc docdnd_doc_drag)
	{
		if (docdnd_doc_drag == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_Doc_Drag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_Doc_Drag.toString(), docdnd_doc_drag.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_Doc_Drop
	 */
	public final dynamicform.proxies.Doc getDocDnD_Doc_Drop() throws com.mendix.core.CoreException
	{
		return getDocDnD_Doc_Drop(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_Doc_Drop
	 */
	public final dynamicform.proxies.Doc getDocDnD_Doc_Drop(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Doc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_Doc_Drop.toString());
		if (identifier != null)
			result = dynamicform.proxies.Doc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_Doc_Drop
	 * @param docdnd_doc_drop
	 */
	public final void setDocDnD_Doc_Drop(dynamicform.proxies.Doc docdnd_doc_drop)
	{
		setDocDnD_Doc_Drop(getContext(), docdnd_doc_drop);
	}

	/**
	 * Set value of DocDnD_Doc_Drop
	 * @param context
	 * @param docdnd_doc_drop
	 */
	public final void setDocDnD_Doc_Drop(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Doc docdnd_doc_drop)
	{
		if (docdnd_doc_drop == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_Doc_Drop.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_Doc_Drop.toString(), docdnd_doc_drop.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_String_Dragged
	 */
	public final dynamicform.proxies.String getDocDnD_String_Dragged() throws com.mendix.core.CoreException
	{
		return getDocDnD_String_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_String_Dragged
	 */
	public final dynamicform.proxies.String getDocDnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.String result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_String_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.String.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_String_Dragged
	 * @param docdnd_string_dragged
	 */
	public final void setDocDnD_String_Dragged(dynamicform.proxies.String docdnd_string_dragged)
	{
		setDocDnD_String_Dragged(getContext(), docdnd_string_dragged);
	}

	/**
	 * Set value of DocDnD_String_Dragged
	 * @param context
	 * @param docdnd_string_dragged
	 */
	public final void setDocDnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.String docdnd_string_dragged)
	{
		if (docdnd_string_dragged == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_String_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_String_Dragged.toString(), docdnd_string_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_DateAndTime_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getDocDnD_DateAndTime_Dragged() throws com.mendix.core.CoreException
	{
		return getDocDnD_DateAndTime_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_DateAndTime_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getDocDnD_DateAndTime_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.DateAndTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_DateAndTime_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.DateAndTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_DateAndTime_Dragged
	 * @param docdnd_dateandtime_dragged
	 */
	public final void setDocDnD_DateAndTime_Dragged(dynamicform.proxies.DateAndTime docdnd_dateandtime_dragged)
	{
		setDocDnD_DateAndTime_Dragged(getContext(), docdnd_dateandtime_dragged);
	}

	/**
	 * Set value of DocDnD_DateAndTime_Dragged
	 * @param context
	 * @param docdnd_dateandtime_dragged
	 */
	public final void setDocDnD_DateAndTime_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.DateAndTime docdnd_dateandtime_dragged)
	{
		if (docdnd_dateandtime_dragged == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_DateAndTime_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_DateAndTime_Dragged.toString(), docdnd_dateandtime_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getDocDnD_Number_Dragged() throws com.mendix.core.CoreException
	{
		return getDocDnD_Number_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getDocDnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Number result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_Number_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Number.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_Number_Dragged
	 * @param docdnd_number_dragged
	 */
	public final void setDocDnD_Number_Dragged(dynamicform.proxies.Number docdnd_number_dragged)
	{
		setDocDnD_Number_Dragged(getContext(), docdnd_number_dragged);
	}

	/**
	 * Set value of DocDnD_Number_Dragged
	 * @param context
	 * @param docdnd_number_dragged
	 */
	public final void setDocDnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Number docdnd_number_dragged)
	{
		if (docdnd_number_dragged == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_Number_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_Number_Dragged.toString(), docdnd_number_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getDocDnD_Decimal_Dragged() throws com.mendix.core.CoreException
	{
		return getDocDnD_Decimal_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getDocDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Decimal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_Decimal_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Decimal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_Decimal_Dragged
	 * @param docdnd_decimal_dragged
	 */
	public final void setDocDnD_Decimal_Dragged(dynamicform.proxies.Decimal docdnd_decimal_dragged)
	{
		setDocDnD_Decimal_Dragged(getContext(), docdnd_decimal_dragged);
	}

	/**
	 * Set value of DocDnD_Decimal_Dragged
	 * @param context
	 * @param docdnd_decimal_dragged
	 */
	public final void setDocDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Decimal docdnd_decimal_dragged)
	{
		if (docdnd_decimal_dragged == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_Decimal_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_Decimal_Dragged.toString(), docdnd_decimal_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DocDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getDocDnD_Boolean_Dragged() throws com.mendix.core.CoreException
	{
		return getDocDnD_Boolean_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DocDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getDocDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Boolean_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocDnD_Boolean_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Boolean_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocDnD_Boolean_Dragged
	 * @param docdnd_boolean_dragged
	 */
	public final void setDocDnD_Boolean_Dragged(dynamicform.proxies.Boolean_ docdnd_boolean_dragged)
	{
		setDocDnD_Boolean_Dragged(getContext(), docdnd_boolean_dragged);
	}

	/**
	 * Set value of DocDnD_Boolean_Dragged
	 * @param context
	 * @param docdnd_boolean_dragged
	 */
	public final void setDocDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Boolean_ docdnd_boolean_dragged)
	{
		if (docdnd_boolean_dragged == null)
			getMendixObject().setValue(context, MemberNames.DocDnD_Boolean_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocDnD_Boolean_Dragged.toString(), docdnd_boolean_dragged.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return docDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddrop.proxies.DocDnD that = (draganddrop.proxies.DocDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDrop.DocDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
