// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddrop.proxies;

public class NumberDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject numberDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDrop.NumberDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberDnD_Drag("DragAndDrop.NumberDnD_Drag"),
		NumberDnD_Drop("DragAndDrop.NumberDnD_Drop"),
		NumberDnD_DateAndTime_dragged("DragAndDrop.NumberDnD_DateAndTime_dragged"),
		NumberDnD_String_Dragged("DragAndDrop.NumberDnD_String_Dragged"),
		NumberDnD_Decimal_Dragged("DragAndDrop.NumberDnD_Decimal_Dragged"),
		NumberDnD_Boolean_Dragged("DragAndDrop.NumberDnD_Boolean_Dragged"),
		NumberDnD_Doc_Dragged("DragAndDrop.NumberDnD_Doc_Dragged");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NumberDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDrop.NumberDnD"));
	}

	protected NumberDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject numberDnDMendixObject)
	{
		if (numberDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDrop.NumberDnD", numberDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDrop.NumberDnD");

		this.numberDnDMendixObject = numberDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'NumberDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddrop.proxies.NumberDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddrop.proxies.NumberDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddrop.proxies.NumberDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddrop.proxies.NumberDnD(context, mendixObject);
	}

	public static draganddrop.proxies.NumberDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddrop.proxies.NumberDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NumberDnD_Drag
	 */
	public final dynamicform.proxies.Number getNumberDnD_Drag() throws com.mendix.core.CoreException
	{
		return getNumberDnD_Drag(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_Drag
	 */
	public final dynamicform.proxies.Number getNumberDnD_Drag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Number result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_Drag.toString());
		if (identifier != null)
			result = dynamicform.proxies.Number.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_Drag
	 * @param numberdnd_drag
	 */
	public final void setNumberDnD_Drag(dynamicform.proxies.Number numberdnd_drag)
	{
		setNumberDnD_Drag(getContext(), numberdnd_drag);
	}

	/**
	 * Set value of NumberDnD_Drag
	 * @param context
	 * @param numberdnd_drag
	 */
	public final void setNumberDnD_Drag(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Number numberdnd_drag)
	{
		if (numberdnd_drag == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_Drag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_Drag.toString(), numberdnd_drag.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_Drop
	 */
	public final dynamicform.proxies.Number getNumberDnD_Drop() throws com.mendix.core.CoreException
	{
		return getNumberDnD_Drop(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_Drop
	 */
	public final dynamicform.proxies.Number getNumberDnD_Drop(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Number result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_Drop.toString());
		if (identifier != null)
			result = dynamicform.proxies.Number.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_Drop
	 * @param numberdnd_drop
	 */
	public final void setNumberDnD_Drop(dynamicform.proxies.Number numberdnd_drop)
	{
		setNumberDnD_Drop(getContext(), numberdnd_drop);
	}

	/**
	 * Set value of NumberDnD_Drop
	 * @param context
	 * @param numberdnd_drop
	 */
	public final void setNumberDnD_Drop(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Number numberdnd_drop)
	{
		if (numberdnd_drop == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_Drop.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_Drop.toString(), numberdnd_drop.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_DateAndTime_dragged
	 */
	public final dynamicform.proxies.DateAndTime getNumberDnD_DateAndTime_dragged() throws com.mendix.core.CoreException
	{
		return getNumberDnD_DateAndTime_dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_DateAndTime_dragged
	 */
	public final dynamicform.proxies.DateAndTime getNumberDnD_DateAndTime_dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.DateAndTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_DateAndTime_dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.DateAndTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_DateAndTime_dragged
	 * @param numberdnd_dateandtime_dragged
	 */
	public final void setNumberDnD_DateAndTime_dragged(dynamicform.proxies.DateAndTime numberdnd_dateandtime_dragged)
	{
		setNumberDnD_DateAndTime_dragged(getContext(), numberdnd_dateandtime_dragged);
	}

	/**
	 * Set value of NumberDnD_DateAndTime_dragged
	 * @param context
	 * @param numberdnd_dateandtime_dragged
	 */
	public final void setNumberDnD_DateAndTime_dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.DateAndTime numberdnd_dateandtime_dragged)
	{
		if (numberdnd_dateandtime_dragged == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_DateAndTime_dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_DateAndTime_dragged.toString(), numberdnd_dateandtime_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_String_Dragged
	 */
	public final dynamicform.proxies.String getNumberDnD_String_Dragged() throws com.mendix.core.CoreException
	{
		return getNumberDnD_String_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_String_Dragged
	 */
	public final dynamicform.proxies.String getNumberDnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.String result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_String_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.String.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_String_Dragged
	 * @param numberdnd_string_dragged
	 */
	public final void setNumberDnD_String_Dragged(dynamicform.proxies.String numberdnd_string_dragged)
	{
		setNumberDnD_String_Dragged(getContext(), numberdnd_string_dragged);
	}

	/**
	 * Set value of NumberDnD_String_Dragged
	 * @param context
	 * @param numberdnd_string_dragged
	 */
	public final void setNumberDnD_String_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.String numberdnd_string_dragged)
	{
		if (numberdnd_string_dragged == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_String_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_String_Dragged.toString(), numberdnd_string_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getNumberDnD_Decimal_Dragged() throws com.mendix.core.CoreException
	{
		return getNumberDnD_Decimal_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getNumberDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Decimal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_Decimal_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Decimal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_Decimal_Dragged
	 * @param numberdnd_decimal_dragged
	 */
	public final void setNumberDnD_Decimal_Dragged(dynamicform.proxies.Decimal numberdnd_decimal_dragged)
	{
		setNumberDnD_Decimal_Dragged(getContext(), numberdnd_decimal_dragged);
	}

	/**
	 * Set value of NumberDnD_Decimal_Dragged
	 * @param context
	 * @param numberdnd_decimal_dragged
	 */
	public final void setNumberDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Decimal numberdnd_decimal_dragged)
	{
		if (numberdnd_decimal_dragged == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_Decimal_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_Decimal_Dragged.toString(), numberdnd_decimal_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getNumberDnD_Boolean_Dragged() throws com.mendix.core.CoreException
	{
		return getNumberDnD_Boolean_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getNumberDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Boolean_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_Boolean_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Boolean_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_Boolean_Dragged
	 * @param numberdnd_boolean_dragged
	 */
	public final void setNumberDnD_Boolean_Dragged(dynamicform.proxies.Boolean_ numberdnd_boolean_dragged)
	{
		setNumberDnD_Boolean_Dragged(getContext(), numberdnd_boolean_dragged);
	}

	/**
	 * Set value of NumberDnD_Boolean_Dragged
	 * @param context
	 * @param numberdnd_boolean_dragged
	 */
	public final void setNumberDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Boolean_ numberdnd_boolean_dragged)
	{
		if (numberdnd_boolean_dragged == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_Boolean_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_Boolean_Dragged.toString(), numberdnd_boolean_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of NumberDnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getNumberDnD_Doc_Dragged() throws com.mendix.core.CoreException
	{
		return getNumberDnD_Doc_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberDnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getNumberDnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Doc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NumberDnD_Doc_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Doc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NumberDnD_Doc_Dragged
	 * @param numberdnd_doc_dragged
	 */
	public final void setNumberDnD_Doc_Dragged(dynamicform.proxies.Doc numberdnd_doc_dragged)
	{
		setNumberDnD_Doc_Dragged(getContext(), numberdnd_doc_dragged);
	}

	/**
	 * Set value of NumberDnD_Doc_Dragged
	 * @param context
	 * @param numberdnd_doc_dragged
	 */
	public final void setNumberDnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Doc numberdnd_doc_dragged)
	{
		if (numberdnd_doc_dragged == null)
			getMendixObject().setValue(context, MemberNames.NumberDnD_Doc_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NumberDnD_Doc_Dragged.toString(), numberdnd_doc_dragged.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return numberDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddrop.proxies.NumberDnD that = (draganddrop.proxies.NumberDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDrop.NumberDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
