// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddrop.proxies;

public class StringDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stringDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDrop.StringDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StringDnD_Drag("DragAndDrop.StringDnD_Drag"),
		StringDnD_Drop("DragAndDrop.StringDnD_Drop"),
		StringDnD_DateAndTime_Dragged("DragAndDrop.StringDnD_DateAndTime_Dragged"),
		StringDnD_Number_Dragged("DragAndDrop.StringDnD_Number_Dragged"),
		StringDnD_Decimal_Dragged("DragAndDrop.StringDnD_Decimal_Dragged"),
		StringDnD_Boolean_Dragged("DragAndDrop.StringDnD_Boolean_Dragged"),
		StringDnD_Doc_Dragged("DragAndDrop.StringDnD_Doc_Dragged");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StringDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDrop.StringDnD"));
	}

	protected StringDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stringDnDMendixObject)
	{
		if (stringDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDrop.StringDnD", stringDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDrop.StringDnD");

		this.stringDnDMendixObject = stringDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StringDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddrop.proxies.StringDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddrop.proxies.StringDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddrop.proxies.StringDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddrop.proxies.StringDnD(context, mendixObject);
	}

	public static draganddrop.proxies.StringDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddrop.proxies.StringDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StringDnD_Drag
	 */
	public final dynamicform.proxies.String getStringDnD_Drag() throws com.mendix.core.CoreException
	{
		return getStringDnD_Drag(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Drag
	 */
	public final dynamicform.proxies.String getStringDnD_Drag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.String result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Drag.toString());
		if (identifier != null)
			result = dynamicform.proxies.String.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Drag
	 * @param stringdnd_drag
	 */
	public final void setStringDnD_Drag(dynamicform.proxies.String stringdnd_drag)
	{
		setStringDnD_Drag(getContext(), stringdnd_drag);
	}

	/**
	 * Set value of StringDnD_Drag
	 * @param context
	 * @param stringdnd_drag
	 */
	public final void setStringDnD_Drag(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.String stringdnd_drag)
	{
		if (stringdnd_drag == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Drag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Drag.toString(), stringdnd_drag.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_Drop
	 */
	public final dynamicform.proxies.String getStringDnD_Drop() throws com.mendix.core.CoreException
	{
		return getStringDnD_Drop(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Drop
	 */
	public final dynamicform.proxies.String getStringDnD_Drop(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.String result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Drop.toString());
		if (identifier != null)
			result = dynamicform.proxies.String.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Drop
	 * @param stringdnd_drop
	 */
	public final void setStringDnD_Drop(dynamicform.proxies.String stringdnd_drop)
	{
		setStringDnD_Drop(getContext(), stringdnd_drop);
	}

	/**
	 * Set value of StringDnD_Drop
	 * @param context
	 * @param stringdnd_drop
	 */
	public final void setStringDnD_Drop(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.String stringdnd_drop)
	{
		if (stringdnd_drop == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Drop.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Drop.toString(), stringdnd_drop.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_DateAndTime_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getStringDnD_DateAndTime_Dragged() throws com.mendix.core.CoreException
	{
		return getStringDnD_DateAndTime_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_DateAndTime_Dragged
	 */
	public final dynamicform.proxies.DateAndTime getStringDnD_DateAndTime_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.DateAndTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_DateAndTime_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.DateAndTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_DateAndTime_Dragged
	 * @param stringdnd_dateandtime_dragged
	 */
	public final void setStringDnD_DateAndTime_Dragged(dynamicform.proxies.DateAndTime stringdnd_dateandtime_dragged)
	{
		setStringDnD_DateAndTime_Dragged(getContext(), stringdnd_dateandtime_dragged);
	}

	/**
	 * Set value of StringDnD_DateAndTime_Dragged
	 * @param context
	 * @param stringdnd_dateandtime_dragged
	 */
	public final void setStringDnD_DateAndTime_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.DateAndTime stringdnd_dateandtime_dragged)
	{
		if (stringdnd_dateandtime_dragged == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_DateAndTime_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_DateAndTime_Dragged.toString(), stringdnd_dateandtime_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getStringDnD_Number_Dragged() throws com.mendix.core.CoreException
	{
		return getStringDnD_Number_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Number_Dragged
	 */
	public final dynamicform.proxies.Number getStringDnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Number result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Number_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Number.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Number_Dragged
	 * @param stringdnd_number_dragged
	 */
	public final void setStringDnD_Number_Dragged(dynamicform.proxies.Number stringdnd_number_dragged)
	{
		setStringDnD_Number_Dragged(getContext(), stringdnd_number_dragged);
	}

	/**
	 * Set value of StringDnD_Number_Dragged
	 * @param context
	 * @param stringdnd_number_dragged
	 */
	public final void setStringDnD_Number_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Number stringdnd_number_dragged)
	{
		if (stringdnd_number_dragged == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Number_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Number_Dragged.toString(), stringdnd_number_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getStringDnD_Decimal_Dragged() throws com.mendix.core.CoreException
	{
		return getStringDnD_Decimal_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Decimal_Dragged
	 */
	public final dynamicform.proxies.Decimal getStringDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Decimal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Decimal_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Decimal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Decimal_Dragged
	 * @param stringdnd_decimal_dragged
	 */
	public final void setStringDnD_Decimal_Dragged(dynamicform.proxies.Decimal stringdnd_decimal_dragged)
	{
		setStringDnD_Decimal_Dragged(getContext(), stringdnd_decimal_dragged);
	}

	/**
	 * Set value of StringDnD_Decimal_Dragged
	 * @param context
	 * @param stringdnd_decimal_dragged
	 */
	public final void setStringDnD_Decimal_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Decimal stringdnd_decimal_dragged)
	{
		if (stringdnd_decimal_dragged == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Decimal_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Decimal_Dragged.toString(), stringdnd_decimal_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getStringDnD_Boolean_Dragged() throws com.mendix.core.CoreException
	{
		return getStringDnD_Boolean_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Boolean_Dragged
	 */
	public final dynamicform.proxies.Boolean_ getStringDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Boolean_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Boolean_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Boolean_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Boolean_Dragged
	 * @param stringdnd_boolean_dragged
	 */
	public final void setStringDnD_Boolean_Dragged(dynamicform.proxies.Boolean_ stringdnd_boolean_dragged)
	{
		setStringDnD_Boolean_Dragged(getContext(), stringdnd_boolean_dragged);
	}

	/**
	 * Set value of StringDnD_Boolean_Dragged
	 * @param context
	 * @param stringdnd_boolean_dragged
	 */
	public final void setStringDnD_Boolean_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Boolean_ stringdnd_boolean_dragged)
	{
		if (stringdnd_boolean_dragged == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Boolean_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Boolean_Dragged.toString(), stringdnd_boolean_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of StringDnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getStringDnD_Doc_Dragged() throws com.mendix.core.CoreException
	{
		return getStringDnD_Doc_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of StringDnD_Doc_Dragged
	 */
	public final dynamicform.proxies.Doc getStringDnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Doc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StringDnD_Doc_Dragged.toString());
		if (identifier != null)
			result = dynamicform.proxies.Doc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StringDnD_Doc_Dragged
	 * @param stringdnd_doc_dragged
	 */
	public final void setStringDnD_Doc_Dragged(dynamicform.proxies.Doc stringdnd_doc_dragged)
	{
		setStringDnD_Doc_Dragged(getContext(), stringdnd_doc_dragged);
	}

	/**
	 * Set value of StringDnD_Doc_Dragged
	 * @param context
	 * @param stringdnd_doc_dragged
	 */
	public final void setStringDnD_Doc_Dragged(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Doc stringdnd_doc_dragged)
	{
		if (stringdnd_doc_dragged == null)
			getMendixObject().setValue(context, MemberNames.StringDnD_Doc_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StringDnD_Doc_Dragged.toString(), stringdnd_doc_dragged.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stringDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddrop.proxies.StringDnD that = (draganddrop.proxies.StringDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDrop.StringDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
