// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} json
 * @returns {Promise.<string>}
 */
export async function JavaScript_removeParenthesis(json) {
	// BEGIN USER CODE
	let x = json ;
	x = x.replace(/[{()}]/g, '');
	x = x.replace(/:/g,'');
	x = x.replaceAll("title","");
	x = x.replaceAll('"','');
	x= x.replace(/[\[\]']+/g,'');
	return x;
	// END USER CODE
}
