// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dynamicform.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class TokenReplacerJava extends CustomJavaAction<java.lang.String>
{
	private java.lang.String CompleteToken;
	private java.lang.String Value;
	private java.lang.String BodyofText;

	public TokenReplacerJava(IContext context, java.lang.String CompleteToken, java.lang.String Value, java.lang.String BodyofText)
	{
		super(context);
		this.CompleteToken = CompleteToken;
		this.Value = Value;
		this.BodyofText = BodyofText;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

String replaceString = BodyofText.replace(CompleteToken, Value);
		return replaceString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TokenReplacerJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
